### ISSUE TITLE
Can't fill JsonArray in for loop

### ISSUE THREAD

**Issue by franklinvv** [bblanchon/ArduinoJson#10]
(Disclaimer: I'm not at all an expert in C/C++)

I am trying to build a JsonArray in a for loop on an Arduino Mega 2560, iterating through an array. Here is a (somewhat) minimal example of what I'm trying to do.

```
struct Person {
    int id;
    char name[32];
};

Person boss;
boss.id = 1;
strcpy(boss.name, "Jeff");
Person employee;
employee.id = 2;
strcpy(employee.name, "John");

Person persons[2] = {boss, employee};

JsonArray<2> json;
for(int i = 0; i < 2; i++) {
    JsonObject<2> object;
    object.add("id", persons[i].id);
    object.add("name", persons[i].name);
    json.add(object);
}

Serial.print(json);
```

The expected result is:

```
[
    {
        id: 1,
        name: "Jeff"
    },
    {
        id: 2,
        name: "John"
    }
]
```

However, I get this:

```
[
    {
        id: 2,
        name: "John"
    },
    {
        id: 2,
        name: "John"
    }
]
```

Any idea why I can't construct an JsonArray this way?

**Comment by ersinpw** [comment]
@bblanchon I have a similar problem, I only see values of the last object. But the code here is outdated I guess? Do you have a suggestion how to solve this in the newest version of ArduinoJson?

**Comment by r-anwar** [comment]
@bblanchon Hi! I have the same problem like ersinpw.

I used the builder pattern with no success. The last entry overrides all elements in 'users' field.

class JSONBuilder
{
    DynamicJsonBuffer _buffer;
    JsonObject& _root;

public:
    JSONBuilder()
            : _root(_buffer.createObject()) {
    }

    void getUsersResult(User users[], int size) {

        JsonArray& usersJSON = _root.createNestedArray("users");

        for(int i = 0; i < size; i++) {
            User user = users[i];

            usersJSON.add(user.toJson(_buffer.createObject()));
        }
    }

    void dumpTo(Print& destination) const {
        _root.prettyPrintTo(destination);
    }

    String dumpTo(String destination) const {
        _root.prettyPrintTo(destination);
        Serial.println(destination);
        return destination;
    }

private:
};

Please, may you can help me?

Best regards
