### ISSUE TITLE
🎉One thousand issues!🎉

### ISSUE THREAD

**Issue by bblanchon** [bblanchon/ArduinoJson#1000]
Happy issuversary ArduinoJson! 🎂

I'm glad to get this opportunity to thank all the people who opened issues in the past five years, either to report a problem, to request a new feature, or to get some help.

ArduinoJson is what it is because of *you*; because you found the courage to click that button, because you took the time to write, because you insisted when I was wrong, and because you showed you care.

So, once again, thank you; **you made ArduinoJson**.

Benoit Blanchon

**Comment by vaz83** [comment]
ArduinoJson is for me the best json library for microcontrollers! I'm a huge fan of it!
