### ISSUE TITLE
measureJson() returns same size, even after [] assignement 

### ISSUE THREAD

**Issue by sglvladi** [bblanchon/ArduinoJson#1010]
## Context
* Platform: ESP8266 (D1-mini) | ESP32(LOLIN32) 
* Firmware Version: ESP8266 2.5.2 | ESP32 1.0.1
* Operating System: Arduino

Hi there,

I've been having a play with `ArduinoJson v6.x` and I thought I'd give myself a little exercise to get my hands a bit dirty. 

## Intro 

So, the idea was to write a small class that wraps a JSON file stored on the ESP32/ESP8266 filesystem (using `SPIFFS`), such as to emulate a simple non-volatile `String` dictionary. The goal of the class is to handle the opening/writing of/to the selected JSON file, and then to act as a server for reading and writing values.

Now, with the coding mostly done, I decided to "stress-test" the class to see how much data I could store and at what rates. So I wrote a simple script that loads a few key-value entries on the document, saves is in Flash, and then reads it back to check if it all went as expected.  

Here's part of the test script:

### Test script (.ino)

<details><summary>CLICK TO SHOW CODE</summary>
<p>

```c++
// Initialise a Json dictionary file
NonVolatileJsonFile dictionary("/test1.json");

String keys[50];
String values[50];

void setupDictEntries(){
  for (int i=0; i<50; i++){
    keys[i] = "testKey"+String(i);
    values[i] = "testValue"+String(i);
    dictionary.set(keys[i], values[i]); 
    ...
  }
}

void verifyDictEntries(){
  for (int i=0; i<50; i++){
    String val = dictionary.get(keys[i]);
    if(val != values[i]){
      Serial.println("ERROR! Stored values don't match -> "+String(i));
    }
    ...
  }
}
...

void setup() {
  ...
  // Open dictionary file
  Serial.println("Opening dictionary file...");
  dictionary.open(true);
  ...

  // Populate the dictionary
  Serial.print("Populating dictionary.");
  setupDictEntries();
  dictionary.save();   // Save to SPIFFS
  ...
 
  // Verify entries have been written correctly 
  Serial.print("Verifying dictionary entries.");
  verifyDictEntries();
  ...
}  
``` 
</p>
</details>

Stepping inside line ``dictionary.set(keys[i], values[i]);`` of the ``setupDictEntries()`` function, we delve into the `set()` method of the developed class.

See below for the relevant class code.

### Library (.cpp)
<details><summary>CLICK TO SHOW CODE</summary>
<p>

```c++
bool NonVolatileJsonFile::set(const String &key, const String &value)
{
    if (value == "")
    {
        return remove(key);
    }

    // Deserialize
    size_t doc_size = _calcDocSize(_size);
    DynamicJsonDocument doc(doc_size);
    DeserializationError derror = deserializeJson(doc, dataBuffer());
    if (derror){
        Serial.print(F("deserializeJson() failed: "));
        Serial.println(derror.c_str());
        return false;
    }
    JsonObject obj = doc.as<JsonObject>();
    Serial.println( String(doc_size) +" - "+ String(size_1 ) + " - " + String(size_2));

    // Set value
 || IMPORTANT BIT ///////////////////// ||
 || size_t size_1 = measureJson(doc)+1; ||
 || doc[key.c_str()] = value;           ||
 || size_t size_2 = measureJson(doc)+1; ||
 || /////////////////////////////////// ||
    // Serialize
    char buffer[size_2];
    if (!serializeJson(doc, buffer, size_2)){
        Serial.print(F("serializeJson() failed: "));
        return false;
    }

    // Save buffer to heap (using `std::vector<char>`) and set `_size=size_2` in preparation for next iteration.
    dataBuffer(buffer, size_2);

    // Auto-save check
    _autoSaveHelper();
    
    return true;
}
...
unsigned long NonVolatileJsonFile::_calcDocSize(unsigned long data_len)
{   
    return data_len + 500;    
}
```

</p>
</details>

## Note
One thing worth noticing is the use of `_calcDocSize()`. This function is used to calculate the size of new `DynamicJsonDocument` objects, similar in a sense to the `measureJson()` function, but for and the idea is that the function uses the last value returned by `measureJson(doc)` (i.e. `size_2`) while adding some (in this case 500 bytes; make a note of this) extra headroom to allow some leeway for the new value(s) to be inserted.    

## The Problem
So, the problem I am having is that only a small (initial) part of the queued entries seem to get written (corrently) to file. At a first glance, I suspect that it has something to do with the size of `DynamicJsonDocument` by the looks of it, but more on that further down. 

I have managed to "zoom" in to the lines where the issue seems to occur. Below I have attached a copy of the observed feedback on the console. The two rightmost columns correspond to the values returned by `measureJson(doc)` before (`step_1`) and after (`step_2`) the assignment`doc[key.c_str()] = value;` is executed. As it ban be seen, the value of `step_2` eventually saturates and does not increase further, which is an indication of that no more values are being written to the object. This seems to happen for `i=32`, which is confirmed by the Debugging of the verification step where we can see that entries 32-49 seem to produce an error!

### Debug (Serial)
<details><summary>CLICK TO SHOW CODE</summary>
<p>

```
Populating dictionary.
i  - doc_size - size_1 - size_2
0  - 402 - 3 - 26
1  - 426 - 26 - 50
2  - 450 - 50 - 74
3  - 474 - 74 - 98
4  - 498 - 98 - 122
5  - 522 - 122 - 146
6  - 546 - 146 - 170
7  - 570 - 170 - 194
8  - 594 - 194 - 218
9  - 618 - 218 - 242
10 - 642 - 242 - 268
11 - 668 - 268 - 294
12 - 694 - 294 - 320
13 - 720 - 320 - 346
14 - 746 - 346 - 372
15 - 772 - 372 - 398
16 - 798 - 398 - 424
17 - 824 - 424 - 450
18 - 850 - 450 - 476
19 - 876 - 476 - 502
20 - 902 - 502 - 528
21 - 928 - 528 - 554
22 - 954 - 554 - 580
23 - 980 - 580 - 606
24 - 1006 - 606 - 632
25 - 1032 - 632 - 658
26 - 1058 - 658 - 684
27 - 1084 - 684 - 710
28 - 1110 - 710 - 736
29 - 1136 - 736 - 762
30 - 1162 - 762 - 788
31 - 1188 - 788 - 814
32 - 1214 - 814 - 831
33 - 1231 - 831 - 831
34 - 1231 - 831 - 831
35 - 1231 - 831 - 831
36 - 1231 - 831 - 831
37 - 1231 - 831 - 831
38 - 1231 - 831 - 831
39 - 1231 - 831 - 831
40 - 1231 - 831 - 831
41 - 1231 - 831 - 831
42 - 1231 - 831 - 831
43 - 1231 - 831 - 831
44 - 1231 - 831 - 831
45 - 1231 - 831 - 831
46 - 1231 - 831 - 831
47 - 1231 - 831 - 831
48 - 1231 - 831 - 831
49 - 1231 - 831 - 831
Done
Verifying dictionary entries.
ERROR! Stored values don't match -> 32
ERROR! Stored values don't match -> 33
ERROR! Stored values don't match -> 34
ERROR! Stored values don't match -> 35
ERROR! Stored values don't match -> 36
ERROR! Stored values don't match -> 37
ERROR! Stored values don't match -> 38
ERROR! Stored values don't match -> 39
ERROR! Stored values don't match -> 40
ERROR! Stored values don't match -> 41
ERROR! Stored values don't match -> 42
ERROR! Stored values don't match -> 43
ERROR! Stored values don't match -> 44
ERROR! Stored values don't match -> 45
ERROR! Stored values don't match -> 46
ERROR! Stored values don't match -> 47
ERROR! Stored values don't match -> 48
ERROR! Stored values don't match -> 49
```

</p>
</details> 

Now, as a further observation, when increasing the offset added by `_calcDocSize()` (thus increasing the memory offset to 1KB+), the issue seems to go away, whereas reducing the offset leads to only a handful of key-value pairs being written to the `DynamicJsonDocument`. This makes me think that the problem is caused by some sort of a memory bottleneck, however, as we can see, `_calcDocSize()` should provide sufficient memory for the new `JsonDocument` to be initialised (see `doc_size - step_2`) and new values to be added, however somehow 500 bytes is not enough to ?!

I would be very grateful for any kind help.

Thanks

**Comment by bblanchon** [comment]
Hi @sglvladi,

Thank you for taking the time to write this question very carefully.
Unfortunately, I don't have time to analyze every piece of it, so I'll only tell you what struck me first.

```c++
size_t size_2 = measureJson(doc)+1;
char buffer[size_2];
```

On the second line, you allocate a large array on the stack.
On ESP, the stack is limited to 4KB by default.
Usually, it raises an exception when you use too much, but it's not guaranteed.

I recommend that you allocate this buffer in the heap.
You can use String for that ([see here to optimize the allocation](https://cpp4arduino.com/2018/11/21/eight-tips-to-use-the-string-class-efficiently.html)).

Best Regards,
Benoit
