### ISSUE TITLE
Use extras sub-folder for ancillary content

### ISSUE THREAD

**Issue by rei-vilo** [bblanchon/ArduinoJson#1011]
Please place the sub-folders `fuzzing`, `scripts`, `third-party` and `test` on sub-folder `extras`, as per https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#extra-documentation.

> The content of the `extras` folder is totally ignored by the IDE; you are free to put anything inside such as supporting documentation, etc.

**Comment by bblanchon** [comment]
Hi @rei-vilo,

Yes, that would certainly help alternative IDEs, like Sloeber Plugin, that had issues with those files.

It will certainly break some code, so I need to wait for a new major revision.

BTW, why do you need that?

Best Regards,
Benoit

**Comment by rei-vilo** [comment]
Thank you for your answer.

I'm the developer of [embedXcode](https://embedxcode.weebly.com), a plug-in for Xcode to ease development for the most popular embedded computing boards.

I had to move the sub-folders previously listed into `extras` by hand to avoid any issue with embedXcode. 

+ General website https://embedxcode.weebly.com
+ User manual website https://embedxcode.com

**Comment by bblanchon** [comment]
Fix available in [ArduinoJson 6.12.0](https://github.com/bblanchon/ArduinoJson/releases/tag/v6.12.0).

**Comment by rei-vilo** [comment]
Thank you!
