### ISSUE TITLE
Cleaning buffer before new serialise/ deserialise

### ISSUE THREAD

**Issue by YogKar** [bblanchon/ArduinoJson#1015]
How to clean buffer before we start new serialise or deserialise?

**Comment by bblanchon** [comment]
Hi @YogKar,

To serialize/deserialize a new JSON document, create a new [JsonDocument](https://arduinojson.org/v6/api/jsondocument/).

Alternatively, you can call [JsonDocument::clear()](https://arduinojson.org/v6/api/jsondocument/clear/).

Best Regards,
Benoit
