### ISSUE TITLE
Problem Parsing String from OpenWeatherMap

### ISSUE THREAD

**Issue by tonyc770** [bblanchon/ArduinoJson#1019]
I am using 6.11.0 and am having issues parsing the weather data.
I pass a String to the function below, but it does not parse the data as expected.
I utilized the Size method here from your Assistant page:
`const size_t capacity = JSON_ARRAY_SIZE(3) + 2*JSON_OBJECT_SIZE(1) + JSON_OBJECT_SIZE(2) + 3*JSON_OBJECT_SIZE(4) + JSON_OBJECT_SIZE(5) + JSON_OBJECT_SIZE(6) + JSON_OBJECT_SIZE(12) + 340;
DynamicJsonDocument doc(capacity);`

And here is my function:
`void ParseJSON(String JSON)
{
  deserializeJson(doc, JSON);

  float coord_lon = doc["coord"]["lon"]; // -0.13
  float coord_lat = doc["coord"]["lat"]; // 51.51
  
  JsonArray weather = doc["weather"];
  
  JsonObject weather_0 = weather[0];
  int weather_0_id = weather_0["id"]; // 301
  const char* weather_0_main = weather_0["main"]; // "Drizzle"
  const char* weather_0_description = weather_0["description"]; // "drizzle"
  const char* weather_0_icon = weather_0["icon"]; // "09n"
  
  JsonObject weather_1 = weather[1];
  int weather_1_id = weather_1["id"]; // 701
  const char* weather_1_main = weather_1["main"]; // "Mist"
  const char* weather_1_description = weather_1["description"]; // "mist"
  const char* weather_1_icon = weather_1["icon"]; // "50n"
  
  JsonObject weather_2 = weather[2];
  int weather_2_id = weather_2["id"]; // 741
  const char* weather_2_main = weather_2["main"]; // "Fog"
  const char* weather_2_description = weather_2["description"]; // "fog"
  const char* weather_2_icon = weather_2["icon"]; // "50n"
  
  const char* base = doc["base"]; // "stations"
  
  JsonObject main = doc["main"];
  float main_temp = main["temp"]; // 281.87
  int main_pressure = main["pressure"]; // 1032
  int main_humidity = main["humidity"]; // 100
  float main_temp_min = main["temp_min"]; // 281.15
  float main_temp_max = main["temp_max"]; // 283.15
  
  int visibility = doc["visibility"]; // 2900
  
  float wind_speed = doc["wind"]["speed"]; // 1.5
  
  int clouds_all = doc["clouds"]["all"]; // 90

  long dt = doc["dt"]; // 1483820400
  
  JsonObject sys = doc["sys"];
  int sys_type = sys["type"]; // 1
  int sys_id = sys["id"]; // 5091
  float sys_message = sys["message"]; // 0.0226
  const char* sys_country = sys["country"]; // "GB"
  long sys_sunrise = sys["sunrise"]; // 1483776245
  long sys_sunset = sys["sunset"]; // 1483805443
  
  long id = doc["id"]; // 2643743
  const char* name = doc["name"]; // "London"
  int cod = doc["cod"]; // 200

  //Print Out Weather Data
  Serial.println("Current Kennesaw Weather Conditions");
  String wx = String(weather_0_description);
  wx.toUpperCase();
  Serial.println(wx);
  float tempF = ((main_temp - 273.15)*9)/5 +32.0;
  Serial.print("Temperature: ");
  Serial.print(tempF);
  Serial.println("F");
}
`

**Comment by bblanchon** [comment]
Hi @tonyc770 ,

What platform are you using?
What is the result of [deserializeJson()](https://arduinojson.org/v6/api/json/deserializejson/)?

Best Regards,
Benoit
