### ISSUE TITLE
register deprecated error with clang

### ISSUE THREAD

**Issue by Slechtvalk** [bblanchon/ArduinoJson#102]
Hi, I got this error when compiling ArduinoJSON on FreeBSD 10.2 (CLang) :+1: 

/opslag/home/oldenburgh/techniek/Variosystem/software/swexternals/software/extern/json/ArduinoJson/src/Internals/JsonParser.cpp:19:3: error: 'register' storage class specifier is deprecated [-Werror,-Wdeprecated-register]
  register const char *ptr = skipSpacesAndComments(_readPtr);
  ^~~~~~~~~
1 error generated.

I think the solution is one of these 

1. drop the register keyword.

2.use a pragma to turn of the error on clang, like
 #pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-register"
< json code >
#pragma clang diagnostic pop

Greetings,

Ewout Boks

**Comment by bblanchon** [comment]
Fixed. Thanks.
