### ISSUE TITLE
use of this library with Arduino Uno and SIM808 module

### ISSUE THREAD

**Issue by AnkyXCoder** [bblanchon/ArduinoJson#1029]
how to use this library with Arduino Uno and SIM808.?
I want to send data to firebase from Arduino Uno through SIM808 GPRS and HTTPS commands.
How do I do that?

**Comment by bblanchon** [comment]
Hi @ankit5036,

I don't know about the SIM808, but you cannot do HTTPS with Arduino UNO.
You'll need a more powerful microcontroller, like an ESP8266.

Best Regards,
Benoit
