### ISSUE TITLE
Compile Error in src/ArduinoJson/Strings/SizedFlashStringAdapter.hpp

### ISSUE THREAD

**Issue by l-gothberg** [bblanchon/ArduinoJson#1036]
Installed Version: 6.11.1

Installed via Arduino library manager.  Version 5.13.5 seems to work fine.  Testing reveals that even declaring the `#include <ArduinoJson.h>` is enough to replicate error.  All searching for documentation of this issue has come up nil.

Error Message:
Line 72:  strncmp_P was not declared in this scope.
    return -strncmp_P(other, reinterpret_cast<const char*>(_str), _size);

**Comment by bblanchon** [comment]
Hi @l-gothberg,

This error happens on platforms that define `PROGMEM` but don't provide the required functions like `strncmp_P()`.
To workaround this problem, you need to define [ARDUINOJSON_ENABLE_PROGMEM](https://arduinojson.org/v6/api/config/enable_progmem/) to 1.

Best Regards,
Benoit

**Comment by l-gothberg** [comment]
@bblanchon Thanks for the feedback.  

I updated to 6.11.1 and added the `#define ARDUINOJSON_ENABLE_PROGMEM 1` to my code, but still get the same error.  Would it be anything related to the fact that I'm using a Particle Xenon instead of a standard Arduino?  Everything else seems to be working fine, if I can solve this issue.

I should probably also note that I have tried using both the library manager (via VS Code and the Particle Workbench Extension) AND a manual install from the GitHub source with the same result.

Running on Particle Xenon
deviceOS v1.1.1
ArduinoJson v6.11.1
Full source file attached here: [xenon-desk-controls.ino.zip](https://github.com/bblanchon/ArduinoJson/files/3353297/xenon-desk-controls.ino.zip)


Here's the full output of the compile error:
```> Executing task: make -f '/Users/leo/.particle/toolchains/buildscripts/1.5.1/Makefile' compile-user -s <

Creating /Users/leo/Desktop/github/home-mesh-devices/xenon-desk-controls/target/module_user_memory.ld ...
In file included from /Users/leo/Desktop/github/home-mesh-devices/xenon-desk-controls/lib/ArduinoJson/src/ArduinoJson/Strings/StringAdapters.hpp:35:0,
                 from /Users/leo/Desktop/github/home-mesh-devices/xenon-desk-controls/lib/ArduinoJson/src/ArduinoJson/Misc/SerializedValue.hpp:7,
                 from /Users/leo/Desktop/github/home-mesh-devices/xenon-desk-controls/lib/ArduinoJson/src/ArduinoJson/Variant/VariantData.hpp:7,
                 from /Users/leo/Desktop/github/home-mesh-devices/xenon-desk-controls/lib/ArduinoJson/src/ArduinoJson/Array/ArrayRef.hpp:7,
                 from /Users/leo/Desktop/github/home-mesh-devices/xenon-desk-controls/lib/ArduinoJson/src/ArduinoJson.hpp:17,
                 from /Users/leo/Desktop/github/home-mesh-devices/xenon-desk-controls/lib/ArduinoJson/src/ArduinoJson.h:9,
                 from /Users/leo/Desktop/github/home-mesh-devices/xenon-desk-controls/src/xenon-desk-controls.ino:7:
/Users/leo/Desktop/github/home-mesh-devices/xenon-desk-controls/lib/ArduinoJson/src/ArduinoJson/Strings/SizedFlashStringAdapter.hpp: In member function 'int8_t ArduinoJson6111_11000::SizedFlashStringAdapter::compare(const char*) const':
/Users/leo/Desktop/github/home-mesh-devices/xenon-desk-controls/lib/ArduinoJson/src/ArduinoJson/Strings/SizedFlashStringAdapter.hpp:18:72: error: 'strncmp_P' was not declared in this scope
     return -strncmp_P(other, reinterpret_cast<const char*>(_str), _size);
                                                                        ^
make[3]: *** [../build/target/user/platform-14-m/xenon-desk-controls/src/xenon-desk-controls.o] Error 1
make[2]: *** [user] Error 2
make[1]: *** [modules/xenon/user-part] Error 2
make: *** [compile-user] Error 2
The terminal process terminated with exit code: 2

Press any key to close the terminal.```

**Comment by bblanchon** [comment]
I'm sorry, I made a mistake in my previous message 🤦‍♂️
You must define it to `0` (and not `1`)

**Comment by l-gothberg** [comment]
Ah!  Thanks!  All good now.
