### ISSUE TITLE
assign json value to variable

### ISSUE THREAD

**Issue by AlexFundorin** [bblanchon/ArduinoJson#1041]
ArduinoJson 6 on vscode with platformio. Using is with ESP32.
I have a "config.json" file in SPIFFS partition.
```
{
    "testString1": "text",
    "testString2": "notext"
}
```

I also have a variable:
```
 char* testString = "false";
```
What I need is to assign "testString1"s "text" value to testString variable.

This is my code so far:
```
void flashSetup(){
    SPIFFS.begin();
    File configFile = SPIFFS.open("/config.json");
    StaticJsonDocument<512> doc;
    deserializeJson(doc, configFile);
    testString = (char*)doc["testString1"];
}
```

What would be the right code to be able to successfully assign that value to the variable?
For now I'm getting different types of errors, while trying to perform the assignment.
The most recent one is:
```
error: invalid conversion from 'ArduinoJson6111_00000::VariantAs<char*>::type {aka const char*}' to 'char*' [-fpermissive]
```

**Comment by bblanchon** [comment]
Hi @AlexFundorin,

You should change the type of `testString` to `const char*`.

See also:

* [FAQ: Error: invalid conversion from 'const char*' to 'char*' [-fpermissive]](https://arduinojson.org/v6/faq/error-invalid-conversion-from-const-char-to-char/)

Best Regards,
Benoit

**Comment by AlexFundorin** [comment]
Thank you. The issue was that I was printing testString's pointer instead of it's value.
