### ISSUE TITLE
Error: deserializeJson IncompleteInput error in ESP-01,But working perfectly in ESP8266-12E

### ISSUE THREAD

**Issue by shaikabdulazeez** [bblanchon/ArduinoJson#1043]
Hello all,

I am using **ESP8266-01(1M),ESP8266-12E(4M)** and saving some data into these modules by using SPIFFS and ArduinoJSon. The below code working perfectly in ESP8266-12E.But in ESP8266-01 it is giving this error **Error: deserializeJson IncompleteInput** i searched internet but i didn't get proper solution.i am new to this programming Please help for this problem.   

This is original code

#include **<FS.h>**
#include <ArduinoJson.h>
const char* json = "{\"ssid\":\"DeveloperZone\",\"password\":\"power2018\"}"
void setup()
{

  Serial.begin(115200);
  delay(1000);
  SPIFFS.begin();
  
  if (SPIFFS.format()) {
    Serial.println("formated");
  } else
  {
    Serial.println("not formated");
  }

//adding data to file using ArduinoJson
  const size_t capacity = JSON_OBJECT_SIZE(3) + 70;
  StaticJsonDocument<capacity> doc;
  deserializeJson(doc, json);
  File configFile = SPIFFS.open("/config.json", "w");
  JsonObject object = doc.as<JsonObject>();
  object["light_status"] = "LOW";
  if (serializeJson(doc, configFile) == 0) {
    Serial.println("failed to write file");
  }
  configFile.close();

//retrieving  data to file using ArduinoJson
  if (SPIFFS.exists("/config.json")) {
    const char * _ssid = "", *_pass = "";
    String light_status;
    File configFile = SPIFFS.open("/config.json", "r");
    if (configFile) {
      const size_t capacity = JSON_OBJECT_SIZE(3) + 70;
      StaticJsonDocument<capacity> doc;
      DeserializationError error = deserializeJson(doc, configFile);
      configFile.close();
      if (error) {
        Serial.println(F("Error: deserializeJson"));
        Serial.println(error.c_str());
      } else {
        _ssid = doc["ssid"];
        _pass = doc["password"];
        light_status = doc["light_status"].as<String>();;
        Serial.println(_ssid);
        Serial.println(_pass);
        Serial.println(light_status);
        delay(1000);
      }
    }
  }
}

void loop()
{
  
}

**Comment by bblanchon** [comment]
Hi @shaikabdulazeez,

Make sure your file isn't empty, because ArduinoJson returns [`IncompleteInput`](https://arduinojson.org/v6/api/misc/deserializationerror/) when the input is empty.

If it's not empty, you can use [ReadLoggingStream](https://github.com/bblanchon/ArduinoStreamUtils) to see were the reading stops.

Anyway, it's likely to be a problem with the ESP8266-01, so try to tweak the SPIFFS configuration or test with another board.

Best Regards,
Benoit
