### ISSUE TITLE
json buffer problem past 1 week i keep on trying it is showing this problem

### ISSUE THREAD

**Issue by sujithkumarjp** [bblanchon/ArduinoJson#1047]
Build options changed, rebuilding all
In file included from C:\Users\admin\Documents\Arduino\libraries\firebase-arduino-0.3\src/Firebase.h:30:0,

             from C:\Users\admin\Documents\Arduino\libraries\firebase-arduino-0.3\src/FirebaseArduino.h:22,

             from C:\Users\admin\Documents\Arduino\libraries\firebase-arduino-0.3\examples\FirebaseDemo_ESP8266\FirebaseDemo_ESP8266.ino:21:
C:\Users\admin\Documents\Arduino\libraries\firebase-arduino-0.3\src/FirebaseObject.h:109:11: error: StaticJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6

 std::shared_ptr<StaticJsonBuffer<FIREBASE_JSONBUFFER_SIZE>> buffer_;

       ^
In file included from C:\Users\admin\Documents\Arduino\libraries\firebase-arduino-0.3\src/FirebaseArduino.h:22:0,

             from C:\Users\admin\Documents\Arduino\libraries\firebase-arduino-0.3\examples\FirebaseDemo_ESP8266\FirebaseDemo_ESP8266.ino:21:
C:\Users\admin\Documents\Arduino\libraries\firebase-arduino-0.3\src/Firebase.h:86:11: error: StaticJsonBuffer is a class from ArduinoJson 5. Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6

std::shared_ptr<StaticJsonBuffer<FIREBASE_JSONBUFFER_SIZE>> buffer_;

       ^
exit status 1
Error compiling for board LOLIN(WEMOS) D1 R2 & mini.

**Comment by bblanchon** [comment]
Hi @sujithkumarjp,

I think firebase-arduino still uses ArduinoJson v5, so you need to downgrade ArduinoJson from the library manager.

Best Regards,
Benoit

**Comment by sujithkumarjp** [comment]
Thank you so much

**Comment by bblanchon** [comment]
You're welcome @sujithkumarjp.
Thank you for using ArduinoJson.
