### ISSUE TITLE
Typo in documentation for `JsonDocument::memoryUsage()`

### ISSUE THREAD

**Issue by sticilface** [bblanchon/ArduinoJson#1053]
Sorry for the deluge of tickets:

Easy fix in example: 

https://arduinojson.org/v6/api/jsondocument/memoryusage/

`Serial.println(doc.memoryUage());`
should read
`Serial.println(doc.memoryUsage());`

**Comment by bblanchon** [comment]
Fixed!

**Comment by bblanchon** [comment]
Thank you very much for reporting this problem.
