### ISSUE TITLE
Problem in transforming a Json into char *

### ISSUE THREAD

**Issue by LucaSalgado** [bblanchon/ArduinoJson#1054]
I have this Json file that I need to turn into char *:

{
   "@context": [
      "https://www.w3.org/2019/wot/td/v1",
      {
      "cov": "http://www.example.org/coap-binding#"
      }
    ],
    "id": "ID",
    "title": "LedTempHum",
    "description" : "Sensing led, temperature, humidity",
	 "securityDefinitions": { "nosec_sc": { "scheme": "nosec" }},
    "security": "nosec_sc",
    "properties": {
       "status-led": {
            "description" : "Shows the current status of the led (on or off)",
            "type": "string",
            "forms": [{
                "op": "readproperty",
                "href": "coaps://IP:PORT/ligthled",
                "cov:methodName" : "GET" 
            }]
        },
		"status-dht11": {
            "description" : "Shows the current temperature and humidity of the sensor DHT11",
            "type": "string",
            "forms": [{
                "op": "readproperty",
                "href": "coaps://IP:PORT/dht11",
                "cov:methodName" : "GET" 
            }]
      },
	 	"status-dht22": {
            "description" : "Shows the current temperature and humidity of the sensor DHT22",
            "type": "string",
            "forms": [{
                "op": "readproperty",
                "href": "coaps://IP:PORT/dht22",
                "cov:methodName" : "GET" 
            }]
      }
    },
    "actions": {
        "toggle": {
            "description" : "Turn on or off the led",
            "forms": [{
                "href": "coaps://IP:PORT/lightled",
                "cov:methodName" : "POST" 
            }]
        }
    }
}

The arduino does not accept this as char * and as it must be written in the code to be sent, it can not be received from an external source.

How do I convert this .json into a char *? Is there a way to convert this to a JsonDocument?

**Comment by bblanchon** [comment]
Hi @LucaSalgado,

Please look at the examples [JsonParserExample.ino](https://arduinojson.org/v6/example/parser/) and [JsonGeneratorExample.ino](https://arduinojson.org/v6/example/generator/)

Best Regards,
Benoit
