### ISSUE TITLE
Typo : rename the name of memoryUsage in exemple

### ISSUE THREAD

**Issue by anctsys** [bblanchon/ArduinoJson#1056]
Hi
In example to use memoryUsage 
You have an typo error , you use memoryUage  instadeof memoryUsage
https://arduinojson.org/v6/api/jsondocument/memoryusage/
Bruno

**Comment by bblanchon** [comment]
Hi Bruno,

Thank you very much for reporting this typo.
It was already reported in #1053, but I forgot to push the change 😕

Best Regards,
Benoit
