### ISSUE TITLE
use ArduinoJson library on IAR STM8

### ISSUE THREAD

**Issue by smnikzad91** [bblanchon/ArduinoJson#1057]
hi
how i should integrate this library on IAR for STM8 and even KEIL for stm32 ?
in iar stm8 i got error said :
Fatal Error[Pe035]: #error directive: ArduinoJson requires a C++ compiler, please change file extension to .cc or .cpp C:\Users\sm\Desktop\Project\stm8\test\ArduinoJson.h 15

**Comment by bblanchon** [comment]
Hi @smnikzad91,

I think the error message is pretty clear:

> ArduinoJson requires a C++ compiler, please change file extension to .cc or .cpp

What else do you need?

Best Regards,
Benoit
