### ISSUE TITLE
not able to send json data to a webserver

### ISSUE THREAD

**Issue by jenish-jain** [bblanchon/ArduinoJson#1066]
hello, I am using the serialized JSON function to read some sensor values and convert them to JSON , I want to send those values to a route I have created on the webserver hosted on esp working in AP mode, I tried doing serializeJson(doc, client); but getting no success I am attaching the send JSON function I have made for further understanding.

`void SendJSONtemp() {
  //{"current_temperature":"5","sensor_one":"4.84","sensor_two":"5.16","sensor_three":"5.16","success":1,"message":"Indoor Current Temperature Data successfully received."}
  server.handleClient();
  Serial.println("entered send json");
const size_t capacity = JSON_OBJECT_SIZE(6);
DynamicJsonDocument doc(capacity);

doc["current_temperature"] = R_temp;
doc["sensor_one"] = t1;
doc["sensor_two"] = t2;
doc["sensor_three"] = t3;
doc["success"] = 1;
doc["message"] = "Indoor Current Temperature Data successfully received.";

serializeJson(doc, client);

}`

**Comment by bblanchon** [comment]
Hi @jenish-jain,

The JSON serialization should be done in the callback.
Please read the documentation of ESP web server or find an example on Internet.

Best Regards,
Benoit
