### ISSUE TITLE
Can arduinojson be made more intelligent in parsing?

### ISSUE THREAD

**Issue by Daemach** [bblanchon/ArduinoJson#1067]
I recently tried test driving cloudflare and my devices started breaking.  For some reason their service is both prepending and appending a bit of garbage to the json packet causing parsing to break down.  In this case the garbage was "290\n" prepended and "\n\n0" appended.  But the json packet itself was intact.  Can the parser be made more intelligent by doing a find for an opening { or { and stopping the parse at the last } or ] that it encounters and discarding everything else?

**Comment by bblanchon** [comment]
Hi @Daemach,

The "garbage" you see is HTTP's [Chunked transfer encoding](https://en.wikipedia.org/wiki/Chunked_transfer_encoding).
It is not the job of the library to remove these markers.

A few options for you:

* use HTTP 1.0 to avoid Chunked transfer encoding
* skip the markers in your program
* use a library that handles HTTP 1.1 properly

Best Regards,
Benoit
