### ISSUE TITLE
Saving JSON to file  question

### ISSUE THREAD

**Issue by mistergreen** [bblanchon/ArduinoJson#1075]
This is more general question. I'm planning to save multiple devices settings onto a SD card, JSON format, for recovery situations. When I make a change on 1 device, can I save and affect that one device JSON branch in the SD card? Or do I need to gather all devices settings, and rewrite all of the JSON data on the SD card?

**Comment by bblanchon** [comment]
Hi @mistergreen,

I'm sorry I don't understand the question.
Can you clarify?

Best Regards,
Benoit

**Comment by mistergreen** [comment]
I'll try to be more clear. Can I alter and save a node (in a JSON tree) on the SD card or is it easier to create a whole new JSON tree with the altered node and unaltered nodes and save that to the SD card?

It's kind of like SQL query, UPDATE a record or rewrite the whole database table.

**Comment by bblanchon** [comment]
No, ArduinoJson doesn't allow editing a value in a file.
Instead, you must load the whole file, edit the value, and save the whole file.

**Comment by mistergreen** [comment]
thanks.
