### ISSUE TITLE
Library can't parse JSON with [] as parent

### ISSUE THREAD

**Issue by yuriyfedyuk** [bblanchon/ArduinoJson#1076]
Hello,
I'm using ESP32 board.

Can't parse JSON with next format
[{
"product_id":"0000"
}]

This JSON can be parsed:
{
"product_id":"0000"
}

Web assistant shows that it should be parsed. I'm using ArduinoJSON ver5

**Comment by bblanchon** [comment]
Hi @yuriyfedyuk,

Did you call [parseArray()](https://arduinojson.org/v5/api/jsonbuffer/parsearray/) or [parseObject()](https://arduinojson.org/v5/api/jsonbuffer/parseobject/)?
Are you sure the [JsonBuffer](https://arduinojson.org/v5/api/jsonbuffer/) is big enough?

Best Regards,
Benoit

**Comment by yuriyfedyuk** [comment]
Hi @bblanchon,

I'm sure that JsonBuffer is big enough. As an example, I used a small part of my JSON string.
In code I call parseObject().

**Comment by yuriyfedyuk** [comment]
It works with parseArray() call.
