### ISSUE TITLE
Cant get a data from Json string V6

### ISSUE THREAD

**Issue by GdLakeIoT** [bblanchon/ArduinoJson#1078]
Hi,
I have been tying to get all that data from the string below.
{"nodeId":2755343285,"subs":[{"nodeId":3290279261,"root":true,"subs":[{"nodeId":2013506667}]}]}

I have replaced the " so the string is 

"{\"nodeId\":2755343285,\"subs\":[{\"nodeId\":3290279261,\"root\":true,\"subs\":[{\"nodeId\":2013506667}]}]}"

What I need exactly need it to be able to get the NodeID that has Root = True
I just cant seem to get it to work.
Any help, links or suggestion will be appreciated.

**Comment by bblanchon** [comment]
Hi @GdLakeIoT,

Please check out the [examples](https://arduinojson.org/v6/example/) and the [ArduinoJson Assistant](https://arduinojson.org/v6/assistant/).

Best Regards,
Benoit

**Comment by GdLakeIoT** [comment]
Hi @bblanchon  
THANK YOU SO MUCH!.
I can now get the data that I need. The assistant will be very time saving.... 
Regards, 
George.
PS. Your work is incredible... :-)

**Comment by bblanchon** [comment]
You're welcome George!
Don't hesitate to [cast a star](https://github.com/bblanchon/ArduinoJson/stargazers) to support ArduinoJson ;-)
Good luck with your project.
