### ISSUE TITLE
How to deserialize json in arduino JSON 6

### ISSUE THREAD

**Issue by Project786** [bblanchon/ArduinoJson#1079]
I have an Arduino mega and Nodemcu. I am trying to send data from Arduino mega to Nodemcu using "ArduinoJson" library. I am able to send data with JSON 5 but not with JSON 6. Below is my code:

**Arduino Mega:**

`void loop()
{
StaticJsonDocument<1000> doc;
JsonObject root = doc.to JsonObject () ;
root["data1"] = 50;
root["data2"] = 70;

serializeJson(doc, Serial1);
}`

**Nodemcu Code:**

`void loop()
{
StaticJsonDocument<1000> doc;
deserializeJson(doc, Serial);

JsonObject root = doc.as JsonObject () ;
 
  Serial.println("JSON received and parsed");
  serializeJsonPretty(doc, Serial);
  Serial.print("Data 1 ");
  Serial.println("");
  int data1=root["data1"];
  Serial.print(data1);
  Serial.print("   Data 2 ");
  int data2=root["data2"];
  Serial.print(data2);
  Serial.println("");
  Serial.println("---------------------xxxxx--------------------");
}
`

**Comment by bblanchon** [comment]
Hi @Project786,

What is the problem exactly?

Best Regards,
Benoit

**Comment by Project786** [comment]
Thankyou so much for your reply.

The scenario is as follows:

--I am trying to send data from Arduino Mega to Nodemcu using the Arduino
Json library. I am connecting the TX of the Nodemcu to the RX of the
Arduino Mega and the RX of the Nodemcu to the TX of the Arduino Mega.
--I am able to send data using Arduino Json 5 library.
--This is the link I used to send data using Arduino Json 5 library:*
https://mybtechprojects.tech/serial-communication-between-nodemcu-and-arduino/
<https://mybtechprojects.tech/serial-communication-between-nodemcu-and-arduino/>.*

My issue is as follows:

--I am able to send data with Arduino Json 5 library so there is no problem
with that.
--*My main issue is that I want to use the newer Arduino Json library,
which is version 6, but I'm not able to have success with that.*

I have attached four *.ino* files for your reference. The first two files
are using the Arduino Json 5 library which works nicely.
In the other two files, I've tried using Arduino Json 6 but without success.

I have named the files appropriately.

I hope this email finds you well and I look forward to hearing from you
soon.

Thanks
Project786

Le mer. 28 août 2019 à 18:59, Benoît Blanchon <notifications@github.com> a
écrit :

**Comment by bblanchon** [comment]
>  but I'm not able to have success with that

What do you mean?
Did you get a compilation error? a runtime error? a crash?

**Comment by Project786** [comment]
No errors, no crashes.

Its just that after uploading, I open the serial monitor of the Nodemcu
side, I get null and 0 values.
With Json 5 I receive the data at the Nodemcu side but not with Json 6.

Le lun. 2 sept. 2019 à 15:17, Benoît Blanchon <notifications@github.com> a
écrit :

**Comment by ewaldc** [comment]
When you say "no error", does _deserializeJson(doc, Serial);_ return no error ?
I am having a challenge with deserialize from stream too, but in my case I am getting an error code back (but no crash)

**Comment by Project786** [comment]
I don't get any errors with any statement. The only thing is with the serial monitor which isn't showing any value. Monday, 02 September 2019, 03:49pm +08:00 from Ewald Comhaire  notifications@github.com :

**Comment by bblanchon** [comment]
We don't have enough information to help you.
Can you share both the v5 and v6 programs? I may be able to spot the mistake.

**Comment by salmanfarisvp** [comment]
Try to allocate the memory using [ArduinoJson Assistant](https://arduinojson.org/v6/assistant/)  , I got the same error (returning only zero) and it was solved by using [ArduinoJson Assistant](https://arduinojson.org/v6/assistant/)

**Comment by ewaldc** [comment]
I found a few cases in V6 (different in V5) where ArduinoJson will flag no error but your deserialized JsonDocument can still be _null_.  For example, if you deserialize in a function, _deserializeJson_ may succeed, but _return jsonDoc_ may still fail if you are running (too) low in heap space since it will fully duplicate the _JsonDoc_.  So you will need to check if the returned document is not null using _returnedJsonDoc.isNull()_
```
error = deserializeJson(jsonDoc, jsonString);
if (!error) return jsonDoc;
```
PS. On nodeMCU/ESP, you can check in the function whether _return jsonDoc;_ will succeed.
You will want to keep some margin for high priority functions (e.g. WifiHandler).
```
error = deserializeJson(jsonDoc, jsonString);
if (!error && ((ESP.getFreeHeap() - jsonDoc.measureLength()) > 4096) return jsonDoc;
... // error processing here
```
Of course, if you share your whole code, we might be able to help you better (and avoid guesswork)
