### ISSUE TITLE
Fault when changing Json 5 to Json 6

### ISSUE THREAD

**Issue by amauryverschooren** [bblanchon/ArduinoJson#1080]
hi,
I wanted to change my arduino sketch to Json 6 and came to an issue.
tried and solve it with the change tutorial but can't get rid of the error.

```
void sendState() {
  StaticJsonDocument<BUFFER_SIZE> jsonDocument;

  JsonObject root = jsonDocument.to<JsonObject>();

  root["state"] = (stateOn) ? on_cmd : off_cmd;
  JsonObject& color = root.createNestedObject("color");
  color["r"] = red;
  color["g"] = green;
  color["b"] = blue;

  root["brightness"] = brightness;
  root["effect"] = effectString.c_str();
  root["white_value"] = map(transitionTime, 1,150, 0, 255);

  char buffer[root.measureLength() + 1];
  root.printTo(buffer, sizeof(buffer));

  client.publish(light_state_topic, buffer, true);
}
```

ERROR

`exit status 1
invalid initialization of non-const reference of type 'ArduinoJson::JsonObject& {aka ArduinoJson6115_000001::ObjectRef&}' from an rvalue of type 'ArduinoJson6115_000001::ObjectRef'`

Somebody that can help?
Thanks!

**Comment by bblanchon** [comment]
Hi @amauryverschooren,

You need to remove the `&` because ArduinoJson 6 returns values, not references.
It's the first topic covered by the tutorial: https://arduinojson.org/v6/doc/upgrade/

Best Regards,
Benoit
