### ISSUE TITLE
duplicate key

### ISSUE THREAD

**Issue by ilyasamraoui** [bblanchon/ArduinoJson#1095]
Hi,
DesrializationError validate json char array that has duplicate key

**Comment by bblanchon** [comment]
Hi @ilyasamraoui,

Indeed, the goal of ArduinoJson is to offer a lightweight parser for embedded platforms and not a JSON validator.
I don't think it's worth increasing the size of the code for such an edge case.

Do you have a use case where detecting duplicate keys is crucial?

Best Regards,
Benoit

**Comment by bblanchon** [comment]
I just made the test and the code grew by only 26 bytes; so that may be worth it.
But do we really need this?

**Comment by bblanchon** [comment]
Looking at [this question on stackoverflow](https://stackoverflow.com/q/21832701/1164966), I realized that duplicate keys are not illegal and are accepted by most implementations.

All major implementations keep the last value:

* Chrome 77: `JSON.parse('{"a":1,"a":2}')` -> `{a: 2}`
* IE 11: `JSON.parse('{"a":1,"a":2}')` -> `{a: 2}`
* Edge 44: `JSON.parse('{"a":1,"a":2}')` -> `{a: 2}`
* Firefox 68: `JSON.parse('{"a":1,"a":2}')` -> `{a: 2}`
* Python 3.6.8: `json.loads('{"a":1,"a":2}')` -> `{'a': 2}`
* Ruby: `JSON.parse('{"a":1,"a":2}')` -> `{"a"=>2}`

So `deserializeJson()` should return `Ok`, but the `JsonDocument` should contain the last value.

**Comment by ilyasamraoui** [comment]
ok i see, i used jsonlint.com to validate json object with duplicate key and it didn't validate it

**Comment by bblanchon** [comment]
Fix published in [ArduinoJson 6.13.0](https://github.com/bblanchon/ArduinoJson/releases/tag/v6.13.0)
