### ISSUE TITLE
serializeMsgPack with integers

### ISSUE THREAD

**Issue by vangalvin** [bblanchon/ArduinoJson#1097]
I have a sensor array of about 40 sensors and will be transmitting the data via a sat link. every byte counts :)

An interesting thing I just found was that if I add the int (4 digits per reading) to the json doc then pack it the compression/saving is minimal. however if I convert the digits in to a sting then pack it the compression/saving seems to be a lot higher.

I may convert the digits to hex and see if that improves things unless anyone has any other suggestions?

Eventually the output has to be converted to binary as the sat modem requires binary data to be sent to it for transmission.

**Comment by bblanchon** [comment]
Hi @vangalvin,

Using integers should lead to smaller serialized messages because ArduinoJson picks the smallest possible representation.

See the following demo, you'll see that strings take twice more space:
https://wandbox.org/permlink/4vq8ggloNAoMBu2Z

Best Regards,
Benoit

**Comment by vangalvin** [comment]
@bblanchon thanks for that, makes a little more sense now and that example gave me a few other ideas how to pack the data down a little more.

**Comment by bblanchon** [comment]
You're welcome @vangalvin! Good luck with your project.
Don't hesitate to star the project on GitHub to show your support ;-)
