### ISSUE TITLE
void clear();

### ISSUE THREAD

**Issue by Pratikm78** [bblanchon/ArduinoJson#1100]
I am creating a json doc then storing in a char array. Then creating a another json doc and overwriting the char array. But i need to clear the contents of the first json doc. 

i tried using clear();

however says the "clear" not defined in the scope.

**Comment by bblanchon** [comment]
Hi @Pratikm78,

Please show a small code snippet that triggers the error.
Also, please copy/paste the compiler output.

Best Regards,
Benoit
