### ISSUE TITLE
Delete objectin loop

### ISSUE THREAD

**Issue by ssduracell** [bblanchon/ArduinoJson#1102]
hello 
for a project i was playing around with Arduino json and after reading the docs i came tothe conclusion you cant delete object in a loop (memory leaks) . So now is my question what if i do want to remove an objectin a loop, whats the best way of doing it?

thanks!

**Comment by bblanchon** [comment]
Hi @ssduracell,

Can you describe your use-case?
Why do you have to delete objects in a loop?

Best Regards,
Benoit
