### ISSUE TITLE
cannot include base64 image string to json

### ISSUE THREAD

**Issue by ligantx** [bblanchon/ArduinoJson#1105]
i use esp32-cam and i want to include an image in base64 encoding to a json i create..
if i copy a base64 long image string inside code it works fine:
```
Serial.println(base64image); //shows the current base64 image String correctly
JsonObject requests_0_image["content"];
requests_0_image["content"] = "/9j/4AA....long base64 String..."
serializeJson(doc, myJsonString);
Serial.println(myJsonString); //Json is fine
```

if i try:
```
Serial.println(base64image); //shows the current base64 image String correctly
JsonObject requests_0_image["content"];
requests_0_image["content"] = base64image;
serializeJson(doc, myJsonString);
Serial.println(myJsonString); //Json is like {"requests":[{"image":{"content":null},.....
```
is also tried:
`requests_0_image["content"] = serialized(base64image);
`
but its also doesnt work..
important: if i use a small String as base64image the code works fine..
so, i guess it has to do with String length (i read that " the content of the String will be duplicated in the JsonDocument" so i guess it is causing the problem)

**Comment by bblanchon** [comment]
Hi @ligantx,

Indeed ArduinoJson duplicates `char*` and `String`s in the `JsonDocument`.
To avoid this duplication, you must pass a `const char*`.

In your case, you can do:

```c++
requests_0_image["content"] = base64image.c_str();
```

`String::c_str()` returns a `const char*`  pointing to the internal buffer of the `String`.
This solution works as long as you keep the `String` in memory, and you don't modify it.

Best Regards,
Benoit

**Comment by ligantx** [comment]
i'll try that and i'll post the results..
until now i found a workaround that works (after many many hours trying to figure this out) and maybe help others:
i made a function that will create and return the whole json except the "content" value (the base64image="").
Then i substring the returned json (using indexOf(content) + offset) concatenate the create base64image String and then concatenate the rest of the json (the substring from the previous indexOf till the end).
So, i finally get a big Json that includes the image, without duplicated anything..
NOTE: it works fine because my json is the same everytime except the base64image

edit: i found time to check the @bblanchon suggestion..
here are the results (and some guesses of why it does or doesnt work) :
```
void createImageJson(String base64image){
    requests_0_image["content"] = base64image; //doesn't work..it does 2 copies of the big base64image String
}
```
```
void createImageJson(String base64image){
    requests_0_image["content"] = base64image.c_str(); //works faulty..it does 1 copy of the base64image String because of String is passed by value.. more [here](https://stackoverflow.com/questions/10789740/passing-stdstring-by-value-or-reference)
}
```
```
void createImageJson(const String& base64image){
    requests_0_image["content"] = base64image.c_str(); //works fine..no copies of the base64image String because of String is passed by reference..more [here](https://arduino.stackexchange.com/questions/3059/functions-with-string-parameters) and c_str() makes it const char*
}
```

important note:
do a `doc.clear();` everytime you create a new json (at the beggining of the function) and clear final Json String before you do serialization:
```
myFinalJson = "";
serializeJson(doc, myFinalJson);
```
