### ISSUE TITLE
Unable to publish a JSON message to MQTT

### ISSUE THREAD

**Issue by nehulagr** [bblanchon/ArduinoJson#1113]
Hello, I am trying to publish a JSON message to my MQTT server. Here is how I am trying to send:

```
if (client.connect((char*) clientName.c_str(),  mqttUser, mqttPassword)) {
        Serial.println("connected");
        StaticJsonDocument<500> JSONbuffer;
        JsonObject JSONencoder = JSONbuffer.to<JsonObject>();

        JSONencoder["name"] = "Hall Computers Master";
        JSONencoder["command_topic"] = "office/switch/hall/computer/state";
        JSONencoder["state_topic"] = "office/switch/hall/computer/state";

        char JSONmessageBuffer[500];
        serializeJson(JSONbuffer, JSONmessageBuffer);        

        Serial.println(JSONmessageBuffer);

        client.publish(topic1_config, JSONmessageBuffer);
        client.publish(topic1_state, "ON");
        client.subscribe(topic1_state);
      } else {
        Serial.print("failed with state ");
        Serial.print(client.state());
        delay(100);
      }
```

With all that as well. I can get serial.println exactly how it should be. But not able to send the publish message on the topic. I don't know where I am wrong. Although my below `client.publish(topic1_state, "ON");` works very well every time.

When I am sending message from my command prompt it works very well. Here is the command 

mosquitto_pub -h 192.168.1.150 -p 8873 -t office/switch/hall/switchboard/config -u fo_officemqtt -P 0288 -m '{"name": "Hall Switch Board", "command_topic": "office/switch/hall/computer/set", "state_topic": "office/switch/hall/computer/state"}'

Just not able to send the JSON payload.

Thank you! (In advance)

**Comment by bblanchon** [comment]
Hi @nehulagr,

Assuming you're using the [PubSubClient](https://github.com/knolleary/pubsubclient) library, you're probably hitting the maximum message size, which is 128 bytes by default. See ["Limitations"](https://github.com/knolleary/pubsubclient#limitations) in the README.

Best Regards,
Benoit
