### ISSUE TITLE
Array Encoding error

### ISSUE THREAD

**Issue by asetyde** [bblanchon/ArduinoJson#113]
i want underline this error , variable pass from c to java but array seems empty ... but code seems not has error . how can i do  ? 

please help 

(mind is struct )
`JsonObject& encodejson(JsonBuffer& jsonBuffer) {`
``
`	// must included #include <ArduinoJson.h>`
`	JsonObject& root = jsonBuffer.createObject();`
``
`	//root["systemversion"] = mind.systemversion;`
`	root["set"] = mind.set;`
`	root["status"] = mind.status;`
`	root["humidity"] = mind.humidity;`
`	root["temperature"] = mind.temperature;`
`	root["delta"] = mind.delta;`
`	root["light"] = mind.light;`
`	root["isrtc"] = mind.isrtc;`
`	root["releinverted"] = mind.releinverted;`
`	root["reversesummer"] = mind.reversesummer;`
`	root["statusmachine"] = mind.statusmachine;`
`	root["ssid"] ="fghfhfgh";`
`	root["password"] = "fgdfg";`
`	root["debounceDelay"] = mind.debounceDelay;`
`	root["countWrite"] = mind.countWrite;`
`	root["counterIdShutter"] = mind.counterIdShutter;`
`	root["countAction"] = mind.countAction;`
`	root["simplyConfig"] = mind.simplyConfig;`
``
`	`
``
`	JsonArray& mac_Address = root.createNestedArray("mac_Address"); {  // byte`
`		for (int i = 0; i < 6; i++) {`
`			int value = mind.mac_Address[i];`
`			mac_Address..add(value);`
`		}`
`	}`
``

java code : 

        
             'InputStream is = null;
             BufferedReader bfReader = null;
            is = new ByteArrayInputStream(buff);
            bfReader = new BufferedReader(new InputStreamReader(is));
             JsonReader jsonReader = new JsonReader(bfReader);
             jsonReader.beginObject();
             while (jsonReader.hasNext()) {

                                String name = jsonReader.nextName();
                                if (name.equals("set")) {
                                            
                                                        int i = jsonReader.nextInt();
                                                        System.out.println(i);

                                  }
                                if (name.equals("status")) {
                                                        int e = jsonReader.nextInt();
                                                        System.out.println(e);

                                  }
                                if (name.equals("humidity")) {
                                                        double e = jsonReader.nextDouble();
                                                        System.out.println(e);

                                  }
                                if (name.equals("temperature")) {
                                                        double e = jsonReader.nextDouble();
                                                        System.out.println(e);

                                  }
                                if (name.equals("delta")) {
                                                        int e = jsonReader.nextInt();
                                                        System.out.println(e);

                                  }
                                if (name.equals("light")) {
                                                        int e = jsonReader.nextInt();
                                                        System.out.println(e);

                                  }
                                if (name.equals("isrtc")) {
                                                        int e = jsonReader.nextInt();
                                                        System.out.println(e);

                                  }
                                if (name.equals("releinverted")) {
                                                        int e = jsonReader.nextInt();
                                                        System.out.println(e);

                                  }
                                if (name.equals("reversesummer")) {
                                                        int e = jsonReader.nextInt();
                                                        System.out.println(e);

                                  }
                                if (name.equals("statusmachine")) {
                                                        int e = jsonReader.nextInt();
                                                        System.out.println(e);

                                  }
                                if (name.equals("ssid")) {
                                                        String e = jsonReader.nextString();
                                                        System.out.println(e);

                                  }
                                if (name.equals("password")) {
                                                        String e = jsonReader.nextString();
                                                        System.out.println(e);

                                  }
                                if (name.equals("debounceDelay")) {
                                                        int e = jsonReader.nextInt();
                                                        System.out.println(e);

                                  }
                                if (name.equals("countWrite")) {
                                                        int e = jsonReader.nextInt();
                                                        System.out.println(e);

                                  }
                                if (name.equals("counterIdShutter")) {
                                                        int e = jsonReader.nextInt();
                                                        System.out.println(e);

                                  }
                                if (name.equals("countAction")) {
                                                        int e = jsonReader.nextInt();
                                                        System.out.println(e);

                                  }
                                if (name.equals("simplyConfig")) {
                                                        int e = jsonReader.nextInt();
                                                        System.out.println(e);

                                  }

                                
                                
                                
                                
                                if (name.equals("mac_Address")){
                                    jsonReader.beginArray();
                                    System.out.println(jsonReader.peek());
                                    while  (jsonReader.hasNext()) {
                                             int e = jsonReader.nextInt();
                                              System.out.println(e);
                                             }
                                    jsonReader.endArray();
                                }

              }
              jsonReader.endObject();
              jsonReader.close();`

output of java : 
last zero value is the last struct variable , after start macaddress array 

![screen shot 2015-09-03 at 16 37 50](https://cloud.githubusercontent.com/assets/6162152/9661248/2217f74a-525a-11e5-8ff8-e0c14f23c6c7.png)

**Comment by bblanchon** [comment]
Can you print the output of ArduinoJson, so we can validate that the array is present?

Also in your C++ code it's written `"mac_Address`, whereas in the Java code it's `"ip"`.

**Comment by asetyde** [comment]
yes i correct , because i use old copy , no problem . thx 
i send my json to udp , you want stream of byte or ?

**Comment by bblanchon** [comment]
```c++
root.printTo(Serial);
```

**Comment by asetyde** [comment]
ok wait , also i found the problem , now al arrive but i change static to dynamic .. wait 
i

**Comment by asetyde** [comment]
Ok problem is about Static and Dynamic allocation ... Dynamic all ok .
i try to send son , 303 bytes with dynamic and same with static but with static array not arrive .

**Comment by asetyde** [comment]
But i think you must wait a board to  test , because esp is different from arduino in many thinks also  i use dynamic , output on serial  is correct.

**Comment by bblanchon** [comment]
The `StaticJsonBuffer` was probably too small.

You can use the macros `JSON_ARRAY_SIZE()` and `JSON_OBJECT_SIZE()` to compute the required size at compile time.

In your case it could be:

    #define BUFFER_SIZE (JSON_OBJECT_SIZE(19)+JSON_ARRAY_SIZE(6))

because your object contains 19 values, and there is an array with 6 elements.

**Comment by bblanchon** [comment]
PS: then if you use `String`s, you need to add the size of each because they'll be duplicated in the `StaticJsonBuffer`.

**Comment by asetyde** [comment]
ok thx .

**Comment by asetyde** [comment]
my jsonarrive to 1700~ bytes and now dynamic buffer not working , structure are corrupted . now i'll be back to jsonstatic to resolve .. i don't understand about string s that you 've said .

**Comment by asetyde** [comment]
and at now i will try to escape from stack error on static buffer .. on <8000> ....4000 , 3000 is maximum ,  i 'm back to dynamic and split struct but it's not a good thing ...
