### ISSUE TITLE
Complement of issue#1132

### ISSUE THREAD

**Issue by mois770** [bblanchon/ArduinoJson#1133]
Hi,
I tryied using toCharArray(). It didn't appear "Incomplete or Invalid Input", but it didn't processed. I used the char json[] of Quickstart, and JsonParserExample as input on Serial monitor.
But instead of:
gps
1351824120
48.756081
2.302038
(the output of JsonParser Example), I've got:

0
0.000000
0.000000

**Comment by mois770** [comment]
Hi Benoit,
I've just checked issue #1121, and your answer there solved my problem.
Thanks

**Comment by bblanchon** [comment]
Cool. I'm glad you found a solution.
Don't forget to [cast a star](https://github.com/bblanchon/ArduinoJson/stargazers) to support the library :wink:
