### ISSUE TITLE
Deserialization error

### ISSUE THREAD

**Issue by pradeep8892** [bblanchon/ArduinoJson#1136]
Hello,
I was using Wifimanage example, https://github.com/tzapu/WiFiManager/blob/master/examples/AutoConnectWithFSParametersAndCustomIP/AutoConnectWithFSParametersAndCustomIP.ino

As currently wifimanager uses ArduinoJson 5, So i upgraded all the code from version 5 to ArduinoJason version 6 using following link.
https://arduinojson.org/v6/doc/upgrade/

I resolved all the errors. But after resolving resolving everything i am getting following error, which is related to library.

**/home/pradeep/Arduino/libraries/ArduinoJson/src/ArduinoJson/Deserialization/Reader.hpp:20:26: error: 'class std::unique_ptr<char []>' has no member named 'read'
     return _source->read();

exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).**

Thanks

**Comment by bblanchon** [comment]
Hi @pradeep14581,

>     error: 'class std::unique_ptr<char []>' has no member named 'read'

It looks like you passed a `unique_ptr` to `deserializeJson()`, which is not supported.
Instead, you should get rid of the `unique_ptr` and pass the `File` directly:

```c++
deserializeJson(doc, configFile);
```

See [JsonConfigFile.ino](https://arduinojson.org/v6/example/config/) for a complete example.

Best Regards,
Benoit
