### ISSUE TITLE
Is possible to make two http.GET(); in the loop?

### ISSUE THREAD

**Issue by guarrod** [bblanchon/ArduinoJson#1139]
I need to make two http.GET(); to two different apis is this possible?

Because i need to get data from the openweathermap, and other api to get the uv index from other site

**Comment by bblanchon** [comment]
Hi @guarrod,

I guess, but you probably need to create two `HTTPClient`.
This is a question for the developers of `HTTPClient`, not for ArduinoJson.

Best Regards,
Benoit

**Comment by guarrod** [comment]
Thanks a lot for the Answer @bblanchon you are right, i will search documentation about it :)
