### ISSUE TITLE
Typo in Documentation of JsonDocument::createNestedObject()

### ISSUE THREAD

**Issue by pkerspe** [bblanchon/ArduinoJson#1149]
There is a copy&paste error on in the documenation of https://arduinojson.org/v6/api/jsondocument/createnestedobject/

`DynamicJsonDocument doc(1024);`
`JsonArray wifi  = doc.createNestedObject("wifi");`
`wifi["SSID"] = "TheBatCave";`

It should be "JsonObject" in the second line instead of "JsonArray"

**Comment by bblanchon** [comment]
Hi @pkerspe,

Thank you very much for reporting this typo.
I already fixed the page.
Don't hesitate to open a new issue if you find anything else.

Best Regards,
Benoit
