### ISSUE TITLE
serial communication between two arduino 

### ISSUE THREAD

**Issue by AshishMehar538** [bblanchon/ArduinoJson#1154]
sir I'm trying to establish communication between two Arduino's using arduinojson. and I'm facing a problem in parsing the received json.
eg I'm sending this string
               {"sensor":"gps","time":1351824120,"data":[48.75608,2.302038]}
but i'm unable to parse this string

how do I convert this into
             "{\"sensor\":\"gps\",\"time\":1351824120,\"data\":[48.75608,2.302038]}"

here is the code

![generating](https://user-images.githubusercontent.com/48563064/71473318-7700bb80-27fc-11ea-806d-7300accb97eb.jpg)

![parsing](https://user-images.githubusercontent.com/48563064/71473321-7bc56f80-27fc-11ea-8736-305d7478f2ee.jpg)

**Comment by bblanchon** [comment]
Hi @AshishMehar538,

Please clarify your question:
* what did you try?
* what happened?
* did you get an error?
* what was the error?
* can you post a code sample?

Best regards,
Benoit
