### ISSUE TITLE
arduinojson assistant does not handle // (comments)

### ISSUE THREAD

**Issue by mars000** [bblanchon/ArduinoJson#1155]
I'm using https://arduinojson.org/v6/assistant/
More of comment rather than issue. I noticed that comments in my json file (i.e. with //) process correctly in the arduino json parser however the online web assistant throws an error. Would be nice if it process them correctly i.e. ignored them :-)

**Comment by bblanchon** [comment]
Hi @mars000,

I updated the Assistant to use the JSON5 parser, which supports comments and single quotes strings.

Best regards,
Benoit
