### ISSUE TITLE
Change StaticJsonDocument to DynamicJsonDocument

### ISSUE THREAD

**Issue by luizpicolo** [bblanchon/ArduinoJson#1163]
I have this little snippet of code and when adding a new node (date time) to json I can't send the data to the server. I tried switching to  DynamicJsonDocument but I was unsuccessful (I don't think I can use  DynamicJsonDocument the right way)

```
StaticJsonDocument<200> root;

//root["datetime"] = "datetime";
root["humidity"] = dht.readHumidity();
root["temperature"] = dht.readTemperature();
String data;
serializeJson(root, data);
```

**Comment by bblanchon** [comment]
Hi @luizpicolo,

You need to increase the capacity of the [JsonDocument](https://arduinojson.org/v6/api/jsondocument/).
Use the [ArduinoJson Assistant](https://arduinojson.org/v6/assistant/) to compute the right capacity for your project.

Best regards,
Benoit
