### ISSUE TITLE
Could it be local include ("x") instead of (<x>)?

### ISSUE THREAD

**Issue by rrakso** [bblanchon/ArduinoJson#1177]
Why here is this
https://github.com/bblanchon/ArduinoJson/blob/42b0d6a83d493bfa8b5a68e1a574fc60b5673036/src/ArduinoJson/Array/ArrayRef.hpp#L7
instead of somethnig like this ` #include "ArrayFunctions.hpp"`?

These files are in the same directory
I've changed these all occurences - all files are on my local computer, I can also make pull request with my changed files is so :wink:

**Comment by rrakso** [comment]
![image](https://user-images.githubusercontent.com/23143274/73601135-28151700-455c-11ea-9757-e93d33146dc4.png)

**Comment by bblanchon** [comment]
Hi @rrakso,

I switched to this form because of issue #1072.

If that's an issue for you, why don't you use the single header distribution?
You can find it in the [release page](https://github.com/bblanchon/ArduinoJson/releases/latest).

Best regards,
Benoit

**Comment by rrakso** [comment]
Hi @bblanchon what means _single header distribution_?
Can you help me understanding it?

(P.s. my problem is resolved, I just thought that probably I can help others)

**Comment by bblanchon** [comment]
Single header means that the library fit in just one header: `ArduinoJson.h`
It's simpler to download this single file than to clone the repository.
See: https://arduinojson.org/v6/doc/installation/
