### ISSUE TITLE
Ambiguous overload for 'operator='

### ISSUE THREAD

**Issue by asetyde** [bblanchon/ArduinoJson#118]
I found a strange thing , i not understand cleary why i must say explicitly that is a string .
arduinoname is a String type.

this is issue : 

![screen shot 2015-09-14 at 12 17 17](https://cloud.githubusercontent.com/assets/6162152/9847725/5e1da170-5adb-11e5-912e-e05de3a6608e.png)

![screen shot 2015-09-14 at 12 17 28](https://cloud.githubusercontent.com/assets/6162152/9847732/67d9aede-5adb-11e5-95e9-222964029902.png)

with explicit asString , all ok : 
![screen shot 2015-09-14 at 12 16 50](https://cloud.githubusercontent.com/assets/6162152/9847704/3b275b2a-5adb-11e5-9092-3789ce3464bc.png)

It's bug or what ? thx for reply

**Comment by bblanchon** [comment]
You're right this is not the expected behavior.
I'll try to fix it, but I'm not sure it's even possible.

**Comment by asetyde** [comment]
Thx , it's not a true problem , you 've included in wiki about casting .

**Comment by bblanchon** [comment]
Please don't close it.
I'm still trying...

**Comment by asetyde** [comment]
ook

**Comment by bblanchon** [comment]
I don't think this is a solution for this.

To help new users, I added a section in `StringExample.ino` that describes this issue.
