### ISSUE TITLE
printTo(string) prints numbers

### ISSUE THREAD

**Issue by burner-** [bblanchon/ArduinoJson#120]
String buffer = "";
root.printTo(buffer);
Serial1.println(buffer);
print just a numbers at esp8266 arduino platfrom. With direct serial print it works fine but that is not suitable method with webserver. 
Using char[] as output format looks working well
String buffer = "";
char cbuf[256];
root.printTo(cbuf,sizeof(cbuf));
buffer = cbuf;
Serial1.println(buffer);

**Comment by bblanchon** [comment]
Fixed in v5.0.3.
Thanks.
