### ISSUE TITLE
Serial Communication between two Arduino Uno

### ISSUE THREAD

**Issue by CarloPirisi** [bblanchon/ArduinoJson#1204]
Hello I'm trying to have a serial communication between two Arduino Uno.
I'm simulating two random float numbers in an Arduino(tx) and I want to send this numbers to another Arduino(Rx).

- The Arduino(tx) simulates the numbers and then serialize an DynamicJsonDocument, in which there are the numbers simulated and a "response" string to send to Arduino(rx).

-The Arduino(rx) will receive the DynamicJsonDocument that will be deserialized. After that Arduino(rx) will print the numbers.

The wiring of this project is the very basic rx<-->tx | tx<-->rx | gnd<-->gnd. So everyone with two Arduinos can try it.

**The problem is that Arduino(rx) is able only to deserialize and so read the first JsonDoc that Arduino(tx) has sent, after that I'm getting the error "deserializeJson() failed: InvalidInput**

these are the codes:

**Arduino (tx)**
```
//Tx
#include <ArduinoJson.h>

int a;
int b;

String Serializ;
String message = "";
bool messageReady = false;

void setup() {
    Serial.begin(9600);

}

void loop() {

a = 10 + random(1,5);
b = 30 - random(1,5);
  
  // Monitor serial communication
  while(Serial.available()) {
    message = Serial.readString();
    messageReady = true;
  }
  // Only process message if there's one
  if(messageReady) {
    DynamicJsonDocument doc(512);
    DeserializationError error = deserializeJson(doc,message);
    if(error) {
      Serial.print(F("deserializeJson() failed: "));
      Serial.println(error.c_str());
      messageReady = false;
      return;
    }
    if(doc["type"] == "request") {
      doc["type"] = "response";
      // Get data from analog sensors
      doc["Humidity"] = a;
      doc["Temperature"] = b;
      //Serializ = serializeJson(doc,Serial);
      serializeJsonPretty(doc, Serial);
      Serial.println(Serializ);
        
    }
    messageReady = false;
  }
}
```

**Arduino (rx)**
```
//Rx
#include <ArduinoJson.h>

String message;


void setup()
{
    Serial.begin(9600);

}

void loop()
{
  handleIndex();
}

void handleIndex()
{
  
  DynamicJsonDocument doc(512); 
  double Humidity = 0, Temperature = 0;
  // Sending the request
  doc["type"] = "request";     
  serializeJson(doc, Serial);  
  // Reading the response
  boolean messageReady = false;
  
  while (messageReady == false) { // blocking but that's ok
    if (Serial.available()) {
      //String message;
      message = "" ;

      message = Serial.readString();
      messageReady = true;
    }
  }
  DeserializationError error = deserializeJson(doc, message);
  if (error) {
    Serial.print(F("deserializeJson() failed: "));
    Serial.println(error.c_str());
    return;
  }
  Humidity = doc["Humidity"];
  Temperature = doc["Temperature"];
  // Prepare the data for serving it over HTTP
  String output = "Humidity: " + String(Humidity) + "\n";
  output += "Temperature: " + String(Temperature);
  // Serve the data as plain text, for example
  Serial.println(output);
}
```

If I try to reset with the button _Arduino(rx)_ I'm constantly receiving the numbers as I would like to have without resetting manually everytime.

How can I solve this issue and constantly receive these data without reset manually the Arduino(rx)? Thank You

**Comment by bblanchon** [comment]
Hi @CarloPirisi,

I'm sorry, I don't have enough information to help you.

[deserializeJson()](https://arduinojson.org/v6/api/json/deserializejson/) returns InvalidInput because there is something wrong with the input.
Check the content of the input.

If the problem is related to ArduinoJson, you should be able to reproduce it without the serial communication.

If the problem is related to the serial communication, you should be able to reproduce it without ArduinoJson.

Lastly, remember that the Arduino UNO only has 2KB of RAM, and I can see that you are making several large allocations.
You should consider removing the temporary String and let [deserializeJson()](https://arduinojson.org/v6/api/json/deserializejson/) pull the data from Serial.

Best regards,
Benoit
