### ISSUE TITLE
Does the DeserializeJson affecting the serial?

### ISSUE THREAD

**Issue by ronneychu** [bblanchon/ArduinoJson#1205]
I am getting a JSON record from my database in this format
`{\"scheduleID\":\"1\",\"name\":\"gor\",\"time\":\"011100\",\"lid\":\"1\"}`

Before implementing deserializeJson, i check the string i pass is exactly what i want. However after implementing deserializeJson, i can't even recieve the json well, what's the problem?? 

`void RecieveOnCloud(int p1hour, int lid){

    String hour,minute,second,s2,rcv;
    getStringTime(&hour,&minute,&second);
                  
    String cmd = "AT+CIPSTART=\"TCP\",\"";
    cmd += IP;
    cmd += "\",80";
    sendAT(cmd);
    if( mySerial.find( "Error" ) )
        {
             Serial.print( "RECEIVED: Error\nExit1" );
              return;
       }else{
              Serial.print("Connected to server \r\n");
            }

      
   
      cmd = GET2 +"time="+p1hour+":00:00&lid="+lid+"\r\n";
      mySerial.print( "AT+CIPSEND=" );
      mySerial.println( cmd.length() );
      Serial.print( F("AT+CIPSEND=" ));
      Serial.println( cmd.length() );

      
    if(mySerial.find( ">" ) )
        {
        Serial.print(">");
        Serial.print(cmd);
        mySerial.print(cmd);

        bool checker = false ;
             while(mySerial.available()){

                 if(mySerial.find("IPD,")){ 
                   checker= true;}

                  if(checker== true) { 
                     String copy = mySerial.readStringUntil("\r"); 
                     rcv+= copy;
                   }
         }  

          Serial.println("result of copying:" +rcv);
                  
             s2=rcv.substring((rcv.indexOf('{')),rcv.indexOf('}')+1);
         Serial.println("result of cropping:"+s2);
           JsonToRecord(s2);

    }`
`void JsonToRecord(String s2){
  
          
        const size_t capacity = JSON_OBJECT_SIZE(4) + 60;
         DynamicJsonDocument doc(capacity);

        //const char* json = "{\"scheduleID\":\"1\",\"name\":\"gor\",\"time\":\"011100\",\"lid\":\"1\"}";
       const char* json = s2.c_str();
         Serial.println(json);  

     DeserializationError err = deserializeJson(doc, json);

      if(err){
        Serial.print("error");
        Serial.print(err.c_str());
        return;}
`

output of  commented the line of deserializeJson
![image](https://user-images.githubusercontent.com/17919954/76138968-fde8d480-6086-11ea-8c24-5fa8bc691c6c.png)

output of Using the deserializeJson
![image](https://user-images.githubusercontent.com/17919954/76138927-89159a80-6086-11ea-9ccb-1e2b86e587bb.png)

**Comment by bblanchon** [comment]
Hi @ronneychu,

I'm sorry, I don't understand your question.
Maybe you're looking for this:

* [Why is the input modified?](https://arduinojson.org/v6/faq/why-is-the-input-modified/)

Best regards,
Benoit

**Comment by ronneychu** [comment]
i keep passing JSON string to a function call JsonToRecord in order to extract the data using a loop, Every time the same JSON(for testing). However, the extraction sometimes work sometimes not.
`void JsonToRecord(String s2){
  
          
      const size_t capacity = JSON_OBJECT_SIZE(4) + 50;
         DynamicJsonDocument doc(capacity);

       // const char* json = "{\"scheduleID\":\"1\",\"name\":\"gor\",\"time\":\"011100\",\"lid\":\"1\"}";
        const char* json = s2.c_str();
         Serial.println(json);  

     DeserializationError err = deserializeJson(doc, s2);

      if(err){
        Serial.print("error");
        Serial.print(err.c_str());
        return;}
        
        const char* ScheduleID = doc["ScheduleID"];
        const char* Time = doc["Time"];
        
        record1.mID= atoi(ScheduleID);
               Serial.print(F("ScheduleID of this record:"));  
               Serial.println(ScheduleID);  

  
             record1.time= Time;       
             Serial.print(F("record1 time:"));
             Serial.println(Time);

      return;
        
  }`
![image](https://user-images.githubusercontent.com/17919954/76142807-fb4ca600-60ab-11ea-8077-8dce1005adcb.png)

**Comment by bblanchon** [comment]
Hi @ronneychu,

I'm sorry, I don't see what's wrong.
Can you create an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)?
What kind of hardware do you use?

Best regards,
Benoit

**Comment by ronneychu** [comment]
hi, i fixed the previous problem and i am using esp8266. However, i am looping the deserializeJson in order to update the info, it's okay to extract the data for the first time, but since the second time , the deserializeJson  either appears noMemory error or extract 0 for int and nothing for string, what is wrong? do I have to and how to reallocate DynamicJsonDocument memory space? 

Update
One of the possibility is in the void loop(), i update the variable record(the extraction of json)  and also reading it at the same time, do you think it is related? but even i try to update and read separately in even and odd is also not working...
`void loop() {

    if(rtc.now().minute()%2 ==0)
       RecieveOnCloud();                        //where i update record

if (mySerial.available())
    Serial.write(mySerial.read());
  
   if (Serial.available())
    mySerial.write(Serial.read()); 
    
 if(rtc.now().minute()%2!=0){
  if(record[1].mID= "25")   //where i access record
  {
        u8g.sleepOff();

  for(int i = 256; i>=0 ; i--){
    u8g.firstPage();
    do {
           
     String t=String("Open lid ")+record[1].lid +String(" to take ")+record[1].mName;
      const char *C = t.c_str();  
       
      u8g.drawStr(i, 20,C);
      
    } while ( u8g.nextPage() );
   
   }
  }
 }
  clearScreen();  
}`

**Comment by bblanchon** [comment]
Hi @ronneychu,

I answered on the following page:

* [How to reuse a JsonDocument](https://arduinojson.org/v6/how-to/reuse-a-json-document/)

Let me know if you have any questions or remarks.

Best regards,
Benoit
