### ISSUE TITLE
Crash When Serializing or Parsing

### ISSUE THREAD

**Issue by lbussy** [bblanchon/ArduinoJson#1208]
Hello,

I was hoping you could put a pair of eyes on this and tell me where I am going wrong.  Since the error is so pervasive and nearly instant, I am sure I am doing something very basic wrong.  That means you've probably seen it 1000 times and can do this in your sleep.

I am parsing/serializing in a singleton class, and saving to SPIFFS on an ESP8266.  As soon as I touch one of the objects, boom.

- Code removed to prevent any embarrassment on my part, it's not going to be helpful for anyone else.

Thank you for taking a look!

**Comment by bblanchon** [comment]
Hi @lbussy,

At first sight, I cannot spot a big mistake.

However, I'm very surprised that you use `single->` in every member function as if they were static methods. I could not make sense of this; what is the rationale here?

What is the problem exactly?
You say "boom"; do you mean an exception? a reboot?
If it's an exception, please use the [EspExceptionDecoder](https://github.com/me-no-dev/EspExceptionDecoder) to get more information.

Also, I would really help to know the exact location of the error.
Please insert some traces with [ArduinoTrace](https://github.com/bblanchon/ArduinoTrace).

Best regards,
Benoit

**Comment by lbussy** [comment]
Hi Benoît, thanks for the over the shoulder look.

Yes, an exception.  I realize I need to do a little more now to find out why. I was just hoping there was a glaring mistake and one fix would do it for me. :)

As to your question about a static method - this is the form I use for a singleton class which may or may not be "classic" but it works for me so far (well, except for this.)

I'm playing with the examples (using structures) in your book.  Having an issue there too which mimics an issue I am having with my project.  I'll deconstruct it and try to figure that out - if I continue to have an issue I'll post a separate one.

Closing this as my quesiton was more a hail-mary pass than an issue.  Thanks again.

**Comment by bblanchon** [comment]
You're welcome, @lbussy.
Don't hesitate to open a new issue if you're stuck.
