### ISSUE TITLE
Question: Partial Update of struct?

### ISSUE THREAD

**Issue by lbussy** [bblanchon/ArduinoJson#1224]
Hello Benoît,

Taking, for example, your `sketchbook6\SpiffsConfig` code again, I am wondering if there's an easy way to apply a partial update to the struct?

The flow would be something like:

1. POST a JSON message with `{"apconfig": {"ssid": "foo"}}`
2. Deserialize as `doc`
3. Load the JSON with ` config.load(doc.as<JsonObject>());`

Fairly certain that's a valid way to go - however, my logic in `load()` has some logic to establish default values if the values are null.  I believe that `doc["apconfig"]["passphrase"]` would be null in this case?  Or is there another way to determine that I should skip fields that are not present?

The result would be an endpoint for the configuration of individual points.  I currently have a long string of `if (data->hasParam(F("ssid"), true))` statements but that seems unglamorous.

ETA:  After staring at this a bit, it seems like I might be able to overload `load()` with a `fromfile` boolean to delineate work with the configuration file versus a JSON post.  Still, feels not sexy.

**Comment by bblanchon** [comment]
Hi Lee,

I don't think I would use `load()` for this feature.
Instead, I would create a `patch()` method that would only apply diffs.

Alternatively, you could read the JSON file from disk, then [merge it](https://arduinojson.org/v6/how-to/merge-json-objects/) with the content of the message, and call `load()` as before.

Best regards,
Benoit

**Comment by lbussy** [comment]
Brilliant!  merge is exactly what I was looking for.  Thank you, sir!  I even re-read the book last night - didn't see merge in there.

Thanks again for your assistance!
