### ISSUE TITLE
Arrays and root

### ISSUE THREAD

**Issue by delcomp** [bblanchon/ArduinoJson#124]
JsonObject &root = jsonBuffer.parseObject(sResponse);
if (root.success()) {
  for (i=0; i<MAX_TS_CHANNELS; i++) {
      const char *sTSChannelName = root[i]["name"];
  }  
}                  

I get: 'invalid conversion from 'int' to '......[aka const char*]'

When I replace root[i] with root[0] or root[1], all works. But then again I would like to use the for to walk through the array.

How to solve this?

**Comment by bblanchon** [comment]
If root is an array, then use:

```c++
JsonArray &root = jsonBuffer.parseArray(sResponse);
```

If root is an object, use iterators:
https://github.com/bblanchon/ArduinoJson/wiki/Examples#example-3-iterators
