### ISSUE TITLE
ParseObject() failed

### ISSUE THREAD

**Issue by cristal91** [bblanchon/ArduinoJson#1243]
Bonjour à tous, i've been trying to use this code to read weather frome openweather.org website but the issue is, i keep having the error: "parseObject failed". I've check my output in JSonLint and it's valid. Now i don't really know what's wrong. Please help. This is my code:

void setup() {
  //Initialize serial and wait for port to open:
  Serial.begin(115200);

  //client.setTimeout(10000);
  // attempt to connect to LAN:
  if (!Ethernet.begin(mac)) {
    Ethernet.begin(mac, "192.168.100.51");
  }
  
  getWeather();
  
  while (client.connected()) {

    line = client.readStringUntil('\n');
    Serial.println(line);

  }
  client.stop();
  
  analyseResponse();
}

void loop() {
// Nothing;
}

void getWeather() {

  Serial.println("Starting connection to www.openweather.org ...");
  if (client.connect(server, 80)) {
    client.println(String("GET /data/2.5/weather?id=") + cityId + "&units=metric&appid=" + apiKey + "\r\n" +
                   "Host: " + server + "\r\nUser-Agent: ArduinoMeteo/1.1\r\n" +
                   "Connection: close\r\n\r\n");
  } else {
    Serial.println("connection failed");
    return;
  }
}
  
 void analyseResponse() {
 
   StaticJsonBuffer<5000> jsonBuffer;
  JsonObject& root = jsonBuffer.parseObject(line);

  if (!root.success()) {
    Serial.println("parseObject() failed");
    return;
  }

  //get the data from the json tree
  String nextWeatherTime0 = root["list"][0]["dt_txt"];
  String nextWeather0 = root["list"][0]["weather"][0]["main"];

  String nextWeatherTime1 = root["list"][1]["dt_txt"];
  String nextWeather1 = root["list"][1]["weather"][0]["main"];

  String nextWeatherTime2 = root["list"][2]["dt_txt"];
  String nextWeather2 = root["list"][2]["weather"][0]["main"];

  nextWeatherTime[0] = nextWeatherTime0;
  nextWeatherTime[1] = nextWeatherTime0;
  nextWeatherTime[2] = nextWeatherTime0;

  nextWeather[0] = nextWeather0;
  nextWeather[1] = nextWeather1;
  nextWeather[2] = nextWeather2;

  // Print values.
  Serial.println(nextWeatherTime0);
  Serial.println(nextWeather0);
  Serial.println(nextWeatherTime1);
  Serial.println(nextWeather1);
  Serial.println(nextWeatherTime2);
  Serial.println(nextWeather2);

}

**Comment by bblanchon** [comment]
Hi @cristal91,

The `JsonBuffer` is probably too small for the gigantic response from OpenWeatherMap.
I recommend [upgrading to ArduinoJson 6](https://arduinojson.org/v6/doc/upgrade/) because it returns an error code that tells you why it failed.

Please also see:

* [How to deserialize a very large document?](https://arduinojson.org/v6/how-to/deserialize-a-very-large-document/)

Best regards,
Benoit
