### ISSUE TITLE
doc[StringVariable]; Is it possible?

### ISSUE THREAD

**Issue by paytah232** [bblanchon/ArduinoJson#1246]
I'm using this on an ESP32 and I have basically this code:

char variableName[25] = "SomeVariable";
DynamicJsonDocument doc(config_size);
if (doc[variableName] != NULL) {
  //Do Stuff
}

When I get to the if statement the ESP32 crashes with this
![image](https://user-images.githubusercontent.com/44075588/80111923-da8cd100-85c3-11ea-954e-24f96182b101.png)

I'm wondering if it is at all possible to pass 'variableName' to doc[variableName]?
Is it and I can't just use char[], because doc["SomeVariable"] where "SomeVariable" is a const char * would work I'd assume, however I am building the string in the char[] before I look for it in the doc.

Any help would be appreciated. Cheers!

**Comment by bblanchon** [comment]
Hi @Paytah232,

I don't think the problem comes from the `char` array, but from `NULL`.

This issue required an extended response, so I wrote an article.
Please see:

* [Why can't I use `NULL`?](https://arduinojson.org/v6/faq/why-cant-i-use-null/)

Best regards,
Benoit

**Comment by paytah232** [comment]
You're right. I used nullptr instead and it works! Thanks!
________________________________

**Comment by bblanchon** [comment]
You're welcome.
Thank your for using ArduinoJson.
