### ISSUE TITLE
Max json size

### ISSUE THREAD

**Issue by BlaiMunoz** [bblanchon/ArduinoJson#1249]
Good day, 

I am programming using an Arduino MKR ZERO with the Arduino IDE 1.8.12

I am trying to read a json stored in an SD. The json looks something like this:

{"123456798":1,"987654321":0}

I have been able to load a json with 200 keys but if I try to load a bigger json the program freezes. Is there any way of loading a much bigger json? I need it to be at least 700 keys.

Thank you very much!

**Comment by bblanchon** [comment]
Hi @BlaiMunoz,

Please read:

* [How to determine the capacity of the JsonDocument?](https://arduinojson.org/v6/how-to/determine-the-capacity-of-the-jsondocument/)
* [How to deserialize a very large document?](https://arduinojson.org/v6/how-to/deserialize-a-very-large-document/)

Best regards,
Benoit
