### ISSUE TITLE
using String variables with ArduinoJSON

### ISSUE THREAD

**Issue by haeleng** [bblanchon/ArduinoJson#1254]
Hi Benoid

When I use the code below, where tst is a String variable, used for SessionID, the result goes wrong. (see the result below in this post)
When tst is replaced by the actual string ("7425fbcb58ee4d15dd4c1f5ace4299a4") at the positon of Request["SessionID"] the result becomes ok. The actual code did I copy from the Asistant.
What am I doing wrong?
I also want PanDirection, PanSpeed, TiltDirection and TiltSpeed to become variable

Code
const size_t capacity = JSON_OBJECT_SIZE(1) + JSON_OBJECT_SIZE(3) + JSON_OBJECT_SIZE(6);
	DynamicJsonDocument doc(capacity);

	String tst = "7425fbcb58ee4d15dd4c1f5ace4299a4";
	JsonObject Request = doc.createNestedObject("Request");
	Request["Command"] = "SetPTCtrl";
	Request["SessionID"] = tst;

	JsonObject Request_Params = Request.createNestedObject("Params");
	Request_Params["PanDirection"] = "Left";
	Request_Params["PanPosition"] = 32768;
	Request_Params["PanSpeed"] = 10;
	Request_Params["TiltDirection"] = "Up";
	Request_Params["TiltPositon"] = 32768;
	Request_Params["TiltSpeed"] = 10;

Result with tst as String variable
{
  "Request": {
    "Command": "SetPTCtrl",
    "SessionID": "7425fbcb58ee4d15dd4c1f5ace4299a4",
    "Params": {
      "PanDirection": "Left"
    }
  }
}

**Comment by bblanchon** [comment]
Hi,

That's a general rule with ArduinoJson: when you use a `String` or a `char*` (ie not a `const char*`), it makes a copy in the `JsonDocument`.
As a consequence, you must increase the capacity of the `JsonDocument`.

Best regards,
Benoit
