### ISSUE TITLE
Performance question vs GSON

### ISSUE THREAD

**Issue by ZweiEuro** [bblanchon/ArduinoJson#1259]
Jut purely out of curiosity, have you ever benchmarked vs GSON?
I would do it myself if i had any idea of how to do it.

https://github.com/nlohmann/json

**Comment by bblanchon** [comment]
Hi @DasVoelkel,

I used this library out of Arduino and was happy with it.
However, I never tried it on Arduino, and I don't think I would (for obvious reasons).

Best regards,
Benoit
