### ISSUE TITLE
Using ArduinJson on VS 2019

### ISSUE THREAD

**Issue by jeromeDevIN** [bblanchon/ArduinoJson#1271]
Hello,

That's not really an issue, but could you tell me if it is possible to use ArduinoJson on Visual Studio 2019.
And how to install it in a VS project if it's possible.

Thanks for your great work

**Comment by bblanchon** [comment]
Hi @jeromeDevIN,

Yes, it's possible: simply download [ArduinoJson-v6.15.2.h](https://github.com/bblanchon/ArduinoJson/releases/download/v6.15.2/ArduinoJson-v6.15.2.h) and save it in your source directory.

Best regards,
Benoit

PS: see also [Installation section](https://arduinojson.org/v6/doc/installation/) on arduinojson.org
