### ISSUE TITLE
ERROR: Filter is not a member of ArduinoJSON

### ISSUE THREAD

**Issue by MHz000** [bblanchon/ArduinoJson#1278]
compiling an unchanged JsonFilterExample from ArduinoJson.h yields in:
"Filter is not a member of ArduinoJson " 
regardless of choosen board ESP8266 or ESP32 (Arduino latest IDE)

Thank you for any advise

**Comment by bblanchon** [comment]
Hi @MHz000,

An older version of ArduinoJson is probably installed on your computer.
Look for a string like this in the compilation output:

    Using library ArduinoJson at version 6.15.2

`DeserializationOption::Filter` was introduced in [ArduinoJson 6.15.0](https://arduinojson.org/news/2020/03/22/version-6-15-0/).

Best regards,
Benoit

**Comment by MHz000** [comment]
Benoit thank you for the hint. It was exactly the case😂

All the best
MHz000


Am Do., 28. Mai 2020 um 10:24 Uhr schrieb Benoît Blanchon <
notifications@github.com>:
