### ISSUE TITLE
Sending a *.ino file in a POST request with ArduinoJson

### ISSUE THREAD

**Issue by dcota** [bblanchon/ArduinoJson#1283]
Hi!
I was wondering if it is possible to send a *ino file in a POST request using ArduinoJson6. I am dealing with a project where I need to send data and the correspondent code to a server and I want to send everything in a unique request. Or in separate requests in alternative.
Thank you.
Duarte

**Comment by bblanchon** [comment]
Hi Duarte,

You can put whatever you want in the request's body, including the text of a file.
However, I don't see how this question relates to ArduinoJson.

Best regards,
Benoit

**Comment by dcota** [comment]
Thanks for the reply, I managed to stringify everything I need to send in the same request, because I need to relate the student ID with the data that is being sent to the server for later analytics.
Thank you very much.
Duarte
