### ISSUE TITLE
iddad or idkfq (or iddqd idkfa)

### ISSUE THREAD

**Issue by d-a-v** [bblanchon/ArduinoJson#1287]
While testing an interactive setup parsing and checking whether an input is valid, I *accidentally* found lots of cheat codes:

```
#include <iostream>
using namespace std;

#include <ArduinoJson.h>

StaticJsonDocument<1024> doc;

void test (const char* str)
{
    doc.clear();
    cout << "str: '" << str << "':" << endl;
    auto err = deserializeJson(doc, str);
    cout << "err: " << err << endl;
    cout << "doc: " << doc << endl << endl;
}

int main ()
{
    test("{\"a\":1}");  // ok (valid)
    test("a");          // ok (error)

    test("tru");        // ok (error)
    test("true");       // ok (valid, true)
    test("truel");      // ok (error)

    test("trop");       // cheat code
    test("tard");       // cheat code
    
    test("fals");       // ok (error)
    test("false");      // ok (valid. false)
    test("falset");     // ok (error)

    test("fille");      // cheat code
    test("futee");      // cheat code
    
    return 0;
}
```

4-letters inputs starting with `t` are bools and `True`,
and 5-letters inputs starting with `f` are bools and `False`.

It may be an optimization. That one questionned me for a little while :)

Let me take advantage of this message to thank you a lot @bblanchon for your library.

**Comment by bblanchon** [comment]
Hi @d-a-v,

It's an optimization to reduce the size of the code.
It's implemented here:

https://github.com/bblanchon/ArduinoJson/blob/6fb52c363849557c69485f97110371d0a4454432/src/ArduinoJson/Json/JsonDeserializer.hpp#L457-L471

As you can see, you missed another cheat code: you can replace `null` with `none` ;-)

There are similar optimizations with UTF-16 surrogate pairs: ArduinoJson assumes that the surrogate pair is valid.

Anyway, it's not a secret, and it's even covered by the unit tests:

https://github.com/bblanchon/ArduinoJson/blob/6fb52c363849557c69485f97110371d0a4454432/extras/tests/JsonDeserializer/invalid_input.cpp#L24-L42

Thanks for the kind words.

Best regards,
Benoit
