### ISSUE TITLE
JsonVariant: operator= is implicitly deleted because the default definition would be ill-formed

### ISSUE THREAD

**Issue by ewaldc** [bblanchon/ArduinoJson#1290]
Initializing a structure with `Const JsonVariant` refuses to compile.
It's fine with non-const _JsonVariant_ and _JsonVariantConst_ 
It's also fine when the structure is being pointed to and initialized with _new()_
The JsonVariant points to valid structure as if I recall well, JSonVariant is implemented as a reference, but it the cases where it works, it also works with e.g. nullptr.

Am I wrong to assume that this should work?
Nothing urgent as I found a working alternative...

```
struct ItemReference {
    const JsonVariant obj;		// drop const and it is fine...	
    const JsonVariant widgetObj;
};
struct ItemReferenceConst {
    JsonVariantConst obj;			
    JsonVariantConst widgetObj;
};
ItemReference itemRef1;
ItemReference *itemRef2;
ItemReferenceConst itemRefConst1;
ItemReferenceConst *itemRefConst2;

JsonVariant varDoc = doc.as<JsonObject>();  // varDoc points to a valid JsonDocument
JsonVariant varArr = doc["data"]; // varDoc points to a valid JsonArray

itemRef1 = { varDoc, varArr };  // fails
itemRef2 = new ItemReference { varDoc, varArr }; //OK
itemRefConst1 = { varDoc, varArr };  //OK
itemRefConst2 = new ItemReferenceConst { varDoc, varArr};  //OK
itemRefConst1 = { nullptr, nullptr };  //OK
```

* target platform: tested on Windows 10, ESP8266/ESP32
* compiler model and version (VS17 MSVC Version 19.16.27039 for x64, VSCode PlatformIO 4.3.4)
* [MVCE ](https://pastebin.com/wzb9eReP)
* AJ: 6.15.2

**Comment by bblanchon** [comment]
Hi @ewaldc,

This problem is not specific to `JsonVariant`; we can easily reproduce this error with a built-in type:

```c++
struct Example {
  const int n;
};

int main()
{
    Example ex;
    ex = {42};
}
```

If you [run this snippet](https://wandbox.org/permlink/hAwft6u7Tkz6ntMF), you'll see;

```
error: use of deleted function 'Example::Example()'
note: 'Example::Example()' is implicitly deleted because the default definition would be ill-formed
error: use of deleted function 'Example& Example::operator=(Example&&)'
note: 'Example& Example::operator=(Example&&)' is implicitly deleted because the default definition would be ill-formed
```

Indeed, the member is `const`, so you cannot change the value; you can only set it once in the constructor.

Best regards,
Benoit

**Comment by ewaldc** [comment]
Yes, totally logical...  
Got confused because it's OK for a `const char *` and `JsonVariantConst `but now I recall that is why there is now `const char const *`.
Have been doing too much work in different languages lately (Linux kernel/C, React, Python, Java/Kotlin) and it's starting to become one big mix/mess.
Sorry for wasting your time!
