### ISSUE TITLE
Can't parse some JSONs on the ESP8266

### ISSUE THREAD

**Issue by vshymanskyy** [bblanchon/ArduinoJson#132]
Just came across the same issue:
http://www.esp8266.com/viewtopic.php?p=21821

**Comment by bblanchon** [comment]
The buffer is too small:

1. root object's size = `JSON_OBJECT_SIZE(2)` = 72 bytes
2. first nested object's size = `JSON_OBJECT_SIZE(2)` = 72 bytes
3. second nested object's size = `JSON_OBJECT_SIZE(2)` = 72 bytes

Total = 216 bytes.

You need to increase the size of the `StaticJsonBuffer` or switch to `DynamicJsonBuffer`.

**Comment by domonetic** [comment]
What happens , if I get something bigger than the buffer?

**Comment by vshymanskyy** [comment]
It appears to be a *similar* issue. but actually i tracked it down to being not able to parse numbers on this platform. I have fixed it, I'll prepare a PR for that.
Thanks!

**Comment by asetyde** [comment]
Actually max 505bytes work ...
