### ISSUE TITLE
ArduinoJSON Canonical Communication

### ISSUE THREAD

**Issue by regina2898** [bblanchon/ArduinoJson#1321]
Hello.. Can anyone help me? 
So I'm trying to build a system where we can do **canonical communication between 2 HC-12 radio modules and NodeRed**
I wish to send a JSON like : 
`{
"sessionid" : 1,
"idmeter" : [1,2,3],
"standmeter":[ ],
"state":[ ]
}`
I planned to fill standmeter and state elements from the HC-12 radio modules (that included with Arduino Pro Mini). I designed it to be like sending the JSON from Node-Red to the first HC-12 module. And the first module will send it to the second HC-12 Module and fill the standmeter and state. Then it will send the filled JSON data back to the first module, then finally send it to Node-Red. 
I connected the first HC-12 module with my Node-Red server through serial port, and I'm using software serial port for the first and second HC-12 modules communication.

**Here is my Node-Red code :** 
`[{"id":"dd940eea.5a143","type":"tab","label":"laman oprek 2","disabled":false,"info":""},{"id":"60f5a3d6.339b4c","type":"serial out","z":"dd940eea.5a143","name":"","serial":"5ecf367f.c83d48","x":630,"y":80,"wires":[]},{"id":"99c9d554.e606d8","type":"serial in","z":"dd940eea.5a143","name":"","serial":"ddc8a65a.e05808","x":130,"y":260,"wires":[["84a63f1b.b33a"]]},{"id":"84a63f1b.b33a","type":"debug","z":"dd940eea.5a143","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"jsonata","x":540,"y":260,"wires":[]},{"id":"db183e5f.a71db","type":"inject","z":"dd940eea.5a143","name":"JSON Data","topic":"","payload":"{\"sessionid\":1,\"idmeter\":[1,2,3],\"standmeter\":[],\"state\":[]}","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":130,"y":80,"wires":[["bbd8e46.b157018"]]},{"id":"bbd8e46.b157018","type":"json","z":"dd940eea.5a143","name":"","property":"payload","action":"","pretty":true,"x":450,"y":80,"wires":[["60f5a3d6.339b4c"]]},{"id":"5ecf367f.c83d48","type":"serial-port","z":"","serialport":"COM3","serialbaud":"9600","databits":"8","parity":"none","stopbits":"1","waitfor":"","newline":"1500","bin":"false","out":"time","addchar":"","responsetimeout":"10000"},{"id":"ddc8a65a.e05808","type":"serial-port","z":"","serialport":"COM3","serialbaud":"9600","databits":"8","parity":"none","stopbits":"1","waitfor":"","dtr":"none","rts":"none","cts":"none","dsr":"none","newline":"5000","bin":"false","out":"time","addchar":"","responsetimeout":"10000"}]`

![image](https://user-images.githubusercontent.com/61671403/88420911-d5812d00-ce11-11ea-859f-32f151523f35.png)

**This is my first HC-12 module code** 
```
//Receive from JSON Data Node-red and send it to sensor nodes

#include <ArduinoJson.h>
#include <SoftwareSerial.h>
#define rxPin 5
#define txPin 4
#define setPin 6

SoftwareSerial HC12(rxPin, txPin); // Declare the SoftwareSerial port RX, TX
String json1;

void setup() {
  // Initialize "debug" serial port
  // The data rate must be much higher than the SoftwareSerial port
  Serial.begin(9600);
  while (!Serial) continue;

  // Initialize the SoftwareSerial port
  // Use the lowest possible data rate to reduce error ratio
  HC12.begin(4800);
  delay(2000);
  readfromNodered();
  delay(2000);
  sensornode1(json1);
  
}

void readfromNodered() {
  delay(2000);
  if (Serial.available()) {
    StaticJsonDocument<200> doc;
    DeserializationError error = deserializeJson(doc, Serial);
    if (error) {
      Serial.print(F("deserializeJson() failed: "));
      Serial.println(error.c_str());
    }
    delay(1000);
    serializeJsonPretty(doc, HC12); //send JSON data to node
  }
}

void sensornode1(String json1){
  StaticJsonDocument<200> doc;
  deserializeJson(doc, json1);
  deserializeJson(doc, HC12);

  delay(1000);
  serializeJsonPretty(doc,json1);
  serializeJsonPretty(doc, Serial);
}

void loop() {
}

```
**And my second HC-12 module code :**
```
//Receive from Concentrator and sendback
#include <ArduinoJson.h>
#include <SoftwareSerial.h>
#define rxPin 5
#define txPin 4
#define setPin 6

SoftwareSerial HC12(rxPin, txPin); // Declare the SoftwareSerial port RX, TX
int idmeterku = 1;
String json1;

void setup() {
  // Initialize "debug" serial port
  // The data rate must be much higher than the SoftwareSerial port
  Serial.begin(9600);
  while (!Serial) continue;

  // Initialize the SoftwareSerial port
  // Use the lowest possible data rate to reduce error ratio
  HC12.begin(4800);
  delay(2000);
  readfromConcentrator();
  delay(2000);
  sendbacktoConcentrator(json1);
}

void readfromConcentrator() {
  //delay(2000);
  if (HC12.available()) {
    StaticJsonDocument<200> doc;
    deserializeJson(doc, HC12);

    JsonObject sessionid = doc["sessionid"];
    JsonArray idmeter = doc["idmeter"].as<JsonArray>();
    JsonArray standmeter = doc["standmeter"].as<JsonArray>();
    JsonArray state = doc["state"].as<JsonArray>();
    for (JsonVariant value : idmeter) {
      HC12.println(value.as<int>());
      if (value == idmeterku) {
        standmeter[0] = 2555;
        state[0] = "done";
      }
    }
  }
}

void sendbacktoConcentrator(String json1) {
  StaticJsonDocument<200> doc;
  serializeJsonPretty(doc, json1);
  serializeJsonPretty(doc, HC12);

}

void loop() {
}
```

But when I try to run the system, it shows **"null"** messages like this 
![image](https://user-images.githubusercontent.com/61671403/88421075-137e5100-ce12-11ea-9eee-1f78bbdc7176.png)

I don't know where the mistake was (whether it's my node-red code or my arduino code)

does anyone know?

Thanks before!

Regards, 
Regina

**Comment by bblanchon** [comment]
Hi Regina,

Did you fix your issue?
If not, I suggest that you summarize your question to just one or two sentences, you'd improve your chances to get an answer.

Best regards,
Benoit
