### ISSUE TITLE
How to access JSON object inside a loop?

### ISSUE THREAD

**Issue by HanSolo72** [bblanchon/ArduinoJson#1324]
Hi, I dynamically create a http form with 30 input elements and send them to the webserver by Fetch API. Then I save the data from the input elements as JSON to LittleFS. It all works fine, but after I read the saved JSON from LittleFS and want to build the website I want to read the saved values from the JSON object, but I don't know how to do this in a loop.

Here I build the 30 input elements (shortened, actually it's in a table):
```
  const size_t capacity = JSON_ARRAY_SIZE(2) + JSON_OBJECT_SIZE(30) + 439;
  DynamicJsonDocument doc(capacity);
  const int AnzahlReed=30;
  for(int i=1;i<=AnzahlReed;i++){
    sprintf(inputfield, "Reed-Kontakt %d: <input type=\"text\" name=\"reed%02d\" value=\"Test%d\">", i, i);
    server.sendContent(inputfield);
  }
```

The JSON looks like this: {"reed01": "Kitchen", "reed02": "Living room","reed03": "Main door"}

I just want to replace the text "Test" in the form with the value from the JSON.

I tried this inside the loop, but that doesn't work:
```
sprintf(reedNo, "reed%02d", i);
room = doc[reedNo];
Serial.print(room);
```

When I compile it I get this eror message from Arduino IDE:
incompatible types in assignment of 'ArduinoJson6152_0000010::enable_if<true, ArduinoJson6152_0000010::MemberProxy<ArduinoJson6152_0000010::JsonDocument&, char*> >::type {aka ArduinoJson6152_0000010::MemberProxy<ArduinoJson6152_0000010::JsonDocument&, char*>}' to 'char [31]'

How can I read a value from the JSON and just put it into a variable?

**Comment by bblanchon** [comment]
Hi,

The error says:

> You cannot assign `doc[reedNo]` to a variable of type `char[31]`

Replace the following:

```c++
char room[31];
room = doc[reedNo];
```

with:

```c++
const char* room = doc[reedNo];
```

Best regards,
Benoit

**Comment by HanSolo72** [comment]
Thank you, now it works perfectely.
