### ISSUE TITLE
How can I remove empty object from an array in JSON

### ISSUE THREAD

**Issue by soloex1991eric** [bblanchon/ArduinoJson#1332]
I used the new json filter to filter an array of json objects and noticed that when the filter can't find the specified key it would leave in its place, an empty {}.
E.g: filtering,  `"LS": [{"Rd": {"Msg": "Hello"}},{"Bl":{"Msg":"Hello"}},{"Yl":{"Msg": "Hello"}}]` . 
Using, `filter["LS"][0]["Rd"]= true`.
Returns, `{"LS": [{"Rd": {"Msg": "Hello" }}, { "Rd": { "Msg": "Hello" } }, {}]} `. 
Is it possible to remove the empty {} ? 
I might be using the function completely wrongly, so any advice is welcomed.

.Tried on Platformio, Teensyduino 1.53, Teensy 4.1

**Comment by bblanchon** [comment]
Hi @soloex1991eric,

This is the expected behavior: the filter doesn't change the number of elements in the array.

If you want to remove the empty elements, you must do it in your code.
For example, you could do:

```c++
JsonArray arr = doc["LS"];
for (JsonArray::iterator it = arr.begin(); it != arr.end(); ++it) {
  if (it->size() == 0)
    arr.remove(it);
}
```

Best regards,
Benoit

**Comment by bblanchon** [comment]
PS: [demo on wandbox.org](https://wandbox.org/permlink/XvFtA2hqu85IAOG2)

**Comment by soloex1991eric** [comment]
Thank you, that was what i was looking for.

**Comment by bblanchon** [comment]
You're welcome.
Good luck with your project, @soloex1991eric.
