### ISSUE TITLE
edit JSON object in file - wear leveling

### ISSUE THREAD

**Issue by thbl** [bblanchon/ArduinoJson#1350]
If we have a big json file (lets say 10kb) to edit a single object in that file we need to write the whole file again to flash ?
Is there a better alternative to edit a single/few objects in a file without causing this wear leveling.

**Comment by bblanchon** [comment]
Hi @thbl,

ArduinoJson doesn't provide any way to do that, and I don't think it's possible.
However, the file-system should mitigate the problem.

Best regards,
Benoit

**Comment by thbl** [comment]
@bblanchon thanks for you input, i feel like i have looked all over the web but cant find any file manegment lib that can do this :(
