### ISSUE TITLE
How to convert Json Array to an array of integer?

### ISSUE THREAD

**Issue by regina2898** [bblanchon/ArduinoJson#1354]
Hi benoit! I want to ask, how to convert my Json Array to an array of integer?
This is my Json Array :
`{"idmeter":[1,2,3]}`

How am i supposed to write on my Arduino IDE?
Thanks before!

**Comment by bblanchon** [comment]
Hi @regina2898,

You can use [copyArray()](https://arduinojson.org/v6/api/misc/copyarray/):

```c++
int myArray[3];
copyArray(doc["idmeter"], myArray);
```

Best regards,
Benoit
