### ISSUE TITLE
Can't extract an char from root/jsonBuffer on V5

### ISSUE THREAD

**Issue by RonGroen** [bblanchon/ArduinoJson#1356]
I want to extract "Houtkachel":"J"  to a char.

I can only achieve this 2 two lines:
char Werk[2];
strcpy(Werk,root["Houtkachel"]);
Houtkachel=Werk[0];

Is there a way to to this in one line?
Houtkachel=root["Houtkachel"].as<char>(); or Houtkachel=root["Houtkachel"]; does not work

**Comment by bblanchon** [comment]
Hi @RonGroen,

Please try:

```c++
char Houtkachel = *root["Houtkachel"].as<const char*>();
```

However, remember that this line will crash your microcontroller if `Houtkachel` is missing.

Best regards,
Benoit

**Comment by RonGroen** [comment]
Thank you for your reply.
Crashing when root["Houtkachel"] does not exist is a to big risk. Is there any thing I can do to make it more stable?

**Comment by bblanchon** [comment]
```c++
const char* HoutkachelString = root["Houtkachel"];
char Houtkachel = HoutkachelString  ? HoutkachelString[0] : 0;
```

**Comment by RonGroen** [comment]
thank you :-)

**Comment by bblanchon** [comment]
You're welcome, @RonGroen.
Don't forget to [star the project](https://github.com/bblanchon/ArduinoJson/stargazers) to show your support 😉 
Good luck with your project!
