### ISSUE TITLE
Writes that version 5

### ISSUE THREAD

**Issue by spothz** [bblanchon/ArduinoJson#1357]
Please tell me why, during installation, it writes an error that I have version 5, although I have 6 installed? Because of this, I can not connect to telegrams.

**Comment by bblanchon** [comment]
Hi @spot320,

You probably have multiple versions of the library installed on your computer.
Search for `ArduinoJson.h` on your hard-drive.

Best regards,
Benoit

**Comment by spothz** [comment]
I tried to install it separately, but it didn't help. Found that only the 5.35 library works properly with universaltelegrambot.

**Comment by bblanchon** [comment]
According to https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot/issues/179, ArduinoJson 6.x is supported on the master branch.
