### ISSUE TITLE
Filtering json to include array

### ISSUE THREAD

**Issue by Bascy** [bblanchon/ArduinoJson#1366]
I have a json file which contains a number of arrays with json objects inside.
I want to filter deserializing this array to only include one of those arrays. How can I do that?

JSON file:
```
{
  "sensors" : [
    {
      "id": "110",
      "terminalId": "10",
      "pollingInterval": "1000"
    },
    {
      "id": "111",
      "terminalId": "3"
    }
  ],
  "some other array": [
    {
      "id": "110",
     "option": "option1"
    }
  ]
}
```

I want only the sensors array deserialized:

```
{
  "sensors" : [
    {
      "id": "110",
      "terminalId": "10",
      "pollingInterval": "1000"
    },
    {
      "id": "111",
      "terminalId": "3"
    }
  ]
}

```

**Comment by bblanchon** [comment]
Hi @Bascy,

You can find documentation on filtering here:

1. [ArduinoJson 6.15: Filtering done right](https://arduinojson.org/news/2020/03/22/version-6-15-0/)
2. [How to deserialize a very large document?](https://arduinojson.org/v6/how-to/deserialize-a-very-large-document/)
3. [JsonFilterExample.ino](https://arduinojson.org/v6/example/filter/)

In your case, it should be something like this:

```c++
StaticJsonDocument<32> filter;
filter["sensors"] = true;

deserializeJson(doc, input, DeserializationOption::Filter(filter));
```

Best regards,
Benoit
