### ISSUE TITLE
deserializeJson() failed: IncompleteInput

### ISSUE THREAD

**Issue by makarna35** [bblanchon/ArduinoJson#1372]
Hi;

My code is:

`DynamicJsonDocument doc(600);

  String input = "{\"coord\":{\"lon\":-0.13,\"lat\":51.51},\"weather\":[{\"id\":301,\"main\":\"Drizzle\",\"description\":\"drizzle\",\"icon\":\"09n\"},{\"id\":701,\"main\":\"Mist\",\"description\":\"mist\",\"icon\":\"50n\"},{\"id\":741,\"main\":\"Fog\",\"description\":\"fog\",\"icon\":\"50n\"}],\"base\":\"stations\",\"main\":{\"temp\":281.87,\"pressure\":1032,\"humidity\":100,\"temp_min\":281.15,\"temp_max\":283.15},\"visibility\":2900,\"wind\":{\"speed\":1.5},\"clouds\":{\"all\":90},\"dt\":1483820400,\"sys\":{\"type\":1,\"id\":5091,\"message\":0.0226,\"country\":\"GB\",\"sunrise\":1483776245,\"sunset\":1483805443},\"id\":2643743,\"name\":\"London\",\"cod\":200}";
  DeserializationError error = deserializeJson(doc, input);

   if (error) {
    Serial.print(F("deserializeJson() failed: "));
    Serial.println(error.c_str());
    return;
  }`

I get "deserializeJson() failed: IncompleteInput" ERROR message. whats wrong?
NOTE: I must use  input as String because my data is String.

**Comment by bblanchon** [comment]
Hi @makarna35,

Most of the time, [IncompleteInput](https://arduinojson.org/v6/api/misc/deserializationerror/#invalidinput) means the input is empty.
I suppose that the allocation of the `String`'s buffer failed, so the input is empty.

See:

* [How to reduce memory usage?](https://arduinojson.org/v6/how-to/reduce-memory-usage/)

Best regards,
Benoit
