### ISSUE TITLE
ARDUINOJSON_DECODE_UNICODE enabled as default (contrary to documentation)

### ISSUE THREAD

**Issue by mibcat** [bblanchon/ArduinoJson#1374]
Hi,
obviously the unicode support is enabled as default in [Configuration.hpp](https://github.com/bblanchon/ArduinoJson/blob/6.x/src/ArduinoJson/Configuration.hpp#L167) which is contrary to the [documentation](https://arduinojson.org/v6/api/config/decode_unicode/).
Very important for embedded devices with small flash size :smile:.
Best regards,
Michael.

**Comment by bblanchon** [comment]
Hi @mibcat,

Thanks for reporting this issue.

I updated [the documentation](https://arduinojson.org/v6/api/config/decode_unicode/) and also included a table that shows the impact on each architecture.

Best regards,
Benoit
