### ISSUE TITLE
Question:  Wrap existing JSON Document

### ISSUE THREAD

**Issue by lbussy** [bblanchon/ArduinoJson#1375]
Hi again!

Searching for a good way to do this.  I have a JSON doc that I put together programmatically.  It's about 3k or so.  I have a block of code that puts it all together that I would like to re-use with a slightly different outcome.  MailerCode(TM) follows:

```
function createReport(bool doSerial = false)
{
    addJsonStuff here;
    String json;
    serializeJson(doc, json); // {"json":"stuff}
    sendHttpReport(json);

    if (sendSerial)
    {
        wrappedJson = wrapJson(json); // {"wrapper":{"json":"stuff}}
        sendSerialReport(wrappedJson);
    }
}
```
If it was a few hundred chars I'd just do it twice.  The way I understand `JsonDocument::createNestedObject()` I'd be duplicating my space.  Is there a good/better way to do this?

**Comment by bblanchon** [comment]
Hi Lee,

You must create a second document that includes the first.

The default way to do that is to duplicate the original document in the enclosing one:

```c++
wrappedJson["wrapped"] = doc;
```

In your case, however, we can avoid the copy because we have a pointer to the serialized string:

```c++
wrappedJson["wrapped"] = serialized(json.c_str());
```

[serialized()](https://arduinojson.org/v6/api/misc/serialized/) obeys to the usual string duplication rules: since we pass a `const char*`, it will not make a copy.

Best regards,
Benoit

**Comment by lbussy** [comment]
Thanks Benoit!  Seems so simple now - hindsight being what it is.  I appreciate the assist.

**Comment by lbussy** [comment]
Okay maybe I'm being dense:

```
        if (sendSerial)
        {
            DynamicJsonDocument wrapped(JSON_OBJECT_SIZE(1) + capacity);
            JsonObject r = wrapped.createNestedObject("r");
            r["r"] = serialized(json.c_str());
            serializeJson(r, Serial);
        }
```

It's using quite a bit more memory which I suspect is not what you told me.

It's entirely possible I need to do this after coffee. :)

**Comment by bblanchon** [comment]
```c++
DynamicJsonDocument wrapped(JSON_OBJECT_SIZE(1));
wrapped["r"] = serialized(json.c_str());
serializeJson(wrapped, Serial);
```

See demo: https://wandbox.org/permlink/LRbibw8hRxbwjqGD

**Comment by lbussy** [comment]
That ... yeah ... sometimes you need to be punched in the face with an answer.  Thank you again sir.
