### ISSUE TITLE
Deserializing from Serial - deserializeJson() failed: IncompleteInput

### ISSUE THREAD

**Issue by MarkEstrada** [bblanchon/ArduinoJson#1376]
I have just started using this library and I am not sure if I am using it correctly.
I have an esp-01 that sends data back to my arduino uno and I am reading the values thru serial communication

```
#include <ArduinoJson.h>
#include <SoftwareSerial.h>

SoftwareSerial mySerial(2, 3); // RX, TX


void setup() {
    Serial.begin(9600);
    mySerial.begin(9600);
    Serial.println("Arduino is ready!");
}


void loop() {
    const size_t capacity = JSON_OBJECT_SIZE(2) + JSON_OBJECT_SIZE(3) + 360;
    DynamicJsonDocument doc(capacity);
    DeserializationError error = deserializeJson(doc, mySerial);
    if (error) {
      Serial.print(F("deserializeJson() failed: "));
      Serial.println(error.c_str());
      return;
    }
}
```

Not sure why I am getting 

`deserializeJson() failed: IncompleteInput`

Could it be that I am receiving an incomplete input?  But my code compiles so maybe some logic problem?
Sorry, just started with C++ and Arduino in general.

**Comment by bblanchon** [comment]
Hi,

When used with a stream, [IncompleteInput](https://arduinojson.org/v6/api/misc/deserializationerror/#incompleteinput) often means "time out".
Are you sure there is something to read from `mySerial`?

Please see:

* [How to do serial communication between two boards?](https://arduinojson.org/v6/how-to/do-serial-communication-between-two-boards/)

Best regards,
Benoit
