### ISSUE TITLE
serializeJSON sometimes returns garbage 

### ISSUE THREAD

**Issue by davidkjackson54** [bblanchon/ArduinoJson#1385]
Using ArduinoJSON in PlatformIO on ESP32
I define 
std::string deviceAddress = foundDevices.getDevice(i).getAddress().toString();  
and occasionally - maybe 1 time in 10 I get one field that returns above value shown as garbage when displayed after SerializeJSON but the input field displays fine before it is copied into the JSONArray.

If I change the above statement to 
String deviceAddress = foundDevices.getDevice(i).getAddress().toString().c_str();
When I make this change I (so far) have been unable to recreate the field displayed as garbage.

Any clues as to why it occurs when I define deviceAddress as std:string? 

The output display looks like this when I run it in a loop: notice the garbage in the mac address field on the second occurrence. 
Scanning...
d2:fe:0e:a1:90:45
Sending..
{"tilts":[{"colour":7,"mac":"**bd21a77601762402596090**","uuid":"a495bb70-c5b1-4b44-b512-1370f02d74de","temp":24.44444,"gravity":1.005,"rssi":-60}]}
Message arrived on topic: scan/tilts Message: {}
Scanning...
d2:fe:0e:a1:90:45
Sending..
{"tilts":[{"colour":7,"mac":"d2:fe:0e:a1:90:45","uuid":"a495bb70-c5b1-4b44-b512-1370f02d74de","temp":24.44444,"gravity":1.005,"rssi":-66}]}

**Comment by bblanchon** [comment]
Hi @davidkjackson54,

Please read:

* [Why does the output contain garbage?](https://arduinojson.org/v6/faq/why-does-the-output-contain-garbage/)

Best regards,
Benoit

**Comment by davidkjackson54** [comment]
Thanks. I had resolved the issue myself but having an explanation is a great help. I hadn't found that link till you pointed it out.
