### ISSUE TITLE
Case independent key selection

### ISSUE THREAD

**Issue by matswebjorn** [bblanchon/ArduinoJson#1391]
Is there some way to configure ArduinoJson so that it becomes case independent when extracting values. 
I.e assume a key "firstLady" that I'd like to extract using
`const char* name = doc["firstlady"];`

**Comment by bblanchon** [comment]
Hi @matswebjorn,

ArduinoJson doesn't natively support case-insensitive lookup.

However, you could use an `std::string` with custom character traits.
See here for an example: https://stackoverflow.com/a/5319855/1164966

If `std::string` is not an option, then you can use [iterators](https://arduinojson.org/v6/api/jsonobject/begin_end/) to find the key.

Best regards,
Benoit

**Comment by matswebjorn** [comment]
Hi Benoit,

Thanks, I’ll try your suggestions

Regards
Mats

Från: Benoît Blanchon [mailto:notifications@github.com]
Skickat: den 30 september 2020 09:46
Till: bblanchon/ArduinoJson
Kopia: Mats Webjörn/WIKAB; Mention
Ämne: Re: [bblanchon/ArduinoJson] Case independent key selection (#1391)


Hi @matswebjorn<https://github.com/matswebjorn>,

ArduinoJson doesn't natively support case-insensitive lookup.

However, you could use an std::string with custom character traits.
See here for an example: https://stackoverflow.com/a/5319855/1164966

If std::string is not an option, then you can use iterators<https://arduinojson.org/v6/api/jsonobject/begin_end/> to find the key.

Best regards,
Benoit
