### ISSUE TITLE
Why "false" is treated as 1?

### ISSUE THREAD

**Issue by MarkEstrada** [bblanchon/ArduinoJson#1397]
I am calling a service that returns the following response

`{"isOk":"false"}`

Note: The "false" has a double quote and even if I call this in my browser, it has quote...
```
  ReadLoggingStream loggingStream(mySerial, Serial);
  DeserializationError error = deserializeJson(doc, loggingStream);


  if (error) {
    //    Serial.print(F("deserializeJson() failed: "));
    Serial.println(error.c_str());
    return error.c_str();
  }

  const bool  isOk = doc["isOk"].as<bool>();
  Serial.print(isOk); -----------> this prints to 1
```
Not sure if "false" is treated as 1?  I used ArduinoJson 6.

**Comment by bblanchon** [comment]
Hi @MarkEstrada,

ArduinoJson treats `0`, `0.0`, `false`, and `null` as falsy.
All other values (including the string `"false"`) are truthy.

Note that JavaScript behaves the same way:

```javascript
if ("false") console.log("Damned!");
```

As a workaround, you can compare `doc["isOk"]` with "true":

```c++
bool isOk = doc["isOk"] == "true";
```

Best regards,
Benoit
