### ISSUE TITLE
Advanced streaming example issue

### ISSUE THREAD

**Issue by tkerby** [bblanchon/ArduinoJson#1402]
Noticed some possible issues in the examples at https://arduinojson.org/v6/api/json/serializejson/

File file = SD.open(filename, FILE_WRITE);
WriteLoggingStream loggedFile(client, Serial);
doc["hello"] = "world";
serializeJson(doc, loggedFile);
file.close();

Should the second line be "file" instead of "client"?

File file = SD.open(filename, FILE_WRITE);
WriteBufferingStream bufferedFile(client, 64);
doc["hello"] = "world";
serializeJson(doc, loggedFile);
bufferedFile.flush();
file.close();

Should the second line be "file" instead of "client"? Also when serializing, should "loggedFile" be "bufferedFile"

**Comment by bblanchon** [comment]
You are absolutely right!
It should be fixed now.
Thanks for reporting this issue 👍
