### ISSUE TITLE
PubSubClient Payload Serialization exit OK but could not access data.

### ISSUE THREAD

**Issue by CristoJV** [bblanchon/ArduinoJson#1403]
The arduino MKR100 is receiving an array of bytes from MQTT telemetric queue supported by the PubSubClient library.

This is the received bytes decoded with UTF-8 format. This is what is printed with Arduino Serial.

SERIAL OUTPUT:
```
"{\"red\":100,\"g\":100,\"b\":100,\"wc\":100,\"ww\":100}"
```
Notice that there is " at the start and the end of the payload, so it is a String.
When I deserialize this array of (bytes *) using the provided library method deserializeJSON, it return no errors. Everything is Ok. However when I tried to access the "red" key-value (the first key), I'm getting -1.

This is my PubSubClient callbacke "handle_msg" method:
```
void handle_msg(char *topic, byte *payload, unsigned int length) {

      #Create Static Json Document.
      StaticJsonDocument<256> doc;
      #Deserialization

      DeserializationError err = deserializeJson(doc, payload, length);
      Serial.println(err.c_str());

      int r = doc["red"] | -1;

      Serial.println(r);
      Serial.print(doc["red"].is<int8_t>());
      Serial.print(doc["red"].is<int16_t>());
      Serial.print(doc["red"].is<int32_t>());
      Serial.print(doc["red"].is<char*>());
      Serial.print(doc["red"].is<double>());
      Serial.print(doc["red"].is<float>());
}

```
SERIAL OUTPUT:
```
Ok
-1
000000
```

I think the error is that the payload is a String interpretation in bytes and therefore the string is not interpreted.

To solve this I have to do the trick I'm posting in the following comment.

**Comment by CristoJV** [comment]
I could find a trick solution.
First I create a String with the payload.
```
String str = String((char*)payload);
```
then I converted to a char array.
```
char output[100];
str.toCharArray(output, length);
```
then I deserialize the JSON
```
deserializeJson(doc, output, length);
int r = doc["red"] | -1;
Serial.println(r);
```
And It works.

SERIAL PRINTS____

```
100
```

**Comment by bblanchon** [comment]
Hi @CristoJV,

The following JSON document is a string, not an object:

```json
"{\"red\":100,\"g\":100,\"b\":100,\"wc\":100,\"ww\":100}"
```

The object looks like this:

```json
{"red":100,"g":100,"b":100,"wc":100,"ww":100}
```

You can extract the object from the original string with ArduinoJson, but you need to call [deserializeJson()](https://arduinojson.org/v6/api/json/deserializejson/) twice:

```c++
StaticJsonDocument<100> doc1;
deserializeJson(doc1, json);

StaticJsonDocument<200> doc2;
deserializeJson(doc2, doc1.as<const char*>());

int r = doc["red"] | -1;
```

Best regards,
Benoit

**Comment by bblanchon** [comment]
PS: [demo on wandbox.org](https://wandbox.org/permlink/AWHlKiSFmMalMZYU)

**Comment by CristoJV** [comment]
Thank you Benoit, but why do I have to call it twice?
Does the deserialization perform different tasks when it is called with a String or with a JSON object?
Is it justified the use of more memory just to be able to deserialize the JSON String?

As far as I understand we are using the recursiveness of this deserialize function. So the first time it deserializes it creates a JSON Object with a string and the second deserialization goes withing this string and decode into another JSON Object.

So is would not be good either to convert the string straightforward to a JSON Object? Is it possible to indicate to the function to return the JSON object obtained after 2 recursions, so I can save memory space?

Thank you :D!

**Comment by bblanchon** [comment]
Usage is unusual because the input is unusual; you would have to do the same with any library.
To simplify the program and reduce memory consumption, you should repair the input.
