### ISSUE TITLE
Converting Json Object to Json String

### ISSUE THREAD

**Issue by thedim-witted** [bblanchon/ArduinoJson#1406]
Hi,

I am using v5.13 
I want to convert a Json Object like this:
{"sensor":"gps","time":1351824120,"data":[48.756080,2.302038]}

To a Json String like this:
`{\"sensor\":\"gps\",\"time\":1351824120,\"data\":[48.756080,2.302038]}`

My server pipeline is expecting data in the Json String format for some reason which cannot be changed at this time. I already have the code to collect data and convert it to Json Object. I want to use it to generate a Json String like above.

**Comment by bblanchon** [comment]
Hi @thedim-witted,

Starting with [JsonGeneratorExample.ino](https://arduinojson.org/v5/example/generator/), simply replace `root.printTo(Serial)` with:

```c++
root.printTo(myString);
```

See also:

* [Serialization Tutorial](https://arduinojson.org/v5/doc/serialization/)
* [JsonObject::printTo()](https://arduinojson.org/v5/api/jsonobject/printto/)

Best regards,
Benoit

**Comment by thedim-witted** [comment]
I have already tried that but does not add the backslashes as mentioned in the question

**Comment by bblanchon** [comment]
The easiest way is to call:

```c++
myString.replace("\"", "\\\"")`
```

This works for simple cases but breaks when strings include escaped quote characters.

For a more robust (but more convoluted) solution using ArduinoJson, you can create an array with one element (the string) and call `printTo()` on that element.

BTW, why do you need to escape the quote characters?
