### ISSUE TITLE
Smart pointers (example in book "Mastering ArduinoJson 6")

### ISSUE THREAD

**Issue by JurgenO** [bblanchon/ArduinoJson#1409]
Good evening,
this issue report is about the example on page 46 in chapter 2.4.3 Smart Pointers in the book "Mastering ArduinoJson 6".

The code doesn't compile without some changes. 

**Issue 1**
The destructor should be
`~MyStructPtr(){
    delete _p;
  }
`

**Issue 2 declare methods as public**
I need to declare the class as
`class MyStruct {
  public: 
   MyStruct() {} // constructor
   ~MyStruct() {} // de-structor
  void myFunction () {} 
};
`
If I don't declare the methods as "public:" then the compiler error message is:

> src\main.cpp: In destructor 'MyStructPtr::~MyStructPtr()':
> src\main.cpp:205:4: error: 'MyStruct::~MyStruct()' is private
>     ~MyStruct() {} // de-structor
>     ^
> src\main.cpp:225:12: error: within this context
>      delete _p;
>             ^
> src\main.cpp: In function 'void setup()':
> src\main.cpp:204:4: error: 'MyStruct::MyStruct()' is private
>     MyStruct() {} // constructor
>     ^
> src\main.cpp:248:30: error: within this context
>    MyStructPtr p(new MyStruct());
>                               ^
> src\main.cpp:206:8: error: 'void MyStruct::myFunction()' is private
>    void myFunction () {} // member function
>         ^
> src\main.cpp:260:17: error: within this context
>    p->myFunction(); 
>                  ^
> *** [.pio\build\nodemcu-32s\src\main.cpp.o] Error 1
 
 
**Issue 3: add void return type**
In class of issue 2: if I don't provide the void return type the compiler error message is: "ISO C++ forbids declaration of 'myFunction' with no type [-fpermissive]"

**My environment:**
- Development: Win 10, Microsoft Visual Studio, Platformio
- Target: ESP32 

BTW, the book "Mastering ArduinoJson 6" is great. I do have experience in coding and embedded systems. It is a pleasure to read the book because it is systematic, clear ... and crisp !

Greetings from Germany 
Juergen

**Comment by bblanchon** [comment]
Hi Juergen,

Thank you very much for reporting these.
I fixed the issues in the manuscript; they'll be part of the next revision.

Best regards,
Benoit
