### ISSUE TITLE
Filtering from JSON Array

### ISSUE THREAD

**Issue by jomiva** [bblanchon/ArduinoJson#1410]
Hey, I've seen others issues about filtering and JsonFilterExample.ino but I couldn't solve my problem.
I have a Json Array (keys.json) which has an array of objects. Example:
[
  {
    "code": 268435455,
    "name": "Maria",
    "status": false,
  },
  {
    "code": 1234,
    "name": "Jose",
    "status": true,
  }
]

If I try to deserialize it without filtering, it works fine. But if I try to filter "code" and "status", returns null.
This is my filter.
StaticJsonDocument<64> filter;
filter["codigo"] = true;
filter["status"] = true;
deserializeJson(doc, llavesFile, DeserializationOption::Filter(filter));

The difference between this and other issues is that I'm filtering from an Json Array and not from a Json Document which has an array inside. 

My code
![image](https://user-images.githubusercontent.com/48603039/96745147-d0416900-1393-11eb-8f1f-8eaf171b9ae3.png)

**Comment by bblanchon** [comment]
Hi,

The input document is an array, so the filter must be an array too:

```c++
filter[0]["codigo"] = true;
filter[0]["status"] = true;
```

See:

* [`deserializeJson()`, Filtering](https://arduinojson.org/v6/api/json/deserializejson/#filtering)
* [JsonFilterExample.ino](https://arduinojson.org/v6/example/filter/)
* [ArduinoJson 6.15: Filtering done right](https://arduinojson.org/news/2020/03/22/version-6-15-0/)

Best regards,
Benoit

**Comment by jomiva** [comment]
Thanks! I thought I needed to filter it with an object.

**Comment by bblanchon** [comment]
You're welcome @jomiva. Good luck with your project!
Don't hesitate to [cast a star](https://github.com/bblanchon/ArduinoJson/stargazers) to support the project 😉.
