### ISSUE TITLE
[proposal] add JsonDocument to keywords.txt

### ISSUE THREAD

**Issue by jjsuwa-sys3175** [bblanchon/ArduinoJson#1413]
for example, we'll write a `JsonDocument`-related function by Arduino IDE:
```
bool transact(JsonDocument& dResponse, const JsonDocument& dRequest) { // regardless of whether static or dynamic
  if (!dRequest.is<JsonArray>) {
    ...
```
sadly, `JsonDocument` won't be highlighted...

**Comment by bblanchon** [comment]
Hi @jjsuwa-sys3175,

That's one of the only cases where I would accept a PR without unit tests.
Come on! Take your chance 😉 

Best regards,
Benoit

**Comment by bblanchon** [comment]
PR merged. Thanks!
