### ISSUE TITLE
Json Response Dynamic

### ISSUE THREAD

**Issue by ghost** [bblanchon/ArduinoJson#1417]
Hello friends.
I have a doubt when using deserializeJson   . (ArduinoJson 6.17.0)

The doubt is as follows:
i'm making a request to a server, he answers me a json, the answer can be dynamic in length, so I can't do DynamicJsonDocument jsonBuffer (200); , because the answer can be greater than 200.

Someone can help me

**Comment by bblanchon** [comment]
Hi @mjoelmendes,

Please read:

* [How to determine the capacity of the JsonDocument?](https://arduinojson.org/v6/how-to/determine-the-capacity-of-the-jsondocument/)

Best regards,
Benoit
