### ISSUE TITLE
arduinojson assistant - offline variant

### ISSUE THREAD

**Issue by valoni** [bblanchon/ArduinoJson#1418]
is there any way to use  offline ArduinoJSON assistant 
(depending of used library 5,6 ...)

hope there's will be such tools

**Comment by bblanchon** [comment]
Hi @valoni,

To use the ArduinoJson Assistant offline, you can save the page from your browser.

Best regards,
Benoit

**Comment by valoni** [comment]
i saved page but when i post json data do not generated anything 
(expecially if i have no internet connection)

**Comment by bblanchon** [comment]
Indeed, I just tested, and it doesn't work :-(
I'm sorry, but I currently don't have any other options.
