### ISSUE TITLE
Error: nullptr defined as a macro on ESP8266 Arduino IDE (Visuino)

### ISSUE THREAD

**Issue by detmot5** [bblanchon/ArduinoJson#1420]
Hey, I got an error while compiling library on ESP8266 with Visuino generated code.

error: #error nullptr is defined as a macro. Remove the faulty #define or #undef ullptr
 #error nullptr is defined as a macro. Remove the faulty #define or #undef nullptr

I also found out how to fix it.

In file Configuration.h where we have 
#if __cplusplus >= 201103L
i inserted
#ifdef nullptr
#undef nullptr
#endif

I already made pull request

**Comment by bblanchon** [comment]
Hi @detmot5,

As I said in PR #1421, this error message is there on purpose; see #1355.

It's not the job of ArduinoJson to fix the mess introduced by other libraries.
Please submit a patch to the library that defines `nullptr` as a macro, or place the `#undef` in your main program.

Thank you for your understanding.

Best regards,
Benoit
