### ISSUE TITLE
Setting values in an array not working for all

### ISSUE THREAD

**Issue by glowlabs** [bblanchon/ArduinoJson#1423]
I am having a weird issue setting values in an array. I have 2 json objects. I'm trying to copy a value called "name" from json1 and set it in json2.

Here's my code:

  for (int i = 0; i < 8; i++) {
    String name1 = json1[i]["name"];
    Serial.println(name1);
    json2[i]["name"] = name1;
    String name2 = json2[i]["name"];
    Serial.println(name2);
  }

This works for the first 2 items, but not the next 6. My serial monitor logs name1 correctly for all 8.

Both JSON objects are created before these step and each have array lengths of 8. Both have the property "name" set as well. 

Any ideas why it stops working after the 2nd value?

**Comment by bblanchon** [comment]
Hi,

Please see [Why is the output incomplete?](https://arduinojson.org/v6/faq/why-is-the-output-incomplete/)

Best regards,
Benoit
