### ISSUE TITLE
Invalid  Input error from deserializeJson

### ISSUE THREAD

**Issue by Andy1968T** [bblanchon/ArduinoJson#1426]
Getting invalid input error from deserializeJson  with the returned Json from weather forcast API it hangs for quite a while before returning error. Other API return fine so don't think it's the code. the serial output of JSON shows 3 strange characters at the begin and a 0 at end.  What is happening to the JSON to have this issue and how do i resolve it.  Also can the code be cleaned up a const size_t capacity seems a bit hit and miss if the returned JSON is bigger than expected.Using esp32 on Arduino IDE.   Bit new at this, so go easy on me. Thanks Andy
void Weather_forcast() {
  StartWiFi();
  HTTPClient http;

  http.begin("http://api.openweathermap.org/data/2.5/weather?q=Highworth,UK&units=metric&APPID=bc6af0*****************479fa8"); //  description of use https://openweathermap.org/current#name
  int httpCode = http.GET();                                        //Make the request

  if (httpCode > 0) { //Check for the returning code
    Serial.println(httpCode);
    const size_t capacity = JSON_ARRAY_SIZE(1) + JSON_OBJECT_SIZE(1) + 2 * JSON_OBJECT_SIZE(2) + JSON_OBJECT_SIZE(4) + JSON_OBJECT_SIZE(5) + JSON_OBJECT_SIZE(6) + JSON_OBJECT_SIZE(13) + 320; // was 270
    DynamicJsonDocument doc(capacity);
    String payload = http.getString();
    const char* json = payload.c_str();
    deserializeJson(doc, json);
    Serial.println(json);
    DeserializationError err = deserializeJson(doc, json);
    if (err) {
      Serial.print ("ERROR:");
      Serial.println(err.c_str());
      return;
    }

Serial debug output of JSON string (sorry output is as a cut and paste image. Adruino serial monitor does not have a copy txt and paste ability

![image](https://user-images.githubusercontent.com/17797134/97798686-26c66700-1c20-11eb-9f16-a25751bd3d55.png)

**Comment by bblanchon** [comment]
Hi @Andy1968T,

This looks like [Chunked transfer encoding](https://en.wikipedia.org/wiki/Chunked_transfer_encoding). It should be handled by `http.getString()`, but there may be a bug. Make sure your [ESP8266 core](https://github.com/esp8266/Arduino) is up to date.

Alternatively, try to call `http.useHTTP10(true)` before sending the request to disable [Chunked transfer encoding](https://en.wikipedia.org/wiki/Chunked_transfer_encoding).

See also:

* [How to use ArduinoJson with HTTPClient?](https://arduinojson.org/v6/how-to/use-arduinojson-with-httpclient/)

Best regards,
Benoit

**Comment by Andy1968T** [comment]
Thank You  I can confirm http.useHTTP10(true) solved the problem
