### ISSUE TITLE
Delay in Json packet

### ISSUE THREAD

**Issue by ArsalanKhan22** [bblanchon/ArduinoJson#1427]
Hi! I am using ArduinoJson version 6.9 for my JSON packet sending through E-Byte E62 modules from an Arduino mega to another but there is much more delay like 2-3 seconds...How i can resolve it?Thanks

**Comment by bblanchon** [comment]
Hi @ArsalanKhan22,

Please read [Why is ArduinoJson slow?](https://arduinojson.org/v6/faq/why-is-arduinojson-slow/) and see if this applies to E-Byte E62 modules.

Best regards,
Benoit
