### ISSUE TITLE
definition of swap() in utilities.hpp conflicts with #define in other Arduino libraries

### ISSUE THREAD

**Issue by agprimatic** [bblanchon/ArduinoJson#1429]
Hi,

May I suggest using a more unique name for your definition of swap() in utility.hpp.

In some other Arduino libraries, swap() is defined as a #define macro, which causes ordering issues when including .h files.

I also let the owners of the Arduino libraries know that #define swap() is dangerous, but it wouldn't hurt to fix it in ArduinoJson as well.

Thanks,

Ag Primatic

**Comment by bblanchon** [comment]
Hi Ag Primatic,

This is clearly not an error in ArduinoJson.
This function is an implementation of the standard [std::swap()](https://en.cppreference.com/w/cpp/algorithm/swap) so I don't want to change the name.

Thank you for contacting the author of the library that defines this macro.
If this library is widely used, I can add a `#error`, as I did for #1355 
What do you think?

Best regards,
Benoit
