### ISSUE TITLE
ESP8266:12e => corrupted output from jsonDocument in case of usage inside class constructor

### ISSUE THREAD

**Issue by Abhimanyu6676** [bblanchon/ArduinoJson#1431]
**BOARD AND FRAME**
  * platform = espressif8266
  * board = nodemcuv2
  * framework = arduino
  * arduinoJson = 6.17.1

#To reproduce

## main.cpp

```
#include "main.hpp"
//#include "ws.hpp"
#inclide <ArduinoJson.h>

customClass C;

void setup(){
Serial.begin(115200);
delay(1000);
Serial.println("<<<<<<<<<<<<<<>>>>>>>>>>>>>>");
printJsonTest();
C.init();
}

void loop(){

}

void printJsonTest()
{
	DynamicJsonDocument doc(500);
	JsonObject obj = doc.to<JsonObject>();
	doc["a"] = 34;
	doc["d"] = 194;
	doc["temp1"] = String("gcouglb.j");
	doc["temp2"] = String("gcouglb.j");
	doc["temp3"] = String("gco uglb.j");
	doc["temp4"] = String("gco uglb.j");
	doc["temp5"] = String("gco uglb.j");
	doc["temp6"] = String("gco uglb.j");
	doc["temp7"] = String("gco uglb.j");
	serializeJson(doc, Serial);
        String temp;
        serializeJson(doc, temp);
        //if(wsClientConnected())
             //wsSendAll(temp);
	doc.clear();
}
```

## main.hpp
```

void printJsonTest();
```

## customClass.hpp

```
#pragma once
#include "main.hpp"

class customClass 
{
private:

public:
    customClass();
    ~customClass();

    void init();

};
```

## customClass.cpp

```
#include <Arduino.h>


customClass::customClass()
{
     printJsonTest();
}

customClass::~customClass()
{
}

void customClass::init()
{
}

```

# The output from the code is 

**{"a":34,"d":194,"temp1":"\N\ \ \N","temp2":"\N\ \ \N","temp3":"gco\Nuglb.j","temp4":"gco\Nuglb.j","temp5":"gco\Nuglb.j","temp6":"gco\Nuglb.j","temp7":"gco\Nuglb.j"}**

## however if the **printJsonTest()** code is changed as such

{
	StaticJsonDocument<500> doc;
	//JsonObject obj = doc.to<JsonObject>();
	doc["a"] = 34;
	doc["d"] = 194;
	doc["temp1"] = String("gco uglb.j");
	doc["temp2"] = String("gco uglb.j");
	doc["temp3"] = String("gco uglb.j");
	doc["temp4"] = String("gco uglb.j");
	doc["temp5"] = String("gco uglb.j");
	doc["temp6"] = String("gco uglb.j");
	doc["temp7"] = String("gco uglb.j");
	serializeJson(doc, Serial);
	//doc.clear();
}

**output is =>**
**{"a":34,"d":194,"temp1":"\N\ \ \N","temp2":"\N\ \ \N","temp3":"\N\ \ \N","temp4":"\N\ \ \N","temp5":"\N\ \ \N","temp6":"\N\ \ \N","temp7":"\N\ \ \N"}**

## inCase I do this 

```
void _stats()
{
	//DynamicJsonDocument doc(500);
	StaticJsonDocument<500> doc;
	//JsonObject obj = doc.to<JsonObject>();
	doc["t"] = "fb kh";
	doc["temp2"] = "hvdjfh";
	doc["d"] = 194;
	doc["temp3"] = "h-jgfgh";
	doc["temp4"] = "sdjha_klb";
	doc["a"] = 34;
	doc["temp5"] = "ryidtgh";
	doc["temp6"] = "adrshastgtj";

	serializeJson(doc, Serial);
	//doc.clear();
}
```

#### output is => **{"t":"\N\ \ \N","temp2":"hvdjfh","d":194,"temp3":"h-jgfgh","temp4":"sdjha_klb","a":34,"temp5":"ryidtgh","temp6":"adrshastgtj"}**

only first entry is corrupted and rest is fine, I have not made enough test to write that the output can not be relied upon

**Comment by bblanchon** [comment]
Hi @Abhimanyu6676,

I'm pretty sure the problem comes from the fact that you call this function *before* the `setup()` function.
I don't know the details but I don't think ArduinoJson is to blame here.

Best regards,
Benoit

**Comment by Abhimanyu6676** [comment]
Have tried after setup also. over http server now that is inside main loop but results are same

**Comment by bblanchon** [comment]
Please provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) so I can reproduce the problem here.

**Comment by Abhimanyu6676** [comment]
[u can find it here](https://github.com/bblanchon/ArduinoJson/issues/1431)

**Comment by bblanchon** [comment]
In a previous message, you said you could reproduce the issue when `serializeJson()` is called after `setup()`.
Would you mind sharing the code?
