### ISSUE TITLE
How connect to MQTT server

### ISSUE THREAD

**Issue by crashcoq** [bblanchon/ArduinoJson#1443]
Hello

I use ArduinoJson for decoding JSON message, it works fine.
But i would like to connect MQTT server with pass and log.

How use the command client.connect() for this?
It's possible?

Thanks

**Comment by bblanchon** [comment]
Hi @crashcoq,

ArduinoJson doesn't interfere with the MQTT connection.

Please read the documentation of your MQTT library.
[Here is the example for PubSubClient](https://github.com/knolleary/pubsubclient/blob/master/examples/mqtt_auth/mqtt_auth.ino)

Best regards,
Benoit
