### ISSUE TITLE
Add Reallocate method to SpiRam example

### ISSUE THREAD

**Issue by avidNewb** [bblanchon/ArduinoJson#1446]
I found a need to use the `shrinkToFit()` method with a JSON document in PSRAM.  I was able to do this by changing the allocator as follows:

```c++
struct SpiRamAllocator {
	void* allocate(size_t size) {
		return heap_caps_malloc(size, MALLOC_CAP_SPIRAM);
	}
	void deallocate(void* pointer) {
		heap_caps_free(pointer);
	}
	void* reallocate(void* ptr, size_t new_size) {
		return heap_caps_realloc(ptr, new_size, MALLOC_CAP_SPIRAM);
	}
};
```

Adding this to your example would be helpful to others.

**Comment by bblanchon** [comment]
Hi @avidNewb,

Thanks for reporting this issue.
I updated the page [How to use external RAM on an ESP32?](https://arduinojson.org/v6/how-to/use-external-ram-on-esp32/) accordingly.

Best regards,
Benoit
