### ISSUE TITLE
JsonArray.add(JsonArray) doesn't make an exact clone.

### ISSUE THREAD

**Issue by timkoers** [bblanchon/ArduinoJson#1457]
As per documentation (https://arduinojson.org/v6/api/jsonarray/add/#arguments), when calling add on an JsonArray it is expected to clone the JsonArray argument into the JsonArray that add is being called on.

Example;

```C++
JsonArray setPoints = output.createNestedArray("set_points");
setPoints.add(root["set_points"].as<JsonArray>()); // This will copy the values into the new array
```

`root["set_points"]` looks like:

```json
"set_points" : [
		{
			"temperature": 120,
			"duration": 90
		},
		{
			"temperature": 165,
			"duration": 30
		},
		{
			"temperature": 182,
			"duration": 120
		},
		{
			"temperature": 210,
			"duration": 30
		},
		{
			"temperature": 182,
			"duration": 30
		}
	]
```

Result:

```json
	"set_points": [
		[
			{
				"temperature": 120,
				"duration": 90
			},
			{
				"temperature": 165,
				"duration": 30
			},
			{
				"temperature": 182,
				"duration": 120
			},
			{
				"temperature": 210,
				"duration": 30
			},
			{
				"temperature": 182,
				"duration": 30
			}
		]
	]

```
Please note the extra pair of array indicators above.

I am expecting this behaviour:

```json

	"set_points": [{
			"temperature": 120,
			"duration": 90
		},
		{
			"temperature": 165,
			"duration": 30
		},
		{
			"temperature": 182,
			"duration": 120
		},
		{
			"temperature": 210,
			"duration": 30
		},
		{
			"temperature": 182,
			"duration": 30
		}
	]

```

**Comment by timkoers** [comment]
When using `set` instead of `add`, the library provides me with the expected result.

**Comment by bblanchon** [comment]
Hi @timkoers,

That's the expected behavior:

* [JsonArray::add()](https://arduinojson.org/v6/api/jsonarray/add/) appends to the array
* [JsonArray::set()](https://arduinojson.org/v6/api/jsonarray/set/) replaces the values

BTW, you can simply your code like so:

```c++
output["set_points"] = root["set_points"];
```

Best regards,
Benoit

**Comment by timkoers** [comment]
Ah ok, I think I misread the documentation. My fault.

Have a nice year's ending and all the best for 2021

**Comment by bblanchon** [comment]
Thanks! Best wishes to you as well.
Good luck with your project.
