### ISSUE TITLE
Recurrence of #1191

### ISSUE THREAD

**Issue by kawinie** [bblanchon/ArduinoJson#1459]
Hi I am experiencing #1191 again with the latest version of the library. Seems like `.set()` treats `char[]` as `const char *` when it should copy all data instead of pointer.

UPDATE: It seems like this only happens if I use JsonVariant

**Comment by bblanchon** [comment]
Hi @kawinie,

I double-checked and [it should already be covered by the unit tests](https://github.com/bblanchon/ArduinoJson/blob/1360b6a396e096365c917a5518cf29aeac6c9444/extras/tests/JsonVariant/set.cpp#L32-L41).
Can you provide a repro?

Best regards,
Benoit
