### ISSUE TITLE
Header content for the meteo-concept website

### ISSUE THREAD

**Issue by jmlocci** [bblanchon/ArduinoJson#1460]
I am trying to retrieve a response at JSON format from the website https://api.meteo-concept.com/ (for which I have a token). I succeed in receiving a response in a XML format, and to get a JSON format I need to append the header.

The instructions to receive a response to a request in JSON format exist only for "curl":

curl -H "Content-Type: application/json" https://api.meteo-concept.com/api/forecast/daily?token=MY_TOKEN&insee=65292

Some other bits of instructions stipulate that the output format is driven by the preferences of User-Agent expressed in the “Accept” header.

I have done a lot of browsing to figure what parameters I shoud use in the http.addHeader() code, with no success. The http.GET() returns a [-1] error code.

I am using the latest Arduino IDE on a nodeMCU board, on which I manage to run all my other JSON deserialzation projects.

Can I receive some help on the issue ?

Many thanks, regards

Jean-Marie LOCCI

**Comment by bblanchon** [comment]
Hi Jean-Marie,

This is a question for the authors of the `HTTPClient` class.

In my projects, I rarely use the HTTP helper libraries; I prefer using `WifiClient` directly, as shown in [JsonHttpClient.ino](https://arduinojson.org/v6/example/http-client/) and the OpenWeatherMap, Reddit, and Adafruit IO cases studies in [Mastering ArduinoJson](https://arduinojson.org/book/).
In this case, adding a header is simply a matter of adding one `client.println(F("Content-Type: application/json"))`.

Best regards,
Benoit
