### ISSUE TITLE
GET requests on server accepting HTTPS & "Let's Encrypt" certificate

### ISSUE THREAD

**Issue by jmlocci** [bblanchon/ArduinoJson#1465]
Good'day all

I want to implement a GET request on a site that only accepts HTTPS with a "Let's Encrypt" certificate. I try to mimic the REDDIT example found in the book, advising the use of WiFiClientSecure.

The site is "api.meteo-concept.com", it requires the implementation of SSL/TLS on port 443.

The piece of code:

` const char* URL = "api.meteo-concept.com";
  const int PORT = 443;

  // Connect to host
  WiFiClientSecure client;
  // BearSSL::WiFiClientSecure client;  // alternative to the above
  client.setInsecure(); // bypass the "Let's Encrypt" certificate to allow succesful connection to server
  client.setTimeout(10000);
  client.connect(URL, PORT));

  // Send HTTP request
  client.println(F("GET /api/forecast/daily?insee=65292 HTTP/1.0"));
  client.println(F("Authorization: MY_TOKEN"));                                  // Happy to provide MY_TOKEN through PM
  client.println(F("Host: api.meteo-concept.com"));
  client.println(F("Connection: close"));

  // Check HTTP status
  char status[32] = {0};
  client.readBytesUntil('\r', status, sizeof(status));
  Serial.print("Server response code : ");
  Serial.println(status);
`
If the "client.setInsecure()" line is inactive, the connection fails
If the "client.setInsecure()" line is active, the connection succeds but the server response is empty

I suspect the GET request is unsuccessful due to incorrect credentials, probably because the "Let's Encrypt" certification authotity is not delt with in Arduino.

Can anyone confirm or advise?

Many thanks

**Comment by bblanchon** [comment]
Hi @jmlocci,

I don't know how the certificate verification works in this library, but you probably need to feed it with root certificates (take a look at `setTrustAnchors()`).
Unfortunately, that means updating them every year, and I don't know if we can securely automate the process.

Regarding the empty response, do you at least get a status code?
Empty responses are often due to a redirect, so I wouldn't be surprised to see a 302 or 301.

Best regards,
Benoit

**Comment by jmlocci** [comment]
Hello Benoit.

I will look into the `setTrustAnchors()`

No, no error code, that's weird. In fact the response to the GET is just "1" (Serial.println(client)). The  word "status" is therefore not found. The "invalid response" code in the serial output below is generated by the "Skip HTTP headers" instruction.

`Serial output in setDebugOutput mode:

dhcp client start ...
ip: 192.168.1.99,mask: 255.255.255.0, gw: 192.168.1.1
Connected to server : api.meteo-concept.com, Port 443
Server response code :
1
pm open,type :2 0
Invalid response`

Well, never mind... Thanks!!!

**Comment by martinius96** [comment]
@jmlocci 
Hello there, can you please specify also what board are you using?
Based on code I think it is ESP32? I tried it with ESP32 and edited it how I am using HTTPS connections.
I have put DST ROOT CA X3 certificate in .pem format to code, connection is working and I get response from webserver about autorization. (THAT ROOT CA IS ISSUING CERTIFICATES FOR LET'S ENCRYPT).
![DST ROOT CA X3 - MOST ROOT authority in chain of trust](https://i.imgur.com/So5dzsw.png)
As you can see at screenshot below from UART monitor, return code HTTP 401 - 401 Unauthorized. So I think, if you put there your token it will work and you will be able to see what server will print you behind Authorization :).
![Successful connection](https://i.imgur.com/hqcnWEQ.png)

**Program implementation on ESP32**: https://pastebin.com/341FAXm7

**Comment by jmlocci** [comment]
Hello Martin

Many thanks for that. I am using an nodeMCU board 12E type based on an ESP8266, so the code will probably not compile straight away and will need some modifications, I have to use the ESP8266WiFi library. Or... I can get myself a ESP32, It was planned anyway.

**Comment by martinius96** [comment]
I have never used that BearSSL library for ESP8266. I was still using only WiFiClientSecure for HTTPS connections.

This one is working for ESP8266, but it  is with setInsecure() option: https://pastebin.com/2nJYxL3e
I was testing it under Arduino Core 2.5.2 for ESP8266 :-) A bit older....
When I was trying with SHA1 fingerprint, I was unable to connect to host, idk why...
DST Root CA X3 at 27th February will expire. Also server cert will expire until new CA (that will come after DST ROOT CA X3) will issue it (it will also change fingerprint, still at renew of certificate and so on). 

Fingerprint nowadays is valid for year or two (if certificate is issued for 2 years). 
Year is more often... For that ESP32 is using Root CA certificates and these can be valid for like 20 years...

**Comment by jmlocci** [comment]
Ni again Martin.

I have used your updated script with my own API key. Good progress (check serial output below), but not quite there. The certificate must be the issue. Curiously, when I modify randomly my token the serial output remains the same (and I am sure my token is correct, it works on a browser).

I have ordered a set of ESP32 to use with the appropriate library, I will need some anyway. I will keep you posted.

Thanks again.

`.
Wifi connected, IP address of ESP:
192.168.1.99
Connection to server was successful
HTTP/1.1 401 Unauthorized
Server: nginx
Date: Tue, 05 Jan 2021 22:00:55 GMT
Content-Type: application/json
Connection: close
Cache-Control: private, must-revalidate
pragma: no-cache
expires: -1
Vary: Authorization

{"message":"Authentication Required"}
`

**Comment by martinius96** [comment]
Hello there. 
Can i try it with some testing API key?
If it is possible, you can send it to me: martinius96@gmail.com
And i can try it and let u know.

**Comment by martinius96** [comment]
I have tested it again and also I checked documentation...
Based on API documentation of meteo-concept: https://api.meteo-concept.com/documentation#auth, there are 2 available methods for Authorization:
- Bearer token header in request
- parameter in GET request (like: /api/forecast/daily?insee=65292&token=XYZKEY)

Last time we were using without Authorization Bearer, so it was working as Basic Auth that require username and password.
There is example for Bearer token (tested with ESP8266 - NodeMCU v3 Lolin) - insecured: https://pastebin.com/vJZgupYh
Now working :-)
![Output - UART](https://user-images.githubusercontent.com/14253034/104725280-26733d80-5732-11eb-93f5-89b698a6d6e2.png)
ESP32 example Bearer token (havent tested, but should work too - same edit in code): https://pastebin.com/8ibA8iGv

**Comment by bblanchon** [comment]
@jmlocci, what is the status of this issue?

**Comment by jmlocci** [comment]
Sorry Benoît, I thought you had closed the issue. I have received some help
that resolved my problem (from Martin, thanks to him).

Merci !!!

Le jeu. 21 janv. 2021 à 09:44, Benoît Blanchon <notifications@github.com> a
écrit :
