### ISSUE TITLE
Arduino IDE 1.6.6. warning ...

### ISSUE THREAD

**Issue by Apollon77** [bblanchon/ArduinoJson#147]
Arduino IDE 1.6.6 brings this wanring on compile time:

WARNING: Category '' in library ArduinoJson is not valid. Setting to 'Uncategorized'

Seems to be that a small change in library.-property can fix this :-)

**Comment by bblanchon** [comment]
I wonder which category I should use:

* Communication
* Data Storage
* Data Processing
* Other

They all seems to match more or less.

**Comment by Apollon77** [comment]
I personally would see "Data Processing" the best fit ... because you parse JSon data ... and this is the basic functionality for later "storage" and/or "communication" ... My personal opinion ...

**Comment by domonetic** [comment]
"Data Processing" +1

2015-11-04 7:36 GMT-03:00 Ingo Fischer <notifications@github.com>:

> I personally would see "Data Processing" the best fit ... because you
> parse JSon data ... and this is the basic functionality for later "storage"
> and/or "communication" ... My personal opinion ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bblanchon/ArduinoJson/issues/147#issuecomment-153677590>
> .
>



-- 
El que pregunta aprende, y el que contesta aprende a responder.

No a la obsolecencia programada:
http://www.rtve.es/noticias/20110104/productos-consumo-duran-cada-vez-menos/392498.shtml

Linux User #495070
http://domonetic.com/blog

**Comment by bblanchon** [comment]
Nevermind... i'll close the issue when this will be available in the library manager

**Comment by bblanchon** [comment]
Fixed in version 5.0.6
