### ISSUE TITLE
Anyone Bored ESP32 smart thermostat needs ArduinoJson ;-)

### ISSUE THREAD

**Issue by ldijkman** [bblanchon/ArduinoJson#1470]
Anyone Bored ESP32 smart thermostat needs ArduinoJson ;-)

it will Better to make a tab discussions on this github page?

maybe someone out here willing to help me with ArduinoJSON
ESP32 smart thermostat

http://www.Arduino.TK
https://oshwlab.com/l.dijkman
https://github.com/ldijkman/ART-ESP32-Touch-TFT-Thermostat
Art's Facebook Group https://www.facebook.com/groups/esp32smartthermostat
youtube.com/user/LuberthDijkman/videos

**Comment by bblanchon** [comment]
Is this a strange way of asking me to enable GitHub's discussion feature on this repo?
Or are you just trying to get backlinks? 🤨
