### ISSUE TITLE
Json Assistant

### ISSUE THREAD

**Issue by victor7376** [bblanchon/ArduinoJson#1474]
When trying to use Arduino Json Assistant v6, near the end of the assistant there is a 'i' which you were able to click on to see the 'expression' for Json, but when clicking on the 'i' since a update of the assistant was released for v6 it doesnt seem to work any longer.

I did think at one point it maybe to do with flash player being uninstalled, but even tried with a laptop that has flash player still installed.

**Comment by bblanchon** [comment]
Thanks for reporting this bug. It should be fixed now.
