### ISSUE TITLE
Wrong capacity for `const` types

### ISSUE THREAD

**Issue by MohammedNoureldin** [bblanchon/ArduinoJson#1488]
Hello,

according to my observations, it turned out that the assistant, if I see correctly, does not distinguish between writable `char *` and the `const char *`, and thus gives the wrong capacity for this `const` case.

Reminder: 

According to https://arduinojson.org/v6/api/json/deserializejson/

> // writable input => zero-copy  
> DeserializationError deserializeJson(JsonDocument& doc, char* input);  
> // read-only input => duplication  
> DeserializationError deserializeJson(JsonDocument& doc, const char* input);

I stated this in my answer here too: https://arduino.stackexchange.com/a/81175/27953

Best,

**Comment by bblanchon** [comment]
Hi @MohammedNoureldin,

Thank you for reporting this bug.
It should be fixed by now.

Best regards,
Benoit
