### ISSUE TITLE
Fix CI Builds

### ISSUE THREAD

**Issue by maxgerhardt** [bblanchon/ArduinoJson#1493]
On the [main page](https://github.com/bblanchon/ArduinoJson) it can be seen that the the builds are failing. 

Further looking at https://travis-ci.org/github/bblanchon/ArduinoJson shows that 3 tests regarding clang are failing with an error message

```
NEW_FUNC[1/1]: ==7314==ERROR: External symbolizer path is set to '/usr/bin/llvm-symbolizer-7' which isn't a known symbolizer. Please set the path to the llvm-symbolizer binary or other known tool.
```

and 3 PlatformIO tests are failing with

```
+pip install --user platformio
..
Successfully installed bottle-0.12.19 click-7.1.2 colorama-0.4.4 marshmallow-2.21.0 platformio-5.1.0 pyelftools-0.27 semantic-version-2.8.5 tabulate-0.8.7
+platformio lib install 868

Error: Python 3.6 or later is required for this operation. 

Please check a migration guide:

https://docs.platformio.org/en/latest/core/migration.html#drop-support-for-python-2-and-3-5
```
The latter shoult be fixed installing Python3 and using `pip3` to install PlatformIO. For the first one, idk.

**Comment by bblanchon** [comment]
Hi @maxgerhardt,

Thank you for reporting this issue.
I'm currently migrating the CI from Travis to GitHub Actions.
Hopefully, it'll be done soon.

Best regards, 
Benoit
