### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by theloypa** [bblanchon/ArduinoJson#1502]
Hi I am Mahmut from turkey ı am studen at mersin university electronic engineering .
Now ı have a project ı will do drone . now ı need to take position of drone . thats why ı am thinking using bno055 and send data with nrf24l01 . But ı dont know how ı can sende a few data same time . ı need to  parse but ı dont know how can ı do.  Can you help me how can ı send a few data with nrf ?
Thank you

**Comment by bblanchon** [comment]
Hi Mahmut,

I'm sorry, I don't have any experience with this hardware.
I think you'll have a better chance of getting a response if you ask the question to the authors of the RF24 library.

Best regards,
Benoit
