### ISSUE TITLE
DynamicJsonDocument size

### ISSUE THREAD

**Issue by yaroshd81** [bblanchon/ArduinoJson#1509]
I have a problem when calculate size for variable DynamicJsonDocument:
`  File jsonFile = SPIFFS.open('/' + fileNameJsonModel, "r");
  if (!jsonFile)
  {
    Serial.printf("Failed to open config file: %s\n", fileNameJsonModel.c_str());
    return 2;
  }
  uint32_t sizeFile = jsonFile.size();
  if (sizeFile > MAX_LENGTH_JSON_FILE)

  {
    Serial.print("Config file size is too large: %d\n", sizeFile);
    return 3;
  }
  jsonModelSelect = new DynamicJsonDocument(sizeFile);
  DeserializationError error = deserializeJson(*jsonModelSelect, jsonFile);
  if (error)
  {
    Serial.println(F("Failed to read file"));
    return 0;
  }
`
If i use this code i see in terminal:

**Failed to read file**
File have size 986 Byte. If i use 

`jsonModelSelect = new DynamicJsonDocument(sizeFile+1000);` 
its working, but i don't understend what i must calculater size for my DynamicJsonDocument variable

**Comment by bblanchon** [comment]
Hi @yaroshd81,

Please read:

* [How to determine the capacity of the JsonDocument?](https://arduinojson.org/v6/how-to/determine-the-capacity-of-the-jsondocument/)

Best regards,
Benoit
