### ISSUE TITLE
Getting issue when use Arduinojson with ESP32 (Board: ESP32 Dev Module) with WIFI

### ISSUE THREAD

**Issue by mwaseemwali** [bblanchon/ArduinoJson#1512]
whenever i use Arduino JSON library with ESP32, Dev Module board. my wifi disconnect after a little time passed.

**Comment by vortex314** [comment]
No Issue here, I used ArduinoJson on ESP32 with esp32_idf and the device keeps running for weeks. Just be aware that JsonDocument could need clear() after use.
See : https://arduinojson.org/v6/api/jsondocument/clear/

**Comment by bblanchon** [comment]
Hi @mwaseemwali,

This could be due to slow serialization.
Please read:

* [How to improve (de)serialization speed?](https://arduinojson.org/v6/how-to/improve-speed/)

Best Regards,
[Benoit](https://paypal.me/benoitblanchon)

**Comment by ratzi30** [comment]
@mwaseemwali, 
I had the same problem with my ESP32.
Check if you have a memory leak, this will cause the wifi to disconnect.
