### ISSUE TITLE
createNestedArray

### ISSUE THREAD

**Issue by amedeodivito** [bblanchon/ArduinoJson#1523]
why the generated json code includes only the first 5 data instead of 6?
who can help me?
`void statoImpianto() {
  doc.clear();
  doc["ident"] = "termo";                                    // identita' dispositivo
  doc["UM"] = Hum;                                           // Umidita'
  doc["TA"] = Tem;                                           // Temperatura attuale
  doc["TC"] = comfort;                                       // Temperatura comfort
  doc["TIME"] = timer;                                       // Tempo attivita' caldaia
  if (stato == 0) doc["SC"] = "Spenta";                      // Stato caldaia
  if (stato == 1 && pausa == true)  doc["SC"] = "Pausa";
  if (stato == 1 && pausa == false) doc["SC"] = "Accesa";

  JsonArray aux_io = doc.createNestedArray("IO");
  aux_io.add(digitalRead(OUT_1));                           // Stato porta 1
  aux_io.add(digitalRead(OUT_2));                           // Stato porta 2
  aux_io.add(digitalRead(OUT_3));                           // Stato porta 3
  aux_io.add(digitalRead(OUT_4));                           // Stato porta 4
  aux_io.add(digitalRead(OUT_5));                           // Stato porta 5
  aux_io.add(digitalRead(OUT_6));                           // Stato porta 6

  // Genera il record JSON e lo salva su variabile output
  char output[BUFLEN];
  serializeJson(doc, output);
  Serial1.println(output);
  delay(50);
}`

result:
{ "ident": "termo", "UM": 55.3, "TA": 19.6, "TC": 21, "TIME": "00:00", "SC": "Spenta", "IO": [ 0, 0, 0, 0, 0 ] }

**Comment by bblanchon** [comment]
Hi @amedeodivito,

Please read [Why is the output incomplete?](https://arduinojson.org/v6/issues/incomplete-output/)

Best regards,
Benoit

**Comment by amedeodivito** [comment]
thanks, i solved
sorry for disturbing

**Comment by bblanchon** [comment]
You're welcome, @amedeodivito!
Thank you for using ArduinoJson.
Don't forget to [cast a star](https://github.com/bblanchon/ArduinoJson/stargazers) to support the project :wink:
