### ISSUE TITLE
invalid conversion from 'const char*' to 'char*' [-fpermissive] another solusion option

### ISSUE THREAD

**Issue by MakGyv3r** [bblanchon/ArduinoJson#1524]
Hi Benoit,

First of all, thank you for your library it is very helpful. 
Second, I wanted to suggest a different solution to this problem.
I am using a changing variable and it can't be const so this is what I used-
char* sensor =(char*) root["sensor"].as<char*>();

best regards,

**Comment by bblanchon** [comment]
Hi @MakGyv3r,

This looks like a programming error.
Can you explain?

Best regards,
Benoit
