### ISSUE TITLE
using JsonArray as an external variable

### ISSUE THREAD

**Issue by j45p41** [bblanchon/ArduinoJson#1526]
First of all, thanks for the great work. I find this library very useful.

Due to historical reasons I am using a mixture of c and c++. For this reason I need to export the JsonArray created from document object as an external variable.

 so in my main.c I have:
```
  DynamicJsonDocument doc(1024);

	// Converting the JsonDocument to the JsonArray.
	JsonArray arr = doc.to<JsonArray>();
```

in main.h

```

extern JsonArray arr;
extern DynamicJsonDocument(1024);
```

This is unfortunately not compiling. I could transfer the contents of the Jsonarray to another array but I cant seem to do this using serializeJson(doc, newArray) but I am pretty sure this is not supported and I would prefer not to have to do this. Help is very much appreciated on a possibly trivial matter,

**Comment by bblanchon** [comment]
Hi @j45p41,

I'm sorry, I don't know what you expect from me.
Do you have a specific question?

Best regards,
Benoit
