### ISSUE TITLE
DynamicJsonDocument - variable in class

### ISSUE THREAD

**Issue by yaroshd81** [bblanchon/ArduinoJson#1535]
Good day. 
In my class i can't do this:
`class xxx
{
  public:
  ...
  private:
    DynamicJsonDocument message(1024);`
Have a metods initialization DynamicJsonDocument in class?

**Comment by bblanchon** [comment]
Hi @yaroshd81,

You need to use [member initiallizer list](https://en.cppreference.com/w/cpp/language/constructor), like so:

```c++
class xxx {
  public:
    xxx() : message(1024) {}
  private:
    DynamicJsonDocument message;
};
```

Best Regards,
[Benoit](https://donate.benoitblanchon.fr)
