### ISSUE TITLE
InvalidInput

### ISSUE THREAD

**Issue by kunmonster** [bblanchon/ArduinoJson#1565]
Hello! 
I'am sorry to ask the question , i use the newest lib ArduinoJson , when i decode the json string "{"ssid":"test","password":"123456"}" , it always show me a message as "InvalidInput" .
then i use the assistant to help me get the code to ESP8266 but it show the message too.
the code like this:

`String input = incomingClient.readString();
//the input is {"ssid":"test","password":"123456"}" , i have used the print to check 
StaticJsonDocument<96> doc;
  DeserializationError error = deserializeJson(doc, input);

  if (error) {
    Serial.print(F("deserializeJson() failed: "));
    Serial.println(error.f_str());
    return;
  }

  const char* ssid = doc["ssid"];          // "k123456"
  const char* password = doc["password"];  // "123456kun"`

**Comment by bblanchon** [comment]
Hi @kunmonster,

Please see:

* [`DeserializationError`](https://arduinojson.org/v6/api/misc/deserializationerror/)

Best regards,
Benoit

**Comment by kunmonster** [comment]
Hi,
I hava look up the doc again and read the all situation carefully,
exclude the simply invalid and it doesn't contain a comment.

Firstly i think it's possible that the input conatin BOM but after i erase the space in the input , and use the print to check the first character  and it's "{",but it also catch the InvalidInput

![QQ截图20210523223520(1).jpg](https://user-images.githubusercontent.com/71956115/119264861-5c13c000-bc17-11eb-9838-87193fc8aee0.jpg)

![QQ截图20210523223527(1).jpg](https://user-images.githubusercontent.com/71956115/119264895-6b930900-bc17-11eb-867a-7818832daf36.jpg)

So,it is very puzzling , wish your reply!

**Comment by bblanchon** [comment]
Replacing spaces with an empty string will not remove the BOM because it's not made of spaces (`0x20`) but non-printable characters (`0xFF` and `0xFE`).
Instead, you should skip the two first bytes, like so:

```c++
client.read();
client.read();
deserializeJson(doc, client);
```

I recommend that you print these two bytes, so we can make sure this is really a BOM issue.

**Comment by kunmonster** [comment]
I have already find the problem.
The reason why the Invalid is that the WiFiCilent.readString() contains the headers！ It's so puzzling! Thank for your help😊

**Comment by bblanchon** [comment]
Indeed, I eliminated this possibility after seeing this picture:

![input](https://user-images.githubusercontent.com/71956115/119264895-6b930900-bc17-11eb-867a-7818832daf36.jpg)

...which you also confirmed by saying 

> and use the print to check the first character and it's "{"

Next time, please, don't hide critical information.
