### ISSUE TITLE
 error: 'const class FirebaseJson' has no member named 'memoryUsage'

### ISSUE THREAD

**Issue by RubensOliveira97** [bblanchon/ArduinoJson#1568]
Hello guys,

I try to download an code in my ESP32, but i have that problem on platformIO:
![image](https://user-images.githubusercontent.com/68352882/119244021-9cedd500-bb42-11eb-8a10-4ea91e03dd51.png)
![image](https://user-images.githubusercontent.com/68352882/119244061-00780280-bb43-11eb-96e3-16113a0b9f85.png)

If need more evidences of problem, ask me, because i'm new in this lib, so i don't know what is necessary for the best analysis.

Thank so much !

**Comment by bblanchon** [comment]
Hi @RubensOliveira97,

What on line 49 of main.cpp?
It seems that you're creating a `DynamicJsonDocument` from a `FirebaseJson` instance; I don't think that's possible.

Best regards,
Benoit

**Comment by RubensOliveira97** [comment]
> Hi @RubensOliveira97,
> 
> What on line 49 of main.cpp?
> It seems that you're creating a `DynamicJsonDocument` from a `FirebaseJson` instance; I don't think that's possible.
> 
> Best regards,
> Benoit

Hello @bblanchon ,

At first, see it:
![image](https://user-images.githubusercontent.com/68352882/119263652-58038600-bbb6-11eb-8d89-4721fb5a1fd7.png)
The SerialPrint:
![image](https://user-images.githubusercontent.com/68352882/119263681-78cbdb80-bbb6-11eb-8df3-c0db411cc9a3.png)

So, the content on line 49 is:
![image](https://user-images.githubusercontent.com/68352882/119263840-132c1f00-bbb7-11eb-822c-c9559cf06f11.png)

**Comment by RubensOliveira97** [comment]
@bblanchon I found the solution hahah:
![image](https://user-images.githubusercontent.com/68352882/119265011-95b6dd80-bbbb-11eb-8b6e-b871fa102e4f.png)
The SerialPrint:
![image](https://user-images.githubusercontent.com/68352882/119265026-a1a29f80-bbbb-11eb-9a89-dee876a6ca81.png)

So, an doubt, what's the best way to split that string in 2 JSON ?

**Comment by bblanchon** [comment]
I'm glad you found the solution!
However, I'm not sure how I can help with your second question... can you clarify?

**Comment by RubensOliveira97** [comment]
> I'm glad you found the solution!
> However, I'm not sure how I can help with your second question... can you clarify?

So, I have a stringfy json  "{\"-MaBsVgSflB5fhJyEQ9S\":{\"name\":\"GRILL\",\"onOff\":false,\"pin\":\"3\",\"power\":\"600\"},\"-MaLPJj23JV6z4NRFdRx\":{\"name\":\"Geladeira\",\"onOff\":false,\"pin\":\"3\",\"power\":\"300\"}}". What is the more simple form with split  it in two jsons, like this :{"
MaBsVgSflB5fhJyEQ9S":{"name":"GRILL"
"onOff":false
"pin":"3"
"power":"600"}
"
MaLPJj23JV6z4NRFdRx":{"name":"Geladeira"
"onOff":false
"pin":"3"
"power":"300"}}.

Say the ESP don't know what's the keys(MaBsVgSflB5fhJyEQ9S" for example ) in case.if I can separate or json from the firebase, according to the keys, then it is like this to use the split () to change each attribute. I don't know is to separate the JSON into a JSON sub.

**Comment by bblanchon** [comment]
I'm sorry, @RubensOliveira97, but I still don't understand what you mean.
I recommend that you start by reading the documentation and maybe come back here if you have any problems.
Start here: [Deserialization tutorial](https://arduinojson.org/v6/doc/deserialization/)
