### ISSUE TITLE
client:60:1: error: 'doc' does not name a type  doc["type"] = "TEM";

### ISSUE THREAD

**Issue by StrSebastian** [bblanchon/ArduinoJson#1570]
i'm copying from the documentation : and it dosnt work
any ideas?

StaticJsonDocument<200> doc;

doc["type"] = "TEM";
doc["bootNr"] = 17500;
doc["gewicht"] = 2000;

**Comment by bblanchon** [comment]
Hi @Jesus8000,

Can you copy/paste the complete compiler output?

Best regards,
Benoit

**Comment by StrSebastian** [comment]
sure :)

StaticJsonDocument<200> doc; //preallocate the jsonBuffer für jeden eintrag eine ["stockNr"] = 1;

doc["type"] = "TEM";
doc["bootNr"] = 17500;
doc["gewicht"] = 2000;

String serializeJsonOutputString = "JSON = ";
serializeJson(doc, serializeJsonOutputString);
------------------------------------------------------------------

client:60:1: error: 'doc' does not name a type
 doc["type"] = "TEM";
 ^
client:61:1: error: 'doc' does not name a type
 doc["bootNr"] = 17500;
 ^
client:62:1: error: 'doc' does not name a type
 doc["gewicht"] = 2000;
 ^
client:65:14: error: expected constructor, destructor, or type conversion before '(' token
 serializeJson(doc, serializeJsonOutputString);
              ^
Mehrere Bibliotheken wurden für "WiFi.h" gefunden
 Benutzt: C:\Users\<>\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\libraries\WiFi
 Nicht benutzt: C:\Program Files (x86)\Arduino\libraries\WiFi
exit status 1
'doc' does not name a type

**Comment by bblanchon** [comment]
Unlike many popular languages like Python or JavaScript, the C++ language doesn't allow statements at the global scope.
Instead, you must move all statements into a function.
The entry point for a regular C++ program is the `main()` function, but in an Arduino program, it's the `setup()` function.

Here is how you could rewrite your program:

```c++
void setup() {
  StaticJsonDocument<200> doc;
  doc["type"] = "TEM";
  doc["bootNr"] = 17500;
  doc["gewicht"] = 2000;

  String serializeJsonOutputString = "JSON = ";
  serializeJson(doc, serializeJsonOutputString);
}
```

See also:

* [JsonGeneratorExample.ino](https://arduinojson.org/v6/example/generator/)

**Comment by StrSebastian** [comment]
ah okey thx.

**Comment by bblanchon** [comment]
You're welcome, @Jesus8000!
Thank you for using ArduinoJson.
Don't forget to [cast a star](https://github.com/bblanchon/ArduinoJson/stargazers) to support the project :wink:
