### ISSUE TITLE
Add std::string_view support

### ISSUE THREAD

**Issue by paulocsanz** [bblanchon/ArduinoJson#1578]
We heavily use non-zero-terminated std::string_view's through our code, but we are not able to serialize them.

Support for std::string_view was mentioned in #704 as something of interest for this lib, but it seems the discussion ended with the stream solution. It's not clear to me how to use it, I will understand it better, but it seems official support for std::string_view still would be very useful.

Are there plans for direct support?

So I'm opening this issue as a request for `std::string_view` support in `JsonDocument`'s `operator[]`.

**Comment by bblanchon** [comment]
Hi @paulocsanz,

PR #1554 should already provide partial support for `std::string_view`, including `operator[]`.
I plan on adding the complete support for `std::string_view` soon, possibly in v6.18.1.

Best regards,
Benoit

**Comment by bblanchon** [comment]
This feature is available in [ArduinoJson 6.18.1](https://github.com/bblanchon/ArduinoJson/releases/tag/v6.18.1)
