### ISSUE TITLE
Different names but same values if uses the same variable to add name/value

### ISSUE THREAD

**Issue by Danielms812** [bblanchon/ArduinoJson#1584]
Hi all,

I'm using the ArduinoJson library with an Arduino Zero (Cortex-M0+ SAMD21), in order to create and modify JSON's to send it via a MQTT communication.

I've been created my own library with add (nested, array...) and delete functions to construct a JSON with a custom format. But I've discovered a strange behaviour when I is it used the same variable to add the value of different names.

I share the function used to add name/value in a nested JSON object called "value" and the code and its output with the behaviour described and the code with a normal output. The add function prints the generate JSON every time is called.

```
bool add(const char* prop, const char* value) {
  char msg[30];
  sprintf(msg, "\"%s\":\"%s\",", prop, value);

  if (strlen(msg) + strlen(message) > BUFFER_SIZE_MSG) {
    echo::warn(F("Message is full, this prop is not added"), prop);
    return false;
  }

  docSendMsg["value"][prop] = value;
  serializeJson(docSendMsg, RH_UART_DEBUG);
  RH_UART_DEBUG.println();
  serializeJson(docSendMsg, message, 512);
  return true;
}
```
**Strange behaviour**
```
//main.cpp
//cfg::get.useVbat, cfg::get.useVsys and cfg::get.useVin are true

char temp[10];

if (cfg::get.useVbat) {
  sprintf(temp, "%u", vbat);
  msg::add("vb", temp);
}

if (cfg::get.useVsys) {
  sprintf(temp, "%u", vsys);
  msg::add("vs", temp);
}

if (cfg::get.useVin) {
  sprintf(temp, "%u", vin);
  msg::add("vi", temp);
}

```
Output

```
{"value":{"vb":"4100"}}
{"value":{"vb":"3900","vs":"3900"}}
{"value":{"vb":"3412","vs":"3412","vi":"3412"}}
```
**Normal behaviour**
```
//main.cpp
//cfg::get.useVbat, cfg::get.useVsys and cfg::get.useVin are true

char temp[10];
char temp2[10];
char temp3[10];

if (cfg::get.useVbat) {
  sprintf(temp, "%u", vbat);
  msg::add("vb", temp);
}

if (cfg::get.useVsys) {
  sprintf(temp2, "%u", vsys);
  msg::add("vs", temp2);
}

if (cfg::get.useVin) {
  sprintf(temp3, "%u", vin);
  msg::add("vi", temp3);
}
```
Output

```
{"value":{"vb":"4097"}}
{"value":{"vb":"4097","vs":"4109"}}
{"value":{"vb":"4097","vs":"4109","vi":"3628"}}
```
Does anyone know why this happens? Maybe ArduinoJson library save the values of the names as a memory address so when the JSON is serialized, the address of the variable is the same and therefore the same value?

Thanks.

**Comment by bblanchon** [comment]
Hi @Danielms812,

As explained in the [Serialization tutorial](https://arduinojson.org/v6/doc/serialization/) (and in many other places), ArduinoJson stores strings differently depending on their type: it stores `const char*` by pointer and all other types by copy.

In your case, the following line stores three pointers:

```c++
docSendMsg["value"][prop] = value;
```

`"value"`, `prop`, and `value` are all `const char*`, so ArduinoJson stores them by address.

If you need to make a copy, you must pass another type, such as `char*`.

Best regards,
Benoit
