### ISSUE TITLE
Error loading 30+ variables after deserialziation

### ISSUE THREAD

**Issue by tatuiot** [bblanchon/ArduinoJson#1586]
Hi team. I have this issue for over 3 days and I cannot make it work. 
After deserialize my stored file

```
uint8_t loadJson(const JsonDocument &doc)
{
    d.g_dyn_HoffModoCalef = doc["g_dyn_HoffModoCalef"];
    d.g_dyn_ModoMicroAsp = doc["g_dyn_ModoMicroAsp"];
    d.g_dyn_HonModoMicroAsp = doc["g_dyn_HonModoMicroAsp"];
    d.g_dyn_HoffModoMicroAsp = doc["g_dyn_HoffModoMicroAsp"];
    d.g_dyn_TactModoMicroAsp = doc["g_dyn_TactModoMicroAsp"];
    d.g_dyn_TRepModoMicroAsp = doc["g_dyn_TRepModoMicroAsp"];
    d.g_dyn_ModoFog = doc["g_dyn_ModoFog"];
    d.g_dyn_HonModoFog = doc["g_dyn_HonModoFog"];
    d.g_dyn_HoffModoFog = doc["g_dyn_HoffModoFog"];
    d.g_dyn_ModoExtSup = doc["g_dyn_ModoExtSup"];
    d.g_dyn_HonModoExtSup = doc["g_dyn_HonModoExtSup"];
    d.g_dyn_HoffModoExtSup = doc["g_dyn_HoffModoExtSup"];
    d.g_dyn_ModoPanExt = doc["g_dyn_ModoPanExt"];
    d.g_dyn_HonModoPanExt = doc["g_dyn_HonModoPanExt"];
    d.g_dyn_HoffModoPanExt = doc["g_dyn_HoffModoPanExt"];
    d.g_dyn_ModoRefrig = doc["g_dyn_ModoRefrig"];
    d.g_dyn_HonModoRefrig = doc["g_dyn_HonModoRefrig"];
    d.g_dyn_HoffModoRefrig = doc["g_dyn_HoffModoRefrig"];
    d.g_dyn_ModoVentAsist = doc["g_dyn_ModoVentAsist"];
    d.g_dyn_ModoVentMain = doc["g_dyn_ModoVentMain"];
    d.g_dyn_HonModoVentMain = doc["g_dyn_HonModoVentMain"];
    d.g_dyn_HoffModoVentMain = doc["g_dyn_HoffModoVentMain"];
    d.g_dyn_ModoSaran = doc["g_dyn_ModoSaran"];
    d.g_dyn_HonModoSaran = doc["g_dyn_HonModoSaran"];
    d.g_dyn_HoffModoSaran = doc["g_dyn_HoffModoSaran"];
    d.g_dyn_tCal_min = doc["g_dyn_tCal_min"];
    d.g_dyn_tCal_max = doc["g_dyn_tCal_max"];
    d.g_dyn_tMinCal = doc["g_dyn_tMinCal"];
    d.g_dyn_tVentMain_min = doc["g_dyn_tVentMain_min"];
    d.g_dyn_tVentMain_max = doc["g_dyn_tVentMain_max"];
    d.g_dyn_tRefrig_min = doc["g_dyn_tRefrig_min"];
    d.g_dyn_tRefrig_max = doc["g_dyn_tRefrig_max"];
    d.g_dyn_tMinRefrig = doc["g_dyn_tMinRefrig"];
    d.g_dyn_hFog_min = doc["g_dyn_hFog_min"];
    d.g_dyn_hFog_max = doc["g_dyn_hFog_max"];
    d.g_dyn_tPanExt_min = doc["g_dyn_tPanExt_min"];
    d.g_dyn_tPanExt_max = doc["g_dyn_tPanExt_max"];
    d.g_dyn_tExtSup_min = doc["g_dyn_tExtSup_min"];
    d.g_dyn_tExtSup_max = doc["g_dyn_tExtSup_max"];
    
    DEBUG_PRINTLN(F("VARS UPDATED"));

    return 0;
}
```
that shows an error

Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
... 
EXCVADDR: 0x00000010  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xffffffff  

If I cut half way the variable load... works fine... 
I wonder if there is any other option to do it by chunk. 
I tested with UNION, without STRUCT... but no luck at all . 
Also Static and Dynamic Json doc... no success. 

Any hint please? thanks a lot in advance

**Comment by bblanchon** [comment]
Hi @tatuiot,

Please try the [ArduinoJson Troubleshooter](https://arduinojson.org/v6/troubleshooter/); I just added a page that should help you fix your issue.

Best regards,
Benoit

**Comment by tatuiot** [comment]
Thanks Benoit. I made all local variables. but did not work either. 
I will keep trying to debug. Very kind of you helpful tips the troubleshooter section.

**Comment by bblanchon** [comment]
Did you try the [ArduinoJson Troubleshooter](https://arduinojson.org/v6/troubleshooter/)?
If so, please include the report(s) in your messages, so I know what you already tried.

Also, please add [traces](https://github.com/bblanchon/ArduinoTrace) to your program so we know exactly which line causes the crash.

**Comment by tatuiot** [comment]
Hi team. I found the issue... has nothing to do with ArduinoJson. 
The error was the following. 
display.println(F(d.g_dyn_tCal_max)); 
Many of the variables were placed on the flash memory... which is not right. 
It works now. Sorry for bothering you, but I was looking for everywhere for so long...  
Hope helps someone...  thanks Beonit. thanks team

**Comment by bblanchon** [comment]
No worries.
Thank you for the quick update, @tatuiot, and thank you for using ArduinoJson!
