### ISSUE TITLE
Lists of key/values or dictionaries, how to?

### ISSUE THREAD

**Issue by deponovo** [bblanchon/ArduinoJson#1588]
Maybe I am missing something, but I could not yet figure out how I could parse/use the following structure:
```
{
    "wifi": {
        [
            "ssid": "ssid1",
            "password": "password for ssid1"
        ],
        [
            "ssid": "ssid2",
            "password": "password for ssid2"
        ] 
    }
}
```

Also tried:
```
{
    "wifi": {
        [
            {
                "ssid": "ssid1",
                "password": "password for ssid1"
            }
        ],
        [
            {
                "ssid": "ssid2",
                "password": "password for ssid2"
            }
        ] 
    }
}
```

What I tried:
```
DynamicJsonDocument ConfigJson(1024);
deserializeJson(ConfigJson, <json_contents>);
auto ssid1 = ConfigJson["wifi"][0]["ssid"].as<const char*>();
```

**Comment by bblanchon** [comment]
Hi @deponovo,

Neither of these examples is a valid JSON document.
Please see an introductory course on JSON.

For example, I created the following material:

* [Serialization and JSON on Arduino](https://www.youtube.com/watch?v=hAB4TdX8dwM) (YouTube video)
* [Mastering ArduinoJson](https://arduinojson.org/book/), chapter 1

Then, of course, there are many other resources on the internet.

Best regards,
Benoit

**Comment by deponovo** [comment]
You are right. I think I was working too late in the night -.- Really nice work with this lib btw!

This dict should do it:
```
{
    "wifi":  [
        {
            "ssid": "ssid1",
            "password": "password for ssid1"
        },
        {
            "ssid": "ssid2",
            "password": "password for ssid2"
        }
    ]
}
```

Just to complement this question just in case somebody bumps into it for some meaningful reason, the idea behind is to be able to loop like:

```
for (int i = 0; i < ConfigJson["wifi"].size(); i++)
{
    auto ssid = ConfigJson["wifi"][i]["id"].as<const char*>();
    auto password = ConfigJson["wifi"][i]["password"].as<const char*>();
    // now do something with this information
}
```

**Comment by bblanchon** [comment]
Please try the [ArduinoJson Assistant](https://arduinojson.org/v6/assistant/); it will write the code for you.

You can find all the information you need in the [Deserialization Tutorial](https://arduinojson.org/v6/doc/deserialization/).
