### ISSUE TITLE
jsonp callback function

### ISSUE THREAD

**Issue by albandes** [bblanchon/ArduinoJson#159]
Hi.

It is possible to add the callback so they can be made croos-domain requests?

Example:

CallBackString([{"device":"Temperatura","status":"OK","value":0.34}])

Tks

**Comment by bblanchon** [comment]
Hi,
Yes it's possible with a bit of imagination :wink: 

```c++
StaticJsonBuffer<200> jsonBuffer;

JsonObject& root = jsonBuffer.createJsonObject();
root["device"] = "Temperatura";
root["status"] = "OK";
root["value"] = 0.34;

Serial.print("CallBackString([");
root.printTo(Serial);
Serial.println("])");
```

Regards.

**Comment by albandes** [comment]
Hi.

I have a webserver in Arduino and return jsonp. I have a lot of problem (memory fragment) because I use string object. Now i use your bib and char. But concat char variable is a problem for me.

Tks

**Comment by bblanchon** [comment]
In the example above, there is neither memory fragmentation (because there is no dynamic allocation), nor `String`, nor `strcat()`.

What are you talking about?

**Comment by albandes** [comment]
Hello

Now I get it.

Thank You

Regards

2015-11-13 8:33 GMT-02:00 Benoît Blanchon <notifications@github.com>:

> In the example above, there is neither memory fragmentation (because there
> is no dynamic allocation), nor String, nor strcat().
>
> What are you talking about?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bblanchon/ArduinoJson/issues/159#issuecomment-156391858>
> .
>



-- 


Rogério AlbandesCel.: [53] 8401-4872Sp: [11] 4063-9932Poa: [51] 4063-9933
Pel: [53] 3025 6043
Site: www.helpdezk.o <http://www.helpdezk.com.br>rg
