### ISSUE TITLE
`build-single-header.sh` fails

### ISSUE THREAD

**Issue by jjsuwa-sys3175** [bblanchon/ArduinoJson#1592]
gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1) :
```
foo@debootstrap:/tmp/ArduinoJson$ extras/scripts/build-single-header.sh 
src/ArduinoJson.h -> ArduinoJson.hpp
   (*snip*)
ArduinoJson/MsgPack/MsgPackSerializer.hpp -> ArduinoJson/Variant/VariantData.hpp
ArduinoJson.hpp -> ArduinoJson/compatibility.hpp
In file included from <stdin>:1:
../ArduinoJson-5ccd62a.h:697:12: fatal error: ArduinoJson/Strings/StdStringAdapter.hpp: No such file or directory
 #  include <ArduinoJson/Strings/StdStringAdapter.hpp>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by bblanchon** [comment]
Hi @jjsuwa-sys3175,

Thank you very much for reporting this bug.
It's about time I add this to the CI anyway.

Best regards,
Benoit

**Comment by bblanchon** [comment]
You can now download the single header distribution from the build artifacts.

1. [Open CI builds history](https://github.com/bblanchon/ArduinoJson/actions/workflows/ci.yml)
2. Click on the relevant run (for example, the latest in branch `6.x`)
3. Scroll at the bottom to download the "Single headers" artifact.

**Comment by bblanchon** [comment]
![2021-06-21_18-23-43](https://user-images.githubusercontent.com/5462433/122796569-d68b3a80-d2be-11eb-8e6c-77e3f0cda264.png)
