### ISSUE TITLE
ERROR!

### ISSUE THREAD

**Issue by zghnx** [bblanchon/ArduinoJson#1602]
0x40204203 in bool ArduinoJson6173_91::JsonDeserializer<ArduinoJson6173_91::Reader<char*, void>, ArduinoJson6173_91::StringMover>::parseObject<ArduinoJson6173_91::AllowAllFilter>(ArduinoJson6173_91::CollectionData&,
ArduinoJson6173_91::AllowAllFilter, ArduinoJson6173_91::NestingLimit) at .pio\libdeps\nodemcuv2\ArduinoJson\src/ArduinoJson/Json/JsonDeserializer.hpp:258
0x40102651 in rcUpdateTxDone at ??:?
0x40204768 in ArduinoJson6173_91::DeserializationError::operator void (ArduinoJson6173_91::DeserializationError::*)() const() const at .pio\libdeps\nodemcuv2\ArduinoJson\src/ArduinoJson/Deserialization/DeserializationError.hpp:62

**Comment by zghnx** [comment]
{
JsonObject obj = doc.as<JsonObject>();
setconfig(obj)
}

void setconfig(JsonObject root){
}

**Comment by bblanchon** [comment]
Hi @zghnx,

Did you try the [ArduinoJson Troubleshooter](https://arduinojson.org/v6/troubleshooter/)?
What is the error message?

Best regards,
Benoit
