### ISSUE TITLE
arduinojson saves in ESP8266 SPIFFS save invalid json format error 

### ISSUE THREAD

**Issue by smartswitchsio** [bblanchon/ArduinoJson#1605]
i am getting below error randomly while saving json to esp8266  SPIFFS, this is error ��  

{"id":"cdata","cd":["R1","C2","S.Bujamma","Buffalo","9573741442","10d","12","10","12","02/07/2021, 10:52 pm"]},
{"id":"cdata","cd":["R1","C2","S.Bujamma","Buffalo","9573741442","10d","12","10","12","02/07/2021, 10:52 pm"]},
{"id":"cdata","cd":["R1","C2","S.Bujamma","Buffalo","9573741442","10","45","14","4","02/07/2021, 10:57 pm"��
{"id":"cdata","cd":["R1","C2","S.Bujamma","Buffalo","9573741442","10d","12","10","12","02/07/2021, 10:52 pm"]},

**Comment by bblanchon** [comment]
Hi @smartswitchsio,

Please have a look at [Why does the output contain garbage?](https://arduinojson.org/v6/issues/garbage-out/).

It's also possible that your Flash memory is corrupted.
Please try to write and read at the same location without the help of ArduinoJson.

If you need more assistance, please share the relevant lines of your program (50 lines max).

Best regards,
Benoit
