### ISSUE TITLE
Arduino IDE v1.8.3 compiler errors due way of #include references

### ISSUE THREAD

**Issue by PaulskPt** [bblanchon/ArduinoJson#1607]
This is not a question. This is a report of what I have been confronted with. 
First: thank you for creating and publishing your ArduinJson repo.

I am not an experienced C/C++ programmer,
but I recently built some experience with C++ projects for the Raspberry Pi Pico.

I tried to compile and flash an example that uses the ThingESP library, which uses ArduinoJson.
First using Arduino IDE version 2.0.0 beta.  Total disaster. The IDE began to report the usual 'String ...' definitions as 'undefined'.
Then using the Arduino IDE version 1.8.13 (in MS Windows 10 latest): 
Many errors of 'No such file or directory' . Example:
../arduinojson/variant/VariantData.hpp:7.10:  '#include <ArduinoJson/Misc/SerializedValue.hpp>.
When I changed this into '#include ../Misc/SerializedValue.hpp" the compiler accepted.

In ArduinoJson there are various #include's using a path while the file referenced was in the same subfolder.
Example:  in the file: '/ArduinoJson/Variant/VariantSlot.hpp' is the include: '#include <ArduinoJson/Variant/VariantContent.hpp>'.
I changed it into: '"include VariantContent.hpp".

Recently I had the same experiences when compiling C++ projects for the Raspberry Pi Pico (pico-sdk). Using relative 
references like "../<filename.h>" or "../../../../<filename.h>" worked instead of  "<thisFolder>/<filename.h>".

Regards,
Paulsk

**Comment by bblanchon** [comment]
Hi Paulsk,

How did you install the library?

Best regards,
Benoit

**Comment by bblanchon** [comment]
PS: ArduinoJson uses an absolute path to workaround #1072

**Comment by PaulskPt** [comment]
Hi Benoit, mci.
I downloaded the zip file of your repo. Unpacked it. Initially I copied it to the 'user' libraries folder in:
"c:\Users\<username>\Documents\Arduino\libraries"
but later I decided to copy it to:
C:\Users\<username>\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.1\libraries\

Excuse me but I think it doesn't matter so much where it is installed. The errors are relative related within the ThingESP library.
The errors are not related to files outside of ThingESP.

Regarding your reference to the workaround.: in my case the errors were not related to a long filename path.

![ThingESP_lib_loc](https://user-images.githubusercontent.com/9107950/124485140-2defd700-dda4-11eb-8566-ea970667afb5.png)

**Comment by PaulskPt** [comment]
Hi Benoit, mci.
I downloaded the zip file of your repo. Unpacked it. Initially I copied it to the 'user' libraries folder in:
"c:\Users\<username>\Documents\Arduino\libraries"
but later I decided to copy it to:
C:\Users\<username>\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.1\libraries\

Excuse me but I think it doesn't matter so much where it is installed. The errors are relative related within the ThingESP library.
The errors are not related to files outside of ThingESP.

Regarding your reference to the workaround.: in my case the errorrs were not related to a long filename path.

![ThingESP_lib_loc](https://user-images.githubusercontent.com/9107950/124485140-2defd700-dda4-11eb-8566-ea970667afb5.png)

**Comment by PaulskPt** [comment]
I Checked: I have ThingESP also in the Tools > Manage Libraries.

![image](https://user-images.githubusercontent.com/9107950/124493480-968f8180-ddad-11eb-8759-f44d53d7fa40.png)

**Comment by bblanchon** [comment]
@PaulskPt, how did you solve your issue?

**Comment by PaulskPt** [comment]
Hi Benoît, by error I clicked the 'close' button. I edited every file until there were no more 'file not found' errors. I sometimes also edited other files that were in a same subdirectory. I edited for several hours. Maybe I edited 50 files (or more). If you like I can make a .zip and upload it to you (if that is allowed by GitHub, I don't know). Now I have some other type of errors in the sketch to deal with.

**Comment by Foinard** [comment]
Same issue

**Comment by bblanchon** [comment]
@PaulskPt, if you don't want to install ArduinoJson via the library manager, you can download the single file distribution.
See [installation instructions](https://arduinojson.org/v6/doc/installation/) for details.

@Foinard, please elaborate:

* Are you using Arduino IDE too?
* Did you download the zip the same way?
* Did it work with older versions of the library?
* What did you try to fix this issue?

**Comment by PaulskPt** [comment]
@bblanchon  Thank you. OK, I already wrote above that I installed the library via the standard way.

**Comment by bblanchon** [comment]
> I downloaded the zip file of your repo. Unpacked it. 

@PaulskPt, is this what you call the standard way?

**Comment by PaulskPt** [comment]
![image](https://user-images.githubusercontent.com/9107950/124791982-7c3bdc00-df44-11eb-8c52-5ca0eef3811f.png)

**Comment by bblanchon** [comment]
I understand that you installed the ThingESP via the Library Manager, but what about ArduinoJson?

**Comment by PaulskPt** [comment]
![image](https://user-images.githubusercontent.com/9107950/124949087-2c731880-e009-11eb-9382-1caa33745da7.png)

**Comment by Foinard** [comment]
Solved !
I tried to install it with the library manager and it worked !

**Comment by bblanchon** [comment]
@PaulskPt, I bet there is something wrong with your installation.
Can you try to uninstall and reinstall?
