### ISSUE TITLE
NULL return 0 but null value exist in json

### ISSUE THREAD

**Issue by SnouF** [bblanchon/ArduinoJson#162]
Hello

By example

  root["null"] = NULL
return
  {"null":0}

If it could return
  {"null":null}
would better right?

**Comment by bblanchon** [comment]
Hi Jonas,

UnfortunateIy, this is not possible as `NULL` is an alias for `0`.
Look at [the definition of `NULL`](http://fr.cppreference.com/w/cpp/types/NULL):

```c++
#define NULL 0
```

However ArduinoJson will behave as you expect if you give a null string pointer:

```c++
root["null"] = static_cast<const char*>(NULL);
```

**Comment by domonetic** [comment]
Can use NIL u other word

2015-11-20 6:14 GMT-03:00 Benoît Blanchon <notifications@github.com>:

> Hi Jonas,
>
> UnfortunateIy, this is not possible as NULL is an alias for 0.
> Look at the definition of NULL
> <http://fr.cppreference.com/w/cpp/types/NULL>:
>
> #define NULL 0
>
> However ArduinoJson will behave as you expect if you give a null string
> pointer:
>
> root["null"] = static_cast<const char*>(NULL);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bblanchon/ArduinoJson/issues/162#issuecomment-158332748>
> .
>



-- 
El que pregunta aprende, y el que contesta aprende a responder.

No a la obsolecencia programada:
http://www.rtve.es/noticias/20110104/productos-consumo-duran-cada-vez-menos/392498.shtml

Linux User #495070
http://domonetic.com/blog

**Comment by bblanchon** [comment]
@domonetic I've never heard of a `NIL`in C++...

**Comment by domonetic** [comment]
I misinterpreted the question



2015-11-20 10:19 GMT-03:00 Benoît Blanchon <notifications@github.com>:

> @domonetic <https://github.com/domonetic> I've never heard of a NILin
> C++...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bblanchon/ArduinoJson/issues/162#issuecomment-158401187>
> .
>



-- 
El que pregunta aprende, y el que contesta aprende a responder.

No a la obsolecencia programada:
http://www.rtve.es/noticias/20110104/productos-consumo-duran-cada-vez-menos/392498.shtml

Linux User #495070
http://domonetic.com/blog

**Comment by SnouF** [comment]
Tanks bblanchon

Sorry for this "impossible feature request" :)

**Comment by bblanchon** [comment]
That's OK Jonas :wink: 
Thank you for using ArduinoJson.
