### ISSUE TITLE
Impressive piece of coding

### ISSUE THREAD

**Issue by Andreotti100** [bblanchon/ArduinoJson#1634]
No issues here. Just want to say that this is an impressive piece of coding.
I noticed code I have never seen before, pushing the platform to it's limits.
Other languages could learn from this, complex on the inside, but how simple it is to use.
Very nice :-)

**Comment by bblanchon** [comment]
Thanks, @Andreotti100.
I wish I received more issues like this; the previous one is 7 years old (#26).
