### ISSUE TITLE
Can't add null value to object when using MSVC 2019

### ISSUE THREAD

**Issue by gwisp2** [bblanchon/ArduinoJson#1638]
Minimal example:
```
#include <iostream>
#include <ArduinoJson.hpp>

using namespace ArduinoJson;

int main()
{
	ArduinoJson::StaticJsonDocument<128> doc;
	doc["key"] = nullptr;
	std::cout << doc << std::endl;
	return 0;
}
```

Compilation fails on line `doc["key"] = nullptr;` when using MSVC 2019 compiler. 
Compiler output can be seen [here](https://github.com/gwisp2/ArduinoJsonNullptrTest/runs/3427475002).

**Comment by gwisp2** [comment]
This workaround works:
```
doc["key"] = (const char*)nullptr;
```

**Comment by bblanchon** [comment]
Hi @gwisp2,

ArduinoJson enables support for `nullptr` based on the value of `__cplusplus` ([see the relevant lines](https://github.com/bblanchon/ArduinoJson/blob/b810833145e3cdab738fb4a45d7d4010a0e13f6d/src/ArduinoJson/Configuration.hpp#L15-L21)).

By default, Visual Studio sets `__cplusplus` to `199711L`, even with recent versions.
You must pass the compilation flag `/Zc:__cplusplus` to get the correct value ([see the documentation](https://docs.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-160)).

CMake will pass this flag if you select the C++ standard; for example:

```cmake
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```

Best regards,
Benoit

**Comment by gwisp2** [comment]
Thanks!

However setting standard in CMakeLists.txt [is not enough](https://gitlab.kitware.com/cmake/cmake/-/issues/18837) by now. So it is needed to set this option manually.

```
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

if(MSVC)
    target_compile_options(ArduinoJsonNullptrTest PRIVATE "/Zc:__cplusplus")
endif()
```
.

**Comment by bblanchon** [comment]
Indeed, I forgot I had to set this flag manually too ([see relevant lines](https://github.com/bblanchon/ArduinoJson/blob/b810833145e3cdab738fb4a45d7d4010a0e13f6d/extras/CompileOptions.cmake#L90-L92)).
Sorry about that.
