### ISSUE TITLE
Iterate keys and print type

### ISSUE THREAD

**Issue by prosd** [bblanchon/ArduinoJson#1649]
Hello again, 

I would like to iterate over all keys in a document and print the key name (if any) and the key type (Object, Array or regular key).
How can this be accomplished?

Example Json (with expected output after the //) :

```
{                                              // Object
  
    "file":{                                   // "file" (Object)
      "version":1,                             // "version" (key)
      "checksum":123456465,                    // "checksum" (key)
    },
  
    "frames": [                                // "frames" (array)
      {                                        // unnamed (object)
        "frame-name": "MyFirstFrame",          // "frame-name" (key)
        "frame-class": "null",                 // "frame-class" (key)
        "items": [                             // "items" (array)
             {                                 // unnames (object)
             "id":1,                           // "id" (key)
             "class":"reader"                  // "class" (key)
             },

             {                                 // ....
             "id":2, 
             "class":"writer"
             }
         ],
  
        "frame-params": {
          "useDataStore": true,
          "timeout": 25,
          "keys": [100,101,102]}
      }
    ]

}
```

Thanks!

**Comment by bblanchon** [comment]
Hi @prosd,

You can iterate with [JsonArray::begin()/end()](https://arduinojson.org/v6/api/jsonarray/begin_end/) and [JsonObject::begin()/end()](https://arduinojson.org/v6/api/jsonobject/begin_end/), and you can test the type with [JsonVariant::is<T>()](https://arduinojson.org/v6/api/jsonvariant/is/).

I wrote a complete example in the "Recursive Analyzer" case study in the last chapter of [Mastering ArduinoJson](https://arduinojson.org/book/).

Best regards,
Benoit
