### ISSUE TITLE
Can´t change some values

### ISSUE THREAD

**Issue by Sinix10** [bblanchon/ArduinoJson#1651]
Hello,

I´m having an issue that I can not find it on google.
I´m running a Wemos D1 R2 (ESP8266).

I can modify values within the json file, but there is something weird happening. After the device boots, I can´t change value "A", even tough I can change other values. I can only change value "A" if I change only value "Y" first, after this I can change "A", at any time. But if I reboot the MCU, the cycle will happen again.
I´m using littleFS. If you need more info, please, feel free to ask.

These are the Value "A" and "Y" on the respective order:
MQTTstate = 0
mqtt_server = aaa

I can only change value "A" if I change "Y" first.

This is the code regarding the values above.
SwitchCase = 1 is to read.
SwitchCase = 2 is to write.

void MQTTFS() {
  delay(1000);
  File configFile = LittleFS.open("/config.json", "r");
  DeserializationError error = deserializeJson(doc, configFile);
  if (error) {
      Serial.println(F("Failed to read file, using default configuration"));
      }
  configFile.close();

  switch (MQTTFileSystem) {
  case 1:
  mqtt_server = doc["mqttServer"];
  MQTTstate = doc["MQTTstate"];
      break;

  case 2:
  doc["mqttServer"] = mqtt_server;
  doc["MQTTstate"] = MQTTstate;

  configFile = LittleFS.open("/config.json", "w");  
  if (serializeJson(doc, configFile) == 0) {
      Serial.println(F("Failed to write the file"));
    }else{}
    configFile.close();
  break;

  default:
    break;
  }
}

**Comment by bblanchon** [comment]
Hi @Sinix10,

I'm sorry, I don't understand your issue.
Please have a look and the example [JsonConfigFile.ino](https://arduinojson.org/v6/example/config/), it uses SD but can easily be adapted for LittleFS.

Best regards,
Benoit
