### ISSUE TITLE
Brackets in openweatherdata 

### ISSUE THREAD

**Issue by tonbor** [bblanchon/ArduinoJson#1660]
https://arduinojson.org/v6/example/filter/ will not work, the brackets makes that the temp etc. values can not been extracted from the (smaller) json doc . Indeed this is a common problem with the arduinojson getting openweather data. Please solve this.

**Comment by bblanchon** [comment]
Hi @tonbor,

I just tested the example on UNO and ESP32, and I can confirm it works on both.
Can you give more details about your problem?

Best regards,
Benoit

**Comment by tonbor** [comment]
Just add  // Print the result
  serializeJsonPretty(doc, Serial);
  String temp = doc["list"]["main"]["temp"];
  Serial.print("Temp = ");
  Serial.println(temp);
}

void loop() {
  // not used in this example
}
This is the result: {
  "list": [
    {
      "dt": 1581498000,
      "main": {
        "temp": 3.23
      }
    },
    {
      "dt": 1581508800,
      "main": {
        "temp": 6.09
      }
    }
  ]
}Temp = null



2021-10-05 9:16 GMT+02:00, Benoît Blanchon ***@***.***>:

**Comment by bblanchon** [comment]
The expression is incorrect; it should be:

```c++
doc["list"][0]["main"]["temp"];
```

**Comment by tonbor** [comment]
Thanks but where can I find the syntaxis for extracting this openweather
data, or for that matter any data from an arduinojson doc?

Op wo 6 okt. 2021 10:01 schreef Benoît Blanchon ***@***.***>:

**Comment by bblanchon** [comment]
You can read the [Deserialization Tutorial](https://arduinojson.org/v6/doc/deserialization/).
Also, the [ArduinoJson Assistant](https://arduinojson.org/v6/assistant/) generates the code for you.
What else do you need?

**Comment by tonbor** [comment]
This is what I get form the ArduinoJson Assistant
<https://arduinojson.org/v6/assistant/>:
JsonObject list_0_main = list_0["main"]; float list_0_main_temp =
list_0_main["temp"]; // 16.8 float list_0_main_feels_like = list_0_main[
"feels_like"]; // 16.49 float list_0_main_temp_min = list_0_main["temp_min"];
// 16.8 float list_0_main_temp_max = list_0_main["temp_max"]; // 17.02 int
list_0_main_pressure = list_0_main["pressure"]; // 1018 int
list_0_main_sea_level = list_0_main["sea_level"]; // 1018 int
list_0_main_grnd_level = list_0_main["grnd_level"]; // 1027 int
list_0_main_humidity = list_0_main["humidity"]; // 75 float
list_0_main_temp_kf = list_0_main["temp_kf"]; // -0.22

This is what I'am looking for, no syntax explanation anywhere,
String location = doc["city"]["name"];
String temperature = doc["list"][0]["main"]["temp"];
String pressure = doc["list"][0]["main"]["pressure"];
String humidity = doc["list"][0]["main"]["humidity"];
String sunset = doc["city"]["sunset"];
String sunrise = doc["city"]["sunrise"];
String weather = doc["list"][0]["weather"][0]["main"];
String description = doc["list"][0]["weather"][0]["description"];
String idString = doc["list"][0]["weather"][0]["id"];
String timeS = doc["list"]["dt_txt"];

so for us who needs our own code, it is trial and error
Thanks
Tonbor

Op do 7 okt. 2021 om 14:03 schreef Benoît Blanchon ***@***.***

**Comment by bblanchon** [comment]
I'm sorry to read that you're dissatisfied with the documentation and the Assistant, but honestly, I don't know what else I could do.
There is already a lot of documentation and examples about the syntax of ArduinoJson:

* [The homepage of arduinojson.org](https://arduinojson.org/)
* [The deserialization tutorial](https://arduinojson.org/v6/doc/deserialization/)
* [The ten official examples](https://arduinojson.org/v6/example/)
* [The book](https://arduinojson.org/book/)

Besides, the bracket syntax is similar to JavaScript, Python, and many other languages, so it should be familiar to most users.

Anyway, I'm always willing to improve the documentation, so **please write the page that you think is missing** and I'll include it on the website if it's good enough (if not, you can still publish this page on your own).

**Comment by tonbor** [comment]
Well, this discussion will show up when people google arduinojson and openweather data. Hope this will help enough for the needed syntaxis. Thanks Tonbor
