### ISSUE TITLE
Using version 6.18.5 - crashes after deserializing valid JSON

### ISSUE THREAD

**Issue by Smashcat** [bblanchon/ArduinoJson#1661]
Found a bug where if the input string to deserialize is changed AFTER deserializing, but before extracting values, program crashes. I think the docs should be updated to reflect the fact the library keeps a reference to the input string, and it must not change while library is in use. Thanks!

**Comment by bblanchon** [comment]
Hi,

Indeed the library keeps a reference to the input string *if* you use the zero-copy mode.
This is not a bug: the library cannot prevent you from corrupting the memory.
If you want to modify the input buffer, you shouldn't use the zero-copy mode (casting to `const char*` should do the trick).

This behavior is documented in many places, but of course not everywhere.
Can you point me to the page where you expect to see this information?

Best regards,
Benoit

**Comment by bblanchon** [comment]
PS: the [troubleshooter](https://arduinojson.org/v6/troubleshooter/) should know about this issue, can you tell me which answers you gave?
