### ISSUE TITLE
Deserialization of internal json objects

### ISSUE THREAD

**Issue by vinny74man** [bblanchon/ArduinoJson#1662]
Hi all how can I deserialize this string?

"{\"topic\": \"homeassistant/cmd/1\", \"payload\": \"{\"state\": \"ON\", \"color\": {\"r\": 255, \"g\": 255, \"b\": 255}}\"}"

Thanks

**Comment by bblanchon** [comment]
Hi @vinny74man,

Did you try the [ArduinoJson Assistant](https://arduinojson.org/v6/assistant/)?

Best regards,
Benoit

**Comment by vinny74man** [comment]
Yes but it did not help me, my problem is not the deserialization of the string, but to access the values of "R, G, B", inside the key payload, the only way I found is to create two jsonDocument , but I wanted to know if there was a way to avoid it.

Thanks

Sorry this is an online translation

**Comment by bblanchon** [comment]
Hi @vinny74man,

It should be as simple as `doc["payload"]["color"]["r"]`.

However, I wonder if your input is valid.
See, this is not a valid JSON document:

```json
{"topic": "homeassistant/cmd/1", "payload": "{"state": "ON", "color": {"r": 255, "g": 255, "b": 255}}"}
```

Please make sure that the input is valid.
If the problem persists, please ask the [ArduinoJson Troubleshooter](https://arduinojson.org/v6/troubleshooter/) and send me the report.

See also:

* [deserializeJson() succeeds but I cannot read any value](https://arduinojson.org/v6/issues/cannot-get-values/).

Best regards,
Benoit

**Comment by vinny74man** [comment]
The correct json is this, 
`{"topic": "homeassistant/cmd/1", "payload": "{\"state\": \"ON\", \"color\": {\"r\": 255, \"g\": 255, \"b\": 255}}"}`
in copying it the slashes have been deleted 
this is valid 

Sorry this is an online translation

**Comment by bblanchon** [comment]
Your JSON document suffers from the "JSON in JSON" syndrome, so as you found out, you must use two `JsonDocument`s and call `deserializeJson()` twice.
