### ISSUE TITLE
Serializing valid JSON object to File output

### ISSUE THREAD

**Issue by Findus76** [bblanchon/ArduinoJson#1664]
**Describe the bug**  
When running serializejson function, junk characters appear at the end of the file. 

**Troubleshooter report**  
Console logg file
"Write file "FunctionList_write.txt"
No of byte write 299
Read File: /FunctionList_write.txt
Filesize: 299
{"Type":"System Function","Function list":{"Relay ch3":{"Settings":{},"Relay":{"Value":false}},"Pump":{"Settings":{"Pump Time":{"Value":60},"Heating Time":{"Value":600},"Wather":{"Calibration(L)":20},"Clear Pump Time":{"Value":false},"Clear Heating Time":{"Value":false}}}},"System":{"Settings":{▒▒▒
{
  "Type": "System Function",
  "Function list": {
    "Relay ch3": {
      "Settings": {},
      "Relay": {
        "Value": false
      }
    },
    "Pump": {
      "Settings": {
        "Pump Time": {
          "Value": 60
        },
        "Heating Time": {
          "Value": 600
        },
        "Wather": {
          "Calibration(L)": 20
        },
        "Clear Pump Time": {
          "Value": false
        },
        "Clear Heating Time": {
          "Value": false
        }
      }
    }
  },
  "System": {
    "Settings": {}
  }
}
Write file "FunctionList_comp.txt"
No of byte write 1648

**Environment**  
Here is the environment that I used:
Microcontroller:  ESP8266
Espressif 8266 v3.2.0
ArduinoJson v6.18.4

**Reproduction**  

Code (part of it)

DynamicJsonDocument FunclistDoc(Listleght + 1200);

if(status)
{
	File file;
	#if defined USE_SPIFFS
		file = SPIFFS.open("/FunctionList_write.txt", "w");
	#else
		file = LittleFS.open("/FunctionList_write.txt", "w");
	#endif

  	if (file) 
	{
		int bytesWritten = serializeJson(FunclistDoc, file);
		Serial.print("Write file \"FunctionList_write.txt\"\r\n");
		Serial.printf("No of byte write %d\r\n", bytesWritten);
  		file.close();
		PrintFile("/FunctionList_write.txt");
  	}
	else
	{
		Serial.println("Can't create output file for writing");
		status = false;
	}

	serializeJsonPretty(FunclistDoc, Serial);
	Serial.print("\r\n");	
}	

**Compiler output**    
0 Error

**Program output**  
Write file "FunctionList_write.txt"
No of byte write 299
Read File: /FunctionList_write.txt
Filesize: 299
{"Type":"System Function","Function list":{"Relay ch3":{"Settings":{},"Relay":{"Value":false}},"Pump":{"Settings":{"Pump Time":{"Value":60},"Heating Time":{"Value":600},"Wather":{"Calibration(L)":20},"Clear Pump Time":{"Value":false},"Clear Heating Time":{"Value":false}}}},"System":{"Settings":{▒▒▒
{
  "Type": "System Function",
  "Function list": {
    "Relay ch3": {
      "Settings": {},
      "Relay": {
        "Value": false
      }
    },
    "Pump": {
      "Settings": {
        "Pump Time": {
          "Value": 60
        },
        "Heating Time": {
          "Value": 600
        },
        "Wather": {
          "Calibration(L)": 20
        },
        "Clear Pump Time": {
          "Value": false
        },
        "Clear Heating Time": {
          "Value": false
        }
      }
    }
  },
  "System": {
    "Settings": {}
  }
}
Write file "FunctionList_comp.txt"
No of byte write 1648
Expected output:

```
[insert expected output here]
```

Actual output:

```
[insert actual output here]
```

**Comment by bblanchon** [comment]
Hi @Findus76n

Please share [ArduinoJson Troubleshooter](https://arduinojson.org/v6/troubleshooter/)'s report.
Do you see the same problem with `serializeJson(doc, Serial)`?

Best regards,
Benoit

**Comment by Findus76** [comment]
Hi Benoit

Loggfile
"{"Type":"System Function","Function list":{"Relay ch3":{"Settings":{},"Relay":{"Value":false}},"Pump":{"Settings":{"Pump Time":{"Value":60},"Heating Time":{"Value":600},"Wather":{"Calibration(L)":20},"Clear Pump Time":{"Value":false},"Clear Heating Time":{"Value":false}}}},"System":{"Settings":{}}}
Write file "FunctionList_write.txt"
No of byte write 299
Read File: /FunctionList_write.txt
Filesize: 299
{"Type":"System Function","Function list":{"Relay ch3":{"Settings":{},"Relay":{"Value":false}},"Pump":{"Settings":{"Pump Time":{"Value":60},"Heating Time":{"Value":600},"Wather":{"Calibration(L)":20},"Clear Pump Time":{"Value":false},"Clear Heating Time":{"Value":false}}}},"System":{"Settings":{▒▒▒
{
  "Type": "System Function",
  "Function list": {
    "Relay ch3": {
      "Settings": {},
      "Relay": {
        "Value": false
      }
    },
    "Pump": {
      "Settings": {
        "Pump Time": {
          "Value": 60
        },
        "Heating Time": {
          "Value": 600
        },
        "Wather": {
          "Calibration(L)": 20
        },
        "Clear Pump Time": {
          "Value": false
        },
        "Clear Heating Time": {
          "Value": false
        }
      }
    }
  },
  "System": {
    "Settings": {}
  }
}"

Code
"if(status)
{
	File file;
	#if defined USE_SPIFFS
		file = SPIFFS.open("/FunctionList_write.txt", "w");
	#else
		file = LittleFS.open("/FunctionList_write.txt", "w");
	#endif


  	if (file) 
	{
		serializeJson(FunclistDoc, Serial);
		Serial.println("");
		int bytesWritten = serializeJson(FunclistDoc, file);
		Serial.print("Write file \"FunctionList_write.txt\"\r\n");
		Serial.printf("No of byte write %d\r\n", bytesWritten);
  		file.close();
		PrintFile("/FunctionList_write.txt");
  	}
	else
	{
		Serial.println("Can't create output file for writing");
		status = false;
	}

	serializeJsonPretty(FunclistDoc, Serial);
	Serial.print("\r\n");	
}	"

Brg
Findus

**Comment by bblanchon** [comment]
Hi Findus,

So I'm assuming your answer is "Yes, it also happens with Serial".
Can you now share [ArduinoJson Troubleshooter](https://arduinojson.org/v6/troubleshooter/)'s report?

Best regards,
Benoit

**Comment by Findus76** [comment]
Hi Benoit

No with serializeJson and serializeJsonPretty, everything looks good. 

At the end with write to file, it looks like this  ","System":{"Settings":{▒▒▒"
While it should look like this "","System":{"Settings":{}}}"

Brg
Findus

**Comment by bblanchon** [comment]
Hi Findus,

Do you mean that the problem only occurs with `File`?
There may be a problem with the filesystem; can you try to write a similar file without ArduinoJson?

Why don't you share the [ArduinoJson Troubleshooter](https://arduinojson.org/v6/troubleshooter/)'s report?

Best regards,
Benoit

**Comment by Findus76** [comment]
Hi Benoit

If I serialize to string and write string to file, it will be correct. 

Code
"char *tempstring;
tempstring = (char*)malloc(350);
serializeJson(FunclistDoc, Serial);
Serial.println("");
//int bytesWritten = serializeJson(FunclistDoc, file);
serializeJson(FunclistDoc, tempstring, 320);
Serial.println(tempstring);
file.print(tempstring);
//Serial.print("Write file \"FunctionList_write.txt\"\r\n");
//Serial.printf("No of byte write %d\r\n", bytesWritten);
  file.close();
free(tempstring);
PrintFile("/FunctionList_write.txt");"

Result 
"
{"Type":"System Function","Function list":{"Relay ch3":{"Settings":{},"Relay":{"Value":false}},"Pump":{"Settings":{"Pump Time":{"Value":60},"Heating Time":{"Value":600},"Wather":{"Calibration(L)":20},"Clear Pump Time":{"Value":false},"Clear Heating Time":{"Value":false}}}},"System":{"Settings":{}}}
{"Type":"System Function","Function list":{"Relay ch3":{"Settings":{},"Relay":{"Value":false}},"Pump":{"Settings":{"Pump Time":{"Value":60},"Heating Time":{"Value":600},"Wather":{"Calibration(L)":20},"Clear Pump Time":{"Value":false},"Clear Heating Time":{"Value":false}}}},"System":{"Settings":{}}}
Read File: /FunctionList_write.txt
Filesize: 299"

Result from Trobleshooter
"
<details><summary>ArduinoJson Troubleshooter's report</summary> <ol><li>The issue happens at run time</li><li>The issue concerns serialization</li><li>Output is incomplete</li><li><code>JsonDocument::overflowed()</code> returns <code>false</code></li><li>No string contains a NUL</li></ol></details>
"

**Comment by bblanchon** [comment]
Hi Findus,

> If I serialize to string and write string to file, it will be correct.

This may be an issue with the filesystem.
Does this problem happen with both LittleFS and SPIFFS?
Is your Core / Platform up to date?
Can you try on another equivalent board?

Please try inserting a `WriteBufferingStream` between `serializeJson()` and `File`, like so:

```c++
WriteBufferingStream bufferedFile(file, 64);
serializeJson(doc, bufferedFile);
bufferedFile.flush();
```

This will write the JSON file in chunks of 64 bytes and may solve your issue.
See more information [here](https://arduinojson.org/v6/how-to/improve-speed/#speed-up-serialization).

> Output is incomplete

I didn't understand that the input was incomplete.
In your original message, you said, "junk characters appear at the end of the file".
If that's still the case, then the correct answer is ["The generated JSON contains garbage"](https://arduinojson.org/v6/troubleshooter/#runtime/serialization/garbage).
Please try the suggestions and share the updated report so I can improve the Troubleshooter after we solve your issue.

Best regards,
Benoit

**Comment by Findus76** [comment]
Hi Benoit

Sorry I made the wrong choice.
I chose between these two options, as my problem fit both of them. The string is truncated but also garbage. 
I try with garbage.

Report from Troubleshooter
"<details><summary>ArduinoJson Troubleshooter's report</summary> <ol><li>The issue happens at run time</li><li>The issue concerns serialization</li><li>Output contains garbage</li><li>Program doesn’t call <code>deserializeJson()</code></li><li>Program calls <code>serializeJson(const JsonDocument&amp;, ...)</code></li><li>Program uses <code>DynamicJsonDocument</code></li><li>Program doesn’t use <code>String</code></li></ol></details>
"

Code
"
if (file) 
{
	//char *tempstring;
	//tempstring = (char*)malloc(350);
	//serializeJson(FunclistDoc, Serial);
	//Serial.println("");
	//int bytesWritten = serializeJson(FunclistDoc, file);
	WriteBufferingStream bufferedFile(file, 64);
	serializeJson(FunclistDoc, bufferedFile);
	bufferedFile.flush();
	//serializeJson(FunclistDoc, tempstring, 320);
	//Serial.println(tempstring);
	//file.print(tempstring);
	Serial.print("Write file \"FunctionList_write.txt\"\r\n");
	//Serial.printf("No of byte write %d\r\n", bytesWritten);
  	file.close();
	//free(tempstring);
	PrintFile("/FunctionList_write.txt");
}
"

Logg output
"
Write file "FunctionList_write.txt"
Read File: /FunctionList_write.txt
Filesize: 299
{"Type":"System Function","Function list":{"Relay ch3":{"Settings":{},"Relay":{"Value":false}},"Pump":{"Settings":{"Pump Time":{"Value":60},"Heating Time":{"Value":600},"Wather":{"Calibration(L)":20},"Clear Pump Time":{"Value":false},"Clear Heating Time":{"Value":false}}}},"System":{"Settings":{▒▒▒
{
"

No difference, still junk at the end. 

All lib is up to date.
ArduinoJson 6.18.5
PubSubClient 2.8
StreamUtills 1.6.1
Espressif 8266 3.2.0

File system in LittleFS give the same result.

I have used the serializeJson function to file before without any problems. It is included in my base platform in all nodes. Even in this project, it has worked. Unfortunately, I have now made so many changes that I do not remember what changes have been made since it stopped working.

Brg
Findus

**Comment by Findus76** [comment]
Hi Benoit

Wait..
I need to test with LitteFS / SPIFFS again.

Brg
Findus

**Comment by Findus76** [comment]
Hi Benoit

It seems to work with littlefs.
Gets core crash though, but thinks it depends on something else.

Brg
Findus

**Comment by Findus76** [comment]
Hi Benoit

Now I have tried a little more.
It appears to be a bug linked to the SPIFFS file system. It seems to work with LittleFS.
At least now I was forced to take the step to LittleFS, the compiler has thought so for a long time.

Thanks for the help.

Brg
Findus

**Comment by bblanchon** [comment]
Hi Findus,

I'm glad you finally found the solution.
I wish I could add some information about it on arduinojson.org, but I need more data.
Did you found any page (for example, a GitHub issue) related to this bug?

Best regards,
Benoit

**Comment by Findus76** [comment]
Hi Benoit

I thank you for an excellent routine and the factual help both in tools and direct support.

The least I can do is help you. To improv the tool and function.
I am open to downgrading, and get the error again if additional data is needed.
I searched a bit for my bug but found nothing that fit.

I find it strange that it has worked and works on other nodes. I do not know what triggered the bug itself. It has made several changes afterwards that I lost which ones.
As the program works, I create a JSON file in the computer (I always test run this in your Assistant tool before it is uploaded to the file system in esp8266). To speed up the handling of data, this file is cleaned from extra characters, such as CR + LF. The result is saved as a new file in the file system (I also take a copy of the result and run it in your tool to see that nothing is damaged). From this modified file I extract key data and save as a new file in the file system.
Like this
Orginal_JSON.txt -> Compress_JSON.txt -> Keyword_JSON.txt.
The bug appears in the last step of saving the "Keyword: JSON" file.

Brg
Findus

**Comment by bblanchon** [comment]
Hi Findus,

Thank you very much for this information.
Unfortunately, there is not enough material to put something in the documentation.

Good luck with your project!

Best regards,
Benoit
