### ISSUE TITLE
Regarding the error request for member 'write' in ..., which is of non-class type 'char*' #1543

### ISSUE THREAD

**Issue by davidcreager** [bblanchon/ArduinoJson#1665]
Could I suggest this error and solution be added to the documentation, either Beginner Gotchas or Compilation errors?

I just spent all day with this *sigh*.......Love the project and was delighted to find the answer!!!

Thanks for your brilliant work!!

**Comment by bblanchon** [comment]
Hi @davidcreager,

I'm sorry you had to spend so much time on this issue.

I added two pages:

* [In the documentation](https://arduinojson.org/v6/error/request-for-member-write-in-char-ptr/)
* [In ArduinoJson Troubleshooter](https://arduinojson.org/v6/troubleshooter/#compiletime/member-write-in-char-ptr)

Please let me know if these pages are unclear.

Best regards,
Benoit
