### ISSUE TITLE
How to properly convert from JsonDocument to JsonObjectConst

### ISSUE THREAD

**Issue by console-netsphere** [bblanchon/ArduinoJson#1667]
**Describe the issue**  
I'm a little bit unsure of the proper way to convert a JsonDocument to a JsonObjectConst. 
I am converting the JsonDocument to a JsonObjectConst in order to pass the object by reference to a method, and I'm concerned if something is being copied along the way.

**Environment**  
Here is the environment that I'm using':
* Microconroller: ESP32
* Core/runtime: 1.0.6
* IDE: Eclipse

**Reproduction**  
```c++
StaticJsonDocument<4096> doc;
DeserializationError checkError = deserializeJson(doc, response);
	if(checkError){
		LOG_MSG("[Error] Failed to deserialize JSON");
		LOG_MSG(String(checkError.c_str()));
		return false;
}
//Should it be done this way?
const JsonObjectConst& obj = doc.as<JsonObjectConst>();
return parseGetConfigResponse(obj, collector_index);
//Or this way?
const JsonObjectConst obj = doc.as<JsonObjectConst>();
return parseGetConfigResponse(obj, collector_index);
```

The parseGetConfigResponse method has the following signature:
```c++
bool parseGetConfigResponse(const JsonObjectConst& doc, uint8_t collector_index = 0);
```

Since both ways are compiling, I'm unsure if the different alternatives generates different behaviors or differences in efficiency.

Thanks for the amazing library!

**Comment by bblanchon** [comment]
Hi @wesee-dev,

The right way to convert a [`JsonDocument`](https://arduinojson.org/v6/api/jsondocument/) to a [`JsonObjectConst`](https://arduinojson.org/v6/api/jsonobjectconst/) is:

```c++
JsonObjectConst obj = doc.as<JsonObjectConst>();
```

[`JsonObjectConst`](https://arduinojson.org/v6/api/jsonobjectconst/) already offers reference semantics, so you don't need `const &`.

Alternatively, your function could accept a reference to a [`JsonDocument`](https://arduinojson.org/v6/api/jsondocument/), like so:

```c++
bool parseGetConfigResponse(const JsonDocuement& doc, ...);
```

This is a more common practice but is less flexible than the [`JsonObjectConst`](https://arduinojson.org/v6/api/jsonobjectconst/) parameter.

Best regards,
Benoit

**Comment by console-netsphere** [comment]
Hi @bblanchon,
thanks for que quick response and explanation.

Awesome, I'll make the necessary changes to JsonObjectConst.
I'm using JsonObjectConst instead of JsonDocuement to pass both deserialized objects, containing a single object, and also nested objects inside a JSON document, but I usually tend to use  JsonDocuement& for more general purposes.

Best Regards,
Ian

**Comment by bblanchon** [comment]
You're welcome, Ian!
Thank you for using ArduinoJson.
Don't forget to [cast a star](https://github.com/bblanchon/ArduinoJson/stargazers) to support the project :wink:
