### ISSUE TITLE
deserialize json IPADDRESS

### ISSUE THREAD

**Issue by laercionit** [bblanchon/ArduinoJson#1668]
I have on a json IP, Mask, GTW, DNS.

[
  {
    "HOST": "DESENV",
    "PWD": "mypassword",
    "EMAIL": "myemail@email.com",
    "PRT": 0,
    "DTF": 0,
    "HRF": 1,
    "BUZZ": 1,
    "FAD": 1,
    "HGT": 0,
    "THM": 0,
    "UTEMP": 1,
    "UWATTS": 13,
    "UKH": 19,
    "UEC": 20,
    "UHG": 21,
    "UOX": 4,
    "PPM": 0.55,
    "LNG": 0,
    "NSR": "pool.ntp.org",
    "NTM": -3,
    "MLT": 0,
    "UFA": 6,
    "UFB": 6,
    "DHCP": 1,
    "IP": "192.168.1.150",
    "MASK": "255.255.255.0",
    "GTW": "192.168.1.1",
    "DNS": "8.8.8.8"
  }
]

I'm having trouble deserialize the JSON for the char variable 

BYTE NetworkIP[4] = {0,0,0,0};
NetworkIP = DOC["IP"];

Could you guide me or is there a function for it?

**Comment by bblanchon** [comment]
Hi @laercionit,

This is a very strange question because

```json
192.168.0.1
```

is not a valid JSON document, and 

```c++
char NetworkIP[4] = {192.168.0.1}
```

is not valid C++ either.

If you want to split the string "192.168.0.1", I recommend that you use `strtok()`, and then call `atoi()` or similar to get the integers. ArduinoJson cannot help you with that.

Best regards
Benoit

**Comment by laercionit** [comment]
Tks @bblanchon 
I'm sorry my friend, I ended up typing it wrong. I adjusted the text.

**Comment by bblanchon** [comment]
This doesn't change my answer: you must extract the IP as a string first, and then convert it.
For example, you can split with `strtok()` and parse the integers with `atoi()`, or you can parse the whole string with `sscanf()`.
See: https://forum.arduino.cc/t/get-ip-address-from-string/478308/10
