### ISSUE TITLE
Mistake in arduinojson.org FAQ

### ISSUE THREAD

**Issue by ilutchenko** [bblanchon/ArduinoJson#1670]
**Describe the bug**  
Hello! I found that on this page:
https://arduinojson.org/v6/error/no-matching-function-for-call-to-converttojson/
function arguments in the example are swapped:

`
bool convertToJson(JsonVariant variant, const tm& t)`

But they must look like:
`bool convertToJson(const tm& t, JsonVariant variant)`

It's not trivial to find in the compiler's errors output why it can't find yours `convertToJson` overload for a new type.

Thanks!

**Comment by bblanchon** [comment]
Hi @ilutchenko,

Thank you very much for reporting this bug 👍 

The page should be fixed now.
Sorry about that.

Best regards,
Benoit
