### ISSUE TITLE
Error serializeJson(doc, file) on SAMD51

### ISSUE THREAD

**Issue by sergioxdev** [bblanchon/ArduinoJson#1672]
Hi Guys

I'm testing ArduinoJson on an Adafruit Metro M4 Express AirLift

I use libraries
#include "SdFat.h"
#include "Adafruit_SPIFlash.h"

when I try to call:
serializeJson (doc, file);
to write the file on the SPIFlash connected to SAMD51
an error is returned to me.

I am attaching the example code to be able to emulate the problem:
`
#include <SPI.h>
#include "SdFat.h"
#include "Adafruit_SPIFlash.h"
#include <ArduinoJson.h>

struct Config {
  char hostname[64];
  int port;
};

const char *filename = "/config.txt";  // <- SD library uses 8.3 filenames
Config config;                         // <- global configuration object

  // Uncomment to run example with custom SPI and SS e.g with FRAM breakout
  // #define CUSTOM_CS   A5
  // #define CUSTOM_SPI  SPI
  #if defined(CUSTOM_CS) && defined(CUSTOM_SPI)
    Adafruit_FlashTransport_SPI flashTransport(CUSTOM_CS, CUSTOM_SPI);
  
  #elif defined(ARDUINO_ARCH_ESP32)
    Adafruit_FlashTransport_ESP32 flashTransport;
  #else
    #if defined(EXTERNAL_FLASH_USE_QSPI)
      Adafruit_FlashTransport_QSPI flashTransport;
    #elif defined(EXTERNAL_FLASH_USE_SPI)
      Adafruit_FlashTransport_SPI flashTransport(EXTERNAL_FLASH_USE_CS, EXTERNAL_FLASH_USE_SPI);
  
    #else
      #error No QSPI/SPI flash are defined on your board variant.h !
    #endif
  #endif
  
  Adafruit_SPIFlash flash(&flashTransport);
  FatFileSystem fatfs;
  File myFile;
  
// Loads the configuration from a file
void loadConfiguration(const char *filename, Config &config) {
  // Open file for reading
  File file = fatfs.open(filename, FILE_WRITE);

  // Allocate a temporary JsonDocument
  // Don't forget to change the capacity to match your requirements.
  // Use https://arduinojson.org/v6/assistant to compute the capacity.
  StaticJsonDocument<512> doc;

  // Deserialize the JSON document
  DeserializationError error = deserializeJson(doc, file);
  if (error)
    Serial.println(F("Failed to read file, using default configuration"));

  // Copy values from the JsonDocument to the Config
  config.port = doc["port"] | 2731;
  strlcpy(config.hostname,                  // <- destination
          doc["hostname"] | "example.com",  // <- source
          sizeof(config.hostname));         // <- destination's capacity

  // Close the file (Curiously, File's destructor doesn't close the file)
  file.close();
}

// Saves the configuration to a file
void saveConfiguration(const char *filename, const Config &config) {
  // Delete existing file, otherwise the configuration is appended to the file
  fatfs.remove(filename);

  // Open file for writing
  File file = fatfs.open(filename, FILE_WRITE);
  if (!file) {
    Serial.println(F("Failed to create file"));
    return;
  }

  // Allocate a temporary JsonDocument
  // Don't forget to change the capacity to match your requirements.
  // Use https://arduinojson.org/assistant to compute the capacity.
  StaticJsonDocument<256> doc;

  // Set the values in the document
  doc["hostname"] = config.hostname;
  doc["port"] = config.port;

  // Serialize JSON to file
  if (serializeJson(doc, file) == 0) {
    Serial.println(F("Failed to write to file"));
  }

  // Close the file
  file.close();
}

// Prints the content of a file to the Serial
void printFile(const char *filename) {
  // Open file for reading
  File file = fatfs.open(filename, FILE_WRITE);
  if (!file) {
    Serial.println(F("Failed to read file"));
    return;
  }

  // Extract each characters by one by one
  while (file.available()) {
    Serial.print((char)file.read());
  }
  Serial.println();

  // Close the file
  file.close();
}

void setup() {
  // Initialize serial port
  Serial.begin(115200);
  while (!Serial) continue;

  Serial.print("Initializing Filesystem on external flash...");
  flash.begin();
    
  if ( !fatfs.begin(&flash) ) {
    Serial.println("Error: filesystem is not existed. Please try SdFat_format example to make one.");
    while(1) yield();
  }
  Serial.println("initialization done.");

  // Should load default config if run for the first time
  Serial.println(F("Loading configuration..."));
  loadConfiguration(filename, config);

  // Create configuration file
  Serial.println(F("Saving configuration..."));
  saveConfiguration(filename, config);

  // Dump config file
  Serial.println(F("Print config file..."));
  printFile(filename);
}

void loop() {
  // not used in this example
}`
any suggestion is accepted

**Comment by bblanchon** [comment]
Hi @sergioxdev,

> an error is returned to me.

What error is returned? Can you be more explicit?

This is probably unrelated but I noticed an error in `printFile()`: you use `FILE_WRITE` instead of `FILE_READ`.

BTW, did you try the [ArduinoJson Troubleshooter](https://arduinojson.org/v6/troubleshooter)?

Best regards,
Benoit

**Comment by sergioxdev** [comment]
hello @bblanchon

i am doing a series of tests, initially i used the DynamicJson,
now I'm testing with the StaticJson version,

I'll update you as soon as I understand the problem

**Comment by sergioxdev** [comment]
Hi @bblanchon

I found the error in the functions:
- loadConfiguration()
- printFile()

when you access the file:
File file = fatfs.open (filename, FILE_WRITE);
must be replaced with
File file = fatfs.open (filename);

Now works
