### ISSUE TITLE
Help - compiling issue while using jsonDoc as function argument

### ISSUE THREAD

**Issue by mchacher** [bblanchon/ArduinoJson#1679]
Hi Benoit,

I was using an old version of Arduino v6 library (unable to tell you which version). Trying to upgrade to the latest my code is not compiling, and I am facing the issue below. I am not a specialist in C++.
Basically what I am doing is pretty simple : 

```
// deserializing in a jsonDoc a payload
DeserializationError error = deserializeJson(jsonDoc, lhf.jsonPayload);
// calling a method with a jsonDoc as an argument
Node->parseJsonRxPayload(jsonDoc);
```
Your help would be well appreciated.

Thanks,

Marc

### Compiler output message:
src/LoRaHomeNode.cpp: In member function 'void LoRaHomeNode::receiveLoraMessage()':
**src/LoRaHomeNode.cpp:291:37: error: 'ArduinoJson6185_91::JsonDocument::JsonDocument(const ArduinoJson6185_91::JsonDocument&)' is private within this context**
     Node->parseJsonRxPayload(jsonDoc);
                                     ^
In file included from .pio/libdeps/pro8MHzatmega328/ArduinoJson/src/ArduinoJson/Document/BasicJsonDocument.hpp:7:0,
                 from .pio/libdeps/pro8MHzatmega328/ArduinoJson/src/ArduinoJson/Document/DynamicJsonDocument.hpp:7,
                 from .pio/libdeps/pro8MHzatmega328/ArduinoJson/src/ArduinoJson.hpp:21,
                 from .pio/libdeps/pro8MHzatmega328/ArduinoJson/src/ArduinoJson.h:9,
                 from src/LoRaHomeNode.h:4,
                 from src/LoRaHomeNode.cpp:2:
**.pio/libdeps/pro8MHzatmega328/ArduinoJson/src/ArduinoJson/Document/JsonDocument.hpp:336:3: note: declared private here
   JsonDocument(const JsonDocument&);**
   ^~~~~~~~~~~~
In file included from src/LoRaHomeNode.cpp:5:0:
src/LoRaNode.h:43:16: note:   initializing argument 1 of 'virtual void LoRaNode::parseJsonRxPayload(ArduinoJson6185_91::JsonDocument)'
   virtual void parseJsonRxPayload(JsonDocument payload) = 0;
                ^~~~~~~~~~~~~~~~~~
src/LoRaHomeNode.cpp:291:37: error: 'ArduinoJson6185_91::JsonDocument::~JsonDocument()' is protected within this context
     Node->parseJsonRxPayload(jsonDoc);
                                     ^
In file included from .pio/libdeps/pro8MHzatmega328/ArduinoJson/src/ArduinoJson/Document/BasicJsonDocument.hpp:7:0,
                 from .pio/libdeps/pro8MHzatmega328/ArduinoJson/src/ArduinoJson/Document/DynamicJsonDocument.hpp:7,
                 from .pio/libdeps/pro8MHzatmega328/ArduinoJson/src/ArduinoJson.hpp:21,
                 from .pio/libdeps/pro8MHzatmega328/ArduinoJson/src/ArduinoJson.h:9,
                 from src/LoRaHomeNode.h:4,
                 from src/LoRaHomeNode.cpp:2:
.pio/libdeps/pro8MHzatmega328/ArduinoJson/src/ArduinoJson/Document/JsonDocument.hpp:318:3: note: declared protected here
   ~JsonDocument() {}
   ^
*** [.pio/build/pro8MHzatmega328/src/LoRaHomeNode.cpp.o] Error 1

**Comment by bblanchon** [comment]
Hi @mchacher,

This fix was introduced in [ArduinoJson 6.15](https://arduinojson.org/news/2020/03/22/version-6-15-0/#copy-constructor-of-jsondocument).
You must change the signature of `parseJsonRxPayload()` to take a reference instead of a copy:

```c++
void parseJsonRxPayload(const JsonDocument& payload)
```

Best regards,
Benoit
