### ISSUE TITLE
How to compile arduinojson using cmake

### ISSUE THREAD

**Issue by 925486270** [bblanchon/ArduinoJson#1680]
**Describe the issue**  
Error message generated by compiling Cmakelist in arduinojson-6. X \ SRC directory

**Troubleshooter report**  
CMake Error at D:/CMake/share/cmake-3.22/Modules/WriteBasicConfigVersionFile.cmake:43 (message):
  No VERSION specified for WRITE_BASIC_CONFIG_VERSION_FILE()
Call Stack (most recent call first):
  D:/CMake/share/cmake-3.22/Modules/CMakePackageConfigHelpers.cmake:237 (write_basic_config_version_file)
  CMakeLists.txt:46 (write_basic_package_version_file)

**Environment**  
Here is the environment that I'm using':
CMake 3.22.0 Gui

**Comment by bblanchon** [comment]
Hi @925486270,

Please see [How to use ArduinoJson with CMake?](https://arduinojson.org/v6/how-to/use-arduinojson-with-cmake/)
If you still get an error, please provide complete instructions to reproduce it.

Best regards,
Benoit

**Comment by 925486270** [comment]
Thank you very much. I have solved the problem. Thank you for your kindness

**Comment by bblanchon** [comment]
You're welcome, @925486270!
Thank you for using ArduinoJson.
Don't forget to [cast a star](https://github.com/bblanchon/ArduinoJson/stargazers) to support the project :wink:
