### ISSUE TITLE
Migrating from Version 5 to 6 I get InvalidInput on deserializeJson

### ISSUE THREAD

**Issue by juancgalvez** [bblanchon/ArduinoJson#1686]
I used to transmit via MQTT codes to me IR Remote micro controller and parse them with ArduinoJson without any issues. After upgrading to version 6 I have problems while parsing the JSON message.

This message used to work;

`{"protocol":"SAMSUNG","data": 0xE0E0E01F}`

That message used to work with version 5. But, with version 6 I get **InvalidInput** error on **deserializeJson**. I have to enclose the hex value inside quotes to make it work. Something like this:

`{"protocol":"SAMSUNG","data": "0xE0E0E01F"}`

 In JSON format, numeric values don't necessarily must be enclosed inside quotes.

**Comment by bblanchon** [comment]
Hi @juancgalvez,

The JSON format doesn't support hexadecimal notation.

ArduinoJson 5 was less picky and didn't impose quotes around strings.
If anything, it's a bug in version 5 but not in version 6.

Best regards,
Benoit

**Comment by juancgalvez** [comment]
You are right. I fixed he issue by including values in quotes.

Thank you and excuse me for reporting a false bug.

**Comment by bblanchon** [comment]
You're welcome, @juancgalvez.
Thank you for using ArduinoJson!
Don't forget to [cast a star](https://github.com/bblanchon/ArduinoJson/stargazers) to support the project :wink:
