### ISSUE TITLE
"No memory" error (no serial console using generics?)

### ISSUE THREAD

**Issue by jeffreyjene** [bblanchon/ArduinoJson#1688]
**Describe the issue**  
I'm trying to pull a 768 character json string from an SD card and deserialize it. Using a DynamicJsonDocument doc(768); causes a NO MEMORY error. using the StaticJsonDocument<768> doc; causes the serial monitor to stop working for some reason even though there are no compiler errors. 

**Troubleshooter report**  
Here is the report generated by the [ArduinoJson Troubleshooter](https://arduinojson.org/v6/troubleshooter/):  
It simply recommends StaticJsonDocument

**Environment**  
Here is the environment that I'm using':
* Microconroller: Arduino (Elegoo) Nano
* Core/runtime: Arduino v1.8.16
* IDE: [e.g. Arduino IDE 1.8.16]

**Reproduction**  
````
#include <SD.h>
#include <ArduinoJson.h> // JSON decoding library

const int chipSelect = 10;

File weatherFile;

String pBuffer;
void setup() {
  Serial.begin(9600);
  initializeSDCard();
  delay(1000);
  
  //read the weather file
  weatherFile = SD.open(F("weather.txt"));
  if (!weatherFile){
    Serial.println("Error opening weather file!");
  }
  while(weatherFile.available()){
    pBuffer = weatherFile.readString();

  }

  weatherFile.close();

  Serial.println(pBuffer);
  
  StaticJsonDocument<768> doc; //DynamicJsonDocument causes NO MEMORY error
  
  // Deserialize the JSON document
  DeserializationError error = deserializeJson(doc, pBuffer);

  // Test if parsing succeeds.
  if (error) {
    Serial.print(F("deserializeJson() failed: "));
    Serial.println(error.f_str());
    return;
  }

  JsonArray weather = doc["weather"];
  JsonObject weather0 = weather[0];
  String weatherDesc = weather0["description"];

  String tempOut = doc["main"]["temp"];
  String feelsLike = doc["main"]["feels_like"];
  String humidOut = doc["main"]["humidity"];
  String sunrise = doc["sys"]["sunrise"];
  String sunset = doc["sys"]["sunset"];

  Serial.print("Forecast: "); Serial.println(weatherDesc);
  Serial.print("Temperature: "); Serial.println(tempOut); Serial.print("   Feels like: "); Serial.println(feelsLike);
  Serial.print("Humidity: "); Serial.println(humidOut); 
  Serial.print("Sunrise: "); Serial.println(sunrise); 
  Serial.print("Sunset: "); Serial.println(sunset); 

}

void loop() {
  

}

void initializeSDCard(){
  
  while (!Serial);
  
  Serial.print("Initializing SD card...");
  if (!SD.begin(chipSelect)) {
    Serial.println("initialization failed. Things to check:");
    Serial.println("1. is a card inserted?");
    Serial.println("2. is your wiring correct?");
    Serial.println("3. did you change the chipSelect pin to match your shield or module?");
    Serial.println("Note: press reset or reopen this serial monitor after fixing your issue!");
    while (true);
  }

  Serial.println("initialization done.");
}
````

Here is the input JSON:
`{"coord":{"lon":-73.8129,"lat":42.5486},"weather":[{"id":804,"main":"Clouds","description":"overcast clouds","icon":"04n"}],"base":"stations","main":{"temp":286.15,"feels_like":285.26,"temp_min":283.46,"temp_max":288.27,"pressure":1010,"humidity":67},"visibility":10000,"wind":{"speed":0.89,"deg":277,"gust":4.02},"clouds":{"all":89},"dt":1639690850,"sys":{"type":2,"id":2009955,"country":"US","sunrise":1639657143,"sunset":1639689786},"timezone":-18000,"id":0,"name":"Selkirk","cod":200}`

**Comment by bblanchon** [comment]
Hi @jeffreyjene,

It looks like you're running out of RAM.
Please share [ArduinoJson Troubleshooter](https://arduinojson.org/v6/troubleshooter/)'s report.
Let me know if you have any problems running the Troubleshooter.

Best regards,
Benoit
