### ISSUE TITLE
Non blocking deserialize

### ISSUE THREAD

**Issue by dbagnara** [bblanchon/ArduinoJson#1690]
Is there a way to prevent deserialize from blocking?

For example, is it possible to either push a stream into the JsonDocument using a ficticious method addSerialData()
`StaticJsonDocument<256> doc ;
doc.addSerialData( "[1," );
doc.addSerialData(  '2' );
doc.addSerialData( ",3]" );`

Or resume a partial deserialization.

`StaticJsonDocument<256> doc ;
deserializeJson( doc, "[1,2," );
deserializeJson( doc, "3]" );`

Thanks

**Comment by bblanchon** [comment]
Hi @dbagnara,

No, ArduinoJson doesn't support incremental/partial deserialization.
I wish to add this feature at some point, but I'm afraid it will increase the code size dramatically.

As a workaround, I suggest that you use a [StringStream](https://github.com/bblanchon/ArduinoStreamUtils#how-to-use-a-string-as-a-stream) as a temporary buffer and call `deserializeJson()` when the message is complete.

Best regards,
Benoit

**Comment by dbagnara** [comment]
Thanks.
