### ISSUE TITLE
DynamicJsonDocument serializeJson size problem

### ISSUE THREAD

**Issue by Mesihas** [bblanchon/ArduinoJson#1691]
**Describe the issue**  
DynamicJsonDocument serializeJson bigger than 4096 bytes just crashes the ESP32

**Error**  
Guru Meditation Error: Core  1 panic'ed (Unhandled debug exception)
Debug exception reason: Stack canary watchpoint triggered (loopTask)  

**Environment**  
ESP32
IDE: [Arduino IDE 1.8.16]
ArduinoJson 6.17.2

I am building the message at runtime and I was able to serialize using `StaticJsonDocument<2048> docItems `with no problem.
Then as the Json message I am building grew in size I started using DynamicJsonDocument `docItems(4096)`  which works fine but I need at least 16384 bytes and any size bigger than 4096 bytes just crash the ESP32.

ESP.getMaxAllocHeap()
113792
ESP.getFreeHeap()
217640

At the same time I am using another ` DynamicJsonDocument docMessage(20000); ` for Deserialization which works perfect.

```
void getItemsStateRequest(int highlithedSceneInt){
  //StaticJsonDocument<2048> docItems;
  DynamicJsonDocument docItems(10000);
  const char* sceneName = scenesL[highlithedSceneInt];

  docItems["op"] = 8;
  JsonObject d = docItems.createNestedObject("d");
  d["requestId"] = "GetItemsStateRequest-01";
  d["haltOnFailure"] = true;

  JsonArray d_requests = d.createNestedArray("requests");

  Serial.println("sourceItemsCount: " + String((int32_t)sourceItemsCount));
  Serial.print("sceneName: ");
  Serial.println(scenesL[0]);

  for (size_t i = 0; i < sourceItemsCount; i++)
  {
    JsonObject d_requests_2 = d_requests.createNestedObject();
    d_requests_2["requestType"] = "GetSceneItemEnabled";
    d_requests_2["requestId"] = sourceItemsL[i][3] + "-" + sourceItemsL[i][0];
    d_requests_2["requestData"]["sceneName"] = sceneName;
    d_requests_2["requestData"]["sceneItemId"] = sourceItemsL[i][1].toInt();
  }

  char output[10000];
  Serial.println("ESP.getMaxAllocHeap()");
  Serial.println(ESP.getMaxAllocHeap());
  Serial.println("ESP.getFreeHeap()");  
  Serial.println(ESP.getFreeHeap());

  serializeJson(docItems, output, sizeof(output));  // Crashes here !!
  SendRequest(output);  
}
```

**Comment by bblanchon** [comment]
@Mesihas, please share the [ArduinoJson Troubleshooter](https://arduinojson.org/v6/troubleshooter/)'s report.

**Comment by Mesihas** [comment]
Please try with a String instead of a char[]

and... It worked.  Sorry that I didn't know the  ArduinoJson Troubleshooter. 

Is this  char[] size limit related to Arduino environment?

THANKS

**Comment by bblanchon** [comment]
You're welcome, @Mesihas!

By default, the size of the stack is limited to 8KB on ESP32, so `char output[10000]` is clearly too big.
If you don't know what I'm talking about, I recommend that you read the first chapter of my book [Mastering ArduinoJson](https://arduinojson.org/book/).

Best regards,
Benoit.

**Comment by Mesihas** [comment]
will do. Thanks
