### ISSUE TITLE
std::string not terminating ?

### ISSUE THREAD

**Issue by proddy** [bblanchon/ArduinoJson#1698]
Since version 6.19.0 I'm finding std::strings are not terminated correctly. 

**Environment** 

ESP8266, ESP32, PlatformIO, also standalone with G++ (reproduced in wandbox)

**Reproduction**  

```c++
#include <iostream>
#include <string>
#define ARDUINOJSON_ENABLE_STD_STRING 1 // just to be sure
#include "ArduinoJson.h"

int main() { 
  DynamicJsonDocument doc(1024);
   
  std::string str(20, '\0');
  snprintf(&str[0], str.capacity()+1, "%s and pong", "ping");
   
  doc["name"] = str;
    
  serializeJson(doc, std::cout);
  
}
```

Expected output:

`{"name":"ping and pong"}`

Actual output:

`{"name":"ping and pong\u0000\u0000\u0000\u0000\u0000\u0000\u0000"}`

I know it's messy code, but it used to work in <6.19.0. I can re-write my project code but wanted to point it out in case it's a new issue.

**Comment by bblanchon** [comment]
Hi @proddy,

This is the expected behavior.
Indeed, ArduinoJson now supports NUL in strings.
To do that, it looks at the size of the `std::string` (20 in this case) instead of stopping at the first NUL.

I don't know if this example comes from an actual code or if it's just an experiment, but it's very unusual.
I would recommend writing this instead:

```c++
char str[20];
snprintf(str, sizeof(str), "%s and pong", "ping");
doc["name"] = str;
```

Best regards,
Benoit

**Comment by proddy** [comment]
Thanks Benoit, that makes total sense. My snippet is actual from some real code I use, in the form of a private function returning a `std::string` like

```
const std::string Device::to_string() const {
    std::string str(160, '\0');

    snprintf(&str[0], str.capacity() + 1, "(DeviceID:0x%02X)", device_id_);

    return str;
}
```

It was originally written for an ESP8266 as I was super paranoid about memory fragmentation so initialized the string upfront. I'll refactor it.

**Comment by bblanchon** [comment]
@proddy, don't hesitate to [contact me on Codementor](https://www.codementor.io/@bblanchon) if you want to do a code review.
