### ISSUE TITLE
float serialization not accurate

### ISSUE THREAD

**Issue by Burnyfighter** [bblanchon/ArduinoJson#1700]
Hello, 
I'm trying to run this small program on esp8266 to fill a json document:
`
float myValue=21.81
StaticJsonDocument<1024> jsonLoad;
JsonArray jsonData=jsonLoad.createNestedArray("data");
JsonObject data_0=jsonData.createNestedObject();
data_0["key"]=myValue;
`
While sending this this is what I have:
{"data":[{"key":20.80999947}]}
Everywhere else where I work with 'myValue' float, caculus are good (as long as I can check) only issue appears while sending it to JSON document.

Any help is appreciated ;-)

**Comment by bblanchon** [comment]
Hi @Burnyfighter,

This probably comes from the limited precision of `float`.
You'd have much better precision with `double`.
See this online demo: https://wandbox.org/permlink/TdrKhBRgNmpXr8JS

Best regards,
Benoit

**Comment by Burnyfighter** [comment]
Thanks so much Benoit for your reply.
Will test it !

Merci Benoit de prendre le temps pour les novices ;-)

**Comment by bblanchon** [comment]
You're welcome, @Burnyfighter!
Thank you for using ArduinoJson.
Don't forget to [cast a star](https://github.com/bblanchon/ArduinoJson/stargazers) to support the project :wink:
