### ISSUE TITLE
only get last temp value

### ISSUE THREAD

**Issue by dabbeknik** [bblanchon/ArduinoJson#1706]
I´m tring to make a little weatherstation and for that I reseav weatherdates from an api and with the programm from the Json assist I´m getting only the last temperature value.
I wont to get all or a part of the values in an arry or in more variables.

**Environment**  
Here is the environment that I'm using':
* Microconroller: ESP 32
* IDE: [e.g. Arduino IDE 1.8.13]

This is the Programm from the Json Assist that im using:
// Stream& input;

DynamicJsonDocument doc(12288);

DeserializationError error = deserializeJson(doc, input);

if (error) {
  Serial.print("deserializeJson() failed: ");
  Serial.println(error.c_str());
  return;
}

JsonObject data_timelines_0 = doc["data"]["timelines"][0];
const char* data_timelines_0_timestep = data_timelines_0["timestep"]; // "1h"
const char* data_timelines_0_startTime = data_timelines_0["startTime"]; // "2022-02-04T01:00:00Z"
const char* data_timelines_0_endTime = data_timelines_0["endTime"]; // "2022-02-08T13:00:00Z"

for (JsonObject data_timelines_0_interval : data_timelines_0["intervals"].as<JsonArray>()) {

  const char* data_timelines_0_interval_startTime = data_timelines_0_interval["startTime"];

  float data_timelines_0_interval_values_temperature = data_timelines_0_interval["values"]["temperature"];

}

and after that I print all varibals to the serial monitor and get for the temperature only the last value.

And Im reseaving this part of temeratures dates:

{"data":{"timelines":[{"timestep":"1h","startTime":"2022-02-04T01:00:00Z","endTime":"2022-02-08T13:00:00Z","intervals":[{"startTime":"2022-02-04T01:00:00Z","values":{"temperature":-37.21}},{"startTime":"2022-02-04T02:00:00Z","values":{"temperature":-37.04}},{"startTime":"2022-02-04T03:00:00Z","values":{"temperature":-36.77}},{"startTime":"2022-02-04T04:00:00Z","values":{"temperature":-36.32}},{"startTime":"2022-02-04T05:00:00Z","values":{"temperature":-35.8}},{"startTime":"2022-02-04T06:00:00Z","values":{"temperature":-35.27}},{"startTime":"2022-02-04T07:00:00Z","values":{"temperature":-34.81}},{"startTime":"2022-02-04T08:00:00Z","values":{"temperature":-34.23}},{"startTime":"2022-02-04T09:00:00Z","values":{"temperature":-33.76}},{"startTime":"2022-02-04T10:00:00Z","values":{"temperature":-33.35}},{"startTime":"2022-02-04T11:00:00Z","values":{"temperature":-33.04}},{"startTime":"2022-02-04T12:00:00Z","values":{"temperature":-32.84}},{"startTime":"2022-02-04T13:00:00Z","values":{"temperature":-32.48}},{"startTime":"2022-02-04T14:00:00Z","values":{"temperature":-31.99}},{"startTime":"2022-02-04T15:00:00Z","values":{"temperature":-32.31}},{"startTime":"2022-02-04T16:00:00Z","values":{"temperature":-32.89}},{"startTime":"2022-02-04T17:00:00Z","values":{"temperature":-33.28}},{"startTime":"2022-02-04T18:00:00Z","values":{"temperature":-34.08}},{"startTime":"2022-02-04T19:00:00Z","values":{"temperature":-34.02}},{"startTime":"2022-02-04T20:00:00Z","values":{"temperature":-34.86}},{"startTime":"2022-02-04T21:00:00Z","values":{"temperature":-35.11}},{"startTime":"2022-02-04T22:00:00Z","values":{"temperature":-35.53}},{"startTime":"2022-02-04T23:00:00Z","values":{"temperature":-35.76}},{"startTime":"2022-02-05T00:00:00Z","values":{"temperature":-36.29}},{"startTime":"2022-02-05T01:00:00Z","values":{"temperature":-36.22}},{"startTime":"2022-02-05T02:00:00Z","values":{"temperature":-35.63}},{"startTime":"2022-02-05T03:00:00Z","values":{"temperature":-34.86}},{"startTime":"2022-02-05T04:00:00Z","values":{"temperature":-33.97}},{"startTime":"2022-02-05T05:00:00Z","values":{"temperature":-33.27}},{"startTime":"2022-02-05T06:00:00Z","values":{"temperature":-32.65}},{"startTime":"2022-02-05T07:00:00Z","values":{"temperature":-32}},{"startTime":"2022-02-05T08:00:00Z","values":{"temperature":-31.3}},{"startTime":"2022-02-05T09:00:00Z","values":{"temperature":-30.71}},{"startTime":"2022-02-05T10:00:00Z","values":{"temperature":-30.05}},{"startTime":"2022-02-05T11:00:00Z","values":{"temperature":-29.72}},{"startTime":"2022-02-05T12:00:00Z","values":{"temperature":-29.47}},{"startTime":"2022-02-05T13:00:00Z","values":{"temperature":-29.47}},{"startTime":"2022-02-05T14:00:00Z","values":{"temperature":-29.4}},{"startTime":"2022-02-05T15:00:00Z","values":{"temperature":-29.81}},{"startTime":"2022-02-05T16:00:00Z","values":{"temperature":-30.24}},{"startTime":"2022-02-05T17:00:00Z","values":{"temperature":-30.73}},{"startTime":"2022-02-05T18:00:00Z","values":{"temperature":-31.27}},{"startTime":"2022-02-05T19:00:00Z","values":{"temperature":-32.06}},{"startTime":"2022-02-05T20:00:00Z","values":{"temperature":-32.57}},{"startTime":"2022-02-05T21:00:00Z","values":{"temperature":-33.29}},{"startTime":"2022-02-05T22:00:00Z","values":{"temperature":-33.95}},{"startTime":"2022-02-05T23:00:00Z","values":{"temperature":-34.49}},{"startTime":"2022-02-06T00:00:00Z","values":{"temperature":-34.8}},{"startTime":"2022-02-06T01:00:00Z","values":{"temperature":-34.76}},{"startTime":"2022-02-06T02:00:00Z","values":{"temperature":-34.42}},{"startTime":"2022-02-06T03:00:00Z","values":{"temperature":-33.89}},{"startTime":"2022-02-06T04:00:00Z","values":{"temperature":-33.26}},{"startTime":"2022-02-06T05:00:00Z","values":{"temperature":-32.57}},{"startTime":"2022-02-06T06:00:00Z","values":{"temperature":-31.99}},{"startTime":"2022-02-06T07:00:00Z","values":{"temperature":-31.49}},{"startTime":"2022-02-06T08:00:00Z","values":{"temperature":-31.07}},{"startTime":"2022-02-06T09:00:00Z","values":{"temperature":-30.69}},{"startTime":"2022-02-06T10:00:00Z","values":{"temperature":-29.77}},{"startTime":"2022-02-06T11:00:00Z","values":{"temperature":-30.31}},{"startTime":"2022-02-06T12:00:00Z","values":{"temperature":-29.8}},{"startTime":"2022-02-06T13:00:00Z","values":{"temperature":-30.28}},{"startTime":"2022-02-06T14:00:00Z","values":{"temperature":-30.43}},{"startTime":"2022-02-06T15:00:00Z","values":{"temperature":-30.95}},{"startTime":"2022-02-06T16:00:00Z","values":{"temperature":-31.67}},{"startTime":"2022-02-06T17:00:00Z","values":{"temperature":-32.39}},{"startTime":"2022-02-06T18:00:00Z","values":{"temperature":-33.31}},{"startTime":"2022-02-06T19:00:00Z","values":{"temperature":-33.93}},{"startTime":"2022-02-06T20:00:00Z","values":{"temperature":-34.52}},{"startTime":"2022-02-06T21:00:00Z","values":{"temperature":-35.06}},{"startTime":"2022-02-06T22:00:00Z","values":{"temperature":-35.56}},{"startTime":"2022-02-06T23:00:00Z","values":{"temperature":-36.12}},{"startTime":"2022-02-07T00:00:00Z","values":{"temperature":-36.58}},{"startTime":"2022-02-07T01:00:00Z","values":{"temperature":-36.78}},{"startTime":"2022-02-07T02:00:00Z","values":{"temperature":-36.54}},{"startTime":"2022-02-07T03:00:00Z","values":{"temperature":-35.75}},{"startTime":"2022-02-07T04:00:00Z","values":{"temperature":-34.62}},{"startTime":"2022-02-07T05:00:00Z","values":{"temperature":-33.36}},{"startTime":"2022-02-07T06:00:00Z","values":{"temperature":-32.1}},{"startTime":"2022-02-07T07:00:00Z","values":{"temperature":-30.85}},{"startTime":"2022-02-07T08:00:00Z","values":{"temperature":-29.87}},{"startTime":"2022-02-07T09:00:00Z","values":{"temperature":-29.09}},{"startTime":"2022-02-07T10:00:00Z","values":{"temperature":-28.48}},{"startTime":"2022-02-07T11:00:00Z","values":{"temperature":-28.05}},{"startTime":"2022-02-07T12:00:00Z","values":{"temperature":-27.88}},{"startTime":"2022-02-07T13:00:00Z","values":{"temperature":-27.89}},{"startTime":"2022-02-07T14:00:00Z","values":{"temperature":-28.45}},{"startTime":"2022-02-07T15:00:00Z","values":{"temperature":-29.73}},{"startTime":"2022-02-07T16:00:00Z","values":{"temperature":-31.49}},{"startTime":"2022-02-07T17:00:00Z","values":{"temperature":-33.28}},{"startTime":"2022-02-07T18:00:00Z","values":{"temperature":-35.09}},{"startTime":"2022-02-07T19:00:00Z","values":{"temperature":-36.65}},{"startTime":"2022-02-07T20:00:00Z","values":{"temperature":-37.9}},{"startTime":"2022-02-07T21:00:00Z","values":{"temperature":-38.7}},{"startTime":"2022-02-07T22:00:00Z","values":{"temperature":-39.02}},{"startTime":"2022-02-07T23:00:00Z","values":{"temperature":-39.33}},{"startTime":"2022-02-08T00:00:00Z","values":{"temperature":-39.46}},{"startTime":"2022-02-08T01:00:00Z","values":{"temperature":-39.01}},{"startTime":"2022-02-08T02:00:00Z","values":{"temperature":-38.22}},{"startTime":"2022-02-08T03:00:00Z","values":{"temperature":-36.99}},{"startTime":"2022-02-08T04:00:00Z","values":{"temperature":-35.46}},{"startTime":"2022-02-08T05:00:00Z","values":{"temperature":-33.79}},{"startTime":"2022-02-08T06:00:00Z","values":{"temperature":-32.08}},{"startTime":"2022-02-08T07:00:00Z","values":{"temperature":-30.5}},{"startTime":"2022-02-08T08:00:00Z","values":{"temperature":-29.27}},{"startTime":"2022-02-08T09:00:00Z","values":{"temperature":-28.14}},{"startTime":"2022-02-08T10:00:00Z","values":{"temperature":-27.32}},{"startTime":"2022-02-08T11:00:00Z","values":{"temperature":-26.79}},{"startTime":"2022-02-08T12:00:00Z","values":{"temperature":-26.52}},{"startTime":"2022-02-08T13:00:00Z","values":{"temperature":-26.55}}]}]}}
 
Im so sorry for that bad english but i hope you unterstand my problem 
and thank you for any help.

**Comment by bblanchon** [comment]
Hi @dabbeknik,

I don't see any print statements in your program.
How do you print the values?

Best regards,
Benoit
