### ISSUE TITLE
How to filter for first xx packages in array?

### ISSUE THREAD

**Issue by Klimbim1** [bblanchon/ArduinoJson#1709]
Hi all,

I receive the following "structure" from a JSON from my weatherstation:

forecast{2} 
    daily[10]
    hourly[241]

The hourly arrays are 241 forecast packages big. If I want to deserialize everything, I would need 98304 bytes and I am running out of memory on a lolin d32 pro board. However if I would filter the biggest amount that I could filter is the data I need which is the forecast data on hourly basis. I only need the first 24 (out of 241) packages, is there a way to filter only the first 24 packages?

Thanks a lot, Regards
Klimbim

**Comment by bblanchon** [comment]
Hi @Klimbim1,

Unfortunately, the filtering feature introduced in [ArduinoJson 6.15](https://arduinojson.org/news/2020/03/22/version-6-15-0/) cannot limit the number of elements in an array.
As a workaround, I suggest that you look at the "deserialize in chunks" technique presented in [How to deserialize a very large document?](https://arduinojson.org/v6/how-to/deserialize-a-very-large-document/).

Several persons ask to extend the filtering feature to limit the number of elements in an array.
Whatever change we introduce must allow the following scenarios:

* keep all of the elements of the array (current behavior)
* keep one element (#1316, #1478)
* keep the n first elements (#1598, #1709)
* keep the n last elements
* keep several elements at random locations?

Unfortunately, no one could find an elegant syntax that would cover every case without doubling the size of the library, so we only have the "deserialization in chunk" technique for now.

Best regards,
Benoit
