### ISSUE TITLE
I want to assign the JSON of the inverse sequence to a new type, similar to string

### ISSUE THREAD

**Issue by 925486270** [bblanchon/ArduinoJson#1722]
![image](https://user-images.githubusercontent.com/66285269/156588591-d78acfc9-17a3-45ea-be70-de745e7338a9.png)

This Help is 404

**Comment by 925486270** [comment]
![image](https://user-images.githubusercontent.com/66285269/156589057-c15446d3-f550-4d97-a59e-7bbdfe6e8db2.png)

**Comment by bblanchon** [comment]
Hi @925486270,

Thanks for reporting this issue.
I added the page; please let me know what you think.

BTW, why would you use ArduinoJson with a `QString` when Qt already supports JSON?

Best regards,
Benoit

**Comment by 925486270** [comment]
Thanks you ,I forget it
