### ISSUE TITLE
Convert JSON document into byte array

### ISSUE THREAD

**Issue by QuinetArnaud** [bblanchon/ArduinoJson#1733]
Hello everybody,

I'm a student in last year of bachelor and i'm trying to exchange information between an Arduino Mega and a Raspberry pi 4 using Xbee in API mode.

I want to send a JSON document but this won't be possible with the Xbee in APi mode. I have seen on this forum that it was possible to convert my json document into string but it seemed outdated. 

In that forum (#issue 485), there was a function called:

 `JsonObject& root  = jsonBuffer.createObject();`

My Arduino compiler told me that i have to use createNestedObject()

Does this convert all of my json document into a String with the number of bytes returned ?

I want to thank you in advance for your response and your work.

**Comment by bblanchon** [comment]
Hi @Jetiou1312,

Please look at the example [JsonGeneratorExample.ino](https://arduinojson.org/v6/example/generator/) and read the [serialization tutorial](https://arduinojson.org/v6/doc/serialization/).

Best regards,
Benoit
