### ISSUE TITLE
Getting size of jsonarray question

### ISSUE THREAD

**Issue by plomba97** [bblanchon/ArduinoJson#174]
Hi, i would like to know if theres a way to get the size of an array:
For array: [] - size 0,
for array: 
[
  {
    "timing": "11:19:21,11:35:16,11:52:11",
    "routeId": 3,
    "type": 2,
    "lineId": 1,
    "lineName": "4"
  },
  {
    "timing": "11:22:18,11:27:04,11:38:32",
    "routeId": 13,
    "type": 2,
    "lineId": 9,
    "lineName": "2"
  }
] - size 2 and so on.
Thank you

**Comment by bblanchon** [comment]
Please try `JsonArray::size()`
