### ISSUE TITLE
DeserializationError::Ok even if input is not a JSON, but just an integer

### ISSUE THREAD

**Issue by ishdemon** [bblanchon/ArduinoJson#1741]
Input is an integer 7, and still it says DeserializationError: OK. How to throw error or handle if its not JSON. Shouldn't it say InvalidInput or something??
Environment: ESP32/ PlatformIO

**Comment by bblanchon** [comment]
Hi @ishdemon,

As I explained in https://github.com/bblanchon/ArduinoJson/issues/1575#issuecomment-850786675:

> A number is a valid JSON document.
> You can do the same in your web browser:
>
> ```
> JSON.parse('7')
> < 7
> ```

The [ArduinoJson Troubleshooter](https://arduinojson.org/v6/troubleshooter/#runtime/deserialization/ok/invalid) seems to agree with me when he says:

> You know, a JSON document doesn’t need to start with a { or a [; the following strings are also valid JSON documents:
> 
> * `0`
> * `1`
> * `-9`
> * `1.234e-34`
> * `true`
> * `false`
> * `null`

If you want to verify that the JSON document is an object, simply call [JsonDocument::is<JsonObject>()](https://arduinojson.org/v6/api/jsondocument/is/).

Best regards,
Benoit

**Comment by ishdemon** [comment]
Thanks. Was not aware of this.. Tried looking closed issues but couldn't find. 
```
if (doc.is<int>()) {
  int value = doc.as<int>();
  ...
}
```
Closing this. Thanks again🙏👍

**Comment by bblanchon** [comment]
You're welcome, @ishdemon!
Thank you for using ArduinoJson.
Don't forget to [cast a star](https://github.com/bblanchon/ArduinoJson/stargazers) to support the project :wink:
