### ISSUE TITLE
parse struct to jsnon

### ISSUE THREAD

**Issue by rozrabiak** [bblanchon/ArduinoJson#1742]
**Description**
How can parse below struct to json using Arduino Jsnon library? At output I need char[].

typedef struct packed_szklarnia
{
  bool glebaMierzWilgoc = false;
  bool glebaCzujnikiWilg[4] = {false, false, false, false};
  unsigned long glebaInterOdczytWilg = 10000;
  bool glebaTemp = false;
};

**Troubleshooter's report**
1. The issue happens at compile time
2. The error is not in the list

**Environment**
* Microcontroller: any arduino compatible
* Core/Framework: Arduino 1.8.19, Platformio

**Comment by bblanchon** [comment]
Hi @rozrabiak,

Please refer to the following resources:

* [Can I automatically serialize an object?<br>How to convert a struct to a JSON object?](https://arduinojson.org/v6/faq/automatically-serialize-an-object/)
* [JsonConfigFile.ino](https://arduinojson.org/v6/example/config/)
* [Serialization tutorial](https://arduinojson.org/v6/doc/serialization/)
* [Deserialization tutorial](https://arduinojson.org/v6/doc/deserialization/)

Best regards,
Benoit
