### ISSUE TITLE
Every second Serial.println puts out false JSON-value

### ISSUE THREAD

**Issue by basementmedia2** [bblanchon/ArduinoJson#1744]
Hi again,

i have the following sketch, which checks every few hours, if a new firmware-file is available:

```c++
void check_firmware_version() {
  HTTPClient http; 
  if (http.begin(firmware_update_url)) {
    int httpCode = http.GET();
    if (httpCode == 200) {
      StaticJsonDocument<1500> doc;
      DeserializationError error = deserializeJson(doc, http.getStream());
      if (error) {
        Serial.print("deserializeJson() failed: ");
        Serial.println(error.c_str());
        //return;
      } else {
        latest_firmware_version = doc["version"]; 
        if (latest_firmware_version > (float)FIRMWARE_VERSION) {
          Serial.println("New firmware available!");
        }

        strcpy(latest_firmware_datum, doc["datum"]);
        strcpy(latest_firmware_link, doc["file"]);
        strcpy(latest_firmware_message, doc["message"]);
        Serial.println("Version:" + (String)latest_firmware_version);
        Serial.println("Datum:" + (String)latest_firmware_datum);
        Serial.println("File:" + (String)latest_firmware_link);
      }
      
    }
    http.end();
  }
}
```

this is the JSON

```json
{
        "version": 0.82,
        "datum": "2022-04-10",
        "file": "http://mywebsite.de/firmwares/2022_1/myfirmwarefile.bin",
        "message": "Optional Firmware-Message"
}
```

When i run the Sketch i get a false firmware file output in Serial-Monitor every second call:

```
Version:0.82
Datum:2022-04-10
File:http://mywebsite.de/firmwar
s/2
Version:0.82
Datum:2022-04-10
File:http://mywebsite.de/firmwares/2022_1/myfirmwarefile.bin
Version:0.82
Datum:2022-04-10
File:http://mywebsite.de/firmwar
s/2
Version:0.82
Datum:2022-04-10
File:http://mywebsite.de/firmwares/2022_1/myfirmwarefile.bin
```

Do you have an idea, why the Serial-Output is wrong every second time?

**Comment by bblanchon** [comment]
Hi Daniel,

This may come from [chunked transfer encoding](https://en.wikipedia.org/wiki/Chunked_transfer_encoding).
Please try to call `http.useHTTP10(true);` before `http.GET()`.
Let me know if this works so I can add this scenario in the [Troubleshooter](https://arduinojson.org/v6/how-to/use-arduinojson-with-httpclient/).

See also:

* [How to use ArduinoJson with HTTPClient?](https://arduinojson.org/v6/how-to/use-arduinojson-with-httpclient/)

Best regards,
Benoit

**Comment by basementmedia2** [comment]
Hi,

works good now, thank you!

**Comment by bblanchon** [comment]
You're welcome, Daniel!
Thank you for using ArduinoJson.
Don't forget to [cast a star](https://github.com/bblanchon/ArduinoJson/stargazers) to support the project :wink:
