### ISSUE TITLE
Fast Arduino JSON Data Logging & Parallel Processing  

### ISSUE THREAD

**Issue by rt2gb** [bblanchon/ArduinoJson#1747]
**Application**  
I am using ESP32 Wroom for ADC data logging project. I need some suggestion regarding parallel computing and resource management. I am storing 3 channel ADC data to SD card in JSON format. Periodically based on timer I need to upload the SD card JSON file to the Firebase Firestore location. Currently I can do all this in sequential or series process on one core. I am measuring in a batch of 100 where 100 x3 Channels values are captured and stored in global variable. This values passed to a sequential task where it is serialized and stored on to the SD card. I am consuming **38ms** processing time in order to write the data captured to the SD card instead of parallely capturing more data samples. Each ADC value is of double type variable. My sampling frequency is 1000 samples per second which is 1 sample taken every 1ms which means in order to capture 100 samples across 3 channels (100 x 3 x 8 bytes = 2400 bytes). I am taking 100ms measuring time window and for each 100 samples I am wasting 38 ms time is wasted in storing the data to SD card which is bad in my application. 

Once timer is over I need to parallely upload the data to Firebase Firestore location.

I am using JSONL format like how you have suggested to faster append the JSON file and  I am also using 'WriteBufferingStream' (allocated 8192 bytes for buffer) and Dynamic memory (also 8192 bytes) but now I realize I really need to take advantage of second core of ESP32 for my application. It takes about a 2 minutes to upload 8-10MB JSON file to Firebase Storage which also a lot of time.

**Question**
1) Is there a way in Arduino JSON library to support parallel processing for ESP32 if I want to run SD append on core 0. My Core 1 needs to send either 2400 bytes of data all at once or 24 bytes after every sample measurement. I don't know how I can do that without creating a FIFO buffer. Can you guide me to some examples of FIFO buffer using ArduinoJSON library
2) Can I also do similar where in third task I upload the data read from SD card to Firebase parallely. How do I manage flags or status to notify the other task that the data is either ready to fetch or upload. What is the best method you would suggest for my application.
  

**Environment**  
Here is the environment that I'm using':
* Microconroller: ESP32 Wroom 32E
* Core/runtime: ESP32 core for Arduino v3.1
* IDE: Arduino 1.8.19

**Comment by bblanchon** [comment]
Hi @rt2gb,

I'm sorry, but I don't know how to do that.
I can just tell you that ArduinoJson offers no guarantee when the same `JsonDocument` is accessed by multiple threads.
If I were you, I'd use a concurrent queue and move the `JsonDocument` declaration in the consumer thread.

Best regards,
Benoit
