### ISSUE TITLE
ArduinoJson Assistant

### ISSUE THREAD

**Issue by nodoubtman** [bblanchon/ArduinoJson#1748]
Good evening from Canada.
 ArduinoJson Assistant with filter used to work, now it's returning NULL even with the examples.

Can you fix it?
Thanks.
Marc.

**Comment by bblanchon** [comment]
Hi Marc,

Thank you very much for reporting this problem.

Can you tell me which browser version you're using?
You can use [whatsmybrowser.org](https://www.whatsmybrowser.org/) to check.

Best regards,
Benoit

**Comment by nodoubtman** [comment]
Firefox Benoit.

**Comment by bblanchon** [comment]
Which version?

**Comment by bblanchon** [comment]
Nevermind. I have the problem too; I didn't realize it was only for the "Deserialize and filter" mode.

**Comment by bblanchon** [comment]
Fixed!
