### ISSUE TITLE
error: 'ArduinoJson6194_F1::JsonDocument::JsonDocument(const ArduinoJson6194_F1::JsonDocument&)' is private within this context      GetValue(password, "password", doc);

### ISSUE THREAD

**Issue by burner-** [bblanchon/ArduinoJson#1751]
**Description**
I assume that I can give JsonDocument as function parameter

**Troubleshooter's report**
1. The issue happens at compile time
2. The error is not in the list

**Environment**
* Microcontroller: ESP32
* Core/Framework: ESPressif Systems 2.0.2
* IDE: Arduino IDE 1.8.16

**Reproduction code**
```c++
bool GetValue(String& value, String key, JsonDocument doc) {
    if (doc.containsKey(key)) {
        String tmp = doc[key];
        value = tmp;
        Serial.println(key + " : " + tmp);
        return true;
    } else
        return false;
}

bool loadWifiConfig() {
    File configFile = SPIFFS.open("/wifi.json", "r");
    if (!configFile) {
        Serial.println("Failed to open wifi config file");
        return false;
    }
    size_t size = configFile.size();
    if (size > 1024) {
        Serial.println("Wifi config file size is too large");
        return false;
    }
    // Allocate a buffer to store contents of the file.
    std::unique_ptr<char[]> buf(new char[size]);
    configFile.readBytes(buf.get(), size);

    StaticJsonDocument<256> doc;
    auto error = deserializeJson(doc, buf.get());
    if (error) {
        Serial.println("Failed to parse wifi config file");
        return false;
    }

    GetValue(ssid, "ssid", doc); // < KABOOM This blow up
    GetValue(password, "password", doc);

    return true;
}
```

**Remarks**

And looks that his had have same issue https://github.com/bblanchon/ArduinoJson/issues/1289

**Comment by bblanchon** [comment]
Hi @burner-,

[`JsonDocument`](https://arduinojson.org/v6/api/jsondocument/) doesn't support copying.

If you need to pass a [`JsonDocument`](https://arduinojson.org/v6/api/jsondocument/) to a function, you can use a reference, like so:

```c++
void myFunction(JsonDocument& doc);
// or
void myFunction(const JsonDocument& doc);
```

You can even make this function more reusable by allowing it to support any part of a JSON document, like so:

```c++
void myFunction(JsonVariant var);
// or
void myFunction(JsonVariantConst var);
```

If you must make a copy, use either [`DynamicJsonDocument`](https://arduinojson.org/v6/api/dynamicjsondocument/) or [`StaticJsonDocument`](https://arduinojson.org/v6/api/staticjsondocument/).

Best regards,
Benoit
