### ISSUE TITLE
serializeJson?

### ISSUE THREAD

**Issue by whes1015** [bblanchon/ArduinoJson#1752]
After serializeJson, do I need to free memory? I have an infinitely increasing string (+=), after serializeJson I make the string (=""), it can keep running normally at first, the result after serializeJson after a while string becomes null

**Comment by whes1015** [comment]
```c
DynamicJsonDocument json(8192);
char json_string[8192];
serializeJson(json, json_string);
```

**Comment by bblanchon** [comment]
Hi @whes1015,

This sounds like a [fragmentation issue](https://cpp4arduino.com/2018/11/06/what-is-heap-fragmentation.html), but you didn't provide enough information.
Please follow one of the issue templates: https://github.com/bblanchon/ArduinoJson/issues/new/choose

Best regards,
Benoit
