### ISSUE TITLE
Memory leak in serializeJson ?

### ISSUE THREAD

**Issue by guestisp** [bblanchon/ArduinoJson#1754]
I think i've found a strange memory leak.
I'm calling `serializeJson` from inside a freertos task that is called from a class.
Every time I spawn the task, i loose near 200bytes of memory

Commnentig the lines:
```
        String jsonResponse;
        serializeJson(docResponse, jsonResponse);
```

in the task code, leaks stop.
So I hink there is something not working as expected here. Any idea ? I've tought that after destroying the task,a garbace collector would start, but that's not the case.

**Comment by bblanchon** [comment]
Hi @guestisp,

`serializeJson()` doesn't allocate any memory in the heap, so it cannot leak.

I don't have enough information to help you further.
Could you provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)?

Best regards,
Benoit

**Comment by guestisp** [comment]
I think i've solved by enclosing the arduinojson calls in `{` and `}`
