### ISSUE TITLE
Abstract ArduinoJson

### ISSUE THREAD

**Issue by guestisp** [bblanchon/ArduinoJson#1761]
Hi @bblanchon 
in my code I have A LOT of calls to ArduinoJson almost identical. It's a json-rpc server so I need to parse a json-rpc request do things and create a new json-rpc response to use as reply.

99% of the code is always the same, what changes is the nested object of response, if `error` or `result`

I've thought to create a class called `JSONRPC` with the constructor initializing and automatically parsing the json string (passed as constructor argument), setting some class property:

```
class JSONRPC
{
    public:
        String jsonrpc;
        String requestId;
        String method;

        JsonObject params;
        JsonObject result;
        JsonObject error;

        DynamicJsonDocument jsonObj;
        JSONRPC(String json);

        String errorResponse();
        String successResponse();
        String notificationResponse();
};
```

Don't know if it's the best way to do, but I would like to call that like this (more or less):

```
String jsonRequest = "..................";
JSONRPC jsonrpc(jsonRequest);
jsonrpc.result["key"] = "value";
String jsonResponse = jsonrpc.successResponse();
```

but i'm having some difficulties in switching between a success response, an error response or a notification one.

Any idea ? I've also thought to "rename" the `result` nested object to `result` in case of success or to `error` in case of failure but I didn't find anything useful in docs.

Main goal is to abstract as much as possible, leaving the JSONRPC calls the same for all kind of responses.
Also tried to init both `results` and `error`   as nested object, then `successResponse` or `errorResponse` remove the unneded object, do a `garbageCollector` and serialize the output, but obviously the compiler is saying that `error` (or `result`) variable is set but not used. I don't want to disable this warning.

**Comment by bblanchon** [comment]
Hi @guestisp,

In the last chapter of Mastering ArduinoJson, I present a minimalist JSONRPC framework designed to support low-end microcontrollers.
The concept is similar to what you suggest, except it uses three classes (request, response, and client) instead of one.
I'll probably update this code after the release of 6.20, so it leverages the new [link()](https://arduinojson.org/v6/api/jsonvariant/link/) function.

Best regards,
Benoit

**Comment by guestisp** [comment]
Do you have an ETA for the 6.20 ? 

Any pseudocode that you used with 3 classes ? Because with multiple classes is "easy" , even right now i'm able to use 3 different object and is what i'm doing: deserialize request, create a new empty document, add values (some took from the request itself) then serialize to string.

But is exactly what I would like to avoid, as 90% of the json is the same, every time and doing every time the same deserialization, object creation, object fill with "static" data just to add 1 or 2 fields for the response is repetitive.

In example, If I need to reply to a json-rpc request asking for a sum , it's one line "result" field and 15 lines of noise:

```
DynamicJsonDocument docRequest(2048);
deserializeJson(docRequest, jsonRequest);
String jsonrpc = docRequest["jsonrpc"];
String method = docRequest["method"];
String requestId = docRequest["id"];

int number1 = docRequest["params"]["number1"];
int number2 = docRequest["params"]["number2"];

DynamicJsonDocument docResponse(2048);
docResponse["jsonrpc"] = jsonrpc;
docResponse["id"] = requestId;
docResponse["result"] = number1 + number2;

String jsonResponse;
serializeJson(docResponse, jsonResponse);
```

if I need to do something similiar but with a different json-rpc , i have to replicate the 15 lines but change just the 1.

I'm sure there is a much better way than copy around all of this.

**Comment by bblanchon** [comment]
I don't have any ETA for 6.20, but the `link()` function is available on the main branch.

**Comment by guestisp** [comment]
how would  you use the `link()` function ?

**Comment by bblanchon** [comment]
I sent you a link to the documentation in my first message.
Here it is again: https://arduinojson.org/v6/api/jsonvariant/link/

**Comment by guestisp** [comment]
Sorry, didn't see the link.
