### ISSUE TITLE
Question about Uninitialized '_data' member variable in JsonDocument.

### ISSUE THREAD

**Issue by johnttaylor** [bblanchon/ArduinoJson#1763]
All of the constructors for the JsonDocument() class make a call to _data.setNull() to presumably initialize the '_data'  member variable.  The VariantData::setNull() method calls the VariantData::setType() method.  However, the setType() method performs read/modify operations on its '_flags' member variable.  From what I can tell - the state of the 'OWNED_KEY_BIT' (0x80) in the JsonDocument::_data._flags variable is indeterminate when an instance of JsonDocument is created, i.e. it could be either a '1' or '0' .  

I don't understand the code well enough to know if the 'OWNED_KEY_BIT' field in a JsonDocument::_data._flags variable is a don't care or potentially an error.  Can you please clarify the usage of the  'OWNED_KEY_BIT' in the context of a JsonDocument instance?

**Comment by bblanchon** [comment]
Hi @johnttaylor,

`OWNED_KEY_BIT` is irrelevant in the context of a `JsonDocument`, since it cannot be attached to a key.

Why do you ask?

Best regards,
Benoit

**Comment by johnttaylor** [comment]
Thank you for your reply. I suspected that was the case, but I wasn't sure.

My company is using JsonArduino in an embedded medical device and our
static analysizer flag the uninitialized _data variable as an issue (which
I can now mark as a false positive with your feedback.

As a side note - I am big fan of your library because it is full featured
Json library where it is extremely easy to use with static memory
allocation paradigm, i.e. not just for Arduinos but any platform where
dynamic memory allocation is a bad thing.

-john

**Comment by bblanchon** [comment]
> with static memory allocation paradigm [...] where dynamic memory allocation is a bad thing

I'm glad to read your feedback.
So many people complained about the fixed capacity, I've considered removing `StaticJsonDocument` in v7.
If only I could keep `StaticJsonDocument` and make `DynamicJsonDocument` elastic without virtual calls...
Well, I'll see when the time comes; right now, there are still many improvements I want to make in v6.

Do you think your company would be interested in sponsoring ArduinoJson?
