### ISSUE TITLE
Fake - nomem error 

### ISSUE THREAD

**Issue by RTPivot** [bblanchon/ArduinoJson#1764]
HI 
I am getting a fake nomem error . 
This makes error trapping difficult 
Platform teensy4.1  
Arduino version 18.19 

********
// ArduinoJson - https://arduinojson.org
// Copyright © 2014-2022, Benoit BLANCHON
// MIT License
//
// This example shows how to store your project configuration in a file.
// It uses the SD library but can be easily modified for any other file-system.
//
// The file contains a JSON document with the following content:
// {
//   "hostname": "examples.com",
//   "port": 2731
// }
//
// To run this program, you need an SD card connected to the SPI bus as follows:
// * MOSI <-> pin 11
// * MISO <-> pin 12
// * CLK  <-> pin 13
// * CS   <-> pin 4
//
// https://arduinojson.org/v6/example/config/
#include "Arduino.h"
#include <ArduinoJson.h>
#include <SD.h>

// Our configuration structure.
//
// Never use a JsonDocument to store the configuration!
// A JsonDocument is *not* a permanent storage; it's only a temporary storage
// used during the serialization phase. See:
// https://arduinojson.org/v6/faq/why-must-i-create-a-separate-config-object/
struct Config {
  char hostname[64];
  int port;
};
const int chipSelect = BUILTIN_SDCARD;
const char *filename = "/config/Settings.jsn";  // <- SD library uses 8.3 filenames
Config config;                         // <- global configuration object

struct BConfig {   

  int NO_OF_Cells = 16   ;        
  int Max_CHARGE_V = 56 ; 
  int Max_CHARGE_I  = 50 ;
  int Max_DIS_V = 46  ; 
  int Max_DIS_I  = 100 ; 
  int Max_TIME_DIS_I_s = 2 ; 
  int Max_TIME_CHARGE_I_s  = 2 ; 
  int Max_TIME_DIS_V_s  = 2 ; 
  int Max_TIME_CHARGE_V_s = 2  ; 
  int Max_Cell_V  = 3600 ; 
  int Min_Cell_V  = 2800  ; 
  int Max_Terminal_T = 60; 
  int Max_Cell_T  = 60 ; 
  int Min_Terminal_T = 60; 
  int Min_Cell_T  = 60 ; 
  int Cutt_off_DISCH_I  = 115 ; 
  int Cutt_off_DISCH_V  = 44 ; 
  int Cutt_off_DISCH_CELL_mV  = 2500 ; 
  int Cutt_off_CHRG_CELL_mV  =  3670 ; 
  bool DISABLE_CHRG =  0 ; 
  bool DISABLE_DISCHRG =  0 ; 
  bool USE_CAN_BUS = 0 ; 
  int CAN_BUS_PROTOCOL = 0 ; // 1 = Victron , 
  bool FORCE_CHARGE_ON = 0 ;  // force charging on for 5 min ;
}   ; 

BConfig GBL_Bat_Settings  ;

// Loads the configuration from a file
bool loadConfiguration(const char *filename, BConfig &GBL_Bat_Settings) {
  // Open file for reading
  File file = SD.open(filename);

  // Allocate a temporary JsonDocument
  // Don't forget to change the capacity to match your requirements.
  // Use https://arduinojson.org/v6/assistant to compute the capacity.
  StaticJsonDocument<512> doc;

  // Deserialize the JSON document
  DeserializationError error = deserializeJson(doc, file);
  if (error){
    Serial.println(F("Failed to read file, using default confnnnnnnnnnnnnnnniguration"));
     Serial.println(error.c_str()) ; 
    Serial.println("error") ; }
  // Copy values from the JsonDocument to the Config

   Serial.println(F("loading local struct and into memory "));
  GBL_Bat_Settings.NO_OF_Cells    =  doc["NO_OF_Cells"]  ;
  GBL_Bat_Settings.NO_OF_Cells  = GBL_Bat_Settings.NO_OF_Cells  +1 ; 
  GBL_Bat_Settings.Max_CHARGE_V     = doc["Max_CHARGE_V"]  ; 
  GBL_Bat_Settings.Max_CHARGE_I     = doc["Max_CHARGE_I"]  ;
  GBL_Bat_Settings.Max_DIS_V      = doc["Max_DIS_V"]  ; 
  GBL_Bat_Settings.Max_DIS_I      = doc["Max_DIS_I"]  ; 
  GBL_Bat_Settings.Max_TIME_DIS_I_s = doc["Max_TIME_DIS_I_s"]  ; 
  GBL_Bat_Settings.Max_TIME_CHARGE_I_s    = doc["Max_TIME_CHARGE_I_s"]  ; 
  GBL_Bat_Settings.Max_TIME_DIS_V_s  = doc["Max_TIME_DIS_V_s"]  ; 
  GBL_Bat_Settings.Max_TIME_CHARGE_V_s    = doc["Max_TIME_CHARGE_V_s"]  ; 
  GBL_Bat_Settings.Max_Cell_V    = doc["Max_Cell_V"]  ; 
  GBL_Bat_Settings.Min_Cell_V     = doc["Min_Cell_V"]  ; 
  GBL_Bat_Settings.Max_Terminal_T   = doc["Max_Terminal_T"]  ; 
  GBL_Bat_Settings.Max_Cell_T     = doc["Max_Cell_T"]  ; 
  GBL_Bat_Settings.Min_Terminal_T   = doc["Min_Terminal_T"]  ; 
  GBL_Bat_Settings.Min_Cell_T     = doc["Min_Cell_T"]  ; 
  GBL_Bat_Settings.Cutt_off_DISCH_I    = doc["Cutt_off_DISCH_I"]  ; 
  GBL_Bat_Settings.Cutt_off_DISCH_V     = doc["Cutt_off_DISCH_V"]  ; 
  GBL_Bat_Settings.Cutt_off_DISCH_CELL_mV    = doc["Cutt_off_DISCH_CELL_mV"]  ; 
  GBL_Bat_Settings.Cutt_off_CHRG_CELL_mV    = doc["Cutt_off_CHRG_CELL_mV"]  ; 
  GBL_Bat_Settings.DISABLE_CHRG    = doc["DISABLE_CHRG"]  ; 
  GBL_Bat_Settings.DISABLE_DISCHRG   = doc["DISABLE_DISCHRG"]  ; 
  GBL_Bat_Settings.USE_CAN_BUS   = doc["USE_CAN_BUS"]  ; 
  GBL_Bat_Settings.CAN_BUS_PROTOCOL    = doc["CAN_BUS_PROTOCOL"]  ; // 1 = Victron , 
  GBL_Bat_Settings.FORCE_CHARGE_ON   = doc["FORCE_CHARGE_ON"]  ; 
Serial.println("here5") ;
Serial.println(String(GBL_Bat_Settings.NO_OF_Cells)) ;

Serial.println(String(GBL_Bat_Settings.FORCE_CHARGE_ON)) ;
 Serial.println("here6") ;
  
  /*
  config.port = doc["port"] | 2731;
  strlcpy(config.hostname,                  // <- destination
          doc["hostname"] | "example.com",  // <- source
          sizeof(config.hostname));         // <- destination's capacity
*/
  // Close the file (Curiously, File's destructor doesn't close the file)
  file.close();
  return 1 ;
}

// Saves the configuration to a file
void saveConfiguration(const char *filename, const BConfig &GBL_Bat_Settings) {
  // Delete existing file, otherwise the configuration is appended to the file
  SD.remove(filename);

  // Open file for writing
  File file = SD.open(filename, FILE_WRITE);
  if (!file) {
    Serial.println(F("Failed to create file"));
    return;
  }

  // Allocate a temporary JsonDocument
  // Don't forget to change the capacity to match your requirements.
  // Use https://arduinojson.org/assistant to compute the capacity.
  StaticJsonDocument<256> doc;

  // Set the values in the document
  doc["hostname"] = config.hostname;
  doc["port"] = config.port;

  // Serialize JSON to file
  if (serializeJson(doc, file) == 0) {
    Serial.println(F("Failed to write to file"));
  }

  // Close the file
  file.close();
}

// Prints the content of a file to the Serial
void printFile(const char *filename) {
  // Open file for reading
  File file = SD.open(filename);
  if (!file) {
    Serial.println(F("Failed to read file"));
    return;
  }

  // Extract each characters by one by one
  while (file.available()) {
    Serial.print((char)file.read());
  }
  Serial.println();

  // Close the file
  file.close();
}

bool Load_SettingsFrom_SD(const char *filename, BConfig &GBL_Bat_Settings ) {
 bool ret = false;
  Serial.println("here1") ; 
  // Open file for reading
 while (!SD.begin(chipSelect)) {
    Serial.println(F("Failed to initialize SD fasfasfasassf"));
    delay(1000);
  }
  
  File file1 = SD.open(filename);
  Serial.println("file>" + String(filename))  ;
//if (!file  ) {

  // Allocate a temporary JsonDocument
  // Don't forget to change the capacity to match your requirements.
  // Use arduinojson.org/v6/assistant to compute the capacity.
  StaticJsonDocument<512> doc;
  Serial.println("here2") ; 
  // Deserialize the JSON document
  DeserializationError error = deserializeJson(doc, file1);
  Serial.println("here3") ; 
  if (error){
    Serial.println(error.c_str()) ; 
    Serial.println("error") ; 
    
    Serial.println(F("Failed to read file, using default configuration"));
      ret = false ; 
    }
else {
    Serial.println(F("loading local struct and into memory "));
  GBL_Bat_Settings.NO_OF_Cells    =  doc["NO_OF_Cells"]  ;
  GBL_Bat_Settings.NO_OF_Cells  = GBL_Bat_Settings.NO_OF_Cells  +1 ; 
  GBL_Bat_Settings.Max_CHARGE_V     = doc["Max_CHARGE_V"]  ; 
  GBL_Bat_Settings.Max_CHARGE_I     = doc["Max_CHARGE_I"]  ;
  GBL_Bat_Settings.Max_DIS_V      = doc["Max_DIS_V"]  ; 
  GBL_Bat_Settings.Max_DIS_I      = doc["Max_DIS_I"]  ; 
  GBL_Bat_Settings.Max_TIME_DIS_I_s = doc["Max_TIME_DIS_I_s"]  ; 
  GBL_Bat_Settings.Max_TIME_CHARGE_I_s    = doc["Max_TIME_CHARGE_I_s"]  ; 
  GBL_Bat_Settings.Max_TIME_DIS_V_s  = doc["Max_TIME_DIS_V_s"]  ; 
  GBL_Bat_Settings.Max_TIME_CHARGE_V_s    = doc["Max_TIME_CHARGE_V_s"]  ; 
  GBL_Bat_Settings.Max_Cell_V    = doc["Max_Cell_V"]  ; 
  GBL_Bat_Settings.Min_Cell_V     = doc["Min_Cell_V"]  ; 
  GBL_Bat_Settings.Max_Terminal_T   = doc["Max_Terminal_T"]  ; 
  GBL_Bat_Settings.Max_Cell_T     = doc["Max_Cell_T"]  ; 
  GBL_Bat_Settings.Min_Terminal_T   = doc["Min_Terminal_T"]  ; 
  GBL_Bat_Settings.Min_Cell_T     = doc["Min_Cell_T"]  ; 
  GBL_Bat_Settings.Cutt_off_DISCH_I    = doc["Cutt_off_DISCH_I"]  ; 
  GBL_Bat_Settings.Cutt_off_DISCH_V     = doc["Cutt_off_DISCH_V"]  ; 
  GBL_Bat_Settings.Cutt_off_DISCH_CELL_mV    = doc["Cutt_off_DISCH_CELL_mV"]  ; 
  GBL_Bat_Settings.Cutt_off_CHRG_CELL_mV    = doc["Cutt_off_CHRG_CELL_mV"]  ; 
  GBL_Bat_Settings.DISABLE_CHRG    = doc["DISABLE_CHRG"]  ; 
  GBL_Bat_Settings.DISABLE_DISCHRG   = doc["DISABLE_DISCHRG"]  ; 
  GBL_Bat_Settings.USE_CAN_BUS   = doc["USE_CAN_BUS"]  ; 
  GBL_Bat_Settings.CAN_BUS_PROTOCOL    = doc["CAN_BUS_PROTOCOL"]  ; // 1 = Victron , 
  GBL_Bat_Settings.FORCE_CHARGE_ON   = doc["FORCE_CHARGE_ON"]  ; 
  ret = true ; 

Serial.println("here5") ;
Serial.println(String(GBL_Bat_Settings.NO_OF_Cells)) ;

Serial.println(String(GBL_Bat_Settings.FORCE_CHARGE_ON)) ;
 Serial.println("here6") ;
  
}

// first 60 adresses for Settings  
// write to memory from here 

  // EEPROM.update(address, val); 
 
 
  /*
  strlcpy(config.hostname,                  // <- destination
          doc["hostname"] | "example.com",  // <- source
          sizeof(config.hostname));         // <- destination's capacity
*/
  // Close the file (Curiously, File's destructor doesn't close the file)
  file1.close();
//}
  return ret;
}

void setup() {
  // Initialize serial port
  Serial.begin(9600);
  while (!Serial) continue;

  // Initialize SD library
  
  while (!SD.begin(chipSelect)) {
    Serial.println(F("Failed to initialize SD library"));
    delay(1000);
  }

  // Should load default config if run for the first time
  Serial.println(F("Loading configuration..."));
  //Load_SettingsFrom_SD(filename, GBL_Bat_Settings);

  // Create configuration file
  //Serial.println(F("Saving configuration..."));
  ///saveConfiguration(filename, config);

  // Dump config file
  Serial.println(F("Print config file..."));
  printFile(filename);
  delay(1000); 
  loadConfiguration(filename , GBL_Bat_Settings) ;  
}

 

void loop() {
  // not used in this example
}

******

serial output 

Loading configuration...
Print config file...
{"NO_OF_Cells":16,"Max_CHARGE_V":56,"Max_CHARGE_I":50,"Max_DIS_V":46,"Max_DIS_I":100,"Max_TIME_DIS_I_s":2,"Max_TIME_DIS_V_s":2,"Max_TIME_CHARGE_V_s":2,"Max_TIME_CHARGE_I_s":2,"Max_Cell_V":3600,"Min_Cell_V":2800,"Max_Terminal_T":60,"Max_Cell_T":60,"Min_Terminal_T":60,"Min_Cell_T":60,"Cutt_off_DISCH_I":115,"Cutt_off_DISCH_V":44,"Cutt_off_DISCH_CELL_mV":2500,"Cutt_off_CHRG_CELL_mV":3670,"DISABLE_CHRG":0,"DISABLE_DISCHRG":0,"USE_CAN_BUS":0,"CAN_BUS_PROTOCOL":0}
Failed to read file, using default confnnnnnnnnnnnnnnniguration

NoMemory   ????????? 

error 

but it still loads the json obect and we and assign the values to struct   very odd 
loading struct and into memory 
here5
17
0
here6

**Comment by bblanchon** [comment]
Hi @RTPivot,

One of the members is probably missing. Please check again.

Please provide a shorter reproduction code (50 lines max) if you still think this is a false positive.

Best regards,
Benoit
