### ISSUE TITLE
11.25 fatal error:ESP8266WIfi.h: no such a file or direectory

### ISSUE THREAD

**Issue by Techworls** [bblanchon/ArduinoJson#1771]
**Description**
11.25 fatal error:ESP8266WIfi.h: no such a file or 

**Troubleshooter's report**
1. The issue happens at compile time
2. The error is not in the list

**Environment**
* Microcontroller: Esp8266
* Core/Framework: Es

**Reproduction code**
```c++
11.25 fatal error:ESP8266WIfi.h: no such a file or directory 
```

**Comment by bblanchon** [comment]
Hi @Techworls,

This issue doesn't seem to be related to ArduinoJson.

Best regards,
Benoit
