### ISSUE TITLE
How to embed a JSON  as the other's value?

### ISSUE THREAD

**Issue by ghost** [bblanchon/ArduinoJson#1775]
**Describe the issue**  
As the title, Here is my JSON
```json
{
  "sensor": {
    "CH1": {
      "status": "sucess",
      "waterLevel": "0.37m"
    },
    "CH2": {
      "status": "sucess",
      "waterLevel": "0.57m"
    }
  }
}
```
And here is my code 

```c++
StaticJsonDocument<192> doc;

JsonObject sensor = doc.createNestedObject("sensor");

JsonObject sensor_CH1 = sensor.createNestedObject("CH1");
sensor_CH1["status"] = "sucess";
sensor_CH1["waterLevel"] = "0.37m";

JsonObject sensor_CH2 = sensor.createNestedObject("CH2");
sensor_CH2["status"] = "sucess";
sensor_CH2["waterLevel"] = "0.57m";

serializeJson(doc, output);
```
But want to define a char array like
`const char *arrary = "{\"status\":\"success\", \"waterLevel\":\"0.37m\"}"`

and 

`sensor[CH1] = array;`

but there always has " "  and   \" , how can I do?

the picture's two way are failed.
<img width="953" alt="image" src="https://user-images.githubusercontent.com/55439370/177769946-0d961a2e-bf18-440d-b882-2b7a7f993b35.png">

**Comment by bblanchon** [comment]
Hi @KiraVerSace,

Please try [serialized()](https://arduinojson.org/v6/api/misc/serialized/):

```c++
doc["CH1"] = serialized("{\"status\":\"success\", \"waterLevel\":\"0.37m\"}");
```

Best regards,
Benoit
