### ISSUE TITLE
Boolean as<const char*> returns empty string

### ISSUE THREAD

**Issue by monte-monte** [bblanchon/ArduinoJson#1776]
**Describe the bug**  
I receive a JSON string from a webpage via web server and then printing it to serial.  I'm not sure if it's a bug, but when converting values from ``bool`` to ``const char*`` the result is empty string. If converting to ``String`` the result is as expected ``false`` or ``true``.

**Environment**  
Here is the environment that I used:
* Microcontroller: ESP32
* Core/runtime:  5.0.0
* IDE: Platformio
* ArduinoJson version: 6.19.4

**Reproduction**  
Here is a small snippet that reproduces the issue.

Incomming JSON:
```
{"lamp_name":"Lamp","power_on":"save","on_button":true,"mqtt_enable":false}
```
```
JsonObject jsonObj = json.as<JsonObject>();
for (JsonPair kv : jsonObj) {
  Serial.print(kv.key().c_str());
  Serial.print(": ");
  Serial.println(kv.value().as<const char*>());
}
```

Expected output:

```
lamp_name: Lamp
power_on: save
on_button: true
mqtt_enable: false
```

Actual output:

```
lamp_name: Lamp
power_on: save
on_button:
mqtt_enable: 
```

**Comment by bblanchon** [comment]
Hi @monte-monte,

When the type doesn’t match, `as<const char*>()` returns a null pointer.
`as<String>()`, however, returns the result of `serializeJson()`.

Best Regards,
Benoit

**Comment by monte-monte** [comment]
@bblanchon ah, I see, so this is expected behavior. ``as<const char*>()`` will return only if value is a string itself? Thanks for clarifying!

**Comment by bblanchon** [comment]
Yes.  
See https://arduinojson.org/v6/api/jsonvariant/as/

**Comment by monte-monte** [comment]
@bblanchon thanks! I've seen it, but evidently I didn't quiet understand what it said :) But now I do.
