### ISSUE TITLE
Array of object AruinoV6

### ISSUE THREAD

**Issue by HDenied** [bblanchon/ArduinoJson#1780]
Hi,

I am trying to generate an array of object, I tried to follow this example in the doc but I am trying to write the object in a file with no much success:
    StaticJsonDocument<200> doc;
    JsonArray array = doc.to<JsonArray>();
    JsonObject nested = array.createNestedObject(); 
    nested["test"]="sprint";
    ofstream out_f {"my.json", ios::out};
    serializeJsonPretty(nested, out_f);

WHat I see printed is:

{"test":"sprint"}

What I expected is:

[{"test":"sprint"}]

Any idea of the problem? Am I missing something?

**Comment by bblanchon** [comment]
Hi @HDenied,

You must replace `serializeJsonPretty(nested, out_f)` with `serializeJsonPretty(doc, out_f)`.

Best regards,
Benoit

**Comment by HDenied** [comment]
I figured it out, thanks, btw, I really like your library and the style you wrote it, there is much to learn from your code

**Comment by bblanchon** [comment]
You're welcome!
Thank you for using ArduinoJson.
