### ISSUE TITLE
null returned when searching for boolean element that is set to false

### ISSUE THREAD

**Issue by Maurizio1** [bblanchon/ArduinoJson#1786]
Is there something I'm missing or is there a bug?

```
{
  "version" : "1.0.0.1",
  "boolean_value" : false,
  "another_boolean_value" : true,
  "bugtest" : "testbug"
}

JsonVariant result;
const char * key;

key = "boolean_value";
JsonVariant foundObject = result[key]; // this returns NULL
key = "another_boolean_value";
JsonVariant foundObject = result[key]; // this returns true
```

The error is systematic. I can successfully retrieve any type of element's value, but booleans when their value is 'false'. This happens with any JSON I tested.

P.S. If I use a JsonObject for result (JsonObject result;) the problem is still there.

I'm using library version: 6.19.4

Thank you in advance for any help.

**Comment by bblanchon** [comment]
Hi @Maurizio1,

Here is a demo: https://wandbox.org/permlink/nLTnhqunyGmSJIes
As you can see, it correctly extracts `false` from the key `boolean_value`.

If you need more assistance, please provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) and include the [Troubleshooter](https://arduinojson.org/v6/troubleshooter/) report.

Best regards,
Benoit

**Comment by Maurizio1** [comment]
> Hi @Maurizio1,
> 
> Here is a demo: https://wandbox.org/permlink/nLTnhqunyGmSJIes As you can see, it correctly extracts `false` from the key `boolean_value`.
> 
> If you need more assistance, please provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) and include the [Troubleshooter](https://arduinojson.org/v6/troubleshooter/) report.
> 
> Best regards, Benoit

Hi Benoit,

thank you for the prompt answer and the demo.

As always, talking with someone opens the trap in which your mind has caught. :-)
Mine was that I did a test to verify if there was a search result or not and that test, now I see, obviously always failed for 'false' booleans.

I need to make it clear that my intent was to get a JsonVariant value by traversing the JSON structure starting at a certain point. Thus I pass a **JsonVariant** to the search function, not an object.

(_I didn't find a way to construct by code a statement like:_

`JsonVariant foundVariant = jsonVariant[key_1][key_2]...[key_n];`

_to get a value, so I am using a vector containing the keys and cycle trough them, recursively pointing at the found variant, to eventually find my needed value_)

**working** pseudo code:

```
  if (!foundVariant.isNull()) {
      return foundVariant;
  }
```

my **wrong** pseudo code was:

```
  if (foundVariant) {
      return foundVariant;
  }
```

which I took, slightly interpreting, from the example:

**How to recursively search for a key?**

```
JsonVariant findNestedKey(JsonObject obj, const char* key) {
    JsonVariant foundObject = obj[key];
    if (foundObject)
        return foundObject;

    for (JsonPair pair : obj) {
        JsonVariant nestedObject = findNestedKey(pair.value(), key);
        if (nestedObject)
            return nestedObject;
    }

    return JsonVariant();
}
```

(I have emphasized it here as a suggestion for others)

Maybe you want to add a slightly changed example to return values.

Thank you for your help and for this fantastic library!

Best regards,

Maurizio

**Comment by bblanchon** [comment]
Hi Maurizio,

I updated the documentation as you suggested.
Thank you for sharing this.

Best regards,
Benoit
