### ISSUE TITLE
serialize to char* with outputSize do not have terminator if the output is too small

### ISSUE THREAD

**Issue by pat1** [bblanchon/ArduinoJson#1794]
**Describe the bug**  
calling:
size_t serializeJson(const JsonDocument& doc, char* output, size_t outputSize);

if output is too small it do not have the terminator

**Troubleshooter report**  
Here is the report generated by the [ArduinoJson Troubleshooter](https://arduinojson.org/v6/troubleshooter/):  
1. The issue happens at run time
2. The issue concerns serialization
3. Output is incomplete
4. Program doesn't call <code>serializeJson()</code> in a loop
5. <code>JsonDocument::overflowed()</code> returns <code>false</code>
6. No string contains a NUL

**Environment**  
Here is the environment that I used:
* Microcontroller: avr atmega1284p
* Core/runtime: platformio

**Reproduction**  
to check the ploblem I have to do something like this:

```c++
    if (serializeJson(json,json_buffer, json_buffer_length) == json_buffer_length){
      json_buffer[0]='\0';
    }
```

**Comment by bblanchon** [comment]
Hi @pat1,

I'm not sure we can qualify that as a bug.
Sure, it's error-prone, just like `strncpy()`, but changing the behavior would break this legitimate use case:

```c++
size_t n = measureJson(doc);
char* json = malloc(n);
serializeJson(doc, json, n);
send(json, n);
free(n);
```

or, as I often see in Arduino code:

```c++
size_t n = measureJson(doc);
char json[n];
serializeJson(doc, json, n);
send(json, n);
```

However, I think this caveat should be documented, so I added a warning in [the documentation](https://arduinojson.org/v6/api/json/serializejson/).

Best regards,
Benoit
