### ISSUE TITLE
Add jsonc format?

### ISSUE THREAD

**Issue by deviashin** [bblanchon/ArduinoJson#1795]
Hello!

Recently learned about json**c** format. This is essentially a normal format, but supports C-style comments (like //).
This is very convenient when creating a new product. Of course, not every project requires posts with comments. However, when debugging, this greatly interferes.

It would be convenient for the library to learn to ignore comments in the original json**c** file when deserialization.

Any ideas about this?

Thanks for the great library! Great person!

**Comment by bblanchon** [comment]
Hi @deviashin,

ArduinoJson already supports C++ style comments, but it's an opt-in feature.
To enable it, you must define [`ARDUINOJSON_ENABLE_COMMENTS`](https://arduinojson.org/v6/api/config/enable_comments/) to `1`.

Best regards,
Benoit

**Comment by deviashin** [comment]
Please forgive me for my carelessness.
Thanks a lot for the quick response!
