### ISSUE TITLE
asString problem for a valid json

### ISSUE THREAD

**Issue by bmafy** [bblanchon/ArduinoJson#180]
Hi, I find your library very useful and quite easy to use, but now I'm facing an annoying issue converting my json (generated using your method) in a string and nothing happens. The converted string (json-->string) is void. Are there any "good methods" for using asString? I didn't find anything excpeting the doc in the wiki page. Thank you very much for your help.
This is the json file as serial monitor prints it:

```json
{
  "DHT11_1": 
{
    "Temp": 27,
    "Hum": 65,
    "Time": 1450619541,
    "ID": "DHT11 Sensor_1"
  },
  "DHT11_2": 
{
    "Temp": 30,
    "Hum": 90,
    "Time": 1450676541,
    "ID": "DHT11 Sensor_2"
  },
  "Acc": {},
  "Microphone":
 {
    "Time": [1450610941, 1450667541, 1450690541, 1452319541, 1450667841],
    "dB": [20, 100, 50, 4.5, 10],
    "ID": "Microphone"
  }
}
```

Matteo

**Comment by bblanchon** [comment]
Hi Matteo,

Can you please copy/paste you program here?

Benoit

**Comment by bmafy** [comment]
Hi! Sorry for delayed answer but it turns out that I was wrong doing in that way... A simple:
`JsonObject.printTo(buffer, sizeof(buffer));`
figured it :+1: 
Thanks for your help!!

**Comment by bblanchon** [comment]
Hi Matteo,
I'm glad you found the answer.
Please apologize for closing the issue without confirmation but, since you gave no response in 7 days, I assumed you moved on.
Thanks for using ArduinoJson.

**Comment by bmafy** [comment]
No problem at all, I just wanted to let other people know what my solution has been.
