### ISSUE TITLE
Nested array and Arduino substring  function

### ISSUE THREAD

**Issue by enjoyneering** [bblanchon/ArduinoJson#1806]
**Describe the issue**  
Hi,
I'm working on a telegram bot and I can't compile my sketch - it always throws an error if I use the Arduino substring function. Also tried to convert string to C-string "menuStr.substring(0, indexTo).c_str()" - no luck. What I'm doing wrong? Thank you in advance.

**Environment**  
Here is the environment that I'm using':
* Microconroller: [e.g. ESP8266]
* Core/runtime: [e.g. ESP8266 core for Arduino v3.0.2]
* IDE: [e.g. Arduino IDE 1.8.16]

```c++
String telegram_showMenu(const String& msgStr, String menuStr)
{
  DynamicJsonDocument jsonDoc(1024);  //create JSON document in heap memory

  jsonDoc["chat_id"] = telegramConfig.chat;
  jsonDoc["text"] = msgStr;
  jsonDoc["parse_mode"] = "HTML"; 

  JsonObject markupDoc  = jsonDoc.createNestedObject("reply_markup"); //{"chat_id":"YYYY", ...,"reply_markup":{}}
  JsonArray  keyboardDocArray = markupDoc.createNestedArray("keyboard");    //{"chat_id":"YYYY", ...,"reply_markup":{"keyboard":[]}}

  while (menuStr.indexOf('\n') != -1)  //-1=not found
  {
    int16_t indexTo = menuStr.indexOf('\n');

    JsonArray buttonDocArray = keyboardDocArray.createNestedArray();  //{"chat_id":"YYYY", ...,"reply_markup":{"keyboard":[[]]}}
    
    buttonDocArray["text"] = menuStr.substring(0, indexTo);  //{"chat_id":"YYYY", ...,"reply_markup":{"keyboard":[["text":"/on"],["text":"/off"]]}}

    menuStr.remove(0, indexTo + 1);  //remove "....\n" from start, until empty

    yield(); //give SDK (ctx: sys) stack a chance to run
  }

  markupDoc["resize_keyboard"]   = true; //{"chat_id":"YYYY", ...,"reply_markup":{"keyboard":[[],...,[]],"resize_keyboard":true}}
  markupDoc["one_time_keyboard"] = true;  //{"chat_id":"YYYY", ...,"reply_markup":{"keyboard":[[],...,[]],"resize_keyboard":true,"one_time_keyboard"=true}}

  String minifiedJsonStr((char *)0);
  minifiedJsonStr.reserve(1024);  //set string size to minimize potential heap memory fragmentation, in bytes

  serializeJson(jsonDoc, minifiedJsonStr);  //generate minified JSON & send it to string, return number of bytes

  return minifiedJsonStr;
}
```

**Comment by bblanchon** [comment]
Hi @enjoyneering,

You're talking about a compilation error, right?
If so, please share the error message.

Have you tried the [ArduinoJson Troubleshooter](https://arduinojson.org/v6/troubleshooter/)?

Best regards,
Benoit

**Comment by enjoyneering** [comment]
the error message:

assignment of read-only location '*(((const char*)"text") + ((sizetype)buttonDocArray.ArduinoJson6194_F1::ArrayRef::<anonymous>.ArduinoJson6194_F1::ArrayRefBase<ArduinoJson6194_F1::CollectionData>::operator bool()))'

**Comment by bblanchon** [comment]
This error occurs because your program uses an array like an object.

```c++
JsonArray array= doc.createNestedArray();
array["key"] = "value";
```

Array are indexed by an integer, not a string.

You probably want to use an object instead.

**Comment by enjoyneering** [comment]
Thank you. The object works!!!

Your library is the best.

**Comment by bblanchon** [comment]
You're welcome, @enjoyneering.
Thank you for using ArduinoJson!
