### ISSUE TITLE
JSON parsing from AsycTCP socket

### ISSUE THREAD

**Issue by barbiani** [bblanchon/ArduinoJson#1813]
Hello everybody,

I am developing a software to parse json from a tcp socket connection. The current implementation is over the asynctcp library that has the "void socket_data_rx(void *arg, AsyncClient *client, void *data, size_t len)" callback. This callback receives at most 1500 bytes worh of data on every call.

What is the proper way to buffer the data and let arduinojson work after I get a complete json?

Should I create a stream and let arduinojson parse it, returning FAIL until it succeeds?

Thank you.

**Comment by bblanchon** [comment]
Hi @barbiani,

Unfortunately, ArduinoJson doesn't support incremental deserialization (#1690).
I want to add this feature at some point, but not in the foreseeable future.

As a workaround, I suggest that you use a [StringStream](https://github.com/bblanchon/ArduinoStreamUtils#how-to-use-a-string-as-a-stream) as a temporary buffer and call `deserializeJson()` when the message is complete.

Best regards,
Benoit
