### ISSUE TITLE
Broken link on homepage for ESPHome

### ISSUE THREAD

**Issue by OidaTiftla** [bblanchon/ArduinoJson#1822]
Hi,

first of all: great library 🎉

I'd like to mention a small issue with a broken link to the ESPHome website.

When I go to the section `They use ArduinoJson` of the https://arduinojson.org and click on ESPHome I get the website of [OpenMQTTGateway](https://docs.openmqttgateway.com/) not [ESPHome](https://esphome.io).

Best regards.

**Comment by bblanchon** [comment]
Hi @OidaTiftla,

Thank you very much for reporting this issue.
It should be fixed by now.

Best regards,
Benoit

**Comment by OidaTiftla** [comment]
Hi @bblanchon,

that was quick 🚀

Best regards,
Christoph
