### ISSUE TITLE
Здраствуйте можете помогать .у меня монитор порт дает  parseOpject () failed Getting date Data loadet

### ISSUE THREAD

**Issue by Xchomkrtchyan** [bblanchon/ArduinoJson#1828]
Здраствуйте можете помогать .у меня монитор порт дает  parseOpject () failed Getting date Data loadet

**Comment by bblanchon** [comment]
Привет.

Спасибо за ваш интерес к ArduinoJson.
Пожалуйста, сформулируйте ваш вопрос на английском языке, чтобы мы могли помочь.
Не забудьте включить все связанные с ним информацию.

Этот текст был переведен искусственным интеллектом

С уважением,
Benoit
