### ISSUE TITLE
Mqtt port is not recognizing 

### ISSUE THREAD

**Issue by AlenSunnyMathew** [bblanchon/ArduinoJson#1831]
**Environment**  
Here is the environment that I'm using':
* Microconroller: . ESP8266
* Core/runtime: [e.g. ESP8266 core for Arduino v3.0.2]
* IDE: [Arduino IDE 1.8.19]
* mqtt library: Adafruit_mqtt_client.h

Hai iam having the issues with the port. I have saved the mqtt configurations in SPIFFS and initialized with structure. When iam trying to connect with mqtt its failed. But its getting connected when the port number defined globally. Any thoughts?

**Comment by bblanchon** [comment]
Hi @AlenSunnyMathew,

This is the repository for ArduinoJson, a JSON serialization library for Arduino.
Please address your MQTT-related questions to [the relevant repository](https://github.com/adafruit/Adafruit_MQTT_Library/issues)

Best regards,
Benoit
