### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by Thuseyanthan** [bblanchon/ArduinoJson#1834]
**Description**
In file included from c:\Users\owner\Documents\Arduino\libraries\firebase-arduino-master\src/Firebase.h:30,
                 from c:\Users\owner\Documents\Arduino\libraries\firebase-arduino-master\src/FirebaseArduino.h:22,
                 from C:\Users\owner\AppData\Local\Temp\.arduinoIDE-unsaved20221114-13588-1w59alp.j629\sketch_dec14a\sketch_dec14a.ino:2:
c:\Users\owner\Documents\Arduino\libraries\firebase-arduino-master\src/FirebaseObject.h:109:11: error: StaticJsonBuffer is a class from ArduinoJson 5. Please see https://arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6
  109 |     std::shared_ptr<StaticJsonBuffer<FIREBASE_JSONBUFFER_SIZE>> buffer_;
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                             
In file included from c:\Users\owner\Documents\Arduino\libraries\firebase-arduino-master\src/FirebaseArduino.h:22,
                 from C:\Users\owner\AppData\Local\Temp\.arduinoIDE-unsaved20221114-13588-1w59alp.j629\sketch_dec14a\sketch_dec14a.ino:2:
c:\Users\owner\Documents\Arduino\libraries\firebase-arduino-master\src/Firebase.h:86:11: error: StaticJsonBuffer is a class from ArduinoJson 5. Please see https://arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6
   86 |   std::shared_ptr<StaticJsonBuffer<FIREBASE_JSONBUFFER_SIZE>> buffer_;
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                               

exit status 1

Compilation error: exit status 1

**Troubleshooter's report**
1. The issue happens at compile time
2. The error is not in the list

**Environment**
* Microcontroller: ESP8266

**Comment by bblanchon** [comment]
Hi @Thuseyanthan,

Please see: https://arduinojson.org/v6/error/jsonbuffer-is-a-class-from-arduinojson-5/

Best regards,
Benoit
