### ISSUE TITLE
ArduinoJson as an ESP-IDF package

### ISSUE THREAD

**Issue by plasmapper** [bblanchon/ArduinoJson#1844]
Dear Benoît,

ESP-IDF has a [component registry](https://components.espressif.com/) that already allows developers to sign-in for preview to release a component. Would you please consider releasing ArduinoJson as an ESP-IDF package. Using it as a package will simplify the installation and versioning for those who use ESP-IDF as it already does for those developing with Arduino IDE.

Thank you.

**Comment by bblanchon** [comment]
Hi @plasmapper,

I requested access to the closed preview.
I'll keep you informed of the progress.

Best regards,
Benoit

**Comment by bblanchon** [comment]
@plasmapper, ArduinoJson is now in the registry:
https://components.espressif.com/components/bblanchon/arduinojson
Please give it a try.

**Comment by plasmapper** [comment]
Great, thanks!
