### ISSUE TITLE
containsKey

### ISSUE THREAD

**Issue by sevelm** [bblanchon/ArduinoJson#1846]
**Describe the issue**  
Using containsKey. It is recommended not to use this. in the instructions we talk about using this version instead:

`
const char* error = root["error"];
if (error) {
  Serial.println(error);
  return;
}
`
**Troubleshooter report**  
not all data type can be retrieved like this, for example int.

**Environment**  
Here is the environment that I'm using':
* Microconroller: ESP32
* IDE: Arduino IDE 1.8.19

**Reproduction** 
this should be avoided:
`
if (doc.containsKey("ChContr4_contr")) { mb.Hreg(Device[websDevNbr].NbrTCPwriteReg+2, doc["ChContr4_contr"]); }
`
**Question** 
Is there a way to find out whether the JSON has a corresponding key independently of the data type.

**Comment by bblanchon** [comment]
Hi @sevelm,

You can use [`JsonVariant`](https://arduinojson.org/v6/api/jsonvariant/) or [`JsonVariantConst`](https://arduinojson.org/v6/api/jsonvariantconst/):

```c++
JsonVariantConst value = doc["key"];
if (value != nullptr) {
  Serial.println(value.as<int>());
}
```

Best regards,
Benoit

**Comment by sevelm** [comment]
that works perfectly! THX!!
             
       JsonVariantConst val;
        val = doc["brand"]; if (val != nullptr) { Serial.println(val.as<String>()); }
        val = doc["wallbox"]; if (val != nullptr) { Serial.println(val.as<int>()); }
        ..... and many more queries
        
        
I have about 100 such queries. do you think this solution is stable enough?

**Comment by bblanchon** [comment]
I don't think I'd repeat this pattern a hundred times, but it depends on the use case.

You can make the test a bit safer by checking the type explicitly with [`is<T>()`](https://arduinojson.org/v6/api/jsonvariant/is/) instead of comparing with `nullptr`.

Also, if you're going to do the test-type-and-print operation repeatedly, you should create a generic function like so:

```c++
template<typename T>
void checkTypeAndPrint(JsonVariantConst v) {
  if (v.is<T>())
    Serial.println(v.as<T>())
}

checkTypeAndPrint<const char*>(doc["brand"]);
checkTypeAndPrint<int>(doc["wallbox"]);
```
