### ISSUE TITLE
Parse to Int throws exception on ESP8266

### ISSUE THREAD

**Issue by bennthomsen** [bblanchon/ArduinoJson#185]
When using the following test code which parses the value of the "light" attribute to an int an exception is always thrown by the ESP8266.

I am using ArduinoJSON Version 5.0.7
```
#include <ESP8266WiFi.h>
#include <ArduinoJson.h>

void setup() {

  Serial.begin(115200);
  while (!Serial);

  StaticJsonBuffer<200> jsonBuffer;

  char data[] = "{\"light\":1}";
   
  JsonObject& root = jsonBuffer.parseObject(data);
  
  int level = root["light"];
  Serial.println(level);
}

void loop() {
  // put your main code here, to run repeatedly:
}
```
If I simply parse to a const char* then the code works as expected i.e.
```
  const char* cmd = root["light"];
  Serial.println(cmd);
```
A workaround is as follows
```
const char*  cmd = root["light"];
int pos = atoi(cmd);
```

Any thoughts?

**Comment by bblanchon** [comment]
There used to be a bug in ESP8266 core, please make sure it's up to date.
You may also have a look at [Compatibility issues: ESP8266](https://github.com/bblanchon/ArduinoJson/wiki/Compatibility%20issues#esp8266).
