### ISSUE TITLE
platformio + arduino + esp32  Unable to compile

### ISSUE THREAD

**Issue by a18805820471** [bblanchon/ArduinoJson#1855]

**Comment by Electrotechnique** [comment]
Release 6.20.0 on  platformio + arduino + Teensy 

I get:

`.pio\libdeps\teensymm\ArduinoJson\src/ArduinoJson/Variant/VariantRefBase.hpp:61:3: error: no type named 'type' in 'struct ArduinoJson6200_F1::enable_if<false, char*>'`

**Comment by bblanchon** [comment]
Hi @a18805820471 and @ElectroTechnique,

Please include the complete compiler output and the relevant lines of your program.

Best regards,
Benoit
