### ISSUE TITLE
SIGSTKSZ no longer a compile time constant

### ISSUE THREAD

**Issue by matswebjorn** [bblanchon/ArduinoJson#1856]
**Description**
When I compile ArduinoJson 6.x at HEAD using SDK generated by Buildroot 2022.11 for RaspBerry Pi Zero 2W, then I get

[  2%] Building CXX object extras/fuzzing/CMakeFiles/msgpack_reproducer.dir/reproducer.cpp.o
In file included from /home/administrator/project/dosell-mu-sweden-v3/externals/br2-external/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/signal.h:328,
                 from /home/administrator/project/dosell-mu-sweden-v3/dosell-mu-sweden/externals/arduino-json/extras/tests/catch/catch.hpp:2143,
                 from /home/administrator/project/dosell-mu-sweden-v3/dosell-mu-sweden/externals/arduino-json/extras/tests/catch/catch.cpp:6:
/home/administrator/project/dosell-mu-sweden-v3/dosell-mu-sweden/externals/arduino-json/extras/tests/catch/catch.hpp:6543:33: error: size of array ‘altStackMem’ is not an integral constant-expression
 6543 |         static char altStackMem[SIGSTKSZ];
      |                                 ^~~~~~~~
/home/administrator/project/dosell-mu-sweden-v3/dosell-mu-sweden/externals/arduino-json/extras/tests/catch/catch.hpp:6594:45: error: size of array ‘altStackMem’ is not an integral constant-expression
 6594 |     char FatalConditionHandler::altStackMem[SIGSTKSZ] = {};

The reason seems to be that SIGSTKSZ is no longer a compile time constant.
See https://github.com/doctest/doctest/issues/473

**Troubleshooter's report**
1. The issue happens at compile time
2. The error is not in the list

**Environment**
* Microcontroller: Raspberry Pi Zero 2 W
* Core/Framework: Buildroot 2022.11
* IDE: N/A

**Reproduction code**
```c++
static char altStackMem[SIGSTKSZ];
See arduino-json/extras/tests/catch/catch.hpp
```

**Comment by matswebjorn** [comment]
Tested to replace arduino-json/extras/tests/catch/catch.hpp with https://gitlab.liu.se/givna-filer/tdiu20-given-files/-/blob/master/catch.hpp , and it worked. At least the compiler succeeded to build the file.

**Comment by bblanchon** [comment]
Hi @matswebjorn,

I'm currently stuck with Catch 1 because the test suite must compile with C++03 compilers (See #1820).

The real question is: why are you compiling the test suite?

Best regards,
Benoit
