### ISSUE TITLE
Missing ';' in copyArray.cpp

### ISSUE THREAD

**Issue by matswebjorn** [bblanchon/ArduinoJson#1857]
**Description**
In extras/tests/JsonArray/copyArray.cpp:160 is a ';' missing after
    CAPTURE(SIZE)

**Troubleshooter's report**
1. The issue happens at compile time
2. The error is not in the list

**Environment**
* Microcontroller: RaspberryPi Zero 2  W
* Core/Framework: Buildroot 2022.11
* IDE: Buildroot 2022.11 SDK

**Comment by bblanchon** [comment]
Thank you for reporting this bug.
Curiously, it was working fine with Catch 1.
