### ISSUE TITLE
Cpp17Tests does not compile with arm-buildroot-linux-gnueabihf-g++.br_real (Buildroot 2022.11) 11.3.0

### ISSUE THREAD

**Issue by matswebjorn** [bblanchon/ArduinoJson#1859]
**Description**
add_subdirectory(Cpp17) in extras/tests/CMakeLists.txt will not link if enabled.
[  4%] Linking CXX executable Cpp17Tests
cd /home/administrator/project/dosell-mu-sweden-v3/build/arm/arduino-json/extras/tests/Cpp17 && /home/administrator/project/dosell-mu-sweden-v3/externals/br2-external/buildroot/output/host/bin/cmake -E cmake_link_script CMakeFiles/Cpp17Tests.dir/link.txt --verbose=1
/home/administrator/project/dosell-mu-sweden-v3/externals/br2-external/buildroot/output/host/bin/arm-buildroot-linux-gnueabihf-g++ --sysroot=/home/administrator/project/dosell-mu-sweden-v3/externals/br2-external/buildroot/output/host/arm-buildroot-linux-gnueabihf/sysroot -pthread -D__BUILD_TYPE__=1 -D__RELEASE_VER__=1.0.10.1 -D__DOSELL_V3__=1 -std=gnu++17   -std=gnu++17 -std=gnu++17 CMakeFiles/Cpp17Tests.dir/string_view.cpp.o -o Cpp17Tests  ../catch/libcatch.a 
/home/administrator/project/dosell-mu-sweden-v3/externals/br2-external/buildroot/output/host/lib/gcc/arm-buildroot-linux-gnueabihf/11.3.0/../../../../arm-buildroot-linux-gnueabihf/bin/ld: CMakeFiles/Cpp17Tests.dir/string_view.cpp.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > Catch::Detail::stringify<std::basic_string_view<char, std::char_traits<char> > >(std::basic_string_view<char, std::char_traits<char> > const&)':
/home/administrator/project/dosell-mu-sweden-v3/dosell-mu-sweden/externals/arduino-json/extras/tests/catch/catch.hpp:1646: undefined reference to `Catch::StringMaker<std::basic_string_view<char, std::char_traits<char> >, void>::convert[abi:cxx11](std::basic_string_view<char, std::char_traits<char> >)'
collect2: error: ld returned 1 exit status
make[2]: *** [extras/tests/Cpp17/CMakeFiles/Cpp17Tests.dir/build.make:101: extras/tests/Cpp17/Cpp17Tests] Error 1

**Troubleshooter's report**
1. The issue happens at compile time
2. The error is not in the list

**Environment**
* Microcontroller: Raspberry Pi Zero 2 W
* Core/Framework: Buildroot 2022.11
* IDE: Buildroot 2022.11 SDK

**Comment by bblanchon** [comment]
Hi @matswebjorn,

In #1856, you mentioned that you replaced `catch.hpp`; that's probably related because it links correctly with GCC 11.1 in the CI.
Again, I'm stuck with Catch 1 until I drop support for C++03 (#1820).

Best regards,
Benoit
