### ISSUE TITLE
Let JsonDocument member reference object in other JsonDocument

### ISSUE THREAD

**Issue by emielch** [bblanchon/ArduinoJson#1865]
**Describe the issue**  
Is it possible to have a member of a JsonDocument be a reference to an object in a different JsonDocument?
Simply put, I want to create JsonDocument in one function which then is passed to another function where it is "wrapped" in an object / nested, so that the top nesting level can contain metadata about the message before sending it out.
Now I have to create a second JsonDocument of at least the same size as the first so it can hold the data, this seems a bit wasteful to me.
The example below better illustrates what I'm trying to do.

**Environment**  
Here is the environment that I'm using:
* ArduinoJson: 6.20.0
* Microconroller: Teensy 3.5
* Core/runtime: Teensyduino 1.57
* IDE: Arduino IDE 1.8.13

**Reproduction**  
Here is a small snippet that demonstrate the problem.

```c++
#include <ArduinoJson.h>

void send(const JsonVariant& msgObj, const char* msgType) {
  StaticJsonDocument<1024> sendDoc;  // needs to fit the data in msgObj, can this be smaller if referenced somehow?
  sendDoc["target"] = "server";
  sendDoc["time"] = millis();

  Serial.printf("sendDoc memoryUsage before adding: %i\r\n", sendDoc.memoryUsage());
  sendDoc[msgType] = msgObj;  // find a way to set as reference so we don't need to allocate as much memory
  Serial.printf("sendDoc memoryUsage after adding: %i\r\n", sendDoc.memoryUsage());

  serializeJson(sendDoc, Serial);
  Serial.println();
}

void log() {
  StaticJsonDocument<1024> doc;
  doc["name1"] = "value1";
  doc["name2"] = "value2";
  doc["etc"] = "etc";
  Serial.printf("doc memoryUsage: %i\r\n", doc.memoryUsage());
  send(doc.as<JsonVariant>(), "Log");
}

void setup() {
}

void loop() {
  delay(1000);
  log();
}
```

**Program output**  
```
doc memoryUsage: 48
sendDoc memoryUsage before adding: 32
sendDoc memoryUsage after adding: 96
{"target":"server","time":5301,"Log":{"name1":"value1","name2":"value2","etc":"etc"}}
```

Ideally the memoryUsage after adding would be 48 instead of 96 (reference only requiring the size of one object)

Or is there a different way of doing this? Maybe by "pushing" an existing object down a nesting level within the same JsonDocument without copying it?

**Comment by bblanchon** [comment]
Hi @emielch,

[JsonVariant::shallowCopy()](https://arduinojson.org/v6/api/jsonvariant/shallowcopy/) does exactly what you want.

BTW, instead of taking a `const JsonVariant&`, the `send()` function should take a [`JsonVariantConst`](https://arduinojson.org/v6/api/jsonvariantconst/); that way, you could pass the `JsonDocument` directly, without calling `as<JsonVariant>()`.

```c++
void send(JsonVariantConst msgObj, const char* msgType) {
  StaticJsonDocument<48> sendDoc;
  sendDoc["target"] = "server";
  sendDoc["time"] = millis();
  sendDoc[msgType].shallowCopy(msgObj);
  serializeJson(sendDoc, Serial);
  Serial.println();
}

void log() {
  StaticJsonDocument<1024> doc;
  doc["name1"] = "value1";
  doc["name2"] = "value2";
  doc["etc"] = "etc";
  send(doc, "Log");
}
```

Now, have a look at [the example for `shallowCopy()`](https://arduinojson.org/v6/api/jsonvariant/shallowcopy/#example) 😉 

Best regards,
Benoit

**Comment by emielch** [comment]
Oh wow this feature just got introduced last month, no wonder I couldn't find it in your book!
This is indeed what I was looking for, thanks for your quick reply and pointing me in the right direction (and of course building this wonderful library).
I'll change all the `const JsonVariant&` to `JsonVariantConst` in my code 😉

**Comment by bblanchon** [comment]
You're welcome, @emielch.
Thank you very much for purchasing my book ❤️
