### ISSUE TITLE
Compilation error: 'StaticJsonDocument' was not declared in this scope

### ISSUE THREAD

**Issue by dakoller** [bblanchon/ArduinoJson#1867]
**Description**
When I copy the boiler plate text 
"void setup() {
  StaticJsonDocument<200> doc;
  doc["hello"] = "world";
  serializeJson(doc, Serial);
}"

I expect it to work, but I get the mentioned error.

I miss a proper include statement for arduinoJSON in the beginning, but maybe thats not needed.

**Troubleshooter's report**
1. The issue happens at compile time
2. Error says "`doc` does not name a type"
3. Moving statement to `setup()` doesn't fix the issue

**Environment**
* Microcontroller: ESP8266 NodeMCU 12E

**Reproduction code**
```c++
#include <Wire.h>
#include <SPI.h>
#include <Adafruit_BME280.h>

#include <ESP8266WiFi.h>
#include <ESP8266WiFiMulti.h>

...
...

Adafruit_BME280 bme; // use I2C interface
Adafruit_Sensor *bme_temp = bme.getTemperatureSensor();
Adafruit_Sensor *bme_pressure = bme.getPressureSensor();
Adafruit_Sensor *bme_humidity = bme.getHumiditySensor();

ESP8266WiFiMulti WiFiMulti;

//DynamicJsonDocument doc(1024);
//StaticJsonDocument<96> doc;

void setup() {
...

  StaticJsonDocument<200> doc;
  doc["hello"] = "world";
  serializeJson(doc, Serial);

}
```

**Comment by bblanchon** [comment]
Hi @dakoller,

I'm afraid you do need to include `ArduinoJson.h`.

Please add the following line at the top of your program:

```c++
#include <ArduinoJson.h>
```

Best regards,
Benoit

**Comment by dakoller** [comment]
Thx @bblanchon ! I was looking for this include-line all the time. Now it works.

**Comment by bblanchon** [comment]
You're welcome, @dakoller!
Thank you for using ArduinoJson.
Don't forget to [cast a star](https://github.com/bblanchon/ArduinoJson/stargazers) to support the project :wink:
