### ISSUE TITLE
Specify custom default for INT and FLOAT

### ISSUE THREAD

**Issue by codegrue** [bblanchon/ArduinoJson#1869]
Currently the documentation says if a key is missing (or empty) the default values returned are 0.0 for float/double and 0 for int/long. However, zero may be a legitimate and expected value for some items, for example, temperature. Is there a process to determine if an actual zero was returned or if the value was empty?

Maybe a solution would be to extend "as" to allow the caller to specify the default value to return if the contents are empty or cannot be parsed. e.g.

`doc["temperature"].as<float>(-9999.0)`

**Comment by bblanchon** [comment]
Hi @codegrue,

Think feature already exists with [operator|](https://arduinojson.org/v6/api/jsonvariant/or/):

```c++
temperature = doc["temperature"] | -9999.0;
```

Best regards,
Benoit
