### ISSUE TITLE
I have a question regarding containsKey()

### ISSUE THREAD

**Issue by jPerotto** [bblanchon/ArduinoJson#1873]
I'm following JsonObject::containsKey() recommendations
https://arduinojson.org/v6/api/jsonobject/containskey/

I implemented it as per your suggestion:
https://github.com/bblanchon/ArduinoJson/issues/1846#issuecomment-1373257927

But I read the references:
https://cpp4arduino.com/2018/10/26/why-cpp-programmers-dont-use-null.html
https://en.wikipedia.org/wiki/Null_object_pattern

And I would like to understand better why the differences in the recommendations for using Example from the V6.

**Comment by bblanchon** [comment]
Hi @jPerotto,

What is your question?
