### ISSUE TITLE
Want store DynamicJsonDocument in psram on ESP32 Wroover

### ISSUE THREAD

**Issue by yann-cesbron** [bblanchon/ArduinoJson#1883]
**Description**
I tring solutions like that. (see Reproduction code)
(1) esp reboot endless
(2) no memory ( normal)
I loking for the good syntax   Thanks

**Troubleshooter's report**
1. The issue happens at run time
2. The issue concerns deserialization
3. `deserializeJson()` returns `NoMemory`
4. Increasing the capacity of the `JsonDocument` doesn't fix the issue
5. The `JsonDocument` is a `DynamicJsonDocument`
6. `doc.capacity()` returns the right value
7. Changing the Assistant settings doesn't solve the issue

**Environment**
* Microcontroller: ESP32 wroover 4m de psram
* IDE: PIO on visual studio

**Reproduction code**
```c++
in "test.h"
const size_t confSysCapacity = 10240;
(1) DynamicJsonDocument __attribute__((section(".psram")))  JSONconfSys(confSysCapacity);
(2) DynamicJsonDocument JSONconfSys(confSysCapacity);

in "test.cpp"
 File SDfile = SD.open(CONFIGFILE);
...
 DeserializationError error = deserializeJson(JSONconfSys, SDfile);
```

**Remarks**
my mail is 'yann@cesbron.org'   
this code is for an association for the physically handicapped, i try help us
you can see the full code on github here: https://github.com/yann-cesbron/HandiPad.git
thank's for your help

**Comment by bblanchon** [comment]
Hi @yann-cesbron,

Please read [How to use external RAM on ESP32?](https://arduinojson.org/v6/how-to/use-external-ram-on-esp32/)

Best regards,
Benoit
