### ISSUE TITLE
[5.x][docs][error] Memory model – typos

### ISSUE THREAD

**Issue by MacDada** [bblanchon/ArduinoJson#1892]
I couldn't find the docs repo to just quickly fix it, instead of making the issue ;-)

https://arduinojson.org/v5/doc/memory/#dynamic-memory-allocation

> However, usage of this memory model make sense only for devices with more that 10KB or RAM

* make -> makes
* that -> than
* or -> of
* period/full stop at the end of the sentence

**Comment by bblanchon** [comment]
Hi @MacDada,

Thank you very much for reporting this typo.
It should be fixed now.

Best regards,
Benoit
