### ISSUE TITLE
[5.x][docs][error] How to reduce memory usage: badly copy-pasted code comment?

### ISSUE THREAD

**Issue by MacDada** [bblanchon/ArduinoJson#1893]
https://arduinojson.org/v5/faq/how-to-reduce-memory-usage/#tip-5-avoid-duplication-of-flash-strings

With the example:

```cpp
// ArduinoJson stores 10 pointers
for (int i=0; i<10; i++) {
  array.add("value");
}

// ArduinoJson stores 10 pointers
for (int i=0; i<10; i++) {
  array.add(F("value"));
}
```

In the second case, I think it was supposed to be `// ArduinoJson stores 10 copies of the Flash string` (or sth like that) [?]

**Comment by bblanchon** [comment]
Hi @MacDada,

Thank you very much for reporting this typo.
It should be fixed now.

Best regards,
Benoit
