### ISSUE TITLE
Parsing yaml, I need to store JsonObject pointers in std::queue, is this possible?

### ISSUE THREAD

**Issue by Bascy** [bblanchon/ArduinoJson#1894]
**Describe the issue**  
I'm trying to create an ArduinoJson document from a yaml file. 
I tried using YamlDuino (https://github.com/tobozo/YAMLDuino) which looked very promising but deserializing a yaml file of 10k will take over 140K of heap memory, which I don't have available, so I am looking for an alternative.

I'm currently looking into yaml-cpp (https://github.com/jbeder/yaml-cpp), which does provide me with the yaml parser, and uses a set of callback to parse found tokens to a builder, i.e. ArduinoJsonBuilder.

For this to work I need to store a queue of JsonObject and/or JsonArrays while creating the tree structure, to know to which parent the actual key/value variants need to be added.

Questions: 
- Can I use a `std::queue<JsonVariant*>` to store this?
- Is there a way of determining the parent JsonVariant of a specific JsonVariant? That way I wont need the queue at all
- Do you know any other yaml libraries I could use to do this task?

**Environment**  
Here is the environment that I'm using:
* ESP32
* Platform: Espressif 32 (5.3.0)
* IDE: PlatformIO

**Comment by bblanchon** [comment]
Hi @Bascy,

> Can I use a std::queue<JsonVariant*> to store this?

You can use `std::queue<JsonVariant>`.

> Is there a way of determining the parent JsonVariant of a specific JsonVariant? That way I wont need the queue at all

No.
I may include a link to the parent in v7, but I need to do some benchmarks first.

> Do you know any other yaml libraries I could use to do this task?

No.
I love YAML and use it for many projects, but I would not use it on an IoT device.
YAML is much more complex than JSON and therefore requires more code, memory, and time to process.

Best regards,
Benoit

**Comment by Bascy** [comment]
@bblanchon Thanks for your reply,
As we are using only a subset of Yaml syntax, and have full control of the actual yaml files, I think i'm just gonna make a yaml  to json parser that just handles the cases we use.
