### ISSUE TITLE
[5.x] Feature requests?

### ISSUE THREAD

**Issue by MacDada** [bblanchon/ArduinoJson#1895]
A quick question ;) I'm using 5.x right now and I have a new feature in mind -> I guess version 5 is closed for new features? I should upgrade to 6 and see if I'm missing that in the new version, right?

To be exact, I'm looking for a way to simplify error handling -> not to have a gazzilion IFs when I'm serializing ;) And I'm not interested in just "skip the error handling" "solution" :D

**Comment by bblanchon** [comment]
Hi @MacDada,

Indeed, version 5 is closed for new features.
Version 6 has [JsonDocument::overflowed()](https://arduinojson.org/v6/api/jsondocument/overflowed/) for that.

Best regards,
Benoit
