### ISSUE TITLE
[6.x][docs] "Why is the output incomplete?" inverse description

### ISSUE THREAD

**Issue by MacDada** [bblanchon/ArduinoJson#1896]
https://arduinojson.org/v6/issues/incomplete-output/#how-to-solve-it

> add JSON_OBJECT_SIZE(n) for each array of size n,
> add JSON_ARRAY_SIZE(n) for each object of size n,

I guess this should be inverse?

**Comment by bblanchon** [comment]
Hi @MacDada,

Thank you very much for reporting this issue.
It should be fixed now.

Best regards,
Benoit
