### ISSUE TITLE
Use number with createnestedobject

### ISSUE THREAD

**Issue by sticilface** [bblanchon/ArduinoJson#190]
is is possible to create a nested object, that consists of a number? 

JsonObject::createNestedObject(const char *key)

Get an error when it is not const char?

**Comment by sticilface** [comment]
I guess you just use array!

**Comment by bblanchon** [comment]
`JsonVariant` is a type that can contain several kind of value: string, number, etc.

```c++
JsonVariant v;
v = "hi!";
v = 42;
```

`JsonArray` and `JsonObject` are collections of `JsonVariant`.

But I don't understand your question... could you elaborate?

**Comment by sticilface** [comment]
I'm being a spanner.  Thanks for the reply.  but please ignore.

**Comment by sticilface** [comment]
Actually... maybe I'm not being a spanner... here is a sample JSON.

```
{
  "0": {
    "name": "SimpleColor",
    "brightness": 177,
    "speed": 1950289429,
    "color1": {
      "R": 184,
      "G": 33,
      "B": 64
    }
  }
}
```

Here the "0":  which is a createNestedObject("0") must be a const char *, but is there a reason it cannot be an integer?

**Comment by bblanchon** [comment]
You mean, like this:

```json
{
  0: {
    "name": "SimpleColor",
    "brightness": 177,
    "speed": 1950289429,
    "color1": {
      "R": 184,
      "G": 33,
      "B": 64
    }
  }
}
```

It's not valid JSON anymore, see [json.org](http://json.org]):

![Object](http://json.org/object.gif)
![String](http://json.org/string.gif)

**Comment by sticilface** [comment]
spoon accepted back!  
Thanks
