### ISSUE TITLE
Cant serialize strings assert falied: MemoryPool.hpp:174 (isAligned(_right))

### ISSUE THREAD

**Issue by pinkcigareti** [bblanchon/ArduinoJson#1902]
**Describe the issue**  
Serializing json, that contains string values (std::string or const char*) crashes program with assert:failed message.
Removing ARDUINOJSON_ASSERT(isAligned(_right) line fixes this issue for me.
``` c++
// MemoryPool.hpp 174
  void checkInvariants() {
    ARDUINOJSON_ASSERT(_begin <= _left);
    ARDUINOJSON_ASSERT(_left <= _right);
    ARDUINOJSON_ASSERT(_right <= _end);
    ARDUINOJSON_ASSERT(isAligned(_right)); 
  }
```
**Troubleshooter report**  
Here is the report generated by the [ArduinoJson Troubleshooter](https://arduinojson.org/v6/troubleshooter/):  
1. The issue happens at run time
2. The issue concerns serialization
3. Program crashes
4. Program uses `StaticJsonDocument`
5. Switching to `DynamicJsonDocument` doesn't fix the issue
6. Program doesn't use `PROGMEM`
7. Program inserts string pointers into the `JsonDocument`
8. Replacing string pointers with literals fixes the crash
9. Printing the string doesn't show any faulty pointer

**Environment**  
Here is the environment that I'm using:
* Microconroller: WT32-ETH01
* IDE: PlatformIO IDE 3.1.1
* ArduinoJson: 6.21.0

**Reproduction**  
Here is a small snippet that demonstrate the problem.

```c++
void SendData(void)
{
  uint32_t number = 20;
  uint16_t year = 23;
  char buf[32];
  StaticJsonDocument<128> json;
  snprintf(buf, sizeof(buf), "%05u-%02u", number, year % 100);
  Serial.println(buf); // prints 00020-23 as it should
  json["firmwareId"]["serialNum"] = buf;
  char data[256];
  serializeJson(json, data); // fails here
  Serial.println(data);

  notifyClients(data);
}

```

**Program output**  
If relevant, include the program output.

Expected output:

```
00020-23
{"firmwareId":{"serialNum":"00020-23"}}
```

Actual output:

```
00020-23
assert failed: void ArduinoJson::V6210PB::detail::MemoryPool::checkInvariants() MemoryPool.hpp:174 (isAligned(_right))
```

**Comment by bblanchon** [comment]
Hi @pinkcigareti,

I tried your program on my ESP32 with the latest version of the Espressif 32 platform (6.1.0), and it's working fine.
I double-check that the build type is "debug" and that asserts are enabled.

There must be something special with your setup.
Can you reinstall the platform and the library?

Best regards,
Benoit
