### ISSUE TITLE
Use without Arduino

### ISSUE THREAD

**Issue by jputcu** [bblanchon/ArduinoJson#1903]
I'm currently using `ArduinoJson-6.18.5` without Arduino on AVR. I have provided the `FlashStringHelper` to support the flash string overloads.
Trying to upgrade to `ArduinoJson-6.21` I run into the issue that I require `Arduino.h` when `ARDUINOJSON_ENABLE_PROGMEM` is enabled.
The `pgm` defines are available on AVR.

Does the library need someting from Arduino to work with generic AVR flash/pgm data? Can we do without the `Arduino.h`?

**Comment by bblanchon** [comment]
Hi @jputcu,

I need `Arduino.h` for the definition of `__FlashStringHelper`.
I cannot redefine it in ArduinoJson because [some cores define it in the `arduino` namespace](https://github.com/arduino/ArduinoCore-API/blob/844e4bf20c5fad8b89a2f307ba3416f61f512eaa/api/String.h#L44).

Why don't you add a dummy `Arduino.h`?

Best regards,
Benoit

**Comment by jputcu** [comment]
Hello

I tried that, but was hoping for a cleaner solution because having that dummy file, which must be public, could trigger other libraries to assume full Arduino support.
Perhaps I can create a lightweight Arduino library, that would open up more libraries for my AVR platform.
Another solution could be to use an alias `using ArduinoFlashString = __FlashStringHelper` and then use the alias in `ArduinoJson`. We could redefine the alias using a macro?

**Comment by bblanchon** [comment]
Hi @jputcu,

Please try the branch [issue1903](https://github.com/bblanchon/ArduinoJson/tree/issue1903).

Best regards,
Benoit

**Comment by jputcu** [comment]
Hello

Thanks for the effort, will try it tomorrow.
BTW, I upgraded the `conan` receipe on `https://github.com/conan-io/conan-center-index/tree/master/recipes/arduinojson/conan-center-index` and saw you have an older repository for that. Perhaps it is best to remove it because it won't work with the newest `conan-2`.

Kind regards

Joris

**Comment by bblanchon** [comment]
Hi Joris,

I archived the repo `bblanchon/conan-ArduinoJson`.
Do I need to do anything else?

Best regards,
Benoit

**Comment by jputcu** [comment]
Hello Benoit

No, I think that's ok to avoid confusion.

Thanks
Joris

**Comment by jputcu** [comment]
I'm trying to use the branch, but run into the issue on `ArduinoJson.hpp:17` due to `ARDUINOJSON_ENABLE_PROGMEM`.

**Comment by bblanchon** [comment]
I added an extra check. Please try again.

**Comment by jputcu** [comment]
It now compiles.

Just a few questions/remarks:
* I had to add `#define ARDUINOJSON_ENABLE_PROGMEM 1`, could it be autodetected on AVR?
* Coming from 6.18.5, my code size went from 72226 to 73174, checking the listing and map file for clues now.

**Comment by bblanchon** [comment]
Finally someone who cares about code size!

If you look at the curves on [this page](https://arduinojson.org/news/2023/03/14/arduinojson-6-21-0/), you'll see that the ProgmemExample grew by about 200 bytes.
In your case, it's five times that, so there is probably a function that is inlined when it should not.

I must admit, PROGMEM support is not my top priority now that ESP32 and ARM are so popular.

How do you want me to detect we're on AVR, is `#ifdef __AVR__` suitable for you?

**Comment by jputcu** [comment]
I'm using `#ifdef __AVR`, but I'm unsure if all AVR have progmem. I've read somewhere in `ArduinoJson` that is detects the `pgm` defines, perhaps that is a better solution?

**Comment by bblanchon** [comment]
The `pgm` macros are defined in `avr/pgmspace.h`, so there is a chicken-and-egg problem here.

I see that many projects are using `#ifdef __AVR___`; any reason why you use a different approach?

**Comment by jputcu** [comment]
The documentation of `pgmspace.h` says it needs the `LPM` or `ELPM` instructions. So perhaps `__AVR__` and either one of the instructions?

**Comment by bblanchon** [comment]
Fix available in [ArduinoJson 6.21.2](https://github.com/bblanchon/ArduinoJson/releases/tag/v6.21.2)
