### ISSUE TITLE
Duplicate install for export ArduinoJson_Targets

### ISSUE THREAD

**Issue by jputcu** [bblanchon/ArduinoJson#1906]
I'm not really sure, but in `src/CMakeLists.txt` there are 2 installs that have `EXPORT ArduinoJson_Targets`.

**Comment by bblanchon** [comment]
As I said in the [comment](https://github.com/bblanchon/ArduinoJson/blob/4ba9c1b0c0a0500980dffb44c89edc33df387588/src/CMakeLists.txt#L5-L6):

>  I have no idea what this is about, I simply followed the instructions from:
> https://dominikberner.ch/cmake-interface-lib/

And, indeed, the example on that page contains two `EXPORT SI_Targets`.  
Do you think it's a problem?

**Comment by jputcu** [comment]
I've read a bit more and it appears to be "normal" CMake, sorry for that. The first item in the `install(TARGETS|EXPORT` expresses a different function.
