### ISSUE TITLE
JSON Error

### ISSUE THREAD

**Issue by evil-electronics-klub** [bblanchon/ArduinoJson#1911]
**Description**
Error communicating with the language server: Error: write EPIPE: undefined.

**Troubleshooter's report**
1. The issue happens at compile time
2. The error is not in the list

**Environment**
* Microcontroller: Arduino MKR 1010
* IDE: 2.0.4

**Comment by bblanchon** [comment]
Hi @evil-electronics-klub,

It doesn’t look like an compilation error.
Where do you see this?

Best regards,
Benoît
