### ISSUE TITLE
Heap goes lower and lower.

### ISSUE THREAD

**Issue by zekageri** [bblanchon/ArduinoJson#1916]
Hi.

I have a page which periodically fetches some json.
Json looks like this:

```json
{
        "name": "M8",
        "type": "M8",
        "address": 39,
        "id": 20,
        "serial": 1,
        "terminated": false,
        "added": false,
        "pinCount": 16,
        "index": 0,
        "isTherm": false,
        "pins": [
            {
                "id": "M8-3502662852",
                "state": false,
                "pinNum": 0,
                "readablePin": 1,
                "faultCode": 0,
                "type": -1,
                "regNum": 0,
                "name": "M8-I1"
            },
            {
                "id": "M8-1284259781",
                "state": false,
                "pinNum": 1,
                "readablePin": 2,
                "faultCode": 0,
                "type": -1,
                "regNum": 0,
                "name": "M8-I2"
            },
            // other pins...
        ]
    }
```

**My methods looks like this**

```cpp
/*
*   It will send periodic status reports at every PERIODIC_STATUS_REPORT_MS
        to the frontend if hasOpenPinTestModal is true
*   It will also handle the timeout of the status report.
*   Timeout will ensure that the user does not stuck on the web
*/
void Hardwares::periodicStatusReport(){
    if(!hasOpenPinTestModal){ return; }
    if(millis() - lastStatusReport >= MAX_OPEN_PIN_TEST_MODAL_WAIT_MS ){
        hasOpenPinTestModal = false;
        return;
    }
    if( millis() - lastStatusReportSendMS >= PERIODIC_STATUS_REPORT_MS ){
        lastStatusReportSendMS = millis();
        sendPinStatuses();
    }
}


void Hardwares::sendPinStatuses(){
    if(modules.empty() || statusInfoString == nullptr){ return; }
    SpiRamJsonDocument doc(10000);
    JsonObject statusObj = doc.to<JsonObject>();
    Module* module = modules[infoModuleIndex];
    if( module ){
        if( module->_id != LS10 ){
            JsonObject moduleObj = doc.createNestedObject(String(module->_address));
            module->getJson(moduleObj);
            if(serializeJson(statusObj,statusInfoString,10000)){
                serverSys.sendEvent("moduleStatus",statusInfoString);
            }
        }
    }
    doc.garbageCollect();
    infoModuleIndex++;
    if( infoModuleIndex >= modules.size() ){
        infoModuleIndex = 0;
    }
}
```

`periodicStatusReport()` handles the timing and `sendPinStatuses()` will get and send the json.
Frontend gets the json correctly but my esp heap goes lower and lower.

I have a char* which allocated in psram in setup, thats what i use to serialize the json into and send it.
I tried `garbageCollect()` but it did not help.

**The attached images shows the free heap over time.**
It only happens when `periodicStatusReport()` runs.

![image](https://user-images.githubusercontent.com/37899881/234012101-6da2f59e-ac73-4292-b956-0d9e9066c286.png)
![image](https://user-images.githubusercontent.com/37899881/234012182-a64dfdde-771e-4168-a2a8-91101658b9e4.png)

**getJson() does nothing fancy just populates the Jso**n.

```cpp
void Module::getJson(JsonObject& moduleJson) {
    if(!updated){ return; }
    moduleJson["name"] = name;
    moduleJson["type"] = type;
    moduleJson["address"] = _address;
    moduleJson["id"] = _id;
    moduleJson["serial"] = _serial;
    moduleJson["terminated"] = terminated;
    moduleJson["added"] = added;
    moduleJson["pinCount"] = _pinCount;
    moduleJson["index"] = _index;
    moduleJson["isTherm"] = _isTherm;
    JsonArray pinsObj = moduleJson.createNestedArray("pins");
    if( _isTherm || pins.empty() ){ return; }
    for (Pin* pin : pins) {
        JsonObject pinObj = pinsObj.createNestedObject();
        pinObj["id"] = pin->id;
        pinObj["state"] = pin->state;
        pinObj["pinNum"] = pin->pinNum;
        pinObj["readablePin"] = pin->readablePin;
        pinObj["faultCode"] = pin->faultCode;
        pinObj["type"] = pin->type;
        pinObj["regNum"] = pin->regNum;
        pinObj["name"] = pin->name.c_str();
    }
}
```

What could be the problem?

**Comment by zekageri** [comment]
As soon as i close the page which fetches the json my heap goes to normal. It only performs this sending operation.

![image](https://user-images.githubusercontent.com/37899881/234014444-3b79cb43-31b7-40fb-93ee-c138fe5c36ed.png)

**Comment by bblanchon** [comment]
Hi @zekageri,

I'll assume your question is *Why does the heap usage increase linearly?*

I cannot give you a definite answer, but I can assert that `SpiRamJsonDocument` only makes one allocation in the constructor and one deallocation in the destructor.  
It also allocates and deallocates in `garbageCollect()` to make a copy of the document. You should not call this function; it will only degrade the performance.

If I had to guess, I would say, that I may come from the `String` you create in the loop.

Best regards,
Benoit

**Comment by zekageri** [comment]
Thank you for the response. You are amazing as always. It turned out that it was my bad, and sorry for the bug label.
I had to take an other approach. The web periodically fetching the data now, with fetch() and the backend just gives the data to it as soon as it can. No heap problem now. Thank you again and sorry.
