### ISSUE TITLE
Trying to use filter on array

### ISSUE THREAD

**Issue by DamronDan** [bblanchon/ArduinoJson#1920]
**Description**
compile time error

**Troubleshooter's report**
1. The issue happens at compile time
2. The error is not in the list

**Environment**
* Microcontroller: ESP32

**Reproduction code**
```c++
File configFile = LittleFS.open("/cfg.json", "r");
  if (!configFile)
  {
    Serial.println("Failed to open config file");
  }

  String configJson = configFile.readString();
  Serial.println("Read config file");
  configFile.close();
  Serial.println("Config file contents:");
  Serial.println(configJson);
  Serial.printf("Size: %d\n", configJson.length());
  DynamicJsonDocument filter[64];
  filter["nw"] = true;
  DynamicJsonDocument doc(1024);
  DeserializationError error = deserializeJson(doc, configJson, filter);
  if (error)
  {
    Serial.println("Failed to parse config file");
    Serial.println(error.c_str());
  }
```

**Remarks**
request for member 'allowArray' in 'filter', which is of pointer type 'ArduinoJson::V6212PB::BasicJsonDocument<ArduinoJson::V6212PB::DefaultAllocator>*' (maybe you meant to use '->' ?)
         if (filter.allowArray())

**Comment by bblanchon** [comment]
Hi @DamronDan,

Please try:

```diff
- DynamicJsonDocument filter[64];
+ DynamicJsonDocument filter(64);
```

Best regards,
Benoit

**Comment by DamronDan** [comment]
Sorry for not replying, I forgot about this until you closed it.  Yes, this fixed it!
