### ISSUE TITLE
Support nonstd::optional for deserialization

### ISSUE THREAD

**Issue by codegrue** [bblanchon/ArduinoJson#1923]
it would be great to support this so we don't have to have an if statement to handle NULL cases:

```
using nonstd::optional;

optional<int> optional_value;;

if (doc["nullableitem"].isNull())
   optional_value.reset();
else
   optional_value = doc["nullableitem"];
```

would become this:

```
  optional_value  = doc["nullableitem"].as<optional<int>>();
```

**Comment by bblanchon** [comment]
Hi @codegrue,

I cannot add a dependency to an external library; however, you can write a [custom converter](https://arduinojson.org/news/2021/05/04/version-6-18-0/) for `nonstd::optional`.
Here is a draft (not tested):

```c++
namespace nonstd {
template<typename T>
void convertFromJson(JsonVariantConst src, optional<T> dst) {
  if (src.is<T>())
    dst.emplace(src.as<T>());
}
}
```

Best regards,
Benoit
