### ISSUE TITLE
How to programmatically add key values 

### ISSUE THREAD

**Issue by cyberbilly** [bblanchon/ArduinoJson#1925]
The following function doesn't work, from my experimentation It appears the the key is not set,  For example if I call 
sendMessage("warning", "State", "unknown");  I would like to get {"Purpose":"warning":"state":"unknown}.
What I get is {}.

void sendMessage( String level, String key, String value){
	DynamicJsonDocument msg(64);
	msg["Purpose"] = level;
	msg[key] = value;
	serializeJson(msg,  Serial);
    Serial.println();		
}

**Comment by bblanchon** [comment]
Hi @cyberbilly,

When you use `String` for keys, the `JsonDocument` copies the string, consuming more space in the memory pool.
To fix this issue, you need to increase the capacity of the memory pool (to 96 in this case).

By default, the [ArduinoJson Assistant](https://arduinojson.org/v6/assistant/) assumes you use only string literals for keys, so it doesn't count the extra bytes needed to copy them. You can change this in the "Tweaks" section of Step 3.

![2023-05-28_19-44-14](https://github.com/bblanchon/ArduinoJson/assets/5462433/b3610c80-2cc6-4576-8b17-8065496bddfd)

Best regards,
Benoit

**Comment by cyberbilly** [comment]
Thank you for your assistance.   You said " By default, the [ArduinoJson Assistant](https://arduinojson.org/v6/assistant/) assumes you use only string literals for keys"  Which I am doing everywhere,  Except for this one little generalized send message function.  In this case at coding time i don't know the key values I want to messages so I would like to use arguments to the function.   I haven't been able to accomplish this.  doc[key] = value.    doesn't work.

**Comment by cyberbilly** [comment]
Okay the print on your screen capture was not readable - who decided light gray was a good font color? and the print is to small /excuses    Any suggestions for getting to this setting on a command line only set up?

My setup is an arduino uno with a serial connection to a La Potato (pi ish running ubuntu),  using arduino-cli to command line compile and upload.  All of this through wifi and a putty terminal....  Is there a linux config file somewhere to edit? Was installed by arduino-cli lib install arduinojson.   don't remember these prompts, but then there is no screen.

**Comment by bblanchon** [comment]
This setting only changes the behavior of the ArduinoJson Assistant.
Again, by default, the Assistant assumes your code only uses string literals to insert members in objects, but this assumption is incorrect in your case so we need to alter the Assistant's behavior.
Apart from the capacity of the `JsonDocument`, there is nothing you need to change in your program.
The fact that you use arduino-cli or any other compilation setup doesn't matter in this case.
