### ISSUE TITLE
Need example for copying 2d byte array to json

### ISSUE THREAD

**Issue by jayateertha043** [bblanchon/ArduinoJson#1933]
Have already checked this, but not sure how to work with 2d array - https://arduinojson.org/v6/api/misc/copyarray/

**Comment by bblanchon** [comment]
Hi @jayateertha043,

I added the following example to the page:

```c++
int values[][3] = {{1, 2, 3}, {4, 5, 6}};

StaticJsonDocument<256> doc;
copyArray(values, doc);
serializeJson(doc, Serial);
```

It will write the following string to the serial port:

```json
[[1,2,3],[4,5,6]]
```

Best regards,
Benoit

**Comment by jayateertha043** [comment]
Thanks!
