### ISSUE TITLE
Get JSON key name

### ISSUE THREAD

**Issue by vmlourenco** [bblanchon/ArduinoJson#1935]
I have the following JSON **data: {"success":"You are welcome"}** that I have named **data** in my code.

When I want to alert You are welcome I do **data["sucess"]**. So now the problem I am facing is that, what about if I want to alert **success**. Is there any way to get it?

**Comment by bblanchon** [comment]
Hi @vmlourenco,

You can enumerate keys in a [`JsonObject`](https://arduinojson.org/v6/api/jsonobject/) with [iterators](https://arduinojson.org/v6/api/jsonobject/begin_end/).
If you have a [`JsonDocument`](https://arduinojson.org/v6/api/jsondocument/), however, you first need to cast it to a [`JsonObject`](https://arduinojson.org/v6/api/jsonobject/).

For example, here is how you would print all the keys at the root of a [`JsonDocument`](https://arduinojson.org/v6/api/jsondocument/):

```c++
for (JsonPair kvp : doc.as<JsonObject>()) {
  Serial.println(kvp.key().c_str());
}
```

Best regards,
Benoit
