### ISSUE TITLE
Need some way to determine if deserialization of float is losing precision or not

### ISSUE THREAD

**Issue by margaretselzer** [bblanchon/ArduinoJson#1936]
I am using JSON to import records to a database. The database uses float for internal representation. I want to be able to check whether the incoming JSON has higher precision than what the `float` is able to accommodate so that I can throw an error/warning during import.

Desired solution?
This is really a complex issue so I am not sure what the best approach is. One thing I thought of is that one could compare the number of (significant) digits in the serialized data to e.g. `std::numeric_digits<FloatT>::max_digits10`. If the serialized data has less (or equal amount) digits it can be safely converted, otherwise not. If this is deemed a feasible approach then having access to the number of digits of a JSON element via some member to `JsonDocument` or `JsonVariant` (when it holds floating point) would be great.

Alternatively there could be some extra info provided with deserialization. `DeserializationError` could have some extra fields that holds information floating point precision overflow when floating point numbers are deserialized. `DeserializationError` should maybe replaced with `DeserializationResult` and that could hold all relevant information about the deserialization: error and info about floating point values.

A third approach could be to have some function to test a conversion before actually doing it or have an overload for deserializeJson that takes some extra parameters where extra conversion info can be unloaded to. That way it would not have any impact on existing functionality but whoever needs it could use it.

In any case, knowing the inside workings of ArduinoJson probably offers a much better solution than what I could come up with here.

**Comment by bblanchon** [comment]
Hi @margaretselzer,

I have to be honest; I have no intention of modifying ArduinoJson to add such a feature.
You can probably call `serializeJson()` to see if it produces the same string as the input, but you may have false positives with this technique.

If I were you, I'd consider transferring these sensitive values as strings instead of floats.
That's what many APIs do when they deal with precise values such as prices and coordinates.

Best regards,
Benoit
