### ISSUE TITLE
How to convert JsonDocument to a string or a char array?

### ISSUE THREAD

**Issue by ghost** [bblanchon/ArduinoJson#1937]
OK, this is my sourc code
```
StaticJsonDocument<512> docTemp;

docTemp.clear();
deserializeJson(docTemp, xSensorData.externChannel[0].data);

params_sensor_value["ch1"] = docTemp;
```

Then you can see the reuslt json, it's all right
```
{
    "sensor": {
        "value": {
            "ch1": {
                "status": "success",
                "waterLevel": "0.508"
            }
        }
    }
}
```

but my cloud server do not support JSON nesting , so I should upload my json like this:
```
{
    "sensor": {
        "value": {
            "ch1": ""status": "success","waterLevel": "0.508""
        }
    }
}
```

Is there any way easily to exchange it?

Thank you for your help!

<img width="733" alt="image" src="https://github.com/bblanchon/ArduinoJson/assets/55439370/6f54be28-7167-4a9d-82c2-b2fd0ee43199">

**Comment by bblanchon** [comment]
Hi @KiraVerSace,

You know the document you want to generate is not a valid JSON document, right?
You should fix your server, but if you cannot, you may be able to generate this ill-formatted document with [serialized()](https://arduinojson.org/v6/api/misc/serialized/).

Best regards,
Benoit

**Comment by ghost** [comment]
Thank you for your help.

**Comment by bblanchon** [comment]
You're welcome, @KiraVerSace!
Thank you for using ArduinoJson.
Don't forget to [cast a star](https://github.com/bblanchon/ArduinoJson/stargazers) to support the project :wink:
