### ISSUE TITLE
Is it possible to pass BLEDevice to serializeJson like serializeJson (doc, BLEDevice)?

### ISSUE THREAD

**Issue by johnleung00** [bblanchon/ArduinoJson#1942]
Trying to send a JSON stream via BLE. Would like to be able to do something like:

```
BLEDevice myBle;
serializeJson(doc, myBle);
```

Error returns as 
 **error: 'class BLEServer' has no member named 'write'**

Right now, I am using character array to send:
```
char ble_stream[128];
serializeJson(doc, ble_stream);
BLE->setValue(ble_stream, size);
BLE->notify();
```
More steps to go but it works. It would be perfect if `serializeJson(doc, myBle)` works too.

**Comment by bblanchon** [comment]
Hi @johnleung00,

`serializeJson()` can only write to classes that support the `Print` interface, which doesn't seem to be the case here.
There is nothing I can do about it.

Best regards,
Benoit
