### ISSUE TITLE
Problem with Json doc size calculation

### ISSUE THREAD

**Issue by johnleung00** [bblanchon/ArduinoJson#1945]
**Describe the issue**  
Tyring to use the following formula to calculate the json doc size of 3 objects in an array with 3 members in each object:
```
const uint16_t capacity = JSON_ARRAY_SIZE(3) + 3 * JSON_OBJECT_SIZE(3);
StaticJsonDocument<capacity> sd_json_doc;
```
The object is described below:
```
{
  "filename": "Lap001.csv",
  "size": 1351824120,
  "date": "2023-07-10 12:25:48"
}
```

Calculated value capacity = 192.

**Environment**  
Here is the environment that I'm using':
* ESP32
* IDE: [MS Visual Studio with VMicro plugin]

**Reproduction**  
Here is a small snippet that demonstrate the problem.
```
///This function search all files from a sd card of *.csv extension. 
///The file list is serialized to sd_json_doc with output exported to char *list.
///The total *.csv file count is returned.

const uint16_t capacity = JSON_ARRAY_SIZE(3) + 3 * JSON_OBJECT_SIZE(3);
StaticJsonDocument<capacity> sd_json_doc;

uint16_t sd_file_list_get(char *list) {

    if (list == NULL) return 0;

    uint16_t file_cnt = 0;
    File root = SD_MMC.open("/");
    File entry;

    while (1) {
        entry = root.openNextFile();

        if (!entry)
            break;

        const char* filename = entry.name();
        std::string s = filename;
        bool csvFound = (s.find(fileExtension) != std::string::npos);

        if (csvFound) {
            
            sd_json_doc[file_cnt]["filename"] = (char *)entry.name();   ///cannot use entry.name() directly, need to cast to (char *)
            sd_json_doc[file_cnt]["size"] = entry.size();

            time_t t = entry.getLastWrite();
            struct tm* tm_info = localtime(&t);
            char buf[26];
            strftime(buf, 26, "%Y-%m-%d %H:%M:%S", tm_info);
            sd_json_doc[file_cnt]["date"] = buf;
            ///uncomment this line if you want to print the raw json message
            //serializeJson(sd_json_doc, Serial); Serial.println();
            file_cnt++;
        }
        entry.close();
    }

    root.close();

    if (file_cnt) {
        size_t _size = measureJson(sd_json_doc);
        serializeJson(sd_json_doc, list, _size);
    }

    return file_cnt;
}
```

**Expected output:**
There are  three .csv files in the sd card for testing at this moment so I expected all three objects in the array will be printed.
```
[{"filename":"Lap001.csv","size":148585,"date":"2023-07-10 12:25:48"},{"filename":"Lap002.csv","size":88840,"date":"2023-07-10 12:26:12"},{"filename":"Lap003.csv","size":160051,"date":"2023-07-10 12:26:50"}]
```
**Program output:**  
 However, if the calculated capacity (192) is used, only two objects are shown with Serial monitor printout. The last element is missing:
`[{"filename":"Lap001.csv","size":148585,"date":"2023-07-10 12:25:48"},{"filename":"Lap002.csv","size":88840,"date":"2023-07-10 12:26:12"}]`

**Question**
So I turned to ArduinoJson Assistant and found the suggested size is 96 bytes for each object. If the same array size of 3 elements is used, the capacity should be 96*3. By enlarging the capacity, all 3 objects are now available.

My question : is there any problem with my formula ?
```
const uint16_t capacity = JSON_ARRAY_SIZE(3) + 3 * JSON_OBJECT_SIZE(3);
StaticJsonDocument<capacity> sd_json_doc;
```

**Comment by bblanchon** [comment]
Hi @johnleung00,

Don't forget that ArduinoJson must also copy all the strings that are not `const char*`.
Your program uses `char*` for `date` and `filename`, so you must increase the `JsonDocument` accordingly.

Best regards,
Benoit
