### ISSUE TITLE
Arudino JSON adding error

### ISSUE THREAD

**Issue by ayeonix** [bblanchon/ArduinoJson#1958]
**Description**
I am unable to add the ArudinoJson library. First of all, it is not showing in the library manager so I downloaded the zip from the official GitHub page but when I am trying to add it, this error is showing: "Error: 13 INTERNAL: Library install failed: archive is not valid: multiple files found in zip file top level" so what shall I do pls tell...

**Troubleshooter's report**
1. The issue happens at compile time
2. The error is not in the list

**Environment**
* Microcontroller: ESP8266

**Comment by bblanchon** [comment]
Hi @anandamalyamukhopadhyay,

The library is available in the Arduino Library Manager under the name "ArduinoJson".
You'll probably need to delete the zip file to get rid of this error.

Best regards,
Benoit
