### ISSUE TITLE
ArduinoJson triggers infinite project configuration when included via symlink in PlatformIO project

### ISSUE THREAD

**Issue by margaretselzer** [bblanchon/ArduinoJson#1968]
**Describe the bug**  
I have to statically link the ArduinoJson library in my PlatformIO project so the actual version I use is located in a sub-folder in the project. I link the library in _platformio.ini_ in the `lib_deps` section. If I link the library as 

```
lib_deps =
    file://path/ArduinoJson
```
all works fine. However if I use a `symlink` 
```
lib_deps =
    symlink://path/ArduinoJson
```
then this triggers PlatformIO to do an infinite loop of project configuration.

Terminal output:
```
Library Manager: Installing symlink://path/ArduinoJson
Library Manager: ArduinoJson@6.21.3 has been installed!
Updating metadata for the vscode IDE...
Project has been successfully updated!
[--- The above four lines repeated multiple times until the process gives up---]

Error: Multiple requests to rebuild the project "controller_project" index have been received!
Automatic index rebuilding process has been terminated for 10 minutes.
at VA.requestRebuild (%USERPROFILE%\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:963897)
	at QA.rebuildIndex ((%USERPROFILE%\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:966099)
	at QA.onDidChangeLibDirs ((%USERPROFILE%\.vscode\extensions\platformio.platformio-ide-3.3.1-win32-x64\node_modules\platformio-node-helpers\dist\index.js:1:967220)
	at n.value ((%USERPROFILE%\.vscode\extensi...
```

Then when actually building the project, the build process is trying to add the library twice every time the project is built:
```
Processing controller_project (board: due; platform: atmelsam; framework: arduino)
---------------------------------------------------------------------------------------------------------------------------------------------------
Library Manager: Installing symlink://path/ArduinoJson
Library Manager: ArduinoJson@6.21.3 has been installed!     
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/atmelsam/due.html
PLATFORM: Atmel SAM (8.2.0) > Arduino Due (Programming Port)
HARDWARE: AT91SAM3X8E 84MHz, 96KB RAM, 512KB Flash
DEBUG: Current (atmel-ice) External (atmel-ice, blackmagic, jlink, stlink)
PACKAGES:
 - framework-arduino-sam @ 1.6.12
 - framework-cmsis @ 1.40500.0 (4.5.0)
 - framework-cmsis-atmel @ 1.2.2
 - toolchain-gccarmnoneeabi @ 1.100301.220327 (10.3.1)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Library Manager: Installing symlink://path/ArduinoJson
Library Manager: ArduinoJson@6.21.3 has been installed!     
Found 16 compatible libraries
Scanning dependencies...
Dependency Graph
...
```

I realize that this is probably as much a PlatformIO issue as ArduinoJson problem, but since other libraries do not trigger this issue it seems that the easier solution is to change in the ArduinoJson library whatever that is that causes the problem than modifying PlatformIO that has to be compatible with potentially all libraries that are out there.

**Troubleshooter report**  
N/A

**Environment**  
Here is the environment that I used:
* Microcontroller: Arduino Due
* Core/runtime: https://github.com/arduino/ArduinoCore-sam, version: 1.6.12
* IDE: VS Code 1.82.1 / PlatformIO Core, version 6.1.11

**Reproduction**  
N/A

**Compiler output**    
N/A

**Program output**  
N/A

Expected output:
When the ArduinoJson library is linked via symlink it should be installed only once when the PlatformIO project is opened or built for the first time.

Actual output:
When the ArduinoJson library is linked via symlink it is installed twice every time the project is built and in addition causes a infinite project configuration loop.

**Comment by bblanchon** [comment]
Hi @margaretselzer,

I don't think there is anything I can do.
Please install the library normally:

```
lib_deps = bblanchon/ArduinoJson@^6.21.3
```

Alternatively, you can download the [single file version](https://github.com/bblanchon/ArduinoJson/releases/download/v6.21.3/ArduinoJson-v6.21.3.h).

Best regards,
Benoit
