### ISSUE TITLE
ArduinoJson USB Packet buffering in STM32Cube C application

### ISSUE THREAD

**Issue by samspencer5991** [bblanchon/ArduinoJson#1971]
**Describe the issue**  
I am currently using ArduinoJSON in a native C application using PlatformIO for an STM32Cube project. I am using a custom writer to invoke TinyUSB CDC output for the serialization. My documents are fairly large, often around 8-12KB. Everything is running well however the performance and related issues of ArduinoJson invoking the writer for heavily fragmented write calls. Because I am not using Arduino, I cannot use the suggestion of StreamUtils to buffer the write. Something like that is an ideal solution though.

Are there any suggestions for being able to: Write the serialization in consecutive chunks (i.e. write it to either an output buffer or my custom writer in 64 byte USB packet chunks until the entire serialization is complete)?

**Environment**  
Here is the environment that I'm using':
* Microconroller: STM32G491
* Core/runtime: STM32Cube
* IDE: PlatformIO

**Comment by bblanchon** [comment]
Hi @samspencer5991,

Indeed, `serializeJson()` doesn't buffer the characters before sending them to the writer.
To improve the performance, you'll have to add a buffer in your writer class.

Best regards,
Benoit

**Comment by samspencer5991** [comment]
Sure, that doesn't address my question specifically though. One issue is there doesn't seem to be a mechanism for the writer to know how many bytes are in the way. Of particular interest is the 64 byte USB packet size which would be ideal for transmitting a full packet over USB. But it can't afford to wait for too long or risk missing the next USB timing frame.

**Comment by bblanchon** [comment]
Why don't you use a 64-byte buffer in your custom writer class and send it as soon as it's full?

**Comment by samspencer5991** [comment]
I thought about that, but the problem is the case where there are less than 64 bytes. Any delay will cause huge delays in sending consecutive large documents, and also risk missing the USB timing frame. Ideally, a dummy serialise function which returns the number of bytes required, then the custom wittier serialise would solve this.

**Comment by bblanchon** [comment]
I would simply send the remaining bytes right after calling `serializeJson()`.
For example, you could add a `flush()` function to your custom writer:

```c++
MyBufferedWriter writer;
serializeJson(doc, writer);
writer.flush();
```

There shouldn't be any delay there.

**Comment by samspencer5991** [comment]
I'm really not sure how that helps sorry. The use case is this. Let's assume that a JSON document consists of several thousand bytes. For optimum efficiency, they should be packed into 64-byte packets, and sent. If the writer functions simply collect a number of bytes, put them into the buffer, and then transmit that as a packet once the buffer is full, what mechanism is there for the writer to know the difference between 38 (for example) bytes in the buffer with more on the way, vs. the last 38 bytes that can be transmitted right away?

**Comment by bblanchon** [comment]
Well, that's what the `flush()` function is here for: it tells the writer to send the last 38 bytes.

**Comment by samspencer5991** [comment]
This perfectly solved my problem, I was completely overthinking things in the trenches of a big code-base re-write. Thanks @bblanchon !

**Comment by bblanchon** [comment]
You're welcome, @samspencer5991!
Thank you for using ArduinoJson.
Don't forget to [cast a star](https://github.com/bblanchon/ArduinoJson/stargazers) to support the project :wink:
