### ISSUE TITLE
Computed capacity discrepancy: Macros vs Assistant

### ISSUE THREAD

**Issue by labodj** [bblanchon/ArduinoJson#1972]
**Describe the bug**  
I'm experiencing a discrepancy in capacity calculation using Macros vs Assistant
I need to calculate the size of the StaticJsonDocument via Macros since the project is configurable at compile time for different devices,  moreover the number of elements is used elsewere to declare static objects with ETL library and many more (since I'm trying to use as little Heap memory as possible)

Take this JSON as example:
```json
{
  "a": "bcdef",
  "gh": [
    false,
    false,
    ...,
    true
  ]
}
```

The "gh" array size is decided at compile time, if I use Assistant with an array of 10 elements, using AVR as arch, Stream as Input and Deserialize mode the result is this (107/128 Bytes):

![image](https://github.com/bblanchon/ArduinoJson/assets/2527836/f341ec64-3641-4a4e-a336-a5a77b58267d)

If I use macros like this
```c++
constexpr uint16_t documentSize = JSON_ARRAY_SIZE(10) + JSON_OBJECT_SIZE(2) + 11U;
```

The result is 395 Bytes, since the ```sizeof(ArduinoJson::detail::VariantSlot))``` is reported as 32 Bytes

**Environment**  
Here is the environment that I used:
* Microcontroller: Arduino Mega2560
* Core/runtime: platform = https://github.com/platformio/platform-atmelavr.git
framework = arduino
* IDE: [Vscode + PlatformIO + AVR-GCC 13.2.0 / c++23 + ArduinoJson 6.21.3 on Manjaro-Linux]

**Comment by bblanchon** [comment]
Hi @labodj,

I just checked with a similar configuration and I find that `sizeof(VariantSlot)` is:

* 8 by default
* 12 if [`ARDUINOJSON_USE_LONG_LONG`](https://arduinojson.org/v6/api/config/use_long_long/) is set to `1`.

I used the following program to check the size:

```c++
#include <ArduinoJson.h>
template <size_t N> void foo();
void setup() { foo<sizeof(ArduinoJson::detail::VariantSlot)>(); }
void loop() {}
```

Here is the output:

```text
Processing mega (platform: atmelavr; board: ATmega2560; framework: arduino)
-----------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/ATmega2560.html
PLATFORM: Atmel AVR (4.2.0) > ATmega2560
HARDWARE: ATMEGA2560 16MHz, 8KB RAM, 256KB Flash
DEBUG: Current (avr-stub) External (avr-stub, simavr)
PACKAGES:
 - framework-arduino-avr-megacore @ 2.2.3
 - toolchain-atmelavr @ 1.70300.191015 (7.3.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 19 compatible libraries
Scanning dependencies...
Dependency Graph
|-- src
Building in release mode
Compiling .pio\build\mega\src\main.cpp.o
Linking .pio\build\mega\firmware.elf
C:\Users\benoi\AppData\Local\Temp\ccpL1CPk.ltrans0.ltrans.o: In function `main':
<artificial>:(.text.startup+0x8c): undefined reference to `void foo<8u>()'
collect2.exe: error: ld returned 1 exit status
```

Please double-check that you are targeting an AVR board.

Best regards,
Benoit

**Comment by labodj** [comment]
Thanks for the fast reply.
I think I got fooled by the IDE intellisense, I'm sorry...
![image](https://github.com/bblanchon/ArduinoJson/assets/2527836/9a51b516-c6bb-470b-929e-dee74ade6f4f)

The compiler output is actually as expected...
```<artificial>:(.text.startup+0xe0): undefined reference to `void foo<8u>()'```

**Comment by bblanchon** [comment]
You're welcome, @labodj!
Thank you for using ArduinoJson.
Don't forget to [cast a star](https://github.com/bblanchon/ArduinoJson/stargazers) to support the project :wink:
