### ISSUE TITLE
This constant expression has type "const char *" instead of the required "unsigned int" type

### ISSUE THREAD

**Issue by DuCLeK65t** [bblanchon/ArduinoJson#1974]
This is my code:

<pre>
const size_t capacity = JSON_OBJECT_SIZE(2) + JSON_OBJECT_SIZE(3);
DynamicJsonDocument jsonBuffer(capacity);

doc["datatype"] = "string";
</pre>

I do not understand why this cause
<pre>this constant expression has type "const char *" instead of the required "unsigned int" type</pre>

one the line
<pre>doc["datatype"] = "string";</pre>

Can anyone help me? Thank you!

**Comment by bblanchon** [comment]
Hi @DuCLeK65t,

I think you mixed up the names `jsonBuffer` and `doc`.

Best regards,
Benoit

**Comment by DuCLeK65t** [comment]
> Hi @DuCLeK65t,
> 
> I think you mixed up the names `jsonBuffer` and `doc`.
> 
> Best regards, Benoit

Oh thank you @bblanchon, my mistake
I've modified it but actually it has the same error:
![image](https://github.com/bblanchon/ArduinoJson/assets/71594219/12fbddef-dbd7-4d4d-9c1f-7cf468752501)

**Comment by DuCLeK65t** [comment]
Oh i've understand, those code lines didn't work because i put it in *.h file
