### ISSUE TITLE
error: 'ArduinoJson::V6213PB2::JsonDocument::JsonDocument()' is protected within this context    JsonDocument doc;

### ISSUE THREAD

**Issue by VichikovD** [bblanchon/ArduinoJson#1980]
**Description**
Just run example code for serializing and get following during compiling
C:\Users\User\AppData\Local\Temp\.arduinoIDE-unsaved2023913-23232-d57l7w.ckwiu\sketch_oct13b\sketch_oct13b.ino: In function 'void setup()':
C:\Users\User\AppData\Local\Temp\.arduinoIDE-unsaved2023913-23232-d57l7w.ckwiu\sketch_oct13b\sketch_oct13b.ino:10:16: error: 'ArduinoJson::V6213PB2::JsonDocument::JsonDocument()' is protected within this context
   JsonDocument doc;
                ^~~
In file included from c:\Users\User\IdeaProjects\Arduino\libraries\ArduinoJson\src/ArduinoJson/Document/BasicJsonDocument.hpp:7,
                 from c:\Users\User\IdeaProjects\Arduino\libraries\ArduinoJson\src/ArduinoJson/Document/DynamicJsonDocument.hpp:7,
                 from c:\Users\User\IdeaProjects\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:33,
                 from c:\Users\User\IdeaProjects\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,
                 from C:\Users\User\AppData\Local\Temp\.arduinoIDE-unsaved2023913-23232-d57l7w.ckwiu\sketch_oct13b\sketch_oct13b.ino:1:
c:\Users\User\IdeaProjects\Arduino\libraries\ArduinoJson\src/ArduinoJson/Document/JsonDocument.hpp:280:3: note: declared protected here
   JsonDocument() : pool_(0, 0) {}
   ^~~~~~~~~~~~
C:\Users\User\AppData\Local\Temp\.arduinoIDE-unsaved2023913-23232-d57l7w.ckwiu\sketch_oct13b\sketch_oct13b.ino:10:16: error: 'ArduinoJson::V6213PB2::JsonDocument::~JsonDocument()' is protected within this context
   JsonDocument doc;
                ^~~
In file included from c:\Users\User\IdeaProjects\Arduino\libraries\ArduinoJson\src/ArduinoJson/Document/BasicJsonDocument.hpp:7,
                 from c:\Users\User\IdeaProjects\Arduino\libraries\ArduinoJson\src/ArduinoJson/Document/DynamicJsonDocument.hpp:7,
                 from c:\Users\User\IdeaProjects\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:33,
                 from c:\Users\User\IdeaProjects\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,
                 from C:\Users\User\AppData\Local\Temp\.arduinoIDE-unsaved2023913-23232-d57l7w.ckwiu\sketch_oct13b\sketch_oct13b.ino:1:
c:\Users\User\IdeaProjects\Arduino\libraries\ArduinoJson\src/ArduinoJson/Document/JsonDocument.hpp:286:3: note: declared protected here
   ~JsonDocument() {}
   ^

exit status 1

Compilation error: 'ArduinoJson::V6213PB2::JsonDocument::JsonDocument()' is protected within this context

**Troubleshooter's report**
1. The program uses ArduinoJson 6
2. The issue happens at compile time
3. The error is not in the list

**Environment**
* Microcontroller: ESP32
* IDE: Arduino IDE 2.2.1

**Reproduction code**
```c++
#include <ArduinoJson.h>

void setup() {
  // Initialize Serial port
  Serial.begin(9600);
  while (!Serial)
    continue;

  // Allocate the JSON document
  JsonDocument doc;

  // Add values in the document
  doc["sensor"] = "gps";
  doc["time"] = 1351824120;

  // Add an array.
  JsonArray data = doc["data"].to<JsonArray>();
  data.add(48.756080);
  data.add(2.302038);

  // Generate the minified JSON and send it to the Serial port.
  serializeJson(doc, Serial);
  // The above line prints:
  // {"sensor":"gps","time":1351824120,"data":[48.756080,2.302038]}

  // Start a new line
  Serial.println();

  // Generate the prettified JSON and send it to the Serial port.
  serializeJsonPretty(doc, Serial);
  // The above line prints:
  // {
  //   "sensor": "gps",
  //   "time": 1351824120,
  //   "data": [
  //     48.756080,
  //     2.302038
  //   ]
  // }
}

void loop() {
  // not used in this example
}
```

**Comment by bblanchon** [comment]
Hi @VichikovD,

This code looks like [the example for ArduinoJson 7](https://arduinojson.org/v7/example/generator/).
Please use [the example for ArduinoJson 6](https://arduinojson.org/v6/example/generator/) instead, or [install ArduinoJson 7](https://arduinojson.org/v7/how-to/install-arduinojson/).

Best regards,
Benoit
