### ISSUE TITLE
Header only library

### ISSUE THREAD

**Issue by bblanchon** [bblanchon/ArduinoJson#199]
Arduino, PlatformIO, Stino, Energia... enough!
I'm tired of the packaging issues.
Let's go header only.

**Comment by DinoStray** [comment]
I wonder, there are so many files in src/ArduinoJson, how do you make them to only one header flie ? Which tool helps you, CMake?
I'd like you to  help me solve the problem, please

**Comment by bblanchon** [comment]
Hi @DinoStray,

I use this horrible bash script:
https://github.com/bblanchon/ArduinoJson/blob/master/scripts/build-single-header.sh

It very slow, so I was planning on writing a C++ version.
Would you be interested, or is the script sufficient?

Regards,
Benoit

**Comment by DinoStray** [comment]
I try to use the bash script, it's amazing.
I think the script is sufficient!
