### ISSUE TITLE
MCUXpresso IDE importing Error 

### ISSUE THREAD

**Issue by GanesanGuru** [bblanchon/ArduinoJson#1991]
Hi @bblanchon & all ,

I've been trying to add this repo to MCUXpresso IDE and I've added the files in include paths for both C/C++ Compilers, as follows:
![Screenshot from 2023-11-09 10-38-10](https://github.com/bblanchon/ArduinoJson/assets/26476060/e1e6c44d-2a26-4cee-b010-019208d8d131)
![Screenshot from 2023-11-09 10-37-14](https://github.com/bblanchon/ArduinoJson/assets/26476060/35106e26-1ca5-4a96-8e5e-9ad5fd6842a5)
Yet, I'm getting this error - How to resolve this error?
![Screenshot from 2023-11-09 10-41-54](https://github.com/bblanchon/ArduinoJson/assets/26476060/d5e45f1c-c3b4-4878-8a32-a87ccb4293a9)

**Comment by bblanchon** [comment]
Hi @GanesanGuru,

You close this issue, so I'm assuming you found the solution.

For anyone else encountering this issue, I recommend downloading the single file version of ArduinoJson (sometimes called the "single file distribution" or "single header").
You can find the link on this page: https://arduinojson.org/v6/doc/installation/

Best regards,
Benoit
