### ISSUE TITLE
Parsing from a Stream

### ISSUE THREAD

**Issue by fishix10** [bblanchon/ArduinoJson#200]
Hi. I'm trying to parse json on the ESP8266. I've been using the aJson library, but run into memory issues constantly. I'm trying to switch to ArduinoJson.

My understanding is that you need the json to be in a string first for ArduinoJson to parse it. I'm wondering if there's a way I could parse it out of a Stream (like in aJson).

Thanks a lot!

EDIT: Ah never mind. I just had a chance to thoroughly read the document. Just to make sure I understand this, this means that if I have a string in my json and I do something like, `const char* sensor = root["sensor"];`, then I need to keep the whole origin string (`char json[]` in the example) all the time while I still need access to `sensor`, right?

**Comment by bblanchon** [comment]
Hi,

Sorry, for the long delay, I wrote an answer at the time but it has probably got lost in a Chrome tab :-).

Yes, you are exactly right, the JSON variable need to stay in memory and needs to be mutable.
As a matter of fact, the `sensor` variable will point to a location in that string.

I added this to the FAQ:
https://github.com/bblanchon/ArduinoJson/wiki/FAQ#can-i-parse-data-from-a-stream
