### ISSUE TITLE
Compile Problem

### ISSUE THREAD

**Issue by RayzxMx** [bblanchon/ArduinoJson#2009]
**Description**
when i use arduinojson version 6, it's show xtensa-lx106-elf-g++: error: unrecognized command-line option '-cppflags'
exit status 1
Error compiling for board NodeMCU 0.9 (ESP-12 Module).
but if i use arduinojson version 5 it's don't show error. i need use version 6 because i want to use dynamicjson 

**Troubleshooter's report**
1. The program uses ArduinoJson 6
2. The issue happens at compile time
3. The error is not in the list

**Environment**
* Microcontroller: ESP8266
* Core/Framework: Node MCU 0.9 (ESP-12 Module)
* IDE: Arduino IDE 1.8.9

**Comment by bblanchon** [comment]
Hi @RayzxMx,

This looks like a problem with the [Arduino Core for ESP8266](https://github.com/esp8266/Arduino).
Please try to upgrade or downgrade the core.
If nothing works, please contact them.

Best regards,
Benoit
