### ISSUE TITLE
help delay with webserver

### ISSUE THREAD

**Issue by anwfeb** [bblanchon/ArduinoJson#2013]
#include <ESP8266WiFi.h>
  #include <ESP8266WebServer.h>
  #include <ESP8266HTTPClient.h>
  ESP8266WebServer webServer(80);
  
  i am running webserver together with arduino json for httpclient, the problem is i feel there is some kind of blocking/delay when i use it together with webServer.handleClient(); then I can't open the webserver. i have used millis for json, but i keep seeing blocking for webserver.
  
  
 `
 //
 void updateDatabaseWithEEPROM() {
  // Check if it's time to send data
  unsigned long CurrentMillis = millis();
  if (CurrentMillis - previousSendMillis >= sendDataInterval) {
    // Update the previous send time
    previousSendMillis = CurrentMillis;

    // Create a JSON object to hold all GPIO data
    DynamicJsonDocument jsonDoc(1024);
    JsonObject dataObject = jsonDoc.createNestedObject("data");

    JsonObject boardData = dataObject.createNestedObject(String(chipid)); // Board is chipid
    JsonArray gpioArray = boardData.createNestedArray("gpio_data");

    // Iterate through each GPIO pin
    for (int i = 0; i < NUM_PINS; i++) {
      // Read the state from EEPROM
      int state = EEPROM.read(EEPROM_ADDR[i]);

      // Create a JSON object for each GPIO pin
      JsonObject gpioObject = gpioArray.createNestedObject();
      gpioObject["gpio"] = String(PIN_ARRAY[i]);
      gpioObject["state"] = String(state);
    }

    // Convert JSON object to a string
    String postData;
    serializeJson(jsonDoc, postData);

    Serial.println("Sending POST data: " + postData);

    // Perform an HTTP POST request
    httpsPOSTRequest(server, postData);
  }
}
//`

when I set sendDataInterval to 10000 (10s) the webserver can be run even though it is slow, but if the sendDataInterval is 3000 (3s) at all I cannot run the webServer.

**Comment by bblanchon** [comment]
Hi @anwfeb,

What makes you think this problem is related to ArduinoJson?

Best regards,
Benoit
