### ISSUE TITLE
Help on optimization

### ISSUE THREAD

**Issue by ScreamZ** [bblanchon/ArduinoJson#2015]
Hello,

I'm really new to cpp and coming from nodeJS / React background with JavaScript.

Currently, I'm connected to a websocket and I receive the payload as follows with a `uint8_t`

```ino
StaticJsonDocument<1024> stateExtractor; // Used to extract WS data into JSON. Adjust size depending on doc size.
JsonObject deviceState; // The synced device state

void onServerEvent(uint8_t *payload, size_t length) {
  // Ignore non-document notification of device state
  if (strstr((char *)payload, ("\"_id\":\"" + deviceID + "\"").c_str()) == NULL)
    return;

  StaticJsonDocument<48> filter;
  filter["result"]["_source"] = true;
  Serial.println((char *)payload);

  DeserializationError error = deserializeJson(stateExtractor, (const char*)payload, length, DeserializationOption::Filter(filter));
  Serial.println(error.c_str());
  deviceState = stateExtractor["result"]["_source"];
}
```

I've been forced to use `(const char*)payload` otherwise as `payload` is a pointer, the value was changed on every new WebSocket message.

But it's written that this is a bad practice to use char*, what do you suggests? I've read about buffer in your doc ? Not sure how to use it ?

Regards

**Comment by bblanchon** [comment]
Hi @ScreamZ,

The documentation doesn't mention it, but [`deserializeJson()`](https://arduinojson.org/v6/api/json/deserializejson/) makes no difference between `uint8_t*` and `char*`.

In ArduinoJson 6, `deserializeJson()` treats `char*` and `const char*` differently.
`char*` enables the zero-copy mode, whereas `const char*` doesn't.
In the zero-copy mode, the `JsonDocument` stores pointers to the input buffer instead of making copies.
In your case, using the zero-copy mode is safe since the `JsonDocument` is scoped to the callback function, so you should use `char*`.

Best regards,
Benoit

**Comment by ScreamZ** [comment]
Hi Benoit, thanks for your answer.

For some reason using char* results in a crash, I suspect that's because my `payload` is changing and sometimes it's a different JSON. (see the early return statement). 

I must be a bad one because I'm making a long-living JSON document (called `deviceState`) that is a synchronized JSON object used to change my loop code accordingly. I guess it's better if I use other variables and just use the JSON while decoding ?

Otherwise using a const without zero-copy mode makes it work. ~I'll maybe stick with this for the moment.~

**EDIT 1:** After reading that will try to use an additional struct for my state https://arduinojson.org/v6/faq/why-must-i-create-a-separate-config-object/.

**EDIT1-BIS** : I've switched my code to
```cpp
struct DeviceState {
  char lightMode[32];
  char ballState[32];
  char pullerState[32];
  bool africanMasksPowered;
};   

DeviceState deviceState; // The synced device state

void webSocketEvent(WStype_t type, uint8_t *payload, size_t length) {
  switch (type) {
    case WStype_ERROR:
      Serial.printf("WebSocket error: %s.\n", payload);
      break;
    case WStype_DISCONNECTED:
      Serial.println("Websocket disconnected, will try reconnect.");
      break;
    case WStype_CONNECTED:
      Serial.println("WebSocket connected.");
      onConnected();
      break;
    case WStype_TEXT:
      // Ignore non-document notification of device state
      if (strstr((char *)payload, ("\"_id\":\"" + deviceID + "\"").c_str()) == NULL)
        return;

      StaticJsonDocument<JSON_DOCUMENT_SIZE> stateExtractor;
      StaticJsonDocument<48> filter;
      filter["result"]["_source"] = true;

      DeserializationError error = deserializeJson(stateExtractor, payload, length, DeserializationOption::Filter(filter));
      if (error) {
        Serial.print("JSON Decoding error: ");
        Serial.println(error.c_str());
        return;
      } else {
        Serial.println("Device state has been updated.");
        hasLoadedInitialState = true;
      }
      onRemoteStateSync(stateExtractor);
      break;
  }
}

void onRemoteStateSync(JsonDocument& docNotification)
{
  deviceState.africanMasksPowered = docNotification["result"]["_source"]["africanMasksPowered"];
  strlcpy(deviceState.lightMode, docNotification["result"]["_source"]["lightMode"], sizeof(deviceState.lightMode));
  strlcpy(deviceState.ballState, docNotification["result"]["_source"]["ballState"], sizeof(deviceState.ballState));
  strlcpy(deviceState.pullerState, docNotification["result"]["_source"]["pullerState"], sizeof(deviceState.pullerState));
}
```

**EDIT2:** J'aime beaucoup la philosophie derrière ta librairie et comment sont réalisés la doc, les tuto et le support que tu fournis. Du coup j'ai acheté le bouquin en soutien, c'est la première fois que je fais ça ! Merci @bblanchon  pour ton boulot. Au plaisir d'échanger un jour! (Compliqué le saut en C++ quand mes derniers course de bas niveau remontent à la fac).

**Comment by bblanchon** [comment]
I'm sorry; I focused so much on the original question about `char*` that I completely missed the fact that your document was global. Indeed, in this case, you must **not** use the zero-copy mode.

By the way, I removed the zero-copy mode in ArduinoJson 7, so you can remove the cast after updating.

Thank you very much for purchasing my book; your support is greatly appreciated ❤️

**Comment by ScreamZ** [comment]
@bblanchon That's a HUGE change in paradigm (you previously recommended to use stack instead of heap as I'm reading book 6)

I'm starting a new project on ESP32, is it stable or release candidate to use 7?

**Comment by bblanchon** [comment]
Yes, I recommend that you start with version 7 right away.
