### ISSUE TITLE
`volatile bool` serialized as `1` or `0` instead of `true` or `false`

### ISSUE THREAD

**Issue by mathieucarbou** [bblanchon/ArduinoJson#2029]
Everything in the title ;-)

Version: `bblanchon/ArduinoJson @ 6.21.4`

Note: workaround can be to use a getter method returning `bool`.

**Comment by bblanchon** [comment]
Hi Mathieu,

Thank you very much for reporting this bug ❤️ 
I love it when users find stuff like that.

Best regards,
Benoit

**Comment by bblanchon** [comment]
The fix was published in ArduinoJson [6.21.5](https://github.com/bblanchon/ArduinoJson/releases/tag/v6.21.5) and [7.0.1](https://github.com/bblanchon/ArduinoJson/releases/tag/v7.0.1).

**Comment by mathieucarbou** [comment]
Thanks a lot, this was fast lol ;-)

**Comment by mathieucarbou** [comment]
Fix just tested. It works 👍
