### ISSUE TITLE
Broken link in a given error.

### ISSUE THREAD

**Issue by ForrestFire0** [bblanchon/ArduinoJson#2032]
**Describe the bug**  
This link https://arduinojson.org/v7/invalid-input/ is broken. It appeared in my console here: 

.pio/libdeps/esp32dev/ArduinoJson/src/ArduinoJson/Deserialization/Reader.hpp:22:21: error: 'struct twai_message_t' has no member named 'read'
   22 |     return source_->read();  // Error here? See https://arduinojson.org/v7/invalid-input/

I am understand the error and do not need help debugging, just thought I would shout out that this link is broken. Seems like a quick fix to update it to https://arduinojson.org/troubleshooter/#v7/compiletime/class-has-no-member-named-read or something link it.

**Troubleshooter report**  
Here is the report generated by the [ArduinoJson Troubleshooter](https://arduinojson.org/v7/troubleshooter/):  
n/a

**Environment**  
n/a
**Reproduction**  
n/a

**Compiler output**    
In file included from .pio/libdeps/esp32dev/ArduinoJson/src/ArduinoJson/Deserialization/deserialize.hpp:9,
                 from .pio/libdeps/esp32dev/ArduinoJson/src/ArduinoJson/Json/JsonDeserializer.hpp:7,
                 from .pio/libdeps/esp32dev/ArduinoJson/src/ArduinoJson.hpp:47,
                 from .pio/libdeps/esp32dev/ArduinoJson/src/ArduinoJson.h:9,
                 from src/MANCTRL.h:22,
                 from src/main.cpp:13:
.pio/libdeps/esp32dev/ArduinoJson/src/ArduinoJson/Deserialization/Reader.hpp: In instantiation of 'int ArduinoJson::V700PB2::detail::Reader<TSource, Enable>::read() [with TSource = twai_message_t; Enable = void]':
.pio/libdeps/esp32dev/ArduinoJson/src/ArduinoJson/Json/Latch.hpp:38:25:   required from 'void ArduinoJson::V700PB2::detail::Latch<TReader>::load() [with TReader = ArduinoJson::V700PB2::detail::Reader<twai_message_t, void>]'
.pio/libdeps/esp32dev/ArduinoJson/src/ArduinoJson/Json/Latch.hpp:30:7:   required from 'char ArduinoJson::V700PB2::detail::Latch<TReader>::current() [with TReader = ArduinoJson::V700PB2::detail::Reader<twai_message_t, void>]'
.pio/libdeps/esp32dev/ArduinoJson/src/ArduinoJson/Json/JsonDeserializer.hpp:47:26:   required from 'char ArduinoJson::V700PB2::detail::JsonDeserializer<TReader>::current() [with TReader = ArduinoJson::V700PB2::detail::Reader<twai_message_t, void>]'
.pio/libdeps/esp32dev/ArduinoJson/src/ArduinoJson/Json/JsonDeserializer.hpp:71:13:   required from 'ArduinoJson::V700PB2::DeserializationError::Code ArduinoJson::V700PB2::detail::JsonDeserializer<TReader>::parseVariant(ArduinoJson::V700PB2::detail::VariantData&, TFilter, ArduinoJson::V700PB2::DeserializationOption::NestingLimit) [with TFilter = ArduinoJson::V700PB2::detail::AllowAllFilter; TReader = ArduinoJson::V700PB2::detail::Reader<twai_message_t, void>]'
.pio/libdeps/esp32dev/ArduinoJson/src/ArduinoJson/Json/JsonDeserializer.hpp:35:23:   required from 'ArduinoJson::V700PB2::DeserializationError ArduinoJson::V700PB2::detail::JsonDeserializer<TReader>::parse(ArduinoJson::V700PB2::detail::VariantData&, TFilter, ArduinoJson::V700PB2::DeserializationOption::NestingLimit) [with TFilter = ArduinoJson::V700PB2::detail::AllowAllFilter; TReader = ArduinoJson::V700PB2::detail::Reader<twai_message_t, void>]'
.pio/libdeps/esp32dev/ArduinoJson/src/ArduinoJson/Deserialization/deserialize.hpp:58:24:   required from 'ArduinoJson::V700PB2::DeserializationError ArduinoJson::V700PB2::detail::doDeserialize(TDestination&&, TReader, TOptions) [with TDeserializer = JsonDeserializer; TDestination = ArduinoJson::V700PB2::JsonDocument&; TReader = Reader<twai_message_t, void>; TOptions = DeserializationOptions<AllowAllFilter>]'
.pio/libdeps/esp32dev/ArduinoJson/src/ArduinoJson/Deserialization/deserialize.hpp:69:38:   required from 'ArduinoJson::V700PB2::DeserializationError ArduinoJson::V700PB2::detail::deserialize(TDestination&&, TStream&&, Args ...) [with TDeserializer = JsonDeserializer; TDestination = ArduinoJson::V700PB2::JsonDocument&; TStream = twai_message_t&; Args = {}; <template-parameter-1-5> = void]'
.pio/libdeps/esp32dev/ArduinoJson/src/ArduinoJson/Json/JsonDeserializer.hpp:679:39:   required from 'typename ArduinoJson::V700PB2::detail::enable_if<ArduinoJson::V700PB2::detail::is_deserialize_destination<TDestination>::value, ArduinoJson::V700PB2::DeserializationError>::type ArduinoJson::V700PB2::deserializeJson(TDestination&&, Args&& ...) [with TDestination = JsonDocument&; Args = {twai_message_t&}; typename detail::enable_if<detail::is_deserialize_destination<TDestination>::value, DeserializationError>::type = DeserializationError]'
src/MANCTRL.h:89:28:   required from here
.pio/libdeps/esp32dev/ArduinoJson/src/ArduinoJson/Deserialization/Reader.hpp:22:21: error: 'struct twai_message_t' has no member named 'read'
   22 |     return source_->read();  // Error here? See https://arduinojson.org/v7/invalid-input/

**Program output**  
n/a

**Comment by bblanchon** [comment]
Hi @ForrestFire0,

Thank you very much for reporting this broken link.
It should be fixed now.

Best regards,
Benoit
