### ISSUE TITLE
Broken link in compiler error message

### ISSUE THREAD

**Issue by arjenhiemstra** [bblanchon/ArduinoJson#2035]
**Describe the bug**  
Just a small little issue. When triggering an invalid conversion error message during compiling, the compiler error message points to a page on your website.
` class InvalidConversion;  // Error here? See https://arduinojson.org/v7/invalid-conversion/`
[https://arduinojson.org/v7/invalid-conversion/](https://arduinojson.org/v7/invalid-conversion/)

Unfortunately this link results in a 404 message on your site.

===
I'll cap the rest of the template because I think in this case it would only clutter this report imho.

**Comment by bblanchon** [comment]
Hi @arjenhiemstram

Thank you very much for reporting this issue.
It should be fixed now.

Best regards,
Benoit
