### ISSUE TITLE
Precise the meaning of `doc.overflowed()` with the default allocator with ArduinoJson 7

### ISSUE THREAD

**Issue by mathieucarbou** [bblanchon/ArduinoJson#2037]
I may have missed it, but I do not see on the website the meaning of `doc.overflowed()` with the default allocator.

I currently have in the code: `assert(!doc.overflowed())`, because my hypothesis is that of the document overflows it means no more allocation on heap is possible, so pretty much all the application heap has been used and in such case any attempt to add more items in the document would fail.

Is this right ? Or the overflowed happens way before the system heap is depleted ?

**Comment by bblanchon** [comment]
Hi @mathieucarbou,

Thank you for reporting this issue.
Indeed, the documentation was an awful copy-and-paste from version 6.

I updated the page; let me know if it needs improvements.
https://arduinojson.org/v7/api/jsondocument/overflowed/

Best regards,
Benoit

**Comment by mathieucarbou** [comment]
Thanks! So if I take the example of ArduinoJson 7, and  I get an overflowed() after adding an object to an array, can I still safely remove the last entry and serialize the existing document, or these steps would block ?

**Comment by mathieucarbou** [comment]
Do you know btw when a 7.0.2 will be available with the fix for clear() ? I could use it in such case.

**Comment by bblanchon** [comment]
> can I still safely remove the last entry

Of course!

> when a 7.0.2 will be available

I published it a few minutes ago; it could take a few hours before it's available on Arduino's IDE.
