### ISSUE TITLE
JSON File bigger than 16384 entrys

### ISSUE THREAD

**Issue by Hundsi11** [bblanchon/ArduinoJson#2047]
**Description**
I am meassuring 16384 samples with an ADXL357 acceleration sensor. I have 4 JsonArrays (time, x, y, z) and try to serialize them to read the json with a python skript. The problem is that the Json file gets cut at 16383 entrys. To make that clear: the first entry is the title and then i get 16383 entrys of data. so the last meassurement is missing. It works perfectly fine with less than 16382 samples. I use a ESP32-WROVER and use the PSRAM. So RAM is not the issue. 

**Troubleshooter's report**
1. The program uses ArduinoJson 7
2. The issue happens at run time
3. The issue concerns serialization
4. Output is incomplete
5. `JsonDocument::overflowed()` returns `true`
6. Freeing some memory doesn't solve the issue.

**Environment**
* Microcontroller: ESP32-WROVER
* Core/Framework: ESP32 Core for Arduino IDE
* IDE: Arduine IDE 2.2.1

**Reproduction code**
```c++
#include <ArduinoJson.h>  // Bibliothek für JSON
#include <PL_ADXL355.h>   // Bibliothek für den ADXL355 Sensor

const int sampleSize = 16384;
const unsigned long sampleInterval = 0.151; // Ungefähr 6600 Werte pro Sekunde bei 0,151 ms
const int sendInterval = 10000; // 10 Sekunden

PL::ADXL355 adxl355(5); // Initialisierung des ADXL355 mit dem CS-Pin
auto range = PL::ADXL355_Range::range2g; // Einstellung des Messbereichs

void setup() {
  Serial.begin(460800);
  adxl355.begin();
  adxl355.setRange(range);
  adxl355.enableMeasurement();
  delay(10000);
}

void loop() {
  Serial.println("Start Samples");
  
  // Verwenden Sie DynamicJsonDocument mit einer ausreichenden Größe
  DynamicJsonDocument doc(4194304); // Größe anpassen, je nach Bedarf

  JsonArray t = doc.createNestedArray("t");
  JsonArray x = doc.createNestedArray("x");
  JsonArray y = doc.createNestedArray("y");
  JsonArray z = doc.createNestedArray("z");

  for (int i = 0; i < sampleSize; i++) {
    unsigned long startTime = micros();

    auto accelerations = adxl355.getAccelerations();
    t.add(startTime);
    x.add(accelerations.x);
    y.add(accelerations.y);
    z.add(accelerations.z);

    while (micros() - startTime < sampleInterval) {}
  }
  
  Serial.println(doc.overflowed());

  serializeJson(doc, Serial);
  Serial.println();
  delay(sendInterval);
}
```

**Remarks**
I need a sample size of 16384 to work with so less than that is not an option

**Comment by bblanchon** [comment]
Hi @Hundsi11,

Please apologize for the late answer.

Due to an optimization, a `JsonDocument` can only contain up to 65,535 nodes on a 32-bit CPU.
A node is a value, a key, or a member of an array.

You can push this limit by increasing `ARDUINOJSON_SLOT_ID_SIZE`, like so:

```cpp
#define ARDUINOJSON_SLOT_ID_SIZE 4
#include <ArduinoJson.h>
```

This will increase the limit to 4,294,967,295 nodes, but the memory consumption will increase by 50%.

Best regards,
Benoit

**Comment by bblanchon** [comment]
Alternatively, you could use `String`s to store the huge arrays, and insert them in the document with [`serialized()`](https://arduinojson.org/v7/api/misc/serialized/).

**Comment by Hundsi11** [comment]
Thank you for the quick answer :) it worked

**Comment by bblanchon** [comment]
You're welcome, @Hundsi11!
Thank you for using ArduinoJson.
Don't forget to [cast a star](https://github.com/bblanchon/ArduinoJson/stargazers) to support the project :wink:
