### ISSUE TITLE
#include <bits/error_constants.h> : exit status 1

### ISSUE THREAD

**Issue by ocvawidi** [bblanchon/ArduinoJson#2059]
In file included from c:\users\ocva widi saputra\appdata\local\arduino15\packages\esp32\tools\xtensa-esp32-elf-gcc\esp-2021r2-patch5-8.4.0\xtensa-esp32-elf\include\c++\8.4.0\bits\ios_base.h:46,
                 from c:\users\ocva widi saputra\appdata\local\arduino15\packages\esp32\tools\xtensa-esp32-elf-gcc\esp-2021r2-patch5-8.4.0\xtensa-esp32-elf\include\c++\8.4.0\ios:42,
                 from c:\users\ocva widi saputra\appdata\local\arduino15\packages\esp32\tools\xtensa-esp32-elf-gcc\esp-2021r2-patch5-8.4.0\xtensa-esp32-elf\include\c++\8.4.0\ostream:38,
                 from c:\Users\Ocva Widi Saputra\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Strings/JsonString.hpp:8,
                 from c:\Users\Ocva Widi Saputra\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Strings/Adapters/JsonString.hpp:8,
                 from c:\Users\Ocva Widi Saputra\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Strings/StringAdapters.hpp:8,
                 from c:\Users\Ocva Widi Saputra\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Memory/StringPool.hpp:11,
                 from c:\Users\Ocva Widi Saputra\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Memory/ResourceManager.hpp:8,
                 from c:\Users\Ocva Widi Saputra\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Variant/JsonVariantConst.hpp:10,
                 from c:\Users\Ocva Widi Saputra\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Variant/VariantRefBase.hpp:9,
                 from c:\Users\Ocva Widi Saputra\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Array/ElementProxy.hpp:7,
                 from c:\Users\Ocva Widi Saputra\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Array/JsonArray.hpp:7,
                 from c:\Users\Ocva Widi Saputra\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:29,
                 from c:\Users\Ocva Widi Saputra\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,
                 from D:\Projek GGR\Ujicoba ESP32-CAM\ESP32_CAM_to_GDrive\ESP32_CAM_to_GDrive.ino:11:
c:\users\ocva widi saputra\appdata\local\arduino15\packages\esp32\tools\xtensa-esp32-elf-gcc\esp-2021r2-patch5-8.4.0\xtensa-esp32-elf\include\c++\8.4.0\system_error:39:10: fatal error: bits/error_constants.h: No such file or directory
 #include <bits/error_constants.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: exit status 1

I don't know what the problem is. Please tell me how to fix it

**Comment by bblanchon** [comment]
Hi @ocvawidi,

What did the [ArduinoJson Troubleshooter](https://arduinojson.org/troubleshooter/) say?

Best regards,
Benoit
