### ISSUE TITLE
Identifying JsonVariant type of a deserialized document

### ISSUE THREAD

**Issue by HamzaHajeir** [bblanchon/ArduinoJson#2086]
Hi

I'm building an entity for serializing/deserializing from/to multiple formats for unknown schemes, one of them is JSON.

Over deserialization, I want to detect whether a `JsonVariant` holds an array by calling: 

```cpp
    std::string data; // The data source
    DynamicJsonDocument doc(1024);
    deserializeJson(doc, data);
    JsonObject root = doc.as<JsonObject>();
    for (JsonPair kv : root){
        std::string out_single;
        std::vector<std::string> out_multiple;
        if (kv.value().getData()->isArray()) /* Append out_multiple by looping inside it */;
        else out_single = kv.value().as<std::string>(); // It's an element, just use this instruction to fetch it.
    }
```

However, I can't perform this operation due to `getData()` method being unaccessable. 

How can I perform such target using ArduinoJson (I'm on v6, but assume the latest: v7).

With Thanks,
Hamza Hajeir

**Comment by bblanchon** [comment]
`kv.value().is<JsonArray>()`

**Comment by HamzaHajeir** [comment]
> `kv.value().is<JsonArray>()`

Great, and getting it as array would be 
`kv.value().as<JsonArray>()`.

It'd be also great to add this to docs or examples ;)

**Comment by bblanchon** [comment]
The documentation already says that `kv.value()` is a `JsonVariant`.
What else do you need, and on which page?

**Comment by HamzaHajeir** [comment]
It's obviously clear to people already familiar with the library's design.

But to my experience, I couldn't find the solution in docs nor examples.
But I've just found it under API Reference looking for `is<>()`, well, I
wasn't aware of it.

Hope it helps.
Hamza
