### ISSUE TITLE
Trying to compile a 2021 program

### ISSUE THREAD

**Issue by dranem50260** [bblanchon/ArduinoJson#2096]
**Description**
OWM is obsoleting one call 2.5. Trying to recompile the code, I end up with compilation errors. Please help.

**Troubleshooter's report**
1. The program uses ArduinoJson 7
2. The issue happens at compile time
3. The error is not in the list

**Environment**
* Microcontroller: esp32
* Core/Framework: Arduino 2.3.2
* IDE: VSCode (latest as of 2024-05-23)

**Comment by bblanchon** [comment]
Hi @dranem50260,

Please provide the compiler output and a short reproduction program.

Best regards,
Benoit

**Comment by dranem50260** [comment]
Hello,

I found MY problem !
I’m sorry I wasted your time.
Please close this incident.

Merci Benoît.
