### ISSUE TITLE
fatal error: ArduinoJson/Variant/VariantRefBase.hpp: No such file or directory

### ISSUE THREAD

**Issue by khvalov** [bblanchon/ArduinoJson#2110]
**Description**
trying to compile your example but got error after most recent updates. Before updates was good

In file included from /Users/admin/Documents/Arduino/libraries/ArduinoJson/src/ArduinoJson/Array/JsonArray.hpp:7:0,
                 from /Users/admin/Documents/Arduino/libraries/ArduinoJson/src/ArduinoJson.hpp:29,
                 from /Users/admin/Documents/Arduino/libraries/ArduinoJson/src/ArduinoJson.h:9,
                 from /Users/admin/Documents/Arduino/shippo/shippo.ino:2:
/Users/admin/Documents/Arduino/libraries/ArduinoJson/src/ArduinoJson/Array/ElementProxy.hpp:7:10: fatal error: ArduinoJson/Variant/VariantRefBase.hpp: No such file or directory
 #include <ArduinoJson/Variant/VariantRefBase.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Troubleshooter's report**
1. The program uses ArduinoJson 7
2. The issue happens at compile time
3. The error is not in the list

**Environment**
* Microcontroller: Arduino Uno
* IDE: Arduino IDE 2.3.2 (Mac)

**Comment by bblanchon** [comment]
Hi @khvalov,

Please try to uninstall and reinstall the library.
Reinstalling solved #448, #685, and #1135.

Best regards,
Benoit
