### ISSUE TITLE
Example on ArduinoJson website crashes at runtime

### ISSUE THREAD

**Issue by NCPlyn** [bblanchon/ArduinoJson#2111]
**Description**
The example [here](https://arduinojson.org/v7/how-to/compute-hash/) crashes the microcontroller as the functions do not return "return 1;" and "return lenght;" respectively as can be seen [here](https://github.com/bblanchon/ArduinoJson/blob/7.x/extras/tests/JsonSerializer/CustomWriter.cpp).

Took me a while to troubleshoot the sudden crashing 😅, trusted the example...

**Environment**
* Microcontroller: ESP32S3
* Core/Framework: Arduino framework with espressif32 6.7 platform
* IDE: Visual Studio Code 1.89.1 with PlatformIO 3.3.3
* ArduinoJson 7

**Comment by bblanchon** [comment]
Hi @NCPlyn,

Thank you very much for reporting this error.
I'm sorry you had to waste much time troubleshooting this.

It should be fixed now.

Best regards,
Benoit
