### ISSUE TITLE
Missing links to specific types in the API reference

### ISSUE THREAD

**Issue by Dapid** [bblanchon/ArduinoJson#2113]
There are sections of the documentation, such as [JsonString](https://arduinojson.org/v7/api/jsonstring/) that are not accessible from anywhere in the reference guide. They should be, because otherwise it is hard to find the methods (in fact, I only encountered that one because searching with the type took me there).

**Comment by bblanchon** [comment]
Hi @Dapid,

Thank you very much for reporting this issue.
There were already links on all pages that mentioned `JsonString`.

1. https://arduinojson.org/news/2022/01/08/arduinojson-6-19-0/
2. https://arduinojson.org/v6/api/jsonobject/begin_end/
3. https://arduinojson.org/v6/api/jsonobjectconst/begin_end/
4. https://arduinojson.org/v6/doc/upgrade/
5. https://arduinojson.org/v7/api/jsonobject/begin_end/
6. https://arduinojson.org/v7/api/jsonobjectconst/begin_end/
7. https://arduinojson.org/v7/how-to/upgrade-from-v5/

Also, if you hover the class name, the Arduino IDE shows the link to the documentation:

![image](https://github.com/user-attachments/assets/8756b690-4974-46ec-a55f-a9a63d01c353)

Lastly, you can easily find the page using [arduinojson.org's built-in search](https://arduinojson.org/v7/search/?q=JsonString):

![image](https://github.com/user-attachments/assets/29866e44-256b-459c-ad82-dd95326d251c)

Still, I added links on the following pages:

1. https://arduinojson.org/v6/api/
2. https://arduinojson.org/v7/api/

Let me know if you find other pages where I should add links.

Best regards,
Benoit
