### ISSUE TITLE
Custom reader: readBytes method is not required?

### ISSUE THREAD

**Issue by boraozgen** [bblanchon/ArduinoJson#2117]
**Description**
I implemented a custom reader for my application. Although the documentation states that a readBytes method is required, my reader compiles and works without it too. Is this method orphaned and should it be removed?

**Troubleshooter's report**
1. The program uses ArduinoJson 7
2. The issue happens at compile time
3. The error is not in the list

**Environment**
* Microcontroller: Not relevant
* Core/Framework: No Arduino core
* IDE: No Arduino IDE

**Comment by bblanchon** [comment]
Hi @boraozgen,

Indeed, `deserializeJson()` doesn't use `readBytes()`, but `deserializeMsgPack()` does.
I'll add a note in the documentation.

Best regards,
Benoit
