### ISSUE TITLE
How to handle the removal of containsKey in ArduinoJson 7

### ISSUE THREAD

**Issue by rvbc1** [bblanchon/ArduinoJson#2126]
Hi,

Since version 7.2.0, the containsKey function has been deprecated. I was using it like this:

`if (requestJson.containsKey(ID_KEY)) { responseJson[ID_KEY] = requestJson[ID_KEY]; }`

I cannot use is\<T\>() because I don’t know the type of ID_KEY in advance; it could be a number, a string, etc.

My question is: how can I update my code in a clean way, without warnings? While the warning is not an issue right now, I’m concerned about the function being removed in the future.

Thank you!

**Comment by bblanchon** [comment]
Hi @rvbc1,

You could use either:

* `requestJson[ID_KEY].isNull()`
* `requestJson[ID_KEY] != nullptr`
* `requestJson[ID_KEY].is<JsonVariant>()`

The last one is the closest to what `containsKey()` did because it includes the value `null`.

Best regards,
Benoit

**Comment by rvbc1** [comment]
Thank you!
