### ISSUE TITLE
Is it correct to replace doc.containsKey(name) with doc[name].is<JsonVariantConst>()) going from 7.1->7.2 ?

### ISSUE THREAD

**Issue by proddy** [bblanchon/ArduinoJson#2128]
If I want to just check if a key exists in a `JsonDocument`/`JsonObject` who's value can be of any type (bool, string, int), is the correct way now in release 7.2 to use `doc[name].is<JsonVariantConst>())` ?

**Comment by bblanchon** [comment]
Yes, `is<JsonVariantConst>()` is the closest equivalent to `containsKey()`.

**Comment by proddy** [comment]
thanks.
