### ISSUE TITLE
assert failed: RamString.hpp:36 (i <= size())

### ISSUE THREAD

**Issue by DaeMonSxy** [bblanchon/ArduinoJson#2137]
Hi,

I am using arduinojson for several places - serialize,deserialize mqtt communication sending back and force.
Now after few days of use ( 3 ), i have got the following crash in log.
Maybe someone came across similar/this issue, and have addvice at least where to start debugging ( have hundred lines of code)
Any hints are appreciated, thanks

**Environment**  

ESP32

Platforio
-DCORE_DEBUG_LEVEL=1 ; Error
https://github.com/bblanchon/ArduinoJson/archive/refs/tags/v7.2.0.zip
platform: https://github.com/platformio/platform-espressif32/archive/refs/tags/v6.9.0.zip
framework is arduino

**Program output**  
```
assert failed: char ArduinoJson::V720PB22::detail::ZeroTerminatedRamString::operator[](size_t) const RamString.hpp:36 (i <= size())


Backtrace: 0x40083d65:0x3ffdaf40 0x4008ca11:0x3ffdaf60 0x40092039:0x3ffdaf80 0x400d4e77:0x3ffdb0b0 0x400e9be9:0x3ffdb0d0 0x400ecd4e:0x3ffdb130 0x40192122:0x3ffdb9f0 0x400f61ed:0x3ffdba10 0x400f62b5:0x3ffdba60 0x401929de:0x3ffdbab0 0x400f7945:0x3ffdbb10 0x400f7ab1:0x3ffdbb60 0x400f5c49:0x3ffdbb90 0x400f5dda:0x3ffdbc50 0x400f3f8b:0x3ffdbc70 0x400f3fe2:0x3ffdbca0 0x400f401d:0x3ffdbcc0 0x400f41ce:0x3ffdbce0 0x400f4241:0x3ffdbd00

```

**Comment by bblanchon** [comment]
Hi @DaeMonSxy,

This sounds like a memory corruption, probably not due to ArduinoJson.
Could you provide the decoded backtrace and a reproduction code?

Best regards,
Benoit
