### ISSUE TITLE
Empty JSON after some time

### ISSUE THREAD

**Issue by Hydro8** [bblanchon/ArduinoJson#219]
Hi

I use your library to send JSON data from DHT. It works fine at the beginning but after some value,  JSON is empty.

My code :

`#include <ESP8266WiFi.h>
#include <ArduinoJson.h>
#include "DHT.h"

#define DHTPIN 2     // what digital pin we're connected to
#define DHTTYPE DHT22
DHT dht(DHTPIN, DHTTYPE);

StaticJsonBuffer<512> jsonBuffer;

WiFiClient wifiClient;
int interval;
char str_humi[6];
char str_temp[6];

void setup() {
  Serial.begin(9600);
  Serial.println("DHTxx test!");

  dht.begin();
  
}

void loop() {
  // Wait a few seconds between measurements.
  delay(20000);
  
  JsonObject& stateObjectTemp = jsonBuffer.createObject();
  stateObjectTemp["Temperature"] = "22";
  stateObjectTemp["Humidity"] = "22";

  stateObjectTemp.printTo(Serial);

}`

And the ouput :{

`"Temperature":"22","Humidity":"22"}{"Temperature":"22","Humidity":"22"}{"Temperature":"22","Humidity":"22"}{"Temperature":"22","Humidity":"22"}{"Temperature":"22","Humidity":"22"}{"Temperature":"22","Humidity":"22"}{"Temperature":"22","Humidity":"22"}{"Temperature":"22","Humidity":"22"}{"Temperature":"22","Humidity":"22"}{"Temperature":"22","Humidity":"22"}{"Temperature":"22","Humidity":"22"}{"Temperature":"22","Humidity":"22"}
{"Temperature":"22"}{}{}{}{}{}{}{}`

And only empty bracket after.

Any idea what i've got this ?

Thank for your work.

**Comment by bblanchon** [comment]
You shall not use a global `JsonBuffer`.
Instead, you should move it inside the `loop()` function.

Please read [Avoiding Pitfalls: Don't reuse the same JsonBuffer](https://github.com/bblanchon/ArduinoJson/wiki/Avoiding%20pitfalls#4-dont-reuse-the-same-jsonbuffer);

> During is lifetime a JsonBuffer growth until it's discarded. If you try to reuse the same instance several time, it will rapidly get full. This is true for both DynamicJsonBuffer and StaticJsonBuffer.
>
> For this reason, you should not use a global variable for your JsonBuffer. I don't think there is any scenario in which a global JsonBuffer would be a valid option.
>
> The best practice is to declare it in a local scope, so that it's discarded as soon as possible. My advice it to declare it in a function which unique role is to handle the JSON serialization.

Please also read the [FAQ](https://github.com/bblanchon/ArduinoJson/wiki/FAQ).
