### ISSUE TITLE
Number of decimal places for double

### ISSUE THREAD

**Issue by tombarks** [bblanchon/ArduinoJson#239]
I'm trying to send ms accurate time from arduino to client. Using code:

root["Time"] = (double)millis() / 1000.0;

But this truncates to two decimal places and I need ms accurate time. There seems to be a way to set the number of decimals in an array but can't see how for a root object.

**Comment by bblanchon** [comment]
Either:

```c++
double time = millis() / 1000.0;
uint8_t digits = 6;
root.set("Time", time, digits);
```

or

```c++
double time = millis() / 1000.0;
uint8_t digits = 6;
root["Time"] = double_with_n_digits(time, 6);
```

**Comment by tombarks** [comment]
How about just:

root["Time"] = double_with_n_digits(((double)millis() / 1000.0), 3);

I only need 3 decimal places I think? Do I need to cast millis() as double here? Perhaps it will automagically do this for me but I am never quite sure of the behaviour.

**Comment by bblanchon** [comment]
The result of `millis() / 1000.0` already has the type `double`, since `1000.0` is a double.

**Comment by tombarks** [comment]
Thanks for your help and for making a great lib!

Tom

**Comment by bblanchon** [comment]
You're welcome, thanks for using ArduinoJson.

Don't hesitated to edit the wiki if you think you can improve it.
In particular, feel free to add you projects to [Projects using ArduinoJson](https://github.com/bblanchon/ArduinoJson/wiki/Projects%20using%20ArduinoJson).
Also, a GitHub star is always appreciated :wink:
