### ISSUE TITLE
How to make a request to a server and receive the JSON response?

### ISSUE THREAD

**Issue by horendus** [bblanchon/ArduinoJson#256]
HEY!

I just need to make a quick arduino sketch to do a POST request to http://ip.jsontest.com/ and parse the JSON response to my arduino 

This is what I get when I paste  http://ip.jsontest.com/ into my browser so I know the server works. 
{"ip": "34.33.111.135"}

None of the examples show an example of this!

It would be great for a quick example, I know this must be something easy.

**Comment by bblanchon** [comment]
Hi Jasper,

You are right, that would be a very good candidate for the Wiki:
https://github.com/bblanchon/ArduinoJson/wiki/Examples

I'm not sure, I'll have time to do that.
Would you mind adding it yourself?

**Comment by horendus** [comment]
If I manage to work it out I will!

**Comment by bblanchon** [comment]
@horendus Please have a look at [this file](https://github.com/bblanchon/ArduinoJson/blob/98652448373d806efde8afad3687a72dba31b572/examples/JsonHttpClient/JsonHttpClient.ino)
If you'r satisfied, I'll include it the the offcial set of excamples.

Note that http://ip.jsontest.com/ what not available (error 503), so I used another service.

**Comment by horendus** [comment]
Looks great many Thanks!
