### ISSUE TITLE
Support for Stream as input

### ISSUE THREAD

**Issue by bblanchon** [bblanchon/ArduinoJson#300]
Copy the content of the stream in the `JsonBuffer`
Ideally, remove the spaces to use less memory.

**Comment by Diaoul** [comment]
I'm reading JSON from Serial and I'd like to avoid an extra buffer. Would that work for me?

**Comment by bblanchon** [comment]
@Diaoul Yes, the input will be copied in the `JsonBuffer` automatically.

**Comment by bblanchon** [comment]
Feature available in release [5.8.0](https://github.com/bblanchon/ArduinoJson/releases/tag/v5.8.0)

**Comment by sticilface** [comment]
Double thumbs up for this!   big help :)  thanks!!!

**Comment by bblanchon** [comment]
Thanks @sticilface, it's been quite a challenge.

It's much more efficient than using `Stream::readBytes()` as before as the `JsonBuffer` will duplicate the minimal amount of data, thus saving a lot of memory if the input JSON is indented.

The [ArduinoJson Assistant](https://bblanchon.github.io/ArduinoJson/) has been updated to tell the number of bytes that are required for the duplication.
