### ISSUE TITLE
How to calculate buffer size of an array of arrays?

### ISSUE THREAD

**Issue by feklee** [bblanchon/ArduinoJson#302]
Example:

    {"type":"scan data","data":[[0,0,0],[0,1,0],[1,0,0],[1,1,0]]}

**Comment by bblanchon** [comment]
![computejsonbuffersize](https://cloud.githubusercontent.com/assets/5462433/15892837/615c38fa-2d7c-11e6-905e-9b5569313afe.png)

Provided that you're using `char*` and not `String`, the required size:

JSON_OBJECT_SIZE(2)+JSON_ARRAY_SIZE(4)+4*JSON_ARRAY_SIZE(3)

Make sure to have a look at:

* [FAQ: How to determine the buffer size?](https://github.com/bblanchon/ArduinoJson/wiki/FAQ#how-to-determine-the-buffer-size)

**Comment by feklee** [comment]
Thanks for clarification! Actually, what you propose is what I did before, and it didn't work until I added some padding. It turned out that it was a memory management issue, caused by me not paying attention.

**Comment by bblanchon** [comment]
No biggie. 
I'm sure that picture will be helpful for others.
Thanks for using ArduinoJson.
