### ISSUE TITLE
Suggestion for global variable support

### ISSUE THREAD

**Issue by clayfreeman** [bblanchon/ArduinoJson#307]
I've noticed multiple places in the documentation that warn against the use of global variables for the `JsonBuffer` family of classes. However, I don't believe that you will *always* be able to avoid having a global `JsonBuffer`.

I understand the technical pitfall in having a global variable for a `JsonBuffer`, however I have a suggestion that might aide those who need a global variable.  If one were to encapsulate the `JsonBuffer` (and potentially a `JsonObject` reference) in a `struct`, it would be trivial to avoid this pitfall by dynamically allocating the `struct` in a global variable and releasing the memory when finished:

```C++
#include <ArduinoJson.h>

struct JsonContainer {
  DynamicJsonBuffer buffer = {};
  JsonObject&       root   = this->buffer.createObject();
};

JsonContainer* json = nullptr;

void resetJson() {
  // Deallocate the existing JSON container
  if (json != nullptr) delete[] json;
  // Allocate a new JSON container
  json = new JsonContainer[1];
}

void setup() {
  // Reset the JSON container
  resetJson();
}

void loop() {
  // ...
}
```

Therefore, I submit a recommendation that the documentation should be revised to point out such a solution to having a global variable.

**Comment by bblanchon** [comment]
See [Bag of tricks: reuse JsonBuffer](https://github.com/bblanchon/ArduinoJson/wiki/Bag%20of%20Tricks#reuse-jsonbuffer) for a **much cleaner** solution.

I'll remove this limitation on version 6.
