### ISSUE TITLE
Pass String to RawJson

### ISSUE THREAD

**Issue by Zeron** [bblanchon/ArduinoJson#311]
I have four arrays of 288 bytes.  Adding them using .add()  takes quite a bit of memory. (4 x 3460 bytes if I read https://github.com/bblanchon/ArduinoJson/wiki/Memory-model correctly)

I can make a string of Raw JSON that takes significant less memory (1.1K per array max assuming every value is 255,255,255...)

In other places, when a Strig is passed; it is copied, but RawJson does not accept strings.

Would this be possible?

Is there a better way to add ``byte Patterns[4][288]`` that uses less memory?

**Comment by bblanchon** [comment]
Here are 4 different ways to solve your problem, in (my) order of preference:

1. JSON seems inappropriate for your use case, have you considered alternatives?
    (maybe a binary format or a base64 encoded string)

2. The 14kB required by the `JsonArray`s should fit in the 96kB of your ESP8266.
    Use a `DynamicJsonBuffer` and specify 16384 (i.e., 16k) to the constructor.

3. If you are concerned about memory consumption, don't use `String` at all.
    Instead, use a `char[]`.

4. If you still want to use a `String`, just do `RawJson(myString.c_str())`.
    And make sure the `String` stays in memory while you call `printTo()`.
