### ISSUE TITLE
has no member asInterger

### ISSUE THREAD

**Issue by 32teeth** [bblanchon/ArduinoJson#314]
`
String data = "{address:1}";
JsonObject& json = jsonBuffer.parseObject(data);
Serial.println(json["address"].asInteger()); // <-- fail
`
class ArduinoJson::JsonObjectSubscript<const char*>' has no member named 'asInteger'

`
String data = "{address:1}";
JsonObject& json = jsonBuffer.parseObject(data);
Serial.println((int)json["address"].asString()); // <-- success
`

**Comment by bblanchon** [comment]
Hi Eugene,

It's `.as<int>()`.

**Comment by bblanchon** [comment]
Added to the doc:
https://github.com/bblanchon/ArduinoJson/wiki/API-Reference#jsonvariantas
