### ISSUE TITLE
Method to detect that JSON string is incomplete?

### ISSUE THREAD

**Issue by psigen** [bblanchon/ArduinoJson#318]
I was wondering if there is any way to distinguish cases where a string could be the first part of a valid JSON string from cases where the string is definitely invalid and unparseable.

The use case is that I am accumulating characters in a buffer which I would like to parse as it is streaming.  I know that the input is a stream of valid JSON objects, but I do not know at first if I am in the middle of the stream or not.  I also know the max size of the objects, so I can simply keep reading and sliding the buffer to find a valid region.

For example:
```json
{ "foo": true } // valid
} {"foo": true } // invalid
{ "foo": } // invalid
{ "foo": true } } // invalid
{ "foo: // could be part of valid JSON!
```

I am trying to port over some code from `jsmn`, which offers this functionality via its `JSMN_ERROR_PART` error flag, distinct from `JSMN_ERROR_INVAL`: https://github.com/zserge/jsmn

**Comment by bblanchon** [comment]
No, this is not possible with the current implementation of ArduinoJson.
You can tell if a parse succeeded or failed, but you cannot know why.
