### ISSUE TITLE
Parsing failure

### ISSUE THREAD

**Issue by tantra21** [bblanchon/ArduinoJson#320]
Hi,

I  am running the following code on Arduino 101.

char json[] = "{ \"num\":2024, \"time\":\"2000-02-18 11:05:33.954\", \"values\":[ [ 39,22,19,0 ] ] }"; StaticJsonBuffer<200> jsonBuffer;
JsonObject& root = jsonBuffer.parseObject(json);
 if(!root.success())
 {
   Serial.println("parse object failed!");
   return;
  }
 int num = root["num"];
 Serial.println(num);

This code works fine but changing 'char json[]' to 'const char* json' or 'String json'causes the parsing to fail.

How to get the parser to parse the json data using const char* or String?

Thanks!

**Comment by bblanchon** [comment]
Hi @tantra21,

Please have a look at:

* [FAQ: Why parsing fails?](https://github.com/bblanchon/ArduinoJson/wiki/FAQ#why-parsing-fails)

Regards.
