### ISSUE TITLE
Is it possible to use containsKey method for nested keys?

### ISSUE THREAD

**Issue by gabrielebellini** [bblanchon/ArduinoJson#322]
Hello,
having this json with nested object:
{"key1":5,"body":{"key2":7,"key3":9}}
Is there a way to use containsKey for finding nested keys?
root.containsKey("key2") return false because it's inside "body" key. Could this function be use to traverse all levels and find, for example, "key2" or "key3" presence?

Thanks in advance.

Gabriele

**Comment by bblanchon** [comment]
Hi Gabriele,

No. There is no function to do that.

However, you can implement it yourself, like this:

```c++
bool containsNestedKey(const JsonObject& obj, const char* key) {
    for (const JsonPair& pair : obj) {
        if (!strcmp(pair.key, key))
            return true;
      
        if (containsNestedKey(pair.value.as<JsonObject>(), key)) 
            return true;
    }

    return false;
}
```

Please add this to [Wiki: Bag of Tricks](https://github.com/bblanchon/ArduinoJson/wiki/Bag%20of%20Tricks) if it works.

Regards,
Benoit.

**Comment by gabrielebellini** [comment]
Thank you Benoit for your help! It works flawlessly. Your JSON library is a masterpiece! Very useful and elegant. As requested, I just added your suggested solution to the Bag of Tricks in the Wiki. Thank you again! Gabriele

**Comment by bblanchon** [comment]
You're welcome, Gabriele.
Thank you for using ArduinoJson and for you contribution on the Wiki.

One last thing, you can show your support by adding a star to the project on GitHub; this is always appreciated :wink:

**Comment by gabrielebellini** [comment]
Added one star 👍 Thanks again for your precious work.

**Comment by enurseitov** [comment]
Arduino IDE's compiler gives error: ```
error: range-based 'for' loops are not allowed in C++98 mode
     for (const JsonPair& pair : obj) {
                                 ^
```

**Comment by bblanchon** [comment]
@enurseitov Newer version of Arduino IDE use C++11.

If for some reason, you cannot upgrade, here is the C++98 version:

```c++
bool containsNestedKey(const JsonObject& obj, const char* key) {
    for (JsonObject::const_iterator it=obj.begin(); it!=obj.end(); ++it) {
        if (!strcmp(it->key, key))
            return true;

        if (containsNestedKey(it->value.as<JsonObject>(), key)) 
            return true;
    }

    return false;
}
```

**Comment by enurseitov** [comment]
@bblanchon That's strange, I use rather new Arduino IDE v. 1.6.6. Anyway, thanks a lot for fast reply, I'll try your code later.

**Comment by wizbowes** [comment]
Hi - I'm trying this currently but get the following compile error:
`undefined reference to `ArduinoJson::JsonObject ArduinoJson::JsonVariant::as<ArduinoJson::JsonObject>() const'`

I'm calling the function like this:

`if (containsNestedKey(root,"speed")) {Serial.println("yay");} else {Serial.println("nah");}`

Not sure if that's correct - pointers confuse me.
