### ISSUE TITLE
Need to Read and parse .json file from SD card for NERC'16 

### ISSUE THREAD

**Issue by syeedhaiderali** [bblanchon/ArduinoJson#325]

**Comment by bblanchon** [comment]
Hi,

You are the third person to ask a similar question for that same contest (#295 and #297).

The difficulties comes from the fact that the sample JSON in the contest page are invalid and that it's not that easy (apparently) to read a file from the SD card.
No problem has been identified on ArduinoJson.

As it's not a problem or a question specifically targetted at ArduinoJson, please go to stackoverflow.com and ask for help.

Sorry.
