### ISSUE TITLE
Q : Can the same JsonBuffer be used for reading (decoding )and writing (encoding) at the same time ?

### ISSUE THREAD

**Issue by vortex314** [bblanchon/ArduinoJson#336]
I didn't find in the documentation ( wiki and examples ) if it is possible that : 
1/ You load a JsonBuffer with a string and parse/get the different elements
2/ You use the same JsonBuffer to set a number of fields.

The use case is the serialization of config to EEPROM/Flash. The idea was to store this as a string, load it in ArduinoJson , modify/read it, store back as string.

**Comment by bblanchon** [comment]
Yes, it's possible, and it's a good practice 👍

**Comment by vortex314** [comment]
Thanks!

**Comment by bblanchon** [comment]
You're welcome Lieven, thanks for using ArduinoJson.

Don't hesitate to edit the wiki if you think you can improve it.
In particular, feel free to add your projects to [Projects using ArduinoJson](https://github.com/bblanchon/ArduinoJson/wiki/Projects%20using%20ArduinoJson).

Also, a GitHub star is always appreciated :wink:

**Comment by vortex314** [comment]
Benoit, just did the Github star. 
Adding the project on the page is out of my reach, don't master the mark-down syntax enough.
Project can be found here : https://sites.google.com/site/limero314/esp8266-to-stm32
A Wifi bootloader for STM32 chips.

**Comment by bblanchon** [comment]
I added the link by I'm having trouble displaying the page, see the screenshot below:

![image](https://cloud.githubusercontent.com/assets/5462433/17803165/f94f590c-65f4-11e6-8495-f1a759910391.png)

**Comment by vortex314** [comment]
Benoit, thanks again for the feedback, I changed the access rights of my document. It should work now.
I hope.

**Comment by bblanchon** [comment]
Good. I can now see the images.
