### ISSUE TITLE
Support for keyset?

### ISSUE THREAD

**Issue by Introvertuous** [bblanchon/ArduinoJson#344]
Is there a way to get the keyset from a JsonObject, in cases where the user does not know what the keys may be beforehand.

**Comment by bblanchon** [comment]
You can enumerate all the keys and values of a `JsonObject`, using iterators.

See:

* [API Reference: JsonObject::begin() / JsonObject::end()](https://github.com/bblanchon/ArduinoJson/wiki/API-Reference#jsonobjectbegin--jsonobjectend)
* [Wiki Examples: iterators](https://github.com/bblanchon/ArduinoJson/wiki/Examples#example-3-iterators)

**Comment by Introvertuous** [comment]
Right, thank you.

**Comment by bblanchon** [comment]
You're welcome.
Thank you for using ArduinoJson.
