### ISSUE TITLE
Problem to compile JsonParserExample: JsonParser.ipp not found

### ISSUE THREAD

**Issue by fabio-limardo** [bblanchon/ArduinoJson#345]
Hi guys, when i try to compile the example Arduino ide (1.6.11) give me following error:

sketch\include/ArduinoJson.hpp:15:48: fatal error: ArduinoJson/Internals/JsonParser.ipp: No such file or directory

I don't understand, the file esist in the directory.

Thanks a lot

**Comment by bblanchon** [comment]
Hi Fabio,

Please apologize for the long wait.
Did you install the library through the Arduino Library Manager?

Regards,
