### ISSUE TITLE
return object corrupted

### ISSUE THREAD

**Issue by lapinroux** [bblanchon/ArduinoJson#346]
Hello and thank you for so beautiful library !!!!

I found a little problem, I don't really know if it comes from my way to code or from library. Return JsonObject is not the same before return and after return. And only first sentence is changed, that's why I'm wondering if it's problem memory with this lib.

Here's my function :
```c++
JsonObject& SdCommunication::TakeActionFromSdCard(unsigned int actionNumber, JsonBuffer& jbuffer)
{
	//Le max de la longueur d'un fichier est 20 caractères, ce qui laisse une possibilité d'actions entre 0 et 999
	char fileName1[20] = "scenario/__";
	itoa(actionNumber, fileName1+11, 10);
	if (actionNumber > 99)
	{
		strncpy(fileName1+14, "__.jsn", 6);
	}
	else if (actionNumber > 9)
	{
		strncpy(fileName1+13, "__.jsn", 6);
	}
	else
	{
		strncpy(fileName1+12, "__.jsn", 6);
	}

	SdFile myFile(fileName1, O_READ);
	//char* fileRead1 = (char*) malloc(myFile.fileSize());
	char fileRead1[FILE_LARGEST] = {0};

	SerialPrint(F("Ouverture du fichier : "));
	SerialPrintln(fileName1);

	if (!myFile.isOpen())
	{
		SerialPrint(F("Aucun fichier du nom : "));
		SerialPrintln(fileName.c_str());
	}

	myFile.read(fileRead1, FILE_LARGEST);
	myFile.close();

	//SerialPrintln(fileRead1);

	JsonObject& object = jbuffer.parseObject(fileRead1);
	//free(fileRead1);
	SerialPrintln(freeRam ());
	object.printTo(Serial);

	if (!object.success())
	{
		SerialPrintln(F("!!!!!!! Parsing du fichier json ko. Trop gros peut-etre ??? !!!!!!!!!!!!!!!"));
		while (1){}
	}

	return object;
}
```

And the calling : 
`DynamicJsonBuffer jsonBuffer(250);
JsonObject& jsonAction = SdCommunication::TakeActionFromSdCard(actionNumber, jsonBuffer);
jsonAction.printTo(Serial);`

Here are printing results (object.printTo(Serial) & jsonAction.printTo(Serial)) : 
{"c":"Wait","p":{"timeInMs":10000}}
{"×":"\b","p":{"timeInMs":10000}}
2nd example with different file : 
{"c":"Compute","p":{"maths":"[nb_cycles]+1"},"var":"nb_cycles"}
{"×":"\b","p":{"maths":"[nb_cycles]+1"},"var":"nb_cycles"}

This behaviour doen't appear without result if I put parseObject() directly in my main function. My environment is arduino mega under eclipse, and I tried arduiJson 5.4.0 & arduinoJson 5.6.6.

I successed to find a compromise solution then don't hesitate to close this issue if you don't success to reproduce it.

Thank you !!!

**Comment by bblanchon** [comment]
Hello,

That's because ArduinoJson doesn't copy the strings, it just stores pointers to it.

It's possible to explicitly duplicate the string in the `JsonBuffer`.

```c++
jbuffer.parseObject(jbuffer.strdup(fileRead1));
```

However, you loose all the good stuff in ArduinoJson :-(

See:

* [Avoiding pitfalls: Keep the JSON string in memory long enough](https://github.com/bblanchon/ArduinoJson/wiki/Avoiding%20pitfalls#5-keep-the-json-string-in-memory-long-enough)
* [FAQ: What's the best way to use the library?](https://github.com/bblanchon/ArduinoJson/wiki/FAQ#whats-the-best-way-to-use-the-library)
