### ISSUE TITLE
Coding Question

### ISSUE THREAD

**Issue by tigergroup** [bblanchon/ArduinoJson#351]
I have been working on this for over a day and seem to not get this working correctly.  I have a json that I parsed.  I need to take the current password in the json, encrypted it and put it back in the json.

json:

{
"wifi": {
    "ssid": "somessid",
    "password": "somepassword"
  },
}

convert to:

{
"wifi": {
    "ssid": "somessid",
    "password": "AGjsdfDv4Sf3f"
  },
}

I tried something like this:

StaticJsonBuffer<MAX_JSON_CONFIG_ARDUINOJSON_BUFFER_SIZE> jsonBuffer;
  JsonObject& parsedJson = jsonBuffer.parseObject(buf);
  if (!parsedJson.success()) {
    this->_interface->logger->logln(F("✖ Invalid JSON in the config string"));
    return;
  }

    JsonObject& jsonWifi = parsedJson["wifi"];
    int strLength = strlen(jsonWifi["password"]);
    char unencryptedPassword[strLength]; 
    strcpy(unencryptedPassword, jsonWifi["password"]);

    char encryptedWifiPasswordEncoded[MAX_WIFI_PASSWORD_LENGTH];
    _encryptPassword(encryptedWifiPasswordEncoded, (byte*)unencryptedPassword, strlen(unencryptedPassword));
    jsonWifi.set("password",encryptedWifiPasswordEncoded);

Can anyone guide me on what I am doing wrong?

scott

**Comment by bblanchon** [comment]
This should work:

```c++
const char* clearPassword = parsedJson["wifi"]["password"];

char securePassword[MAX_WIFI_PASSWORD_LENGTH];
_encryptPassword(securePassword, (byte*)clearPassword, strlen(clearPassword));

parsedJson["wifi"]["password"] = securePassword;
```

However, I'm a little concerned about the extra comma at the end of the "wifi" object in the input.
What does `parsedJson.success()` says?

**Comment by tigergroup** [comment]
got this compiler error for esp8266 chip:

error: passing 'const ArduinoJson::JsonObjectSubscript<const char*>' as 'this' argument of 'typename ArduinoJson::TypeTraits::EnableIf<ArduinoJson::JsonObject::CanSet<T>::value, ArduinoJson::JsonObjectSubscript<TKey> >::type& ArduinoJson::JsonObjectSubscript<TKey>::operator=(T) [with T = char*; TKey = const char*; typename ArduinoJson::TypeTraits::EnableIf<ArduinoJson::JsonObject::CanSet<T>::value, ArduinoJson::JsonObjectSubscript<TKey> >::type = ArduinoJson::JsonObjectSubscript<const char*>]' discards qualifiers [-fpermissive]

 parsedJson["wifi"]["password"] = securePassword;

**Comment by bblanchon** [comment]
Hmmm... that's strange; I'll open an issue on that topic.

Anyway, here is the workaround:

```c++
JsonObject& wifi = parsedJson["wifi"];
const char* clearPassword = wifi["password"];

char securePassword[MAX_WIFI_PASSWORD_LENGTH];
_encryptPassword(securePassword, (byte*)clearPassword, strlen(clearPassword));

wifi["password"] = securePassword;
```

**Comment by bblanchon** [comment]
Interesting, did you have an error from the compiler?

**Comment by bblanchon** [comment]
I just realized that you're using a `StaticJsonBuffer` that is probably too big to fit in the stack.

You should switch to a `DynamicJsonBuffer`.
