### ISSUE TITLE
Adafruit MQTT lib publish with ArduinoJSON

### ISSUE THREAD

**Issue by sachinranka4u** [bblanchon/ArduinoJson#357]
Hi, I have a quick question.
I am using Adafruit MQTT library
(https://github.com/adafruit/Adafruit_MQTT_Library)
I want to publish (send) a JSON string over MQTT protocol.
I tried going through Wikis and FAQs, but could'nt find a solution,
For eg.,

`#include <ArduinoJson.h>`
`#include "Adafruit_MQTT.h"`
`#include "Adafruit_MQTT_Client.h"`
` `
`// server details `
`...`
`StaticJsonBuffer<200> jsonBuffer;`
`JsonObject& jsonObj = jsonBuffer.createObject();`
`JsonArray& p1 = jsonObj.createNestedArray("p1");`
`// normal string publish we send it as `
`if(! publishObj.publish(strObj)){`
`    Console.println(F("Failed"));`
`  } else {`
`    Console.println(F("OK!"));`
`  }`
`...`

But how do I send jsonObj to publish, its obviously not defined in the Adafruit MQTT lib,
Am using Arduino YUN, Any suggestions are welcome...

**Comment by bblanchon** [comment]
Hi,

You need to write the JSON to a temporary buffer.

```c++
char strObj[256];
jsonObj.printTo(strObj, sizeof(strObj));
```

The string can be dynamically allocated if you prefer:

```c++
String strObj;
jsonObj.printTo(strObj);
```

Regards
