### ISSUE TITLE
MessagePack Support?

### ISSUE THREAD

**Issue by mahmed8003** [bblanchon/ArduinoJson#358]
Is it possible to have MessagePack support.
Instead of printing JSON string to buffer using this method
`size_t prettyPrintTo(char *buffer, size_t bufferSize)`
can we have another method like
`size_t msgPackPrintTo(char *buffer, size_t bufferSize)`

Use case:
- Final buffer size could be smaller and it can reduce the network data usage where sensor sending lot of data in json string.
- Instead of storing plain JSON string to SPIFFS we can store small msgPack buffer. It will reduce file size.

**Comment by bblanchon** [comment]
This sound like a good idea, and that's 100% aligned with the philosophy of ArduinoJson.
However, I'm afraid most users would prefer the official implementation instead of ArduinoJson...

Also, it looks like there will be a lot of testing, so I'd like to see how much traction this feature gets before writing a lot of code.

Let's see how many upvotes 👍 we get on this feature request.

**Comment by heman4t** [comment]
When its about...
> Final buffer size could be smaller and it can reduce the network data usage where sensor sending lot of data in json string.

I upvote. For me size is equally important to performance in micro controllers.

**Comment by sticilface** [comment]
I'd be keen on this.  reducing the buffer size is great from my end!  limited ram and all..

**Comment by cosmikwolf** [comment]
upvote. I want to use arduino JSON to store data on local storage, but it is not efficiently packed. Would love a way to reduce the output size. Even just storing variables in their hex format would be good.

**Comment by cosmikwolf** [comment]
ArduinoJSON is miles ahead of the msgPack arduino implementation, would way rather use ArduinoJSON for this purpose.

**Comment by bblanchon** [comment]
Branch 5.8.x seems to be quite stable now.
I'll now focus on this feature.

**Comment by Matheus-Garbelini** [comment]
@bblanchon there's a new PR of mine that includes an initial support to messagepack.
https://github.com/bblanchon/ArduinoJson/pull/682

**Comment by bblanchon** [comment]
MessagePack is finally available in [ArduinoJson 6.0.0](https://arduinojson.org/news/2018/06/07/version-6-0-0/?utm_source=github&utm_medium=issues)
