### ISSUE TITLE
Using the library outside the Arduino

### ISSUE THREAD

**Issue by leventesen** [bblanchon/ArduinoJson#361]
Is it possible to port and use the ArduinoJson library without the Arduino, for example in AVR MCU - GNU Toolchain - Atmel Studio?

What are the Arduino dependencies to remove and which compiler/linker options must be set?

**Comment by bblanchon** [comment]
ArduinoJson is not dependent on Arduino, nor anything else.

It's a header-only library, so you just have to `#include <ArduinoJson.h>` and that's all.

You do not need any compiler/linker flags.
However you'll have a warning if you use the flag `--fpack-struct`, you'll have the following warning:

    ignoring packed attribute because of unpacked non-POD field

See issue #255.

**Comment by leventesen** [comment]
When I build, compiler gives this error:

undefined reference to __cxa_guard_acquire
undefined reference to __cxa_guard_release

**Comment by bblanchon** [comment]
This should be fixed by adding the flags `-fno-threadsafe-statics`.

See issue #356.
