### ISSUE TITLE
Adding nested objects in a loop

### ISSUE THREAD

**Issue by koffienl** [bblanchon/ArduinoJson#362]
So, I allready noticed that creating nestedobjects in a loop is not going to work.
I have upgraded my Arduino ESP8266 version to 2.3.0 and installed latest ArduinoJson Master.

(simplified) Snippet of what I want:

```
  DynamicJsonBuffer jsonBuffer;
  JsonObject& cfg = jsonBuffer.parseObject(const_cast<char*>(jsn.c_str()));

  if (!cfg.containsKey("recipe"))
  {
    cfg.createNestedObject("recipe");
  }
  JsonObject& recipe = cfg["recipe"];
  if (!recipe.containsKey("mash"))
  {
    recipe.createNestedObject("mash");
  }
  else
  {
    recipe.remove("mash");
    recipe.createNestedObject("mash");
  }
  JsonObject& mash = recipe["mash"];

  for (uint8_t i = 0; i < 5; i++)
  {
    String Step = "mash" + i;
    if (!mash.containsKey(const_cast<char*>(Step.c_str())))
    {
      mash.createNestedObject(const_cast<char*>(Step.c_str()));
    }
  }
```

I have read this topic : https://github.com/bblanchon/ArduinoJson/issues/258 and the FAQ, unfortunately my skills are not good enought to understand how to incorporate that into my snippet.

Outcome of the json should look likte this : 
```
{
	"settings": {},
	"recipe": {
		"mash": {
			"mash1": {},
			"mash2": {},
			"mash3": {},
			"mash4": {}
		}
	}
}
```` 

But it gets corrupted (or only writes the last 'mash4' under 'mash'.
The reason I have to use the loop, is because in the final project I have to loop through som dynamic values to determine IF and WHAT nestedobject should be created.

**Comment by bblanchon** [comment]
ArduinoJson has a different behavior with `String`: it copies its content into the `JsonBuffer`.
This is based on the assumption that most people use `String` as a temporary value, just like you.
In your code, this behavior was not triggered because you called `String::c_str()`.

Just replace:

```c++
for (uint8_t i = 0; i < 5; i++)
  {
    String Step = "mash" + i;
    if (!mash.containsKey(const_cast<char*>(Step.c_str())))
    {
      mash.createNestedObject(const_cast<char*>(Step.c_str()));
    }
  }
```

by

```c++
for (uint8_t i = 0; i < 5; i++)
  {
    String Step = "mash" + i;
    if (!mash.containsKey(Step))
    {
      mash.createNestedObject(Step);
    }
  }
```

**Comment by koffienl** [comment]
Got it working, thanks for pointing the problem :)

**Comment by bblanchon** [comment]
You're welcome @koffienl, thanks for using ArduinoJson.

Don't hesitate to edit the wiki if you think you can improve it.
In particular, feel free to add your projects to [Projects using ArduinoJson](https://github.com/bblanchon/ArduinoJson/wiki/Projects%20using%20ArduinoJson).

Also, a GitHub star is always appreciated :wink:
