### ISSUE TITLE
Copy object into new object

### ISSUE THREAD

**Issue by koffienl** [bblanchon/ArduinoJson#375]
Perhaps I'm overlooking something complete easy or already stated somewhere in the wiki ..

I have a parsed json in my buffer and read a part into a object. Now I want to create and parse a *new* json object and copy the previous object into the new json.
How can I do this ?

**Comment by bblanchon** [comment]
```c++
JsonObject& obj1 = jsonBuffer.parseObject(json1);
JsonObject& obj2 = jsonBuffer.parseObject(json2);
obj1["key"] = obj2;
```

**Comment by koffienl** [comment]
Thanks!
Didn't know it was possible with such a easy way :o
