### ISSUE TITLE
List<JsonObject>

### ISSUE THREAD

**Issue by tiagotaz** [bblanchon/ArduinoJson#38]
Hello, I am trying to create a list of JSONObject and then interact with the list.
But I found no documentation specific for this use, and to include the item in the list and then remove, could help me with this question?

**Comment by tiagotaz** [comment]
Hi,i need To implement the function remove can You help me ?

**Comment by bblanchon** [comment]
I added issue #58, I'll try to do that ASAP.

**Comment by bblanchon** [comment]
@tiagotaz: I added the JsonArray::removeAt() in the master branch. Sorry for the delay.

**Comment by tiagotaz** [comment]
Great!!!!!!!!! very thank's

Tiago de Almeida
(11)9-8204-4454

2015-05-02 10:17 GMT-03:00 Benoît Blanchon <notifications@github.com>:
