### ISSUE TITLE
How to delect a Object

### ISSUE THREAD

**Issue by waayst** [bblanchon/ArduinoJson#384]
with StaticJsonBuffer(global variable) we can use parseObject but After a few times parse,it will full and won't work,so how to
delect a useless object.

**Comment by bblanchon** [comment]
The problem is that you're reusing the same JsonBuffer several times.
Please, have a look at the FAQ.

**Comment by bblanchon** [comment]
See:

* [FAQ: Why shouldn't I use a global JsonBuffer?](https://github.com/bblanchon/ArduinoJson/wiki/FAQ#why-shouldnt-i-use-a-global-jsonbuffer)
* [FAQ: How to reuse a JsonBuffer?](https://github.com/bblanchon/ArduinoJson/wiki/FAQ#how-to-reuse-a-jsonbuffer)
* [FAQ: What's the best way to use the library?](https://github.com/bblanchon/ArduinoJson/wiki/FAQ#whats-the-best-way-to-use-the-library)
