### ISSUE TITLE
trying to create nested object inside a FOR loop

### ISSUE THREAD

**Issue by geetee24** [bblanchon/ArduinoJson#386]
JsonArray& arrayZoneStatus = jsonBuffer.createArray();

			for ( ..... ) {

				JsonObject& forNestedZoneStatus = arrayZoneStatus.createNestedObject();

}

the above code seems to be wrong.
No examples for how to deal with a FOR LOOP.

Can you advise?

**Comment by bblanchon** [comment]
Your code seems right, what's wrong with it?

See:

* [FAQ: Why some parts are missing?](https://github.com/bblanchon/ArduinoJson/wiki/FAQ#why-some-parts-are-missing)
* [FAQ: Why does the generated JSON contain garbage?](https://github.com/bblanchon/ArduinoJson/wiki/FAQ#why-does-the-generated-json-contain-garbage)
* [Avoiding Pitfalls: Make StaticJsonBuffer big enough](https://github.com/bblanchon/ArduinoJson/wiki/Avoiding-pitfalls#1-make-staticjsonbuffer-big-enough)
* [Avoiding Pitfalls: Do not assume that strings are compied](https://github.com/bblanchon/ArduinoJson/wiki/Avoiding-pitfalls#6-do-not-assume-that-strings-are-copied)
