### ISSUE TITLE
is not support ESP32 Arduino?

### ISSUE THREAD

**Issue by 0x1abin** [bblanchon/ArduinoJson#389]
C:\Users\27099\AppData\Local\Temp\arduino_build_505689\sketch\Mement.ino.cpp.o:(.literal._ZN11ArduinoJson9JsonArray7invalidEv[ArduinoJson::JsonArray::invalid()]+0x8): undefined reference to `__cxa_guard_acquire'

C:\Users\27099\AppData\Local\Temp\arduino_build_505689\sketch\Mement.ino.cpp.o:(.literal._ZN11ArduinoJson9JsonArray7invalidEv[ArduinoJson::JsonArray::invalid()]+0xc): undefined reference to `__cxa_guard_release'

C:\Users\27099\AppData\Local\Temp\arduino_build_505689\sketch\Mement.ino.cpp.o: In function `ArduinoJson::JsonArray::invalid()':

C:\Users\27099\Documents\Arduino\libraries\ArduinoJson/include/ArduinoJson/JsonArray.hpp:148: undefined reference to `__cxa_guard_acquire'

C:\Users\27099\Documents\Arduino\libraries\ArduinoJson/include/ArduinoJson/JsonArray.hpp:148: undefined reference to `__cxa_guard_release'

C:\Users\27099\AppData\Local\Temp\arduino_build_505689\sketch\Mement.ino.cpp.o: In function `ArduinoJson::JsonObject::invalid()':

C:\Users\27099\Documents\Arduino\libraries\ArduinoJson/include/ArduinoJson/JsonObject.hpp:131: undefined reference to `__cxa_guard_acquire'

C:\Users\27099\Documents\Arduino\libraries\ArduinoJson/include/ArduinoJson/JsonObject.hpp:131: undefined reference to `__cxa_guard_release'

collect2.exe: error: ld returned 1 exit status

Thanks.

**Comment by bblanchon** [comment]
You need to add the flag `-fno-threadsafe-statics` to the compiler's command line.

See:

* [Compatibility issues](https://github.com/bblanchon/ArduinoJson/wiki/Compatibility%20issues#error-undefined-reference-to-__cxa_guard_acquire-and-__cxa_guard_release)
