### ISSUE TITLE
.containsKey() missing from API Reference

### ISSUE THREAD

**Issue by nuket** [bblanchon/ArduinoJson#394]
Would be helpful if .containsKey() were also mentioned in the API Reference. I only learned of its existence after reading the [check values](https://github.com/bblanchon/ArduinoJson/wiki/Decoding-JSON#check-values) section of Decoding JSON, but I did check the API Reference for this method first and was confused not to find it immediately there.

**Comment by bblanchon** [comment]
[Done](https://github.com/bblanchon/ArduinoJson/wiki/API-Reference#jsonobjectcontainskey)

Thanks for submitting this issue 👍 

Feel free to edit the wiki.
