### ISSUE TITLE
The "new" operator definition collides with the standard (?) one

### ISSUE THREAD

**Issue by highfield** [bblanchon/ArduinoJson#40]
Benoit, your library is simply awesome: no kidding!
ATM, I'm still in the phase of "assembly" several parts or a small project, originally written in C#, but my knowledge yet experience in C/C++ is close to zero.
https://highfieldtales.wordpress.com/2014/11/07/azure-veneziano-part-1/

More specifically, I'm re-writing the code for the Seeedstudio Link-It, which is an ARM-based board, and comes with a Arduino 1.5-like SDK.
http://www.seeedstudio.com/depot/LinkIt-ONEBackorder-p-2017.html

The problem I bumped to is against your "new" operator definition (PlacementNew.hpp). If I leave it, the compilation raises an error about the re-definition of the "new" operator. If comment out, there's no collision, but your List.cpp module (and another one, I think) raises a overloading not found for the operator "new".
Right now I'm in the office and I don't have the exact errors, but I may send you once at home.

Any clue?

Thanks and have a happy Christmas.
Mario

**Comment by bblanchon** [comment]
Hi Mario,
Any update on that issue?

**Comment by highfield** [comment]
Huh?...There's no "update", because was already solved: the library works fine.
The compilation (and thus the runtime) are working fine by simply:
- commenting out the "inline" directive within the PlacementNew module;
- adding (substituting the above one) the "#include <new>" in the List.hpp module.
Should I perform any other test?

**Comment by bblanchon** [comment]
OK, thanks for the clarification.

You're not the only one having issues with the placement new definitions.
I think I'll just remove it from the next release.
