### ISSUE TITLE
JSON Strings with quotes ...

### ISSUE THREAD

**Issue by Humancell** [bblanchon/ArduinoJson#401]
I'm slowly getting the hang of the library, and I'm parsing ok, but now I've hit an issue with comparing/checking values of the properties ... specifically Strings.

Using your example, if I have this JSON: 

```
 char json[] =
      "{\"sensor\":\"gps\",\"time\":1351824120,\"data\":[48.756080,2.302038]}";
```

I can then successfully parse it.

Now, I want to check a value ... and this continues to fail:

```
  Serial.print("sensor: ");
  if (json.containsKey("sensor"))
  {
    json["sensor"].printTo(Serial);  // NOTE: This prints "gps" with the quotes!
    Serial.println();

    if (json["sensor"]) == "gps") {  // NOTE: Always fails!  Unless changed to "\"gps\""
      /*
       *   How can I compare/get the value WITHOUT the quotes?
       *    - I don't want to have to always put escaped quotes in all comparisons?
       */
    }

```

How can I do a comparison of a string, but drop the quotes?  Or reference the JSON string without the quotes?

**Comment by bblanchon** [comment]
`printTo()` is meant to serialize a value to its JSON form, so the quotes are expected.

To get the string out of `json["sensor"]`, there are three syntaxes:

    const char* sensor = json["sensor"];
    const char* sensor = json["sensor"].as<char*>();
    const char* sensor = json.get<char*>("sensor");

To compare `char*` strings, you need to call `strcmp()` like this:

    if (strcmp(sensor, "gps") == 0) {

    }

Now, I agree that there is something wrong because this should have worked too:

    if (json["sensor"] == "gps") {
 
    }

This looks like a bug, let me see if I can fix it...

**Comment by Humancell** [comment]
Thank you for your quick reply!

Just so that you know, I had to use the following syntax to get it to work:

```
    if (strcmp(json["sensor"], "\"gps\"") == 0) {
      Serial.println(F("sensor is a gps"));
      /*
       *   Again here if I don't escape the quotes it fails ...
       *    - I'll assume this is because I did not properly de-reference it
       */
      return true;
    }
```

I really like your fix to support:

```
if (json["sensor"] == F("gps")) {

}
```

I'll grab the latest version and test later today!

**Comment by bblanchon** [comment]
Hi Scott,
This `strcmp(json["sensor"], "gps")` is really bothering me.
I'm pretty sure it works as expected.
See [this passing unit test](https://github.com/bblanchon/ArduinoJson/blob/0d8204bffa13610dc3d1bca7c433e273fe606028/test/Issue401.cpp)
Can you please check once again?

**Comment by Humancell** [comment]
Ok ... my bad.

If you look above, I was actually using the wrong comparison to detect when the strings don't "match".  I was looking for the "fail" condition, and forgot that "0" indicates a match.

`if (strcmp(json["sensor"], "gps") == 0) {
  // this is where we fail
`
I should have been using:

`if (strcmp(json["sensor"], "gps") != 0) {
  // this is where we fail
`

Your code is correct.  :-)

**Comment by bblanchon** [comment]
Good. Thanks.

**Comment by Humancell** [comment]
BTW ... when will you create a update/release that includes the fix:

```
if (json["sensor"] == F("gps")) {

}
```

This will read much better ... :-)

**Comment by Humancell** [comment]
Also ... will `!=` work also?

**Comment by bblanchon** [comment]
Yes `!=` will too.
But `<`, `>`, `<=`, `>=` won't.

**Comment by Humancell** [comment]
Excellent!  And I got the update ... I'll continue testing.

Thanks again!
