### ISSUE TITLE
ESP32 compile error

### ISSUE THREAD

**Issue by kenken64** [bblanchon/ArduinoJson#407]
Hit with compilation error urgent help pls

home/kenneth/Arduino/libraries/ArduinoJson/include/ArduinoJson/Internals/../Internals/StringFuncs.hpp:101:8: error: redefinition of 'struct ArduinoJson::Internals::StringFuncs<const char*>'
 struct StringFuncs<const __FlashStringHelper*> {
        ^
/home/kenneth/Arduino/libraries/ArduinoJson/include/ArduinoJson/Internals/../Internals/StringFuncs.hpp:52:8: error: previous definition of 'struct ArduinoJson::Internals::StringFuncs<const char*>'
 struct StringFuncs<const char*> : CharPtrFuncs {};

**Comment by bblanchon** [comment]
The problem comes from the [ESP32 core for Arduino](https://github.com/espressif/arduino-esp32).

[This line in particular](https://github.com/espressif/arduino-esp32/blob/2ba4c40acaa76f9cfa2e5c22069fbc17f1eeee48/cores/esp32/pgmspace.h#L32):

```c++
typedef char __FlashStringHelper;
```

The solution is to disable `PROGMEM` support in ArduinoJson.
To do that, just add the following line at the top of your program:

```c++
#define ARDUINOJSON_ENABLE_PROGMEM 0
```

PS: this has been added to the [Compatibility issues](https://github.com/bblanchon/ArduinoJson/wiki/Compatibility-issues#esp32), thanks for reporting it.

**Comment by kenken64** [comment]
after doing so i am getting this error

/home/kenneth/Arduino/libraries/ArduinoJson/include/ArduinoJson/JsonArray.hpp:148: undefined reference to `__cxa_guard_acquire'
/home/kenneth/Arduino/libraries/ArduinoJson/include/ArduinoJson/JsonArray.hpp:148: undefined reference to `__cxa_guard_release'
sketch/ePillBox-firmware.ino.cpp.o: In function `ArduinoJson::JsonObject::invalid()':
/home/kenneth/Arduino/libraries/ArduinoJson/include/ArduinoJson/JsonObject.hpp:131: undefined reference to `__cxa_guard_acquire'
/home/kenneth/Arduino/libraries/ArduinoJson/include/ArduinoJson/JsonObject.hpp:131: undefined reference to `__cxa_guard_release'
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board Nano32.

**Comment by kenken64** [comment]
How do you add the following argument  -fno-threadsafe-statics to the esp32 compiler ?

**Comment by kenken64** [comment]
ok added to the platform.txt but it seems the compilation erorrs still happens

"/home/kenneth/Arduino/hardware/espressif/esp32/tools/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc" "-L/home/kenneth/Arduino/hardware/espressif/esp32/tools/sdk/lib" "-L/home/kenneth/Arduino/hardware/espressif/esp32/tools/sdk/ld" -nostdlib -T esp32_out.ld -T esp32.common.ld -T esp32.rom.ld -T esp32.peripherals.ld -u call_user_start_cpu0 -Wl,--gc-sections -Wl,-static -Wl,--undefined=uxTopUsedPriority -fno-threadsafe-statics  -Wl,--start-group "/tmp/arduino_build_900112/sketch/ePillBox-firmware.ino.cpp.o" "/tmp/arduino_build_900112/libraries/DHT_sensor_library/DHT.cpp.o" "/tmp/arduino_build_900112/libraries/DHT_sensor_library/DHT_U.cpp.o" "/tmp/arduino_build_900112/arduino.ar" -lapp_update -lbt -lbtdm_app -lc -lcoexist -lcore -ldriver -lesp32 -lethernet -lexpat -lfreertos -lg -lhal -ljson -llog -llwip -lm -lmbedtls -lnet80211 -lnewlib -lnghttp -lnvs_flash -lopenssl -lphy -lpp -lrtc -lsmartconfig -lspi_flash -ltcpip_adapter -lulp -lvfs -lwpa -lwpa2 -lwpa_supplicant -lwps -lxtensa-debug-module -Wl,--end-group -o "/tmp/arduino_build_900112/ePillBox-firmware.ino.elf"
/tmp/arduino_build_900112/sketch/ePillBox-firmware.ino.cpp.o:(.literal._ZN11ArduinoJson9JsonArray7invalidEv[ArduinoJson::JsonArray::invalid()]+0x8): undefined reference to `__cxa_guard_acquire'
/tmp/arduino_build_900112/sketch/ePillBox-firmware.ino.cpp.o:(.literal._ZN11ArduinoJson9JsonArray7invalidEv[ArduinoJson::JsonArray::invalid()]+0xc): undefined reference to `__cxa_guard_release'
/tmp/arduino_build_900112/sketch/ePillBox-firmware.ino.cpp.o: In function `ArduinoJson::JsonArray::invalid()':
/home/kenneth/Arduino/libraries/ArduinoJson/include/ArduinoJson/JsonArray.hpp:148: undefined reference to `__cxa_guard_acquire'
/home/kenneth/Arduino/libraries/ArduinoJson/include/ArduinoJson/JsonArray.hpp:148: undefined reference to `__cxa_guard_release'
/tmp/arduino_build_900112/sketch/ePillBox-firmware.ino.cpp.o: In function `ArduinoJson::JsonObject::invalid()':
/home/kenneth/Arduino/libraries/ArduinoJson/include/ArduinoJson/JsonObject.hpp:131: undefined reference to `__cxa_guard_acquire'
/home/kenneth/Arduino/libraries/ArduinoJson/include/ArduinoJson/JsonObject.hpp:131: undefined reference to `__cxa_guard_release'
collect2: error: ld returned 1 exit status

**Comment by kenken64** [comment]
ok done put the -fno-threadsafe-statics wrong argument placeholder. Its SOLVED now

**Comment by bblanchon** [comment]
I completed [Wiki: Compatibility Issues](https://github.com/bblanchon/ArduinoJson/wiki/Compatibility-issues#esp32) with this information.
Can you please edit and add more detail, like the location of the file and the right placeholder?
Thank you very much @kenken64

**Comment by hamdiyavuz** [comment]
Hello,

If you have roaming directory under the AppData, you should change the C:\Users\XXXXXX\AppData\Roaming\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\Platform.txt. Thank you for library.

**Comment by psun03** [comment]
so where does '-fno-threadsafe-statics' go in the platform.txt file?

**Comment by bblanchon** [comment]
Hi @psun03,

See:

* [FAQ: Error: undefined reference to __cxa_guard_acquire and __cxa_guard_release](https://arduinojson.org/faq/error-undefined-reference-to-cxaguardacquire-and-cxaguardrelease/?utm_source=github&utm_medium=issues)

Regards,
Benoit
