### ISSUE TITLE
Array inside a JSON

### ISSUE THREAD

**Issue by pydesai** [bblanchon/ArduinoJson#410]
How would i generate this
```
{
  "timestamp" : 1483036273819,
  "values" : [ {
    "objectId" : 4,
    "instanceId" : 0,
    "resourceId" : 6,
    "datatype" : "int",
    "value" : "2"
  } ]
}
```

**Comment by bblanchon** [comment]
Just call `createNestedArray()` as in the [example](https://github.com/bblanchon/ArduinoJson/blob/master/examples/JsonGeneratorExample/JsonGeneratorExample.ino#L46).
Then call `createNestedObject()` on the new array.

See:

* [ArduinoJson: Encoding JSON](https://github.com/bblanchon/ArduinoJson/wiki/Encoding%20JSON)
* [API Reference: JsonObject::createNestedArray](https://github.com/bblanchon/ArduinoJson/wiki/API%20Reference#jsonobjectcreatenestedarray)

@pydesai, I believed this was a well-covered topic in the documentation; I'm quite surprised you didn't find it. Do you have any suggestion to improve the documentation?

**Comment by pydesai** [comment]
@bblanchon : Thanks for the prompt reply. I just skimmed through the examples topic in Wiki and found one with array but none with nested array containing json elements so posted here.
