### ISSUE TITLE
Issue with JSON element not correctly formatted.

### ISSUE THREAD

**Issue by deejayspinz** [bblanchon/ArduinoJson#413]
I have a project pulling data from Weather Underground. It's been working flawlessly for weeks.  However today, WU published JSON data that is messing it up. Wondering if the library handles non-quoted strings or if I have to do something in my code.  The offending item is dewpoint_c which is passing **:null** without quotes.

`"dewpoint_string":"NA",
"dewpoint_c":null,`

My codes results in an ESP WDT reset (yields are in there already):
`strcpy(dewpointCurr, current["dewpoint_c"]); ` <<fails here with WDT reset.
 `if (debug) {Serial.print(" Current Dewpoint: ");Serial.print(dewpointCurr); Serial.println(" C (dewpoint), ");}`

**Comment by bblanchon** [comment]
`null` is a valid JSON value and ArduinoJson translate it into a `NULL`.
This is why you get an access violation when calling `strcpy()`.

**Comment by deejayspinz** [comment]
Ah.. I see. Thanks.  For anyone else who runs into this, fixed as follows:

strcpy(dewpointCurr, checkNulls(current["dewpoint_c"]));

const char *checkNulls(char const* val)
{
  const char *pt = val;
  
  if (strlen(pt) == 0)
  {
    return "";
  }
  else
  {
    return val;
  }
}

**Comment by bblanchon** [comment]
```c++
const char* checkNulls(const char* s) {
    return s ? s : "";
}
```

but I think the Arduino's `String` class deals correcly with nulls, so this should work:

```c++
String dewpointCurr = checkNulls(current["dewpoint_c"];
```

**Comment by deejayspinz** [comment]
Thanks for the tip.  Can you help me understand this statement? I assume its a comparison but not sure how it reads?  

`return s ? s : "";`

**Comment by bblanchon** [comment]
It's a combination of the [conditional operator](https://en.wikipedia.org/wiki/%3F:) and implicit conversion from pointer to `bool`.
It's equivalent to:

```c++
if (s != NULL) 
  return s;
else
  return "";
```

**Comment by deejayspinz** [comment]
Cool. Thx for your help. Here's what [I have done](https://goo.gl/Pt8Wxb) using your JSON parser (thx!)

**Comment by bblanchon** [comment]
Congratulations 👍 
Please add it the [Wiki: Projects using ArduinoJson](https://github.com/bblanchon/ArduinoJson/wiki/Projects%20using%20ArduinoJson).
