### ISSUE TITLE
Ethernet Compatibility

### ISSUE THREAD

**Issue by andrewfasch** [bblanchon/ArduinoJson#42]
Trying to send the JSON data using the Arduino Ethernet library.
Is this possible with the library you have written? 
If so could you provide a small example?

**Comment by bblanchon** [comment]
I'll add an example as soon a possible.

I think I'll rewrite the WebServer example provided with the Ardiuno IDE and change the output to be a JSON string instead of a web page.

**Comment by bblanchon** [comment]
I added an example using EthernetServer.
Please see [JsonServer.ino](https://github.com/bblanchon/ArduinoJson/blob/master/examples/JsonServer/JsonServer.ino)

![JsonServer screen shot](https://cloud.githubusercontent.com/assets/5462433/5691896/3894b04e-98dd-11e4-89e5-92a5109b2fb3.png)
