### ISSUE TITLE
Ambiguous overload for 'operator[]'

### ISSUE THREAD

**Issue by zgoda** [bblanchon/ArduinoJson#423]
I revisited my old code written against 5.6.x and found that in 5.8.1 I'm no longer allowed to use `char[]` variable as object key:

```
src/process.cpp: In member function 'bool ProcessManager::_loadConfig()':
src/process.cpp:38:33: error: ambiguous overload for 'operator[]' (operand types are 'ArduinoJson::JsonObject' and 'char [21]')
JsonArray& statesList = root[rootKeyBuf];
```

`rootKeyBuf` is regular C string variable so I can do `sprintf()` on it. It works if I cast it to `const char *`:

```C++
JsonArray& statesList = root[(const char *)rootKeyBuf];
```

Was that intentional?

**Comment by bblanchon** [comment]
No it was not intentional; it's a bug.
Thank you for reporting it.
I'll fix it ASAP.
