### ISSUE TITLE
format not supported

### ISSUE THREAD

**Issue by maximo80** [bblanchon/ArduinoJson#426]
Hi again,

I could finally make a copy of https to http and now your script is reading the string.
I found It is not identifying well the header I suppose that the format is different.
Also It is not getting the structure I suppose as well that the format is different.

This is the http: http://afeelink.com/tado.php

I checked all buffers and there are right.

**Comment by bblanchon** [comment]
Hi @maximo80,

I'll be glad to help you.
Unfortunately, there is not enough information in your message.
Can you please elaborate?

**Comment by bblanchon** [comment]
@maximo80, any progress?
Should I close this issue?

**Comment by maximo80** [comment]
Hi @bblanchon , I am trying to find other way but I'm having problems with parsing.
This is the reading:
{"success":true,"operation":"HOME","preheating":false,"preheatingTargetOperation":null,"autoOperation":"HOME","operationTrigger":"SYSTEM","insideTemp":19.91,"setPointTemp":20.0,"controlPhase":"HEATUP","currentUserPrivacyEnabled":false,"currentUserGeoStale":null,"deviceUpdating":false,"homeId":17285,"heatingOn":true,"internetGatewayType":"GW02","internetGatewayConnected":true,"heatingMuscleType":"RU01","heatingMuscleConnected":true,"insideTemperatureSensorType":"RU01","insideTemperatureSensorConnected":true,"settingsEnabled":true,"fallbackOperation":false,"helpUrl":"https://support.tado.com/hc/","pendingDeviceInstallation":false}

The difference with your http input is the newline your example have newline and this one doesn't have I think it is why it is not working properly.
What do you think is the modification I need to do to consider this?

thanks.

**Comment by bblanchon** [comment]
@maximo80, any progress?
Should I close this issue?

**Comment by maximo80** [comment]
Hi, Close it.
I don’t know what it happens, but it doesn’t work well.

Thanks.

El 4 feb 2017, a les 12:25, Benoît Blanchon <notifications@github.com<mailto:notifications@github.com>> va escriure:


@maximo80<https://github.com/maximo80>, any progress?
Should I close this issue?

**Comment by bblanchon** [comment]
@maximo80, I'd really like to help you, but you need to provide more details.
What doesn't work well?
