### ISSUE TITLE
Help to optimize my code correctly

### ISSUE THREAD

**Issue by renat2985** [bblanchon/ArduinoJson#437]
Please help to correctly optimize my code for ArduinoJson

JSON format:
```
[{"ssid":"Laura","dbm":-81,"pass":"*"},{"ssid":"www.etaxi.lv","dbm":-48,"pass":"*"},{"ssid":"P110006"
,"dbm":-85,"pass":"*"},{"ssid":"WiFi_Tikls","dbm":-82,"pass":"*"}]
```

My code:
 ``` int n = WiFi.scanNetworks();
  String wifiScan = "[";
  if (n == 0)
    wifiScan = "{\"ssid\":\"none\"}";
  else {
    for (int i = 0; i < n - 1; ++i) {
      wifiScan += "{";
      wifiScan += "\"ssid\":\"";
      wifiScan += WiFi.SSID(i);
      wifiScan += "\",";
      wifiScan += "\"dbm\":";
      wifiScan += WiFi.RSSI(i);
      wifiScan += ",";
      wifiScan += "\"pass\":\"";
      wifiScan += (WiFi.encryptionType(i) == ENC_TYPE_NONE) ? "" : "*";
      wifiScan += "\"}";
      if (i != n - 2) wifiScan += ",";
      delay(10);
    }
    wifiScan += "]";
  }
  HTTP.send(200, "text/json", wifiScan);

**Comment by renat2985** [comment]
Thanks
```
  int n = WiFi.scanNetworks();
  DynamicJsonBuffer jsonBuffer;
  JsonObject& root = jsonBuffer.createObject();
  JsonArray& networks = root.createNestedArray("networks");
  for(int i=0;i<n;i++) {
    JsonObject& network = networks.createNestedObject();
    network["ssid"] = WiFi.SSID(i);
    network["pass"] = (WiFi.encryptionType(i) == ENC_TYPE_NONE) ? "" : "*";
    network["dbm"] = WiFi.RSSI(i);
    network["bssid"] = WiFi.BSSIDstr(i);
    network["channel"] = WiFi.channel(i);
    network["isHidden"] = WiFi.isHidden(i);
  }
  String retJson;
  root.printTo(retJson);
  HTTP.send(200, "text/json", retJson);
```

**Comment by bblanchon** [comment]
Hello Renat,

I'm glad you found the answer you were looking for.

I don't know what class is `HTTP`, but if it implements the `Print` interface, then you can do:

```
retJson.printTo(HTTP);
```

Just after sending the HTTP headers.
It would save a useless copy of the data.

Also, you should provide an initial size of the DynamicJsonBuffer.
You can use [ArduinoJson Assistant](https://bblanchon.github.io/ArduinoJson/assistant/) to find the right size.

**Comment by renat2985** [comment]
Yes I use `#include <ESP8266WebServer.h>`
I have an error. What do you think, what's the problem?
![rgb - http_init ino arduino 1 6 13_127](https://cloud.githubusercontent.com/assets/1230815/22594288/254b5654-ea2b-11e6-9c2a-57e5669afd1a.png)

**Comment by bblanchon** [comment]
Nevermind, it's not possible to do that with ESP8266WebServer.
Anyway, there are so many dynamic allocation and string duplications in ESP8266WebServer that I'm not sure it's worth optimizing the JSON side.

**Comment by gabrielklein** [comment]
Instead of json.printTo(HTTP);        

Do
String s;
json.printTo(s);
this->webServer->send(200, "text/json", s);

ESP8266 contains 4Mo of memory.

Where webServer is 
ESP8266WebServer *webServer =  new ESP8266WebServer(80);

**Comment by bblanchon** [comment]
@gabrielklein According to [wikipedia](https://en.wikipedia.org/wiki/ESP8266) the ESP8266 has 96KB of RAM for data.
