### ISSUE TITLE
Ability to print ints as hex

### ISSUE THREAD

**Issue by cosmikwolf** [bblanchon/ArduinoJson#439]
Somewhat related to #358 , but also separate. 

I use ArduinoJson to serialize data before so it can be written to flash memory on a teensy based project. I have very limited memory, and if I could have a .set(int, HEX) to print to hex, and an inverse operation to read an int in by its HEX value, you could save significant space.

**Comment by bblanchon** [comment]
Hello Tenkai,
I'm not sure it's a good idea since it not standard.
This would generate a JSON that cannot be read by other parsers.
