### ISSUE TITLE
Auto filling of variables 

### ISSUE THREAD

**Issue by renat2985** [bblanchon/ArduinoJson#440]
The file I have a lot of records. I want to automate the filling of variables. Is that possible?
Thanks
```
  File configFile = SPIFFS.open("/config.json", "r");

  jsonConfig = configFile.readString();
  DynamicJsonBuffer jsonBuffer;
  JsonObject& root = jsonBuffer.parseObject(jsonConfig);

  ssidAPName = root["ssidAPName"].as<String>();
  ssidAPPassword = root["ssidAPPassword"].as<String>();
  timezone = root["timezone"];
  SSDPName = root["SSDPName"].as<String>();
  ssidName = root["ssidName"].as<String>();
  ssidPassword = root["ssidPassword"].as<String>();

  ***
```

**Comment by bblanchon** [comment]
Hello Renat,

You can look on each key/value pair with iterators or use the program generated by the assistant.

See:

* [API Reference: JsonObject::begin() / JsonObject::end()](https://bblanchon.github.io/ArduinoJson/api/jsonobject/begin_end/)
* [ArduinoJson Assistant](https://bblanchon.github.io/ArduinoJson/assistant/)
