### ISSUE TITLE
Arduino Due

### ISSUE THREAD

**Issue by traymaster** [bblanchon/ArduinoJson#454]
Had a problem port from Mega to Due ... seemed to have resolved this now.
Thanks

**Comment by bblanchon** [comment]
The Mega has only 8KB of SRAM.
It's not very big, so you have to be very careful not to waste memory.

In particular, make sure that you do not duplicate the JSON input.
Use `parseObject(char*)` or `parseObject(Stream&)`, and not the other overloads as they duplicate the input.

See:

* [API Reference: JsonBuffer::parseObject()](https://bblanchon.github.io/ArduinoJson/api/jsonbuffer/parseobject/)
