### ISSUE TITLE
JsonObject constructor example wrong

### ISSUE THREAD

**Issue by stephenmwolfe** [bblanchon/ArduinoJson#464]
The JsonObject constructor example on the documentation site is wrong

https://bblanchon.github.io/ArduinoJson/api/jsonobject/constructor/

The example has it parsing a JsonArray

Should be changed to something like this:

  StaticJsonBuffer<200> jsonBuffer;
  
  // create an empty object
  JsonObject& object1 = jsonBuffer.createObject();
  
  // parse a JSON object
  char json[] = "{\"json\": \"test\"}";
  JsonObject& object2 = jsonBuffer.parseObject(json);

**Comment by bblanchon** [comment]
Thank you very much @stephenmwolfe 👍
It should now be fixed.
