### ISSUE TITLE
 DynamicJsonBuffer  jsonBuffer crashes my iot. 

### ISSUE THREAD

**Issue by SanjayGautam** [bblanchon/ArduinoJson#469]
Hi Blanchon ,

I also tried to use the DynamicBuffer which crashes the system , I will upload the more information , have you used , please let me know if it works for you . 

Thanks
Sanjay G

**Comment by bblanchon** [comment]
Hi Sanjay,

Can you provide more information?

Thanks,
Benoit

**Comment by bblanchon** [comment]
@SanjayGautam, did you solve this problem? Can I close the issue?
