### ISSUE TITLE
virtual destructor warning

### ISSUE THREAD

**Issue by Slechtvalk** [bblanchon/ArduinoJson#47]
When compiling for STM32 Cortex-M4 I got this warning :-1:: 

` ArduinoJson/src/Internals/../../include/ArduinoJson/Internals/../JsonBuffer.hpp:21:7: error: 'class ArduinoJson::JsonBuffer' has virtual functions and accessible non-virtual destructor [-Werror=non-virtual-dtor]
 class JsonBuffer {
       ^
cc1plus: all warnings being treated as errors`
I saw the comment about adding malloc() to Arduino code. This is quite true, but leaving a  destructor not virtual with virtual functions is considered very sloppy programming.

:smile: I propose you add `#ifndef ARDUINO` around the virtual destructor. On my STM32 those 500 bytes are of no concern and I would like to get rid of the compiler warning, which translates into an error in my build.

**Comment by bblanchon** [comment]
There is no reason to pay the price of a virtual destructor: 
1. the base class destructor is empty
2. all the derived classes are known
3. by design you must use them within a scope so the destructor is statically called.

The best solution here is to mute the warning.
I'll add a pragma.
