### ISSUE TITLE
Reusing StaticJsonBuffers

### ISSUE THREAD

**Issue by andrey-gvrd** [bblanchon/ArduinoJson#470]
The guide calls for an allocation of a buffer right before parsing. The problem with that is that it's easy to run out of stack space at runtime.

A preferable method would be to use a single (per file) global `StaticJsonBuffer` so that a potential memory issue is found at compile time. That approach doesn't currently work (even when clearing the buffer between parsing calls), not sure why.

**Comment by bblanchon** [comment]
Hello Andrey,

Please read:

* [FAQ: Why shouldn't I use a global JsonBuffer?](https://bblanchon.github.io/ArduinoJson/faq/why-shouldnt-i-use-a-global-jsonbuffer/)
* [FAQ: How to reuse a JsonBuffer?](https://bblanchon.github.io/ArduinoJson/faq/how-to-reuse-a-jsonbuffer/)

Regards,
Benoit

**Comment by andrey-gvrd** [comment]
Right on.
