### ISSUE TITLE
Basic help using jasonGenerator & ESP8226 mqqt 

### ISSUE THREAD

**Issue by luisgcu** [bblanchon/ArduinoJson#475]
#hello I was able to follow the jasonGenerator example and create a json with my sensors data, i can see it when print to serial.    -->  root.printTo(Serial);
  // This prints:
  // {"sensor":"gps","time":1351824120,"data":[48.756080,2.302038]}
what I want to know is how  I  can send the constructed Jason   using the this Mqtt library [https://github.com/knolleary/pubsubclient/blob/master/examples/mqtt_esp8266/mqtt_esp8266.ino](url)
the following function is the one  publish a mqtt  msg , how can link  the created jason to be send with client,publish funtion? 
client.publish("outTopic", msg);
Thanks

**Comment by bblanchon** [comment]
Hello @luisgcu,

Use `printTo()` to write in a `char[]` or a `String`.

See:

* [User Manual: Encoding JSON](https://bblanchon.github.io/ArduinoJson/doc/encoding/)
* [JsonArray::printTo()](https://bblanchon.github.io/ArduinoJson/api/jsonarray/printto/)
