### ISSUE TITLE
Iteration through the key-value pairs

### ISSUE THREAD

**Issue by jm4r7in** [bblanchon/ArduinoJson#477]
Hello,
I have a object like {"1" : 123, "2" : 234}
I tried to use the code : 
`for (JsonObject::iterator it=root.begin(); it!=root.end(); ++it)
{
  Serial.println(it->key);
  Serial.println(it->value.asString());
}`

But I'd like to convert the it->key into an index of an array, to do something like : 
`myarray[it->key] = it->value`

Is something like this possible ?
Thanks a lot !

**Comment by bblanchon** [comment]
Hello Jérome,

You need to convert the key to an integer.
Use [atoi()](http://en.cppreference.com/w/cpp/string/byte/atoi) to convert a `char*` to an `int`.

**Comment by jm4r7in** [comment]
Thanks a lot !
