### ISSUE TITLE
ESP8266 strange behavior

### ISSUE THREAD

**Issue by merlokk** [bblanchon/ArduinoJson#489]
Platform: arduino + ESP8266
Last commit from github. 4e9f0b2e2e80ef60dc674770bea013b5a542f3eb

this code works ok:

```
  char jsonMem[JSON_MEM_BUFFER_LEN] = {0};

  StaticJsonBuffer<JSON_OBJ_BUFFER_LEN> jsonBuffer;
  JsonObject &root = jsonBuffer.parseObject(String(jsonMem));
  if (!root.success()){
    return
  };
  root.set(paramName, paramValue);
  root.printTo(&jsonMem[0], JSON_MEM_BUFFER_LEN);
```

but if i change `JsonObject &root = jsonBuffer.parseObject(String(jsonMem));` to `JsonObject &root = jsonBuffer.parseObject(jsonMem);` it will corrupt `jsonMem` contents

as I see this code:
```
  StaticJsonBuffer<JSON_OBJ_BUFFER_LEN> jsonBuffer;
  JsonObject &root = jsonBuffer.parseObject(jsonMem);
  root.printTo(&jsonMem[0], JSON_MEM_BUFFER_LEN);
```
corrupts `jsonMem`

**Comment by merlokk** [comment]
after some investigation i see that code deletes <">, <:>, <"> or adds some <\> near <">

**Comment by merlokk** [comment]
ps. code here https://github.com/merlokk/SmartHome/blob/master/lib/xparam.h

**Comment by bblanchon** [comment]
Hi Oleg,

This is intentionnal but it's not propery documented.
I added the following page to the FAQ:

* [FAQ: Why is the input modified?](https://bblanchon.github.io/ArduinoJson/faq/why-is-the-input-modifed/)

Regards,
Benoit

**Comment by merlokk** [comment]
but it modifies not only escape characters. it modifies <"> chfracters. It made the string fully corrupted.

**Comment by bblanchon** [comment]
If this is a problem for you, just cast your input to a `const char*`.

**Comment by merlokk** [comment]
works(

**Comment by merlokk** [comment]
https://github.com/merlokk/SmartHome/commit/0411070981f3ef435757d1c3e463511f10ed8a97
https://github.com/merlokk/SmartHome/commit/0411070981f3ef435757d1c3e463511f10ed8a97
