### ISSUE TITLE
wemos D1 esp8266 parsing 

### ISSUE THREAD

**Issue by ionezz** [bblanchon/ArduinoJson#490]
hallo sir 
my output json data  : [{\"stats\":\"1\"}] 
but example {\"stats\":\"1\"} 

i cant decode [{\"stats\":\"1\"}] 
im using codeigniter for webservice and wemos D1 esp8266  
please help me

**Comment by ionezz** [comment]
Fixed just use String replace Function

**Comment by bblanchon** [comment]
Hello,

Please try

```c++
JsonArray& root = jsonBuffer.parseArray(json);
const char* stats = root[0]["stats"];
```

Regards
