### ISSUE TITLE
Parsing json fail with 4+ object or 6+ number factor in buffer costruction

### ISSUE THREAD

**Issue by EkaCreativeSolutions** [bblanchon/ArduinoJson#499]
Hi.
I have a json file in a sdcard.

example:
`,[
  {
    "name": "Legumi",
    "mode": 3,
    "state": 0,
    "manualState": 0,
    "startHour_auto": 21,
    "maxHumidity": 60,
    "minHumidity": 30,
    "startHour_timed": 22,
    "startMinute_timed": 0,
    "tempIrrigation_timed": 1,
    "lastIrrigation_start": 0,
    "lastIrrigation_stop": 0,
    "humidityStability": 0,
    "irrigationReserved": 0,
    "irrigationDay": [
      0,
      1,
      0,
      0,
      1,
      1,
      0
    ]
  }, (more object)
]`

When i have 3 object, parsing succesfull but not when costruct buffer with
`const size_t bufferSize = JSON_ARRAY_SIZE(n) + n*JSON_ARRAY_SIZE(7)  + n*JSON_OBJECT_SIZE(15) + 340*n;`
when n = 6 or +

When i have 4 or + object, parsing fail ever.

Is a problem with memory?
Sorry for my enghish. THX

**Comment by bblanchon** [comment]
Hi,

Yes, it's likely to be a memory problem.
You should use the [assistant](https://bblanchon.github.io/ArduinoJson/assistant/) to compute the required memory, and compare with the available memory on your platform.

See:

* [Why parsing fails?](https://bblanchon.github.io/ArduinoJson/faq/why-parsing-fails/)
* [ArduinoJson Assistant](https://bblanchon.github.io/ArduinoJson/assistant/)
