### ISSUE TITLE
Get JSON String Length in Arduino

### ISSUE THREAD

**Issue by tombarks** [bblanchon/ArduinoJson#50]
I want to send a JSON string via UDP from my Arduino. I was thinking to use this method (from the wiki):

char buffer[256];
array.printTo(buffer, sizeof(buffer));

I would prefer not to allocate such a large buffer. Is there a way to get the length of the string that will be generated so the buffer can be sized accordingly? Example code that could do with these improvements:

StaticJsonBuffer<200> jsonBuffer;

  JsonObject& root = jsonBuffer.createObject();
  root["sensor"] = "gps";
  root["time"] = 1351824120;

  JsonArray& data = root.createNestedArray("data");
  data.add(48.756080, 6);  // 6 is the number of decimals to print
  data.add(2.302038, 6);   // if not specified, 2 digits are printed

  char buffer[256];
  root.printTo(buffer, sizeof(buffer));

  // send a reply, to the IP address and port that sent us the packet we received
  Udp.beginPacket(remoteIP, port);
  Udp.write(buffer, sizeof(buffer));
  Udp.endPacket();

**Comment by bblanchon** [comment]
You don't need to use a buffer, you can directly print the JSON object to `Udp`.

    Udp.beginPacket(remoteIP, port);
    root.printTo(Udp);
    Udp.endPacket();

Please see the new example: [JsonUdpBeacon](https://github.com/bblanchon/ArduinoJson/blob/master/examples/JsonUdpBeacon/JsonUdpBeacon.ino)

**Comment by tombarks** [comment]
Awesome! Thanks so much for this help and this great library!

Tom
