### ISSUE TITLE
Correct JSON for special chars

### ISSUE THREAD

**Issue by dmitry-rivlin-vrp** [bblanchon/ArduinoJson#500]
I have an issue with correct JSON if inside exists special chars

`{"SSID":"DIRECT-51-HP DeskJet 3830 series ****�","RSSI":-81,"BSSID":"3c:a8:2a:c5:8:52","channel":5,"isHidden":false,"encryptionType":"WPA2"}`

must be

`{"SSID":"DIRECT-51-HP DeskJet 3830 series **\u0005**�","RSSI":-81,"BSSID":"3c:a8:2a:c5:8:52","channel":5,"isHidden":false,"encryptionType":"WPA2"}`

**Comment by bblanchon** [comment]
This is not supported by ArduinoJson, see #304.
