### ISSUE TITLE
Variable name in the query

### ISSUE THREAD

**Issue by mcmega** [bblanchon/ArduinoJson#502]
Hello Everybody!
Help! Very interesting situation!
I pass in the query a list of variable names. I want to get their meaning and return to JSON.

```
void GetOnRequest() {
  String root = "{}";
  DynamicJsonBuffer jb;
  JsonObject& json = jb.parseObject(root);
  for (int i = 0; i < HTTP.args(); i++) {
    json[HTTP.argName(i)] = HTTP.argName(i);
  }
  root = "";
  json.printTo(root);
  HTTP.send(200, "text/json", root);
}
```
Request type: /gor?CD=
Response: {"CD":"CD"}
But I need to return the value of the global variable CD, and not the name. How to write instead of HTTP.argName (i) the received text, so that the compiler is asleep on it as a code (this can be a variable, a function)?

```
Exampler request:  /gor?WiFi.localIP().toString()=
Should become:     json[HTTP.argName (i)] = WiFi.localIP().ToString();
And the request:   /gor?CD=
Should become:     json[HTTP.argName (i)] = CD;
```

It is possible certainly so:
```
if (HTTP.argName(i) == "RA") {
  Serial.println("RA:" + RA);
  json["RA"] = RA;
} else if ...
```
But I do not know what variables or functions may be needed.

**Comment by bblanchon** [comment]
Hello @mcmega,

I'm sorry, I don't understand your question...
Please try the following pattern:

1. What did you try?
2. What is the expected outcome?
3. What result did you get instead?

**Comment by mcmega** [comment]
Ok,
Request: /gor?CD=
Back I want to get the value of CD (CD - global variable in the sketch), but I'm response: {"CD":"CD"}.
I need {"CD": "Value"}
Arduino sees the CD not as the name of a variable, but as text.
The number of arguments in the query can be different, so I do not want to use "if else", but I want to cycle through the arguments. The arguments correspond to the names of the variables in the sketch.

**Comment by bblanchon** [comment]
This might be one of the only acceptable use case for a [global `JsonBuffer`](https://bblanchon.github.io/ArduinoJson/faq/why-shouldnt-i-use-a-global-jsonbuffer/):

```c++
// global JsonBuffer, only used for globalRepository
DynamicJsonBuffer globalJsonBuffer;

// variable repository, stores RA, TD, ND
JsonObject& globalRepository = globalJsonBuffer.createObject();

void GetOnRequest() {
  DynamicJsonBuffer jb; // <- don't reuse globalJsonBuffer
  JsonObject& json = jb.createObject();

  for (int i = 0; i < HTTP.args(); i++)
    json[HTTP.argName(i)] = globalRepositoty[HTTP.argName(i)];

  String root;
  json.printTo(root);
  HTTP.send(200, "text/json", root);
}
```
