### ISSUE TITLE
DynamicJsonBuffer fills whole memory

### ISSUE THREAD

**Issue by mvandi** [bblanchon/ArduinoJson#505]
Hi,
I am developing a Web of Things middleware with two university colleagues using Arduino UNOs and Raspberry Pis where the Arduino UNOs communicate with Pis via Bluetooth.
Our problem is that after roughly seven requests the DynamicJsonBuffer fills the whole Arduino memory and the creation of new JsonObjects or JsonArrays always fails. We also tried to use StaticJsonBuffers but the parsing of requests always fails.
We are using a global DynamicJsonBuffer since using local DynamicJsonBuffers fills the memory even faster.

We tried to create a new pointer to the global DynamicJsonBuffer each loop and then release it via the "delete" keyword but no improvements. The compiler also warns us that "deleting object of polymorphic class type 'ArduinoJson::DynamicJsonBufferBase<ArduinoJson::DefaultAllocator>' which has non-virtual destructor might cause undefined behaviour".

Is there a way to clear the dynamic memory allocated by the DynamicJsonBuffer?

Thanks in advance
Mattia Vandi

**Comment by bblanchon** [comment]
Hi Mattia,

The solution is simple to **not** reuse the `DynamicJsonBuffer`.
For example, you can move its declaration into the loop.

See:

* [FAQ: The first parsing succeeds, why do the next ones fail?](https://bblanchon.github.io/ArduinoJson/faq/the-first-parsing-succeeds-why-do-the-next-ones-fail/)
* [FAQ: Why shouldn't I use a global JsonBuffer?](https://bblanchon.github.io/ArduinoJson/faq/why-shouldnt-i-use-a-global-jsonbuffer/)
* [FAQ: How to reuse a JsonBuffer?](https://bblanchon.github.io/ArduinoJson/faq/how-to-reuse-a-jsonbuffer/)
* [FAQ: What's the best way to use the library?](https://bblanchon.github.io/ArduinoJson/faq/whats-the-best-way-to-use-the-library/)

Regards,
Benoit
