### ISSUE TITLE
How reuse jsonBuffer?

### ISSUE THREAD

**Issue by alessandro308** [bblanchon/ArduinoJson#508]
I've read other posts on come function ::clear() or similar. The problem is that I have the following code in the loop() on ESP-01:

```c++
  JsonObject& message = jsonBuffer.createObject();
  message["from"]=mesh.getChipId();
  message["id"]=++packetSendNumber;
  message["temp"]=getTemperature();
  String msg;
  message.printTo(msg);
  mesh.sendBroadcast(msg);
  Serial.println(msg);
```

If I creare a staticBuffer<512> after the 9-th message json object, the String msg became "{}", empty string! If I use Dinamycbuffer same thing appears on 580-th packet. How can I flush buffer after sent packet in the mesh network and printed on Serial?

**Comment by bblanchon** [comment]
Hello Alessandro,

You cannot reuse a `JsonBuffer`.
Just move its declaration in the `loop()` function.

See:

* [FAQ: The first serialization succeeds, why do the next ones fail?](https://bblanchon.github.io/ArduinoJson/faq/the-first-serialization-succeeds-why-do-the-next-ones-fail/)
* [FAQ: Why shouldn't I use a global JsonBuffer?](https://bblanchon.github.io/ArduinoJson/faq/why-shouldnt-i-use-a-global-jsonbuffer/)
* [FAQ: How to reuse a JsonBuffer?](https://bblanchon.github.io/ArduinoJson/faq/how-to-reuse-a-jsonbuffer/)
* [FAQ: What's the best way to use the library?](https://bblanchon.github.io/ArduinoJson/faq/whats-the-best-way-to-use-the-library/)

Regards,
Benoit
