### ISSUE TITLE
Compiling errors in EWARM

### ISSUE THREAD

**Issue by believe0815** [bblanchon/ArduinoJson#515]
Hello,
I am using EWARM(IAR for ARM 7.80.3), 
the compiling errors:
Error[Pe848]: expression must have arithmetic or enum type  \src\ArduinoJson\Polyfills\math.hpp Line:73 
Error[Pe848]: expression must have arithmetic or enum type  \src\ArduinoJson\Polyfills\math.hpp Line:98 

Thanks!

**Comment by bblanchon** [comment]
Hello @believe0815,

I'll need some help from you.
Can you tell me how to call `isnan()` and `isinf()` on this platform?

Regards,
Benoit

**Comment by bblanchon** [comment]
Please checkout [branch issue483](https://github.com/bblanchon/ArduinoJson/tree/issue483).
