### ISSUE TITLE
How to convert boolean (True/False) to a float value

### ISSUE THREAD

**Issue by duythang** [bblanchon/ArduinoJson#516]
Dear author
I am having a problem about converting a boolean value in JSON object to a float value.
Here is my code
```
float getData(const char* payload){
    StaticJsonBuffer<MQTT_MAX_PAYLOAD_SIZE> jsonBuffer;
    JsonObject& root = jsonBuffer.parseObject(payload);
    if (!root.success()) {
        Serial.println("parseMsg() failed");
        return;
    }

    if (root["data0"] == true){
        return 1;
    }else if(root["data0"] == false){
        return 0;
    }else{
        return root["data0"];
    };
}
```
I test this code and saw that:
- When i send a true/false value, the return value is 1/0 successfully
- However, when i send a float value, the return is always equal to 1. 

Can you help me ? Thank you so much

**Comment by duythang** [comment]
Update
I tested the code. When i send a true/false value, the return value is always 0 . When i send a float value, the return is right value.
```
float PlugPlayMQTT::getData(const char* payload, const char* type){
    StaticJsonBuffer<MQTT_MAX_PAYLOAD_SIZE> jsonBuffer;
    JsonObject& root = jsonBuffer.parseObject(payload);
    if (!root.success()) {
        Serial.println("parseMsg() failed");
        return;
    }
    return root[type];
}
```

**Comment by bblanchon** [comment]
Hello @duythang,

This is a bug, I may need a few days to find the time to fix it.
Meanwhile, you [can test the type of the value](https://bblanchon.github.io/ArduinoJson/faq/how-to-know-the-type-of-a-value/) before reading the content.

Sorry for the inconvenience.

Regards,
Benoit

**Comment by duythang** [comment]
@bblanchon Thank you so much
