### ISSUE TITLE
Json parseObject() failed in esp8266

### ISSUE THREAD

**Issue by abhiberad** [bblanchon/ArduinoJson#517]
I am using esp8266 with ardunio uno on which i want to control a led through a web server i am using this tutorial[http://blog.nyl.io/esp8266-led-arduino]( http://blog.nyl.io/esp8266-led-arduino/) but i always got parseObject() failed i also try changing StaticJsonBuffer value but no use help me Thanx in advance.

[esp8266_json.txt](https://github.com/bblanchon/ArduinoJson/files/1046672/esp8266_json.txt)

`// Parse JSON
  int size = result.length() + 1;
  char json[size];
  result.toCharArray(json, size);
  StaticJsonBuffer<200> jsonBuffer;
  JsonObject& json_parsed = jsonBuffer.parseObject(json);
  if (!json_parsed.success())
  {
    Serial.println("parseObject() failed");
    return;
  }

  // Make the decision to turn off or on the LED
  if (strcmp(json_parsed["light"], "on") == 0) {
    digitalWrite(pin, HIGH); 
    Serial.println("LED ON");
  }
  else {
    digitalWrite(pin, LOW);
    Serial.println("led off");
  }
}`

**Comment by bblanchon** [comment]
Hi @abhiberad,

Please have a look at:

* [FAQ: Why parsing fails?](https://bblanchon.github.io/ArduinoJson/faq/why-parsing-fails/)

Regards,
Benoit
