### ISSUE TITLE
ParseObject failed with different requests from openweathermap 

### ISSUE THREAD

**Issue by polebounce** [bblanchon/ArduinoJson#518]
Hello ! I would like to receive and handle weather forecast with open data from **openweathermap**. I am using **Arduino Uno** and a **Wifi Shield**. I tried to draw from examples, [this one for parsing forecast](https://www.arduino.cc/en/Tutorial.WiFi101WeatherAudioNotifier) and [this one for current weather](https://gist.github.com/ericoporto/fb9c975a290a822edca9),but I can't success, something is wrong. Indeed, I can receive forecast with sketches below, but I can't receive the current weather. In addition, when I receive data, the parsing fails.

I think there is a problem with the lenght of the weather forecast (at least 14 000 characters), and I don't know how to proceed in order to solve this issue. I know I can change the StaticJsonBuffer but I think that won't be enough. In fact, the first three data would be enough.

I need your help to fix these issues or to find a way to get and parse the first three data. @bblanchon 

Thank you.

Here are the links of the different requests and sketches. 

**Request of the current weather** : [current](http://api.openweathermap.org/data/2.5/weather?q=Paris,fr&appid=79ea8639364a5b3802bf4a29cb1edaef)

**Request of forecast** : [forecast](http://api.openweathermap.org/data/2.5/forecast?q=Paris,fr&appid=79ea8639364a5b3802bf4a29cb1edaef)

**Sketch for the current weather**  : 

`#include <ArduinoJson.h>
#include <SPI.h>
#include <WiFi.h>

#define RBUFFSIZE 600
const char server[] = "api.openweathermap.org"; 
char ssid[] = "ssid"; //  your network SSID (name)
char pass[] = "password";    // your network password (use for WPA, or use as key for WEP)
int keyIndex = 0;
int status = WL_IDLE_STATUS;
WiFiClient client;
char responseBuffer[RBUFFSIZE];
int  rbindex = 0;

boolean startCapture;

void setup() {
  Serial.begin(9600);
  while (!Serial) {
    ; // wait for serial port to connect. Needed for native USB port only
  }

  // check for the presence of the shield:
  if (WiFi.status() == WL_NO_SHIELD) {
    Serial.println("WiFi shield not present");
    // don't continue:
    while (true);
  }

  String fv = WiFi.firmwareVersion();
  if (fv != "1.1.0") {
    Serial.println("Please upgrade the firmware");
  }

  // attempt to connect to Wifi network:
  while (status != WL_CONNECTED) {
    Serial.print("Attempting to connect to SSID: ");
    Serial.println(ssid);
    // Connect to WPA/WPA2 network. Change this line if using open or WEP network:
    status = WiFi.begin(ssid, pass);

    // wait 10 seconds for connection:
    delay(10000);
  }
  Serial.println("Connected to wifi");
  printWifiStatus();
  
  Serial.println("\nStarting connection to server...");
  // if you get a connection, report back via serial:
  if (client.connect(server, 80)) {
    Serial.println("connected to server");
    // Make a HTTP request:
    client.println("GET /data/2.5/forecast?q=Paris,fr&appid=79ea8639364a5b3802bf4a29cb1edaef HTTP/1.1");
    client.println("Host: api.openweathermap.org");
    client.println("Connection: close");
    client.println();
    responseBuffer[0] = '\0';
    rbindex = 0;

    startCapture = false;   
  } 
  }

void loop()
{
  // if there are incoming bytes available 
  // from the server, read them and buffer:
  if (client.available())
  {
    char c = client.read();
    if(c == '{') {
      startCapture=true;
    }
    
    if(startCapture && rbindex < RBUFFSIZE) {
      responseBuffer[rbindex] = c;
      rbindex++;
    }
  }
  
  // if the server's disconnected, stop the client:
  if (!client.connected()) {   
      
    
    Serial.print("Received bytes");
    Serial.print(strlen(responseBuffer));
    Serial.println("Disconnecting.");
    client.stop();
    client.flush();
    
    Serial.println(responseBuffer);
    
    Serial.println();
        
    StaticJsonBuffer<500> jsonBuffer;
    
    JsonObject& root = jsonBuffer.parseObject(responseBuffer);

    if (!root.success()) {
      Serial.println("parseObject() failed");
    }  else {
    
      //Now, some examples of how to use it!    
      Serial.print("Current Temperature: ");
      Serial.print((double)root["main"]["temp"]);
      Serial.println(" K\n");
      
    }
    // do nothing forevermore:
    while(true);  
  }
}
void printWifiStatus() {
  // print the SSID of the network you're attached to:
  Serial.print("SSID: ");
  Serial.println(WiFi.SSID());

  // print your WiFi shield's IP address:
  IPAddress ip = WiFi.localIP();
  Serial.print("IP Address: ");
  Serial.println(ip);

  // print the received signal strength:
  long rssi = WiFi.RSSI();
  Serial.print("signal strength (RSSI):");
  Serial.print(rssi);
  Serial.println(" dBm");
}

`

**Sketch for the weather forecast**  : 

`#include <ArduinoJson.h>
#include <SPI.h>
#include <WiFi.h>

#define RBUFFSIZE 600
const char server[] = "api.openweathermap.org"; 
char ssid[] = "ssid"; //  your network SSID (name)
char pass[] = "password";    // your network password (use for WPA, or use as key for WEP)
int keyIndex = 0;
int status = WL_IDLE_STATUS;
WiFiClient client;
char responseBuffer[RBUFFSIZE];
int  rbindex = 0;

boolean startCapture;

void setup() {
  Serial.begin(9600);
  while (!Serial) {
    ; // wait for serial port to connect. Needed for native USB port only
  }

  // check for the presence of the shield:
  if (WiFi.status() == WL_NO_SHIELD) {
    Serial.println("WiFi shield not present");
    // don't continue:
    while (true);
  }

  String fv = WiFi.firmwareVersion();
  if (fv != "1.1.0") {
    Serial.println("Please upgrade the firmware");
  }

  // attempt to connect to Wifi network:
  while (status != WL_CONNECTED) {
    Serial.print("Attempting to connect to SSID: ");
    Serial.println(ssid);
    // Connect to WPA/WPA2 network. Change this line if using open or WEP network:
    status = WiFi.begin(ssid, pass);

    // wait 10 seconds for connection:
    delay(10000);
  }
  Serial.println("Connected to wifi");
  printWifiStatus();
  
  Serial.println("\nStarting connection to server...");
  // if you get a connection, report back via serial:
  if (client.connect(server, 80)) {
    Serial.println("connected to server");
    // Make a HTTP request:
    client.println("GET /data/2.5/forecast?q=Paris,fr&appid=79ea8639364a5b3802bf4a29cb1edaef HTTP/1.1");
    client.println("Host: api.openweathermap.org");
    client.println("Connection: close");
    client.println();
    responseBuffer[0] = '\0';
    rbindex = 0;

    startCapture = false;   
  } 
  }

void loop()
{
  // if there are incoming bytes available 
  // from the server, read them and buffer:
  if (client.available())
  {
    char c = client.read();
    if(c == '{') {
      startCapture=true;
    }
    
    if(startCapture && rbindex < RBUFFSIZE) {
      responseBuffer[rbindex] = c;
      rbindex++;
    }
  }
  
  // if the server's disconnected, stop the client:
  if (!client.connected()) {   
      
    
    Serial.print("Received bytes");
    Serial.print(strlen(responseBuffer));
    Serial.println("Disconnecting.");
    client.stop();
    client.flush();
    
    Serial.println(responseBuffer);
    
    Serial.println();
        
    StaticJsonBuffer<500> jsonBuffer;
    
    JsonObject& root = jsonBuffer.parseObject(responseBuffer);

    if (!root.success()) {
      Serial.println("parseObject() failed");
    }  else {
    
      JsonArray& list = root["list"];
      JsonObject& now = list[0];
      JsonObject& later = list[1];
      float tempNow = now["main"]["temp"];

      float tempLater = later["main"]["temp"];
      Serial.println(tempNow);
      Serial.println(tempLater);
    }
    // do nothing forevermore:
    while(true);  
  }
}
void printWifiStatus() {
  // print the SSID of the network you're attached to:
  Serial.print("SSID: ");
  Serial.println(WiFi.SSID());

  // print your WiFi shield's IP address:
  IPAddress ip = WiFi.localIP();
  Serial.print("IP Address: ");
  Serial.println(ip);

  // print the received signal strength:
  long rssi = WiFi.RSSI();
  Serial.print("signal strength (RSSI):");
  Serial.print(rssi);
  Serial.println(" dBm");
}

  
`

**Comment by bblanchon** [comment]
Hello @polebounce,

The Arduino UNO has only 2KB of RAM, you cannot parse such a big JSON.

See:

* [FAQ: Can I parse a JSON input that is too big to fit in memory?](https://bblanchon.github.io/ArduinoJson/faq/can-i-parse-a-json-input-that-is-too-big-to-fit-in-memory/)

Regards,
Benoit
