### ISSUE TITLE
error output of double type data 

### ISSUE THREAD

**Issue by lewis081** [bblanchon/ArduinoJson#519]
target platform:   nodemcu(ESP8266)
ide: eclipse neo  

short description:
I used the example and add two double type datas(88.888888 and 23.12346) to test, 
the code like this：

            StaticJsonBuffer<200> jsonBuffer;

		JsonObject& root = jsonBuffer.createObject();
		root["sensor"] = "gps";
		root["time"] = 1351824120;

		JsonArray& data = root.createNestedArray("data");
		data.add(2.302038);
		data.add(48.756081);
		data.add(88.888888);
		data.add(23.12346);

		Serial.println();
		root.prettyPrintTo(Serial);

output:
                `{
  "sensor": "gps",
  "time": 1351824120,
  "data": [
    2.302038,
    48.756081,
    88.888885,
    23.123461
  ]
}`

I was confused by the output result. Is this a bug or sth other ?
how can I get the right double value ?

**Comment by bblanchon** [comment]
Hello @lewis081,

By default ArduinoJson stores `float`, you can define [ARDUINOJSON_USE_DOUBLE](https://bblanchon.github.io/ArduinoJson/api/config/use_double/) to switch to `double`.

Regards,
Benoît
