### ISSUE TITLE
4.2 wont verify in eclipseArduinoIDE

### ISSUE THREAD

**Issue by yuanhaoliang** [bblanchon/ArduinoJson#52]
I download the eclipseArduinoIDE from http://www.baeyens.it/eclipse/,

When I verify JsonParserExample.ino  in the eclipseArduinoIDE using ArduinoIDE1.5.6-r2 which eclipse insists to,
I get the error:

Starting combiner
"E:/arduino/LinkItOne/arduino-1.5.6-r2/hardware/tools/g++_arm_none_eabi/bin/arm-none-eabi-g++" -O2 -Wl,--gc-sections -mcpu=arm7tdmi-s "-T/E:/arduino/LinkItOne/arduino-1.5.6-r2/hardware/arduino/mtk/variants/linkit_one/linker_scripts/gcc/scat.ld" "-Wl,-Map,E:/arduino/LinkItOne/eclipseArduino/workspace/Test/Release/Test.map" -o "E:/arduino/LinkItOne/eclipseArduino/workspace/Test/Release/Test.elf" "-LE:/arduino/LinkItOne/eclipseArduino/workspace/Test/Release" -lm -fpic -msvr4-struct-return -pie -Wl,--entry=gcc_entry -Wl,--unresolved-symbols=report-all -Wl,--warn-common -Wl,--warn-unresolved-symbols -Wl,--start-group "E:/arduino/LinkItOne/eclipseArduino/workspace/Test/Release/arduino/syscalls_mtk.c.o"    ./.ino.cpp.o  ./Libraries/Wire/example/LiquidCrystal_I2C1602V1/LiquidCrystal_I2C.cpp.o  ./Libraries/Wire/Wire.cpp.o  ./Libraries/Stepper/Stepper.cpp.o  ./Libraries/Servo/Servo.cpp.o  ./Libraries/SPI/SPI.cpp.o  ./Libraries/LWiFi/LWiFi.cpp.o ./Libraries/LWiFi/LWiFiClient.cpp.o ./Libraries/LWiFi/LWiFiServer.cpp.o ./Libraries/LWiFi/LWiFiUdp.cpp.o  ./Libraries/LStorage/LFlash.cpp.o ./Libraries/LStorage/LSD.cpp.o ./Libraries/LStorage/LStorage.cpp.o  ./Libraries/LGSM/utility/VoiceCall.cpp.o  ./Libraries/LGSM/LSMS.cpp.o ./Libraries/LGSM/LVoiceCall.cpp.o  ./Libraries/LGPS/utility/GPS.cpp.o  ./Libraries/LGPS/LGPS.cpp.o  ./Libraries/LGPRS/LGPRS.cpp.o ./Libraries/LGPRS/LGPRSClient.cpp.o ./Libraries/LGPRS/LGPRSServer.cpp.o ./Libraries/LGPRS/LGPRSUdp.cpp.o  ./Libraries/LGATT/utility/GATTClient.cpp.o ./Libraries/LGATT/utility/GATTServer.cpp.o  ./Libraries/LGATT/LGATTClient.cpp.o ./Libraries/LGATT/LGATTServer.cpp.o ./Libraries/LGATT/LGATTUUID.cpp.o  ./Libraries/LEEPROM/utility/sysfile.cpp.o  ./Libraries/LEEPROM/LEEPROM.cpp.o  ./Libraries/LDateTime/LDateTime.cpp.o  ./Libraries/LBattery/utility/Battery.cpp.o  ./Libraries/LBattery/LBattery.cpp.o  ./Libraries/LBT/utility/BTClient.cpp.o ./Libraries/LBT/utility/BTServer.cpp.o  ./Libraries/LBT/LBT.cpp.o ./Libraries/LBT/LBTClient.cpp.o ./Libraries/LBT/LBTServer.cpp.o  ./Libraries/LAudio/utility/Audio.cpp.o  ./Libraries/LAudio/LAudio.cpp.o  ./Libraries/ArduinoJson/src/Internals/IndentedPrint.cpp.o ./Libraries/ArduinoJson/src/Internals/JsonParser.cpp.o ./Libraries/ArduinoJson/src/Internals/List.cpp.o ./Libraries/ArduinoJson/src/Internals/Prettyfier.cpp.o ./Libraries/ArduinoJson/src/Internals/QuotedString.cpp.o ./Libraries/ArduinoJson/src/Internals/StringBuilder.cpp.o  ./Libraries/ArduinoJson/src/Arduino/Print.cpp.o  ./Libraries/ArduinoJson/src/JsonArray.cpp.o ./Libraries/ArduinoJson/src/JsonBuffer.cpp.o ./Libraries/ArduinoJson/src/JsonObject.cpp.o ./Libraries/ArduinoJson/src/JsonVariant.cpp.o  ./Libraries/ArduinoJson/ArduinoJson.cpp.o   E:/arduino/LinkItOne/eclipseArduino/workspace/Test/Release/arduino.ar   "/E:/arduino/LinkItOne/arduino-1.5.6-r2/hardware/arduino/mtk/variants/linkit_one/libmtk.a" "E:/arduino/LinkItOne/eclipseArduino/workspace/Test/Release/arduino.ar" -Wl,--end-group
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::Internals::IndentedPrint::write(unsigned char)':
E:/arduino/workspace/libraries/ArduinoJson/src/Internals/IndentedPrint.cpp:11: multiple definition of `ArduinoJson::Internals::IndentedPrint::write(unsigned char)'
./Libraries/ArduinoJson/src/Internals/IndentedPrint.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/Internals/IndentedPrint.cpp:11: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::Internals::JsonParser::skip(char const*)':
E:/arduino/workspace/libraries/ArduinoJson/src/Internals/JsonParser.cpp:32: multiple definition of `ArduinoJson::Internals::JsonParser::skip(char const*)'
./Libraries/ArduinoJson/src/Internals/JsonParser.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/Internals/JsonParser.cpp:32: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::Internals::QuotedString::extractFrom(char*, char**)':
E:/arduino/workspace/libraries/ArduinoJson/src/Internals/QuotedString.cpp:60: multiple definition of `ArduinoJson::Internals::QuotedString::extractFrom(char*, char**)'
./Libraries/ArduinoJson/src/Internals/QuotedString.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/Internals/QuotedString.cpp:60: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::Internals::StringBuilder::write(unsigned char)':
E:/arduino/workspace/libraries/ArduinoJson/src/Internals/StringBuilder.cpp:11: multiple definition of `ArduinoJson::Internals::StringBuilder::write(unsigned char)'
./Libraries/ArduinoJson/src/Internals/StringBuilder.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/Internals/StringBuilder.cpp:11: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonArray::at(int) const':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonArray.cpp:17: multiple definition of `ArduinoJson::JsonArray::at(int) const'
./Libraries/ArduinoJson/src/JsonArray.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonArray.cpp:17: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonBuffer::createArray()':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonBuffer.cpp:16: multiple definition of `ArduinoJson::JsonBuffer::createArray()'
./Libraries/ArduinoJson/src/JsonBuffer.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonBuffer.cpp:16: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonBuffer::createObject()':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonBuffer.cpp:21: multiple definition of `ArduinoJson::JsonBuffer::createObject()'
./Libraries/ArduinoJson/src/JsonBuffer.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonBuffer.cpp:21: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonVariant::operator ArduinoJson::JsonArray&() const':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:17: multiple definition of `ArduinoJson::JsonVariant::operator ArduinoJson::JsonArray&() const'
./Libraries/ArduinoJson/src/JsonVariant.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:17: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonVariant::operator ArduinoJson::JsonObject&() const':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:21: multiple definition of `ArduinoJson::JsonVariant::operator ArduinoJson::JsonObject&() const'
./Libraries/ArduinoJson/src/JsonVariant.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:21: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonVariant::operator bool() const':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:25: multiple definition of `ArduinoJson::JsonVariant::operator bool() const'
./Libraries/ArduinoJson/src/JsonVariant.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:25: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonVariant::operator char const*() const':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:29: multiple definition of `ArduinoJson::JsonVariant::operator char const*() const'
./Libraries/ArduinoJson/src/JsonVariant.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:29: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonVariant::operator double() const':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:33: multiple definition of `ArduinoJson::JsonVariant::operator double() const'
./Libraries/ArduinoJson/src/JsonVariant.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:33: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonVariant::operator long() const':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:37: multiple definition of `ArduinoJson::JsonVariant::operator long() const'
./Libraries/ArduinoJson/src/JsonVariant.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:37: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonVariant::set(bool)':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:41: multiple definition of `ArduinoJson::JsonVariant::set(bool)'
./Libraries/ArduinoJson/src/JsonVariant.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:41: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonVariant::set(char const*)':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:47: multiple definition of `ArduinoJson::JsonVariant::set(char const*)'
./Libraries/ArduinoJson/src/JsonVariant.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:47: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonVariant::set(double, unsigned char)':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:53: multiple definition of `ArduinoJson::JsonVariant::set(double, unsigned char)'
./Libraries/ArduinoJson/src/JsonVariant.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:53: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonVariant::set(long)':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:59: multiple definition of `ArduinoJson::JsonVariant::set(long)'
./Libraries/ArduinoJson/src/JsonVariant.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:59: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonVariant::set(ArduinoJson::JsonArray&)':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:65: multiple definition of `ArduinoJson::JsonVariant::set(ArduinoJson::JsonArray&)'
./Libraries/ArduinoJson/src/JsonVariant.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:65: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonVariant::set(ArduinoJson::JsonObject&)':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:71: multiple definition of `ArduinoJson::JsonVariant::set(ArduinoJson::JsonObject&)'
./Libraries/ArduinoJson/src/JsonVariant.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:71: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonVariant::size() const':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:77: multiple definition of `ArduinoJson::JsonVariant::size() const'
./Libraries/ArduinoJson/src/JsonVariant.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:77: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonVariant::operator[](int)':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:83: multiple definition of `ArduinoJson::JsonVariant::operator[](int)'
./Libraries/ArduinoJson/src/JsonVariant.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:83: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::Internals::QuotedString::printTo(char const*, Print&)':
E:/arduino/workspace/libraries/ArduinoJson/src/Internals/QuotedString.cpp:34: multiple definition of `ArduinoJson::Internals::QuotedString::printTo(char const*, Print&)'
./Libraries/ArduinoJson/src/Internals/QuotedString.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/Internals/QuotedString.cpp:34: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonObject::getNodeAt(char const*) const':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonObject.cpp:62: multiple definition of `ArduinoJson::JsonObject::getNodeAt(char const*) const'
./Libraries/ArduinoJson/src/JsonObject.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonObject.cpp:62: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonObject::remove(char const*)':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonObject.cpp:46: multiple definition of `ArduinoJson::JsonObject::remove(char const*)'
./Libraries/ArduinoJson/src/JsonObject.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonObject.cpp:46: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonObject::operator[](char const*)':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonObject.cpp:30: multiple definition of `ArduinoJson::JsonObject::operator[](char const*)'
./Libraries/ArduinoJson/src/JsonObject.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonObject.cpp:30: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonVariant::operator[](char const*)':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:88: multiple definition of `ArduinoJson::JsonVariant::operator[](char const*)'
./Libraries/ArduinoJson/src/JsonVariant.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:88: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonObject::createNestedObject(char const*)':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonObject.cpp:55: multiple definition of `ArduinoJson::JsonObject::createNestedObject(char const*)'
./Libraries/ArduinoJson/src/JsonObject.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonObject.cpp:55: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonObject::createNestedArray(char const*)':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonObject.cpp:48: multiple definition of `ArduinoJson::JsonObject::createNestedArray(char const*)'
./Libraries/ArduinoJson/src/JsonObject.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonObject.cpp:48: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonObject::at(char const*) const':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonObject.cpp:25: multiple definition of `ArduinoJson::JsonObject::at(char const*) const'
./Libraries/ArduinoJson/src/JsonObject.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonObject.cpp:25: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonObject::at(char const*)':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonObject.cpp:20: multiple definition of `ArduinoJson::JsonObject::at(char const*)'
./Libraries/ArduinoJson/src/JsonObject.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonObject.cpp:20: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::Internals::Prettyfier::unindentIfNeeded()':
E:/arduino/workspace/libraries/ArduinoJson/src/Internals/Prettyfier.cpp:81: multiple definition of `ArduinoJson::Internals::Prettyfier::unindentIfNeeded()'
./Libraries/ArduinoJson/src/Internals/Prettyfier.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/Internals/Prettyfier.cpp:81: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::Internals::Prettyfier::indentIfNeeded()':
E:/arduino/workspace/libraries/ArduinoJson/src/Internals/Prettyfier.cpp:74: multiple definition of `ArduinoJson::Internals::Prettyfier::indentIfNeeded()'
./Libraries/ArduinoJson/src/Internals/Prettyfier.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/Internals/Prettyfier.cpp:74: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::Internals::Prettyfier::write(unsigned char)':
E:/arduino/workspace/libraries/ArduinoJson/src/Internals/Prettyfier.cpp:11: multiple definition of `ArduinoJson::Internals::Prettyfier::write(unsigned char)'
./Libraries/ArduinoJson/src/Internals/Prettyfier.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/Internals/Prettyfier.cpp:11: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::Internals::JsonParser::skipSpaces()':
E:/arduino/workspace/libraries/ArduinoJson/src/Internals/JsonParser.cpp:20: multiple definition of `ArduinoJson::Internals::JsonParser::skipSpaces()'
./Libraries/ArduinoJson/src/Internals/JsonParser.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/Internals/JsonParser.cpp:20: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::Internals::JsonParser::skip(char)':
E:/arduino/workspace/libraries/ArduinoJson/src/Internals/JsonParser.cpp:24: multiple definition of `ArduinoJson::Internals::JsonParser::skip(char)'
./Libraries/ArduinoJson/src/Internals/JsonParser.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/Internals/JsonParser.cpp:24: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonObject::writeTo(ArduinoJson::Internals::JsonWriter&) const':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonObject.cpp:69: multiple definition of `ArduinoJson::JsonObject::writeTo(ArduinoJson::Internals::JsonWriter&) const'
./Libraries/ArduinoJson/src/JsonObject.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonObject.cpp:69: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonVariant::writeTo(ArduinoJson::Internals::JsonWriter&) const':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:93: multiple definition of `ArduinoJson::JsonVariant::writeTo(ArduinoJson::Internals::JsonWriter&) const'
./Libraries/ArduinoJson/src/JsonVariant.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:93: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonArray::writeTo(ArduinoJson::Internals::JsonWriter&) const':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonArray.cpp:46: multiple definition of `ArduinoJson::JsonArray::writeTo(ArduinoJson::Internals::JsonWriter&) const'
./Libraries/ArduinoJson/src/JsonArray.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonArray.cpp:46: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonArray::add()':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonArray.cpp:23: multiple definition of `ArduinoJson::JsonArray::add()'
./Libraries/ArduinoJson/src/JsonArray.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonArray.cpp:23: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonArray::createNestedObject()':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonArray.cpp:39: multiple definition of `ArduinoJson::JsonArray::createNestedObject()'
./Libraries/ArduinoJson/src/JsonArray.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonArray.cpp:39: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonArray::createNestedArray()':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonArray.cpp:32: multiple definition of `ArduinoJson::JsonArray::createNestedArray()'
./Libraries/ArduinoJson/src/JsonArray.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonArray.cpp:32: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::Internals::JsonParser::parseArray()':
E:/arduino/workspace/libraries/ArduinoJson/src/Internals/JsonParser.cpp:89: multiple definition of `ArduinoJson::Internals::JsonParser::parseArray()'
./Libraries/ArduinoJson/src/Internals/JsonParser.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/Internals/JsonParser.cpp:89: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::Internals::JsonParser::parseAnythingTo(ArduinoJson::JsonVariant&)':
E:/arduino/workspace/libraries/ArduinoJson/src/Internals/JsonParser.cpp:41: multiple definition of `ArduinoJson::Internals::JsonParser::parseAnythingTo(ArduinoJson::JsonVariant&)'
./Libraries/ArduinoJson/src/Internals/JsonParser.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/Internals/JsonParser.cpp:41: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonBuffer::parseArray(char*, unsigned char)':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonBuffer.cpp:26: multiple definition of `ArduinoJson::JsonBuffer::parseArray(char*, unsigned char)'
./Libraries/ArduinoJson/src/JsonBuffer.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonBuffer.cpp:26: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::Internals::JsonParser::parseObject()':
E:/arduino/workspace/libraries/ArduinoJson/src/Internals/JsonParser.cpp:119: multiple definition of `ArduinoJson::Internals::JsonParser::parseObject()'
./Libraries/ArduinoJson/src/Internals/JsonParser.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/Internals/JsonParser.cpp:119: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::JsonBuffer::parseObject(char*, unsigned char)':
E:/arduino/workspace/libraries/ArduinoJson/src/JsonBuffer.cpp:31: multiple definition of `ArduinoJson::JsonBuffer::parseObject(char*, unsigned char)'
./Libraries/ArduinoJson/src/JsonBuffer.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonBuffer.cpp:31: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::Internals::IndentedPrint::writeTabs()':
E:/arduino/workspace/libraries/ArduinoJson/src/Internals/../../include/ArduinoJson/Internals/List.hpp:60: multiple definition of `ArduinoJson::JsonArray::_invalid'
./Libraries/ArduinoJson/src/JsonArray.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonArray.cpp:17: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `ArduinoJson::Internals::IndentedPrint::writeTabs()':
E:/arduino/workspace/libraries/ArduinoJson/src/Internals/../../include/ArduinoJson/Internals/ListNode.hpp:20: multiple definition of `ArduinoJson::JsonObject::_invalid'
./Libraries/ArduinoJson/src/JsonObject.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/../include/ArduinoJson/Internals/List.hpp:32: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o: In function `.LANCHOR1':
E:/arduino/workspace/libraries/ArduinoJson/src/Internals/IndentedPrint.cpp:11: multiple definition of `ArduinoJson::JsonVariant::_invalid'
./Libraries/ArduinoJson/src/JsonVariant.cpp.o:E:/arduino/workspace/libraries/ArduinoJson/src/JsonVariant.cpp:17: first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o:(.data.rel.ro+0x0): multiple definition of `vtable for ArduinoJson::Internals::StringBuilder'
./Libraries/ArduinoJson/src/Internals/StringBuilder.cpp.o:(.data.rel.ro+0x0): first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o:(.data.rel.ro+0x10): multiple definition of `vtable for ArduinoJson::Internals::Prettyfier'
./Libraries/ArduinoJson/src/Internals/Prettyfier.cpp.o:(.data.rel.ro+0x0): first defined here
./Libraries/ArduinoJson/ArduinoJson.cpp.o:(.data.rel.ro+0x20): multiple definition of `vtable for ArduinoJson::Internals::IndentedPrint'
./Libraries/ArduinoJson/src/Internals/IndentedPrint.cpp.o:(.data.rel.ro+0x0): first defined here
collect2: ld returned 1 exit status

Only the ArduinoJson will be error. help.....

**Comment by bblanchon** [comment]
You probably just need to delete (or exclude) `ArduinoJson.cpp` at the root of the library.
This file is including all other `.cpp` files, this is just for the classic Arduino IDE.

You can see I already put a `#ifdef ARDUINO` in this file, in hope it would be ignores by other IDEs.
But apparently it doesn't work.

I would be very interested if you find another preprocessor symbol that we could use to exclude this file on Eclipse.

**Comment by yuanhaoliang** [comment]
OK, I will try.

**Comment by dcsoftware** [comment]
I had the same problem and resolved it by excluding the "src" folder from building.
After you include the library in your project, expand Libraries->ArduinoJson->right click on the "src" folder->select Resource Configurations->Exclude from Build-> tick the release option. OK and verify again, it should work now!
