### ISSUE TITLE
Visual-Micro Errors

### ISSUE THREAD

**Issue by mo2menelzeiny** [bblanchon/ArduinoJson#522]
I'm still experiencing the same errors as issue #483 on Visual-Micro, I tried a new empty Arduino Project with only ArduinoJson included and around 1108 errors are produced.
However by just adding #undef _MSC_VER before the ArduinoJson include statment, simply removes all the errors. I've also made sure I have the latest 5.10.0 library version.
I can't seem to understand why is this happening, any thoughts?

**Comment by bblanchon** [comment]
Hello @mo2menelzeiny,

This issue is fixed on the master branch, and will be available in 5.10.1.

Regards,
Benoit

**Comment by mo2menelzeiny** [comment]
Yep, just cloned it and replaced the release in the Arduino Library folder, errors are all gone! 
Thanks @bblanchon!

**Comment by bblanchon** [comment]
I just released [5.10.1](https://github.com/bblanchon/ArduinoJson/releases/tag/v5.10.1).
Sorry about that.
