### ISSUE TITLE
Can't compile ArduinoJson with GNU++11

### ISSUE THREAD

**Issue by Sparow199** [bblanchon/ArduinoJson#548]
Hello,
I'm working with [PlatformIO](https://github.com/platformio) and i'm wan't to make some unit tests with [ArduinoFake](https://github.com/FabioBatSilva/ArduinoFake).
`
[env:native]
  | platform = native
  | build_flags = -std=gnu++11
  | lib_deps = ArduinoFake
  | # lib_deps = git@github.com:FabioBatSilva/ArduinoFake.git
`
All my libraries compile without problems ( ex Hashmap for arduino ) but ArduinoJson don't.
My project is based on ArduinoJson so i can't replace it, so i can't make any unit tests.

Unfortunatly, i hadn't save the log but, it was composed by : 
`no match for ‘operator=’ (operand types are ‘ArduinoJson::JsonVariant’ and ‘const String’)`
`error: ‘equals’ is not a member of ‘ArduinoJson::Internals::StringTraits<const String&, void>`

I'm using the last realease of ArduinoJson.

Thank you.

**Comment by bblanchon** [comment]
Hello @Sparow199,

Please try to set [ARDUINOJSON_ENABLE_ARDUINO_STRING](https://bblanchon.github.io/ArduinoJson/api/config/enable_arduino_string/) to 1.

Regards,
Benoit

**Comment by bblanchon** [comment]
@Sparow199, any progress?

**Comment by Sparow199** [comment]
Hello, i'm sorry for late reply, the tests was in stand by waiting for solution, i tried to compile Arduino Json now with this trick and it works fine.

Thank you!
