### ISSUE TITLE
Support of Arduino's String class

### ISSUE THREAD

**Issue by bblanchon** [bblanchon/ArduinoJson#56]

**Comment by MadLittleMods** [comment]
:+1:

**Comment by jelledewit** [comment]
In current situation, how can we use a String as parameter for parseObject function?

**Comment by bblanchon** [comment]
Yes but you have to `const_cast` the result of `c_str()` because the JSON parse needs to modify the string:

    jsonBuffer.parserObject(const_cast<char*>(myString.c_str()));

**Comment by jelledewit** [comment]
That's great. Many thanks.

**Comment by bblanchon** [comment]
Available in [v5.0 beta 1](https://github.com/bblanchon/ArduinoJson/releases/tag/v5.0-beta-1)
