### ISSUE TITLE
wrong link in docs (Link to Examples goes to API page)

### ISSUE THREAD

**Issue by linuxlurak** [bblanchon/ArduinoJson#572]
Over at
https://bblanchon.github.io/ArduinoJson/doc/
you have:
"**Examples**
Contains complete programs that shows how to use ArduinoJson in various situations."
And the **Example** title is inked to the API description.

Thanks for your great work and the time you investedt!
Cheers

**Comment by bblanchon** [comment]
Hi @linuxlurak,
Thanks you very much for reporting this mistake.
Regards,
Benoit
