### ISSUE TITLE
ArduinoJson conflicts WiFi.h

### ISSUE THREAD

**Issue by akigamana** [bblanchon/ArduinoJson#576]
hello everybody. i tried to use serial comm, WiFi (TCP), and ArduinoJson in an ESP32 project (doit devkit v1) and failed. the problem appears even when you include ArduinoJson while you're simply connecting to a wifi AP.

**Comment by bblanchon** [comment]
Hi @akigamana 

Thank you very much for reporting this issue.
Can you please share an [MCVE](https://stackoverflow.com/help/mcve)?

**Comment by TLS1000** [comment]
I'm using the same setup and i haven't experienced any problems so far.
wifi, arduinojson, AWS IOT, serial monitor, ESP32-DOITV1
