### ISSUE TITLE
Too many decimal points when using float or double

### ISSUE THREAD

**Issue by pranaliraval** [bblanchon/ArduinoJson#578]
Hi,
I'm trying to assign float or double value as following.

double t = 16.53;
float p = 1.9; 

root.set("t", t);
 root.set("p", p);

However, when I print the values from root, it prints something like this : 16.529999956 or 1.955555443. I went through change log of the library and previous issues and there it's mentioned that this issue is taken care of but I'm unable to use float/double because of this. Also, sometimes it gives correct output but that behavior is highly random. 

Please help me out with this and let me know if I'm doing something wrong. Any guidance would be appreciated. 

Thank you.

**Comment by bblanchon** [comment]
Hi @pranaliraval,

Currently, the only solution is to switch the internal storage to `float` by defining [ARDUINOJSON_USE_DOUBLE](https://bblanchon.github.io/ArduinoJson/api/config/use_double/) to `0`

See demo: https://wandbox.org/permlink/C6ZO22Cx7tEL1Vig

Regards,
Benoit
