### ISSUE TITLE
Testing for a json value?

### ISSUE THREAD

**Issue by faceless105** [bblanchon/ArduinoJson#580]
Is there a good way to check if a json value exists before calling it up?

For example, if I'm looking for ...

`char json[payload.length())];
      payload.toCharArray(json,payload.length());
      StaticJsonBuffer<200> jsonBuffer;
      JsonObject& root = jsonBuffer.parseObject(json);
      override = atoi(root["override"]);`

But what if for whatever reason, root['override'] was never sent?

**Comment by bblanchon** [comment]
Hi @faceless105,

Please have a look at [JsonObject::containsKey()](https://bblanchon.github.io/ArduinoJson/api/jsonobject/containskey/).

Regards,
Benoit
