### ISSUE TITLE
How to add array property of nested objects

### ISSUE THREAD

**Issue by adnan-kamili** [bblanchon/ArduinoJson#583]
Hi,
The nested array example, creates array of numbers. How do I add objects e.g.

```
{
  "a": 10,
  "b": [
    {
      "id": "1",
      "value": 23
    },
    {
      "id": "2",
      "value": 24
    }
  ]
}
```

**Comment by bblanchon** [comment]
Hi @adnan-kamili,

You just need to call [createNestedObject()](https://bblanchon.github.io/ArduinoJson/api/jsonarray/createnestedobject/) instead of [add()](https://bblanchon.github.io/ArduinoJson/api/jsonarray/add/).

Regards,
Benoit
