### ISSUE TITLE
how to reset JsonBuffer???

### ISSUE THREAD

**Issue by mechanic98** [bblanchon/ArduinoJson#585]
hi ,
i am writing a code that give whether forecasr from Wunderground website and send to telegram robat.
but in the firt runing the code work good but the next loop i cant give forecast :(
i also reed this : https://bblanchon.github.io/ArduinoJson/faq/the-first-parsing-succeeds-why-do-the-next-ones-fail/
i want to reset jsonbuffer in other to modify code, mabye
but i cant modify code :(
please help me
thanks,
this is my code:

https://pastebin.com/78XUP7xa

and this is my Serial monitor report:

https://pastebin.com/dptRUvRm

**Comment by bblanchon** [comment]
Hi @mechanic98,

Please realize that there is not much we can do without modifying the code :wink:

Anyways, have a look at [JsonBuffer::clear()](https://bblanchon.github.io/ArduinoJson/api/jsonbuffer/clear/).

Regards,
Benoit
