### ISSUE TITLE
Help formmating Json

### ISSUE THREAD

**Issue by matusalens** [bblanchon/ArduinoJson#587]
Hi I put arduinoJson in my program, and have a method to get wifi lans and send in json to web page.
But one of lans have especial caracters on name, and this make json invalid.

There are some way to valiate caracteres before ?

Sorry my bad english, I put bellow json sended to page:

{"redes":6,"data":["Dori","ESPTyphon__588","ESPTyphon_997","DIRECT-92-HP DeskJet 3630 series Ì","matusalens 2.4g","Matusalens_Convidados"]}

Best Regards

**Comment by bblanchon** [comment]
Hi @matusalens,

ArduinoJson is not able to translate to UTF-16 surrogate pair like `\u1234` (see #304).

However, it doesn't modify the characters, so if you use the same encoding as the sender (UTF-8 is a good choice), then everything should be OK.

If you're getting this in the Arduino Serial Monitor, this is normal.
As far as I know, it doesn't support UTF-8, see: https://playground.arduino.cc/Code/UTF-8
You may try another application to read from the serial.

Regards,
Benoit
