### ISSUE TITLE
Can't purchase e-book

### ISSUE THREAD

**Issue by heritageorchard** [bblanchon/ArduinoJson#601]
Hi,

Fantastic library !!! Thank You for your work.

The link: https://ebook.benoitblanchon.fr/buy

appears to be broken.

Take Care,
Mike

**Comment by bblanchon** [comment]
Not yet, I'm in the process of writing it and should be ready by the end of this month.
Sorry about that 😃

**Comment by heritageorchard** [comment]
No worries at all my friend. 

Would you consider some way to identify c++ knowledge versus Json?

I have 30 years(!!!) c++ experience so need the Json side more. 

As an aside, I want to use Json as the persistence. Should my ctor take in a JsonObject or varient!

Once again I really appreciate your work. I had open source code and a few textbooks for the verification world and know the effort involved. 

Typos due to small phone and big fingers.

**Comment by bblanchon** [comment]
> As an aside, I want to use Json as the persistence. Should my ctor take in a JsonObject or varient!

If you want to hydrate an object from a JSON object, you most likely want its constructor to take a `JsonObject&`.
A `JsonVariant` would just add a layer of indirection that is probably not necessary.

**Comment by heritageorchard** [comment]
Yes that makes perfect sense. Sorry for being dense.

**Comment by bblanchon** [comment]
# [The book is out!!!!](https://leanpub.com/arduinojson) 🎉
