### ISSUE TITLE
Create Nested Object from const char *

### ISSUE THREAD

**Issue by mcmega** [bblanchon/ArduinoJson#605]
Hello!
I get the answer in the form of a json line. How can I put this object in an array?
I do not want to use the buffer and lose memory for the conversion, because the response is the json object.
It should turn out:
```
// Need to add an array of objects
const char * data = "{...}";  // Answer in the form of a json (I get different at each iteration of the cycle)

[ data, data, data, ... ]
```

**Comment by bblanchon** [comment]
Hi @mcmega,

You can either use an array of `String`, or an array of array of char:

```c++
const size_t NAME_LEN = 32;
const size_t MAX_NAMES = 8;

char names[MAX_NAMES][NAME_LEN];
size_t nameCount = 0;

// and call  strcpy to copy in the array
strncpy(names[nameCount++], "{...}", NAME_LEN);
```

Regards,
Benoit
