### ISSUE TITLE
EBook purchase is unavailable - 503

### ISSUE THREAD

**Issue by rafkhan** [bblanchon/ArduinoJson#616]
Hey, I wasn't sure how to reach out to @bblanchon - couldn't find an email, so I thought I'd leave an issue. We're using this library in our project, so I wanted to grab the e-book and support a great cause!

Unfortunately - the page is returning a 503 :(

I hope this gets resolved soon, thanks for all the hard work.

**Comment by bblanchon** [comment]
Hi,

The book is not finished yet, it should be ready at the end of the month.
Sorry about that.

**Comment by bblanchon** [comment]
# [The book is out!!!!](https://leanpub.com/arduinojson) 🎉

**Comment by beicnet** [comment]
WOW!!! Congrats!!! :1st_place_medal:
