### ISSUE TITLE
Simple Json Stream

### ISSUE THREAD

**Issue by kalindud** [bblanchon/ArduinoJson#618]
Hello...
 A simple question..

How do you generate a simple JSON stream like this:

[
{
 "Temperature" : 20
 "Humidity" : 30
}
]

I tried Arrays and Nested Arrays but couldn't entirely get it.
Thank you

**Comment by bblanchon** [comment]
Hi @kalindud,

Just use the [ArduinoJson Assistant](https://arduinojson.org/assistant/), it generate the following program:

```c++
const size_t bufferSize = JSON_ARRAY_SIZE(1) + JSON_OBJECT_SIZE(2);
DynamicJsonBuffer jsonBuffer(bufferSize);

JsonArray& root = jsonBuffer.createArray();

JsonObject& root_0 = root.createNestedObject();
root_0["Temperature"] = 20;
root_0["Humidity"] = 30;

root.printTo(Serial);
````
