### ISSUE TITLE
Non library related issue! ;) #616

### ISSUE THREAD

**Issue by beicnet** [bblanchon/ArduinoJson#625]
Hey @bblanchon,

Please fix you "buy" link on the [Pruchase button](https://ebook.benoitblanchon.fr/buy), because it gives me "**503 Service Temporarily Unavailable**" error, tried yesterday, but also got the same error today.

Regards,
Viktor

Same as at #616, did not see it, closing'

**Comment by bblanchon** [comment]
Hi @beicnet,

Sorry about that, I'm almost done writing the book.

Regards,
Benoit

**Comment by beicnet** [comment]
Hey @bblanchon,

Not a big deal, we can wait for it! ;)

Regards,
Viktor

**Comment by mikefresh** [comment]
+1 want to give you money and also read asap to possibly suggest it for some of my students in January.

**Comment by bblanchon** [comment]
# [The book is out!!!!](https://leanpub.com/arduinojson) 🎉

**Comment by beicnet** [comment]
Let's celebrate then!!! ;)
