### ISSUE TITLE
Why is FlashStringHelper duplicated into buffer on ESP8266?

### ISSUE THREAD

**Issue by me21** [bblanchon/ArduinoJson#627]
Consider the following code snippet:

```
StaticJsonBuffer<200> b;
JsonObject& o = b.CreateObject();
o[F("key")] = F("value");
```

Why the contents of "key" and "value" strings are duplicated into StaticJsonBuffer? After all, they are pointers to constant string in flash memory, just as **const char* ** are pointers to constant string in RAM, and they are not duplicated.

Is it just to simplify the code, i.e. we know that all strings end up in RAM, be it user provided pointer, or a pointer inside JsonBuffer?

**Comment by bblanchon** [comment]
Hi @me21,

Please have a look at https://github.com/bblanchon/ArduinoJson/issues/597#issuecomment-341030039

Extract:

> The decision to make a copy of Flash string is motivated by:
> 
> 1. Keeping the code smaller when Flash strings are not used.
>     You don't want to link your program to `strcmp_P()` if you don't use Flash strings.
> 2. Keeping the `JsonPair` key type to `const char*`.
>     It is used when you iterate over the key-value pairs of an object.
>     Changing the type would break a lot of code.
> 3. Being able to call `myObject["key"].as<char*>()` regardless of how the value was inserted.
