### ISSUE TITLE
serialisation of JsonObject 

### ISSUE THREAD

**Issue by jhoogeboom** [bblanchon/ArduinoJson#63]
Excuse me if this is a silly question and I've just overlooked something, but the only way to serialise the generated JsonObject is to run it with the two print-methods right? Using the stream/print interfaces of arduino or commandlineoutput if not on arduino.

Is there a straightforward way to get the serialised data in a buffer? say a char array? The reason I ask is I would like to store some json on eeprom as configuration for a node as well as have nodes send json over RF using packets.

I can see one way, to implement a stream that just collects the bytes as they come in, but if there is an easier way/already existing, that'd be way better.

**Comment by bblanchon** [comment]
char buffer[256];
    myJsonObject.printTo(buffer, sizeof(buffer));

See https://github.com/bblanchon/ArduinoJson/wiki/Encoding%20JSON#use-a-classic-char

**Comment by jhoogeboom** [comment]
great! thanks
