### ISSUE TITLE
parse a primitive 

### ISSUE THREAD

**Issue by vortex314** [bblanchon/ArduinoJson#633]
I didn't find in the documentation a way to parse a primitive like string,boolean,number which could return a JsonVariant. I have a use case where I can receive any of the JSON primitive values.
The only way around this would be to encapsulate it first as an array and extract element 0.

Any other recommendation ? 

BTW : Great library ! Works excellent on ESP8266 and ESP32.

**Comment by bblanchon** [comment]
Hi @vortex314,

You are looking for [`JsonBuffer::parse()`](http://arduinojson.org/api/jsonbuffer/parse/).

Thank you very much for the kind words ;-)

Regards,
Benoit

**Comment by vortex314** [comment]
Benoit, thanks for the swift response ! Apparently I succeeded to miss this in the documentation. :-(
Is there also an equivalent to do the opposite like JsonVariant::printTo() ?
Lieven

**Comment by bblanchon** [comment]
Hi Lieven,

There is [`JsonVariant::printTo()`](https://arduinojson.org/api/jsonvariant/printto/).
It was missing in the documentation, I just added it.

Regards,
Benoit

**Comment by vortex314** [comment]
Hi Benoit,
great ! Thanks for the swift help you provided.
Lieven

**Comment by bblanchon** [comment]
You're welcome, thanks for using ArduinoJson.
