### ISSUE TITLE
How to check if element of a parsed array is null ? 

### ISSUE THREAD

**Issue by VijayKrishna91** [bblanchon/ArduinoJson#635]
I am using this library in my code in ESP8266.
It is not a bug, but a question i have. I am using this code.

```
JsonObject& root = jsonBuffer.parseObject(reinterpret_cast<const char*>(myData));
JsonArray& codes = root["codes"];
const char *code;

for(short int i=0; i<codes.size();i++){
    code = codes[i];
    Serial.println(code);
}


``` 

And it's crashing my ESP if codes is an array of null - something like this - 

`myData = {"codes": [null]}`

So i am looking for a way to check if an element in the parsed array is null. and i was wondering if the way i am assiging codes[i] to code is right way of doing it or not.. Any help would be very appreciated..

**Comment by bblanchon** [comment]
Hi @VijayKrishna91,

You can test if the value is null by comparing the variable `code` to `nullptr`:

```c++
if (code != nullptr)
  Serial.println(code);
```

Your program is correct but can be improved in three ways:

1. You should use the [iterators of `JsonArray`](https://arduinojson.org/api/jsonarray/begin_end/), as it would improve the performance.
2. You should declare the variable `code` inside the loop, as it's only used here.
3. You can use the `|` operator to provide an alternative value when the string is null.

Here is a reworked version of your program that implements the three suggestions:

```c++
JsonObject& root = jsonBuffer.parseObject(reinterpret_cast<const char*>(myData));
JsonArray& codes = root["codes"];

for(const char* code : codes){
    Serial.println(code | "N/A");
}
```

Check out the free sample of ["Mastering ArduinoJson"](https://leanpub.com/arduinojson); it includes the chapter "Deserialize with ArduinoJson," a tutorial that covers all the topics above.

Regards,
Benoit
