### ISSUE TITLE
How to update(POST) sensor data using json in Arduino

### ISSUE THREAD

**Issue by Lingesharya** [bblanchon/ArduinoJson#646]
I want to update sensor data to my application using JSON format(My application accepts JSON format only). I'm able to get read sensor data(Data: Integer type) and now I want to post that data.
I have tried this, but it is not updating value in my application
```
oldst=25; //(old value from sensor)
newst=10; //(new value from sensor)
int S1 = http.POST("{\"itemId\":\"000D3A305744A1E7BA328A2251AC00C6.1\",\"item\":{\"Properties\":{\"AssetDistance\":newst,\"Status\":\"online\"}},\"operationType\":\"Update\",\"originalItem\":{\"Properties\":{\"AssetDistance\":oldst,\"Status\":\"offline\"}}}");
Serial.print("Sensor Status: ");
Serial.println(S2);
```
It is getting http code as 500.

**Comment by bblanchon** [comment]
Hi @Lingesharya,

I'm sorry but here is not the right place to ask this question.
We only answer questions about the library "ArduinoJson".

Thank you for your understanding.

Regards,
Benoit
