### ISSUE TITLE
How to change data of a field in json?

### ISSUE THREAD

**Issue by tackelua** [bblanchon/ArduinoJson#650]
Example I have a json:

`
{
   "Name":"John",
   "Age":18,
   "Sex":"Male"
}
`

How can I change the "Age" of json above?
Please leave an example, thank you so much <3

**Comment by tackelua** [comment]
OK, I find the topic #612 
Example: https://wandbox.org/permlink/LYkuILoDnrxPD0wK
Please close. Thank you 💃

**Comment by bblanchon** [comment]
Hi @tackelua,

Thank you for posting the answer 👍 

Regards,
Benoit
