### ISSUE TITLE
after root.printTo(output);  then time":true

### ISSUE THREAD

**Issue by bkht** [bblanchon/ArduinoJson#655]
After
root.printTo(output);
{"sensor":"gps","time":1351824120,"data":[48.756080,2.302038]}
the time becomes 'true':
{"sensor":"gps","time":true,"data":[48.756080,2.302038]}

**Comment by bblanchon** [comment]
Hi @bkht,

Thank you for reporting this issue.
However, I don't manage to reproduce it.
See demo here: https://wandbox.org/permlink/0dShFQ2hPNJDPwIh

Can you provide an [MCVE](https://stackoverflow.com/help/mcve)?

Regards,
Benoit
