### ISSUE TITLE
Cannot compile after upgrading

### ISSUE THREAD

**Issue by ivoras** [bblanchon/ArduinoJson#674]
After upgrading the ArduinoJson library to the latest version (5.13.0) I suddenly get these C++ errors while compiling any code which includes it: https://pastebin.com/jnhBsfnx

The same happens with ArduinoJson examples (e.g. String example) so it's not specific to my code.

Any ideas?

**Comment by bblanchon** [comment]
Hi @ivoras,

It seems that not all files have been upgraded to 5.13.0.
I suggest that you re-install the library from scratch.

Regards,
Benoit

**Comment by ivoras** [comment]
Thank you, re-installing the library solved the problem.
