### ISSUE TITLE
Using default value problem (x=json["Test"] | x;)

### ISSUE THREAD

**Issue by ttlappalainen** [bblanchon/ArduinoJson#675]
I have problem with using default value. I have on json: "Test": 1
```
  const char *strTest;
  double v=5;
  v=jsonProperty[strTest] | v;

```
Works fine and returns 1, but
```
  uint8_t v=5;
  v=jsonProperty[strTest] | v;

```
returns 5 allways. Last works fine without | v

**Comment by bblanchon** [comment]
Hi @ttlappalainen,

I cannot reproduce the bug.
See demo: https://wandbox.org/permlink/Q0FLElI8oJ9nuThD

Please provide an [MCVE](https://stackoverflow.com/help/mcve).

Regards,
Benoit

**Comment by ttlappalainen** [comment]
Now I am not sure is this bug or feature. With below code first returns wrong and second right. Also I expect that the reason is that you when I am using existing data, it has internally double object.

```
#include <Arduino.h>
#include <ArduinoJson.h>

void setup() {
  Serial.begin(115200);
  delay(300);

  Serial.println("Startup");

  DynamicJsonBuffer jsonBuffer(1000);
  jsonBuffer.clear();
  JsonObject& jsonControl=jsonBuffer.createObject();
  double a=100;
  jsonControl["Test"]=a;

  jsonControl.prettyPrintTo(Serial);

  uint8_t v=jsonControl["Test"] | 5;
  
  Serial.println();
  Serial.print("Read value:"); Serial.println(v);

  char buf[1000];
  jsonControl.prettyPrintTo(buf,1000);
  DynamicJsonBuffer jsonBuffer2(1000);
  JsonObject& jsonControl2=jsonBuffer2.parseObject(buf);
  v=jsonControl2["Test"] | v;
  Serial.println();
  Serial.print("Read value:"); Serial.println(v);
}

void loop() {
}

```

**Comment by bblanchon** [comment]
```c++
DynamicJsonBuffer jsonBuffer(1000);
char buf[1000];
DynamicJsonBuffer jsonBuffer2(1000);
```

Are you sure that there is enough RAM on your micro-controller?

**Comment by ttlappalainen** [comment]
Teensy 3.5 RAM 196 kB. Totally with flash more than on my first computer:)

**Comment by bblanchon** [comment]
OK, now I see it.

`jsonControl["Test"]` is a `double` so when you try to extract a `uint8_t`, it returns the default value.

To me, it's a bug because it's not consistent with:

```c++
uint8_t v = jsonControl2["Test"]; // return 100 as expected
```

**Comment by ttlappalainen** [comment]
OK - thanks. Meanwhile I can go around problem with
`jsonControl["Test"]=(uint8_t)a;`
where it is possible.
