### ISSUE TITLE
Replace specific content in the json file

### ISSUE THREAD

**Issue by Shinyhero36** [bblanchon/ArduinoJson#679]
Hi,
I would like to know how to replace specific content on the json file
Here is the json file:
{
	"data":	[
	{	
		"nom": "leban",
		"prenom": "gerald",
		"jetons": "10",
		"numero": "9562"
		},
		{"nom": "billon",
		"prenom": "yannis",
		"jetons": "10",
		"numero": "4562"
		},
		{
		"nom": "valencia",
		"prenom": "gael",
		"jetons": "10",
		"numero": "7412"
		},
		{"nom":"bru",
		"prenom": "joris",
		"jetons": "10",
		"numero": "8426"
		},
		{"nom": "monteleone",
		"prenom": "guillaume",
		"jetons": "10",
		"numero":"1256"
		}
	]
}
I want to replace the number after each "jetons".
The Json file and the arduino code is in the zip file
[Json and Arduino Code.zip](https://github.com/bblanchon/ArduinoJson/files/1716224/Json.and.Arduino.Code.zip)

**Comment by bblanchon** [comment]
Hi @Shinyhero36,

In your code, I see the following statement, which seems correct:

```c++
data_0["jetons"] = jetons0;
```

What is wrong with that?

BTW, I notice that your program could be improved by using loops. Have a look at [JsonArray::begin()/end()](https://arduinojson.org/api/jsonarray/begin_end/?utm_source=github&utm_medium=issues) for an example. You can also find a complete walkthrough in the chapter "Deserialize with ArduinoJson" of [Mastering ArduinoJson](https://arduinojson.org/book/?utm_source=github&utm_medium=issues).

Regards,
Benoit
