### ISSUE TITLE
Improve out-of-memory handling

### ISSUE THREAD

**Issue by firepick1** [bblanchon/ArduinoJson#68]
Benoit, I made a few tweaks in my branch to handle several out-of-memory edge cases that were blowing up my code. You might be interested in this:
https://github.com/firepick1/ArduinoJson/commit/bc8c3d988e1f4a0fba3207ab25b5a086f2af36e8

**Comment by bblanchon** [comment]
What happened before you added the changes?
It should be 100% safe to manipulate invalid `JsonVariant`, `JsonArray` and `JsonObject`, every operation should be nops.

**Comment by bblanchon** [comment]
PS: Do you think you can write a unit test?

**Comment by firepick1** [comment]
I've got a unit test in my code that fails without these changes. I'll try
to add one in ArduinoJson.

It was failing on something like this:
StaticJsonBuffer<JSON_OBJECT_SIZE(4)> jbtiny;
{"a":{"b":{"c":{"d":123}}}

jbtiny.parseObject() returns  success.
However, a printTo() of the parsed JSON yields:
{"a":{"b":{"c":{}}

I knew that your intent was to make the invariants mutable, but I couldn't
figure out why this particular case broke, so after getting a headache I
slapped a goto bandaid on it and it seemed to work.


On Sun, Apr 26, 2015 at 7:49 AM, Benoît Blanchon <notifications@github.com>
wrote:

> PS: Do you think you can write a unit test?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bblanchon/ArduinoJson/issues/68#issuecomment-96393044>
> .
>



-- 
Karl Lew
FIREPICK SERVICES LLC
karl@firepick.org
www.firepick.org

**Comment by bblanchon** [comment]
Excellent!
I'll fix this ASAP.

**Comment by firepick1** [comment]
Cool. Thanks! I was trying to figure out the unit tests and that would take
some time.

On Sun, Apr 26, 2015 at 8:08 AM, Benoît Blanchon <notifications@github.com>
wrote:

> Excellent!
> I'll fix this ASAP.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bblanchon/ArduinoJson/issues/68#issuecomment-96397850>
> .
>



-- 
Karl Lew
FIREPICK SERVICES LLC
karl@firepick.org
www.firepick.org

**Comment by bblanchon** [comment]
I fixed the bug in a completely different way.
Please have a look at [branch issue68](https://github.com/bblanchon/ArduinoJson/commits/issue68).
I'll merge into master ASAP.

**Comment by firepick1** [comment]
Thanks, Benoit!

Your fix feels much better than my bandaid. :D

On Sun, Apr 26, 2015 at 11:01 AM, Benoît Blanchon <notifications@github.com>
wrote:

> I fixed the bug in a completely different way.
> Please have a look at branch issue68
> <https://github.com/bblanchon/ArduinoJson/commits/issue68>.
> I'll merge into master ASAP.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bblanchon/ArduinoJson/issues/68#issuecomment-96414507>
> .
>



-- 
Karl Lew
FIREPICK SERVICES LLC
karl@firepick.org
www.firepick.org
