### ISSUE TITLE
How to optimize get and remove value from object without multiple lookups

### ISSUE THREAD

**Issue by CZEMacLeod** [bblanchon/ArduinoJson#681]
I am looking to optimize the time taken to update a loaded JSON object I have in memory, before writing it out again.
The process parses the object, reads and acts upon various parameters, then removes those values before writing the JSON back out again.
As my circumstance is executing many times I want to optimize the performance, and wanted to remove multiple string lookups (which seem to be the slowest part of the routine I can see).
Assume this virtual scenario:

```
// Load JSON to JObject & root;

bool secure = root["secure") | false;
root.remove("secure");
if (secure) {
   String password = String(root["password"] | defaultPassword);
   root.remove("password");
   // Do Something securely
} else {
   // Do Something insecurely
}
// Add results to file
// Save JSON from root e.g.
root.prettyPrintTo(Serial);
```

As you can see, we are doing 2 string lookups for each key.
I would like to do something like
```
JsonVariant jSecure = root["secure");
bool secure = jSecure;
root.remove(jSecure);
```
or
`jSecure.remove();`

This could potentially be wrapped up as a getAndRemove type function.

**Comment by bblanchon** [comment]
Hi @CZEMacLeod,

I understand why you request this feature, but it seems that you're the only one that would ever use it.
Is worth bloating the library with something so specific? I'm not sure.

Also, are you sure that the lookup hurts the performance?
How many members are there in the object?
What about this `String`, don't you think it hurts the performance too?

Regards,
Benoit
