### ISSUE TITLE
Two json parse routines, both OK in ESP8266, second one fails on ESP32

### ISSUE THREAD

**Issue by MikeyMoMo** [bblanchon/ArduinoJson#686]
There is a different problem.  Sorry, just delete this, if possible or close it.  I am getting garbage, not the fault of json code.  Sorry for the post.  

This is known good 3266 code and it is not running well on the ESP32.  Lots of networking problems.  Will post them elsewhere.

**Comment by bblanchon** [comment]
Thanks for the update @MikeyMoMo.
I'm closing this issue then.
