### ISSUE TITLE
Custom converters

### ISSUE THREAD

**Issue by huming2207** [bblanchon/ArduinoJson#687]
Hi,

I'm writing a program which needs to convert ISO8601 time string (e.g. `2018-02-22T13:21:00Z` as general or `20180222T132100Z` for some special cases) to `time_t` or `struct std::tm`.  

Currently I'm using `strptime()` function to parse the time string to those two time data types. I'm wondering if I can use `.as<time_t>()` or `.as<struct std::tm>()`? 

Regards,
Jackson

**Comment by bblanchon** [comment]
Hi Jackson,

I plan on adding *custom converters* in the future so that anyone can enrich ArduinoJson to support new types.
Unfortunately, I'm currently in the middle of a transformation in the API, so this new feature will have to wait a little.

Regards,
Benoit

**Comment by huming2207** [comment]
Hi Benoit,

Thanks for your works, I'm looking forward to try that. 

Regards,
Jackson

**Comment by Triangulix** [comment]
Hi 
I would also like to chime in on this. I'm currently looking for a way to have enum values serialized as names and not as numbers. I guess custom converters would be a way to implement this.

**Comment by bblanchon** [comment]
Feature published in [ArduinoJson 6.18.0](https://arduinojson.org/news/2021/05/04/version-6-18-0/)
