### ISSUE TITLE
how to write code in java for this JSON format

### ISSUE THREAD

**Issue by kbketan** [bblanchon/ArduinoJson#703]
{
    "ScheduleList": [
      ["xyabc2ba"],
        ["wyabc3ba"]
        ],
       "xyabc2ba" :[
         ["01/03/2018"],
         ["01/03/2018"],
         ["01/03/2018"]
         ],          
         "wyabc3ba" :[
           ["01/03/2018"],
           ["01/03/2018"]
           ]
}

**Comment by bblanchon** [comment]
Hi @kbketan,

It seems that you post this question in the wrong place.
Here, it's only about the C++ library "ArduinoJson", sorry.

Regards,
Benoit
