### ISSUE TITLE
I want de-frame a sentence in Arduino

### ISSUE THREAD

**Issue by navinyate** [bblanchon/ArduinoJson#712]
Am using Neoway N10 GPRS module, where I using the location of a device.

The Sentence is +CIPGSMLOC: {"location":{"lat":12.534121,"lng":76.9126},"accuracy":550.0}

Am trying to get lat and lon and use this as variable. 

Please help me.

**Comment by bblanchon** [comment]
```c++
const size_t bufferSize = 2*JSON_OBJECT_SIZE(2) + 60;
DynamicJsonBuffer jsonBuffer(bufferSize);

const char* json = "{\"location\":{\"lat\":12.534121,\"lng\":76.9126},\"accuracy\":550}";

JsonObject& root = jsonBuffer.parseObject(json);

float location_lat = root["location"]["lat"]; // 12.534121
float location_lng = root["location"]["lng"]; // 76.9126

int accuracy = root["accuracy"]; // 550
```

**Comment by bblanchon** [comment]
[![How to use ArduinoJson](https://user-images.githubusercontent.com/5462433/37862539-bf4361f2-2f4e-11e8-9d9c-b5c54b096e6f.png)](https://youtu.be/JX_wIFz4WRg)

**Comment by navinyate** [comment]
@bblanchon love it
