### ISSUE TITLE
Purpose of a command

### ISSUE THREAD

**Issue by Shinyhero36** [bblanchon/ArduinoJson#714]
Hello, I was wondering what is the purpose of these commands
const size_t bufferSize = JSON_ARRAY_SIZE(5) + JSON_OBJECT_SIZE(1) + 5*JSON_OBJECT_SIZE(4);

DynamicJsonBuffer jsonBuffer(bufferSize);

JsonObject& root = jsonBuffer.createObject();

JsonArray& data = root.createNestedArray("data");

JsonObject& data_0 = data.createNestedObject();

I need a comment for each line of code
Thanks in advance...

**Comment by bblanchon** [comment]
Hello @Shinyhero36,

See the documentation:

* [JsonGeneratorExample.ino](https://arduinojson.org/example/generator/?utm_source=github&utm_medium=issues)
* [JsonBuffer](https://arduinojson.org/api/jsonbuffer/?utm_source=github&utm_medium=issues)
* [JsonBuffer::createObject()](https://arduinojson.org/api/jsonbuffer/createobject/?utm_source=github&utm_medium=issues)
* [JsonObject::createNestedArray()](https://arduinojson.org/api/jsonobject/createnestedarray/?utm_source=github&utm_medium=issues)
* [JsonArray::createNestedObject()](https://arduinojson.org/api/jsonarray/createnestedobject/?utm_source=github&utm_medium=issues)

Please tell me if you have a more specific question.

Regards,
Benoit
