### ISSUE TITLE
ESP32 unsigned long long 

### ISSUE THREAD

**Issue by maxdd** [bblanchon/ArduinoJson#719]
I need to fetch a timestamp of value 1523470536687 that is in useconds.
I would of course divide it by 1000 but the problem is that i can't retrieve it as an unsigned long long but only as String or Char*.

My current workaround is 

```
uint64_t c_time = 0;
c_time = strtoull(root["timestamp"].as<char*>(), NULL , 10);
```

but i would be great to have directly

`uint64_t c_time = root["timestamp"].as<unsigned long long>();`

**Comment by bblanchon** [comment]
You can make it work by defining [ARDUINOJSON_USE_LONG_LONG](https://arduinojson.org/api/config/use_long_long/?utm_source=github&utm_medium=issues).
Unfortunately, this will make every JsonVariant bigger.
