### ISSUE TITLE
help parse google firebase REST 

### ISSUE THREAD

**Issue by vlad2005** [bblanchon/ArduinoJson#721]
Hi!
I try to use firebase REST api with esp8266.
When i try to retrieve an collection, response is like this:
````
{
  "documents": [
    {
      "name": "p1",
      "fields": {
        "a": {
          "integerValue": "50"
        },
        "b": {
          "integerValue": "11"
        },
        "c": {
          "integerValue": "8"
        }
      },
      "createTime": "2018-04-17T16:48:19.991839Z",
      "updateTime": "2018-04-17T16:48:19.991839Z"
    },
    {
      "name": "p2",
      "fields": {
        "a": {
          "integerValue": "40"
        },
        "b": {
          "integerValue": "12"
        },
        "c": {
          "integerValue": "7"
        }
      },
      "createTime": "2018-04-17T19:20:40.981209Z",
      "updateTime": "2018-04-17T19:22:17.457813Z"
    }
  ]
}
````
It's a combination between json and array. How to parse this response as elegant and efficient is possible?
Thanks in advance!

**Comment by bblanchon** [comment]
Hi @vlad2005,

See:

* [JsonHttpClient.ino](https://arduinojson.org/example/http-client/?utm_source=github&utm_medium=issues)
* [Can I parse from a Stream?](https://arduinojson.org/faq/can-i-parse-data-from-a-stream/?utm_source=github&utm_medium=issues)
* [ArduinoJson Assistant](https://arduinojson.org/assistant/?utm_source=github&utm_medium=issues)
* [How to use the ArduinoJson Assistant](https://youtu.be/JX_wIFz4WRg)

Regards,
Benoit

**Comment by vlad2005** [comment]
Uauu!
Beautiful tool! Thanks!
If i want to loop through each element of array, how do that?
Below is a sketch of how I think it should be done.
````  C++
DynamicJsonBuffer jsonBuffer;
JsonObject& root = jsonBuffer.parseObject(json_string);

//here i want to use same jsonBuffer variable to parse again json. 
JsonArray& array = jsonBuffer.parseArray(root["documents"]);

for (i=0, i<array.size(), i++){
     JsonObject& _obj = array[i];
     Serial.println(_obj["fields"]["a"]["integerValue"]);
}
````
It's ok?

**Comment by vlad2005** [comment]
I found an older post with response that i think will solve my question. I will test later to see if it's working.
Here is code concept
````C++
DynamicJsonBuffer jsonBuffer;
JsonObject& root = jsonBuffer.parseObject(intput);
JsonArray& requests = root["requests"];
for (auto& request : requests) {
   int type = request["type"];
   const char* value = request["value"];
}
````

**Comment by bblanchon** [comment]
Yes, that is the idea.
It's even better if you replace `auto` with `JsonObject` (because `auto` will be deduced to `JsonVariant`):

```c++
DynamicJsonBuffer jsonBuffer;
JsonObject& root = jsonBuffer.parseObject(intput);
JsonArray& requests = root["requests"];
for (JsonObject& request : requests) {
   int type = request["type"];
   const char* value = request["value"];
}
```

See:

* [JsonArray::begin() / JsonArray::end()](https://arduinojson.org/api/jsonarray/begin_end/?utm_source=github&utm_medium=issues)

Regards,
Benoit

**Comment by vlad2005** [comment]
Thanks!
My main concern is that I do not want to take too much data from the database because it would take up a lot of memory. I need to run api with option requestQuery, but is hard to find exactly how to do that.
Maybe i will try to find some responses on google forums.
Here is docs for what i need. Obviously is not subject for arduinojson, but if someone can help, then will be nice.
[https://firebase.google.com/docs/firestore/reference/rest/v1beta1/projects.databases.documents/runQuery](https://firebase.google.com/docs/firestore/reference/rest/v1beta1/projects.databases.documents/runQuery)

**Comment by vlad2005** [comment]
Problem solved. Google has an api explorer witch work fine. I will not post here the solution, because is not subject for arduinojson, but topic can pe closed and marked as solved. 
Thanks for responses!

**Comment by bblanchon** [comment]
Thanks for the update @vlad2005.
I'm closing the issue.

BTW, if you like this project [please add a ⭐️ ](https://github.com/bblanchon/ArduinoJson/stargazers)
