### ISSUE TITLE
How to add an empty array at root ?

### ISSUE THREAD

**Issue by gusantor** [bblanchon/ArduinoJson#722]
Hello, using Arduino IDE 1.8, I'm trying to add an empty array to the root, no success

For my project, I just check if file exists in FS, if not, want to create an epmty one, like this

    []

After creation I want to populate it, something like this

    [
        {"nombre":"A","texto":"B"},
        {"nombre":"V","texto":"M"}
    ]

I 've tried

    JsonObject& root = jsonBuffer.createObject();
    JsonArray& rarr = root.createNestedArray("");
    root.printTo(Serial);// results in {"":[]}

and

    JsonObject& root = jsonBuffer.createObject();
    root = RawJson("[]");// which result in compile error, no match for 'operator=' (operand types are 'ArduinoJson::JsonObject' and 'ArduinoJson::Internals::RawJsonString<const char*>')

How this should be done ?

Thanks

**Comment by bblanchon** [comment]
Hi @gusantor,

I'm glad you found the solution.
Thank you for using ArduinoJson.

Regards,
Benoit
