### ISSUE TITLE
Parsing Failed! By Arduino Yún

### ISSUE THREAD

**Issue by MESA0511** [bblanchon/ArduinoJson#724]
Hello bblanchon, sorry my english not very well. I use Arduino Yún parsing jsonarray and Arduino IDE version (1.8.5) this is my project: if I upload this code, I get "parsing failed!". I want to know why? Thank you!

#include <Bridge.h>
#include <HttpClient.h>
#include <Console.h>
#include <ArduinoJson.h>

void setup() {

pinMode(13, OUTPUT);
digitalWrite(13, LOW);

Bridge.begin();

digitalWrite(13, HIGH);

Console.begin();
while (!Console);
}

void loop() {
HttpClient client;

client.get("http://opendata.epa.gov.tw/ws/Data/ATM00625/?$format=json");

while (client.available()) {

const size_t bufferSize = JSON_ARRAY_SIZE(76) + 76*JSON_OBJECT_SIZE(5) + 6420;
DynamicJsonBuffer jsonBuffer(bufferSize);

JsonArray& root = jsonBuffer.parseArray(client);

if (!root.success()) {
  Console.println("Parsing Failed!");
  return;
  } else {
    Console.println("OK");
    return;
  }
}

Console.flush();

delay(5000);
}

**Comment by bblanchon** [comment]
Hi,

Please see:

* [FAQ: Why parsing fails?](https://arduinojson.org/faq/why-parsing-fails/?utm_source=github&utm_medium=issues)

Please make sure that:

1. the input is valid and not prefixed with the Chunked Encoding header
2. there is enough RAM on the device

Regards,
Benoit

**Comment by MESA0511** [comment]
Thanks for your reply. I rewrite my project, add "Send HTTP request" but "Check HTTP status" I got "Unexpected response:" and didn't have "static value". I'm afraid I've brought you a lot of trouble ...

```
#include <Bridge.h>
#include <HttpClient.h>
#include <Console.h>
#include <ArduinoJson.h>

HttpClient client;

void setup() {
  pinMode(13, OUTPUT);
  digitalWrite(13, LOW);
  
  Bridge.begin();
  
  digitalWrite(13, HIGH);

  Console.begin();
  while (!Console);

  // Send HTTP request
  client.println(F("GET /ws/Data/ATM00625/?$format=json HTTP/1.0"));
  client.println(F("Host: opendata.epa.gov.tw"));
  client.println(F("Connection: close"));
  if (client.println() == 0) {
    Console.println(F("Failed to send request"));
    return;
  } else {
    Console.println(F("success to send request"));
  }

  // Check HTTP status
  char status[32] = {0};
  client.readBytesUntil('\r', status, sizeof(status));
  if (strcmp(status, "HTTP/1.1 200 OK") != 0) {
    Console.print(F("Unexpected response: "));
    Console.println(status);
    return;
  } else {
    Console.println("success response");
  }
}

void loop() {

  while (client.available()) {

  }
  
  Console.flush();
}
```

**Comment by bblanchon** [comment]
I'm sorry I don't have an Arduino Yùn to check.

Did you try to increase the timeout?
Can you print the complete response from the server?

**Comment by MESA0511** [comment]
@bblanchon Thank you for your help. Now, I can print JSON data from the website. 

```
#include <Bridge.h>
#include <Console.h>
#include <ArduinoJson.h>
#include <BridgeClient.h>

BridgeClient client;

void setup() {
  pinMode(13, OUTPUT);
  digitalWrite(13, LOW);
  
  Bridge.begin();
  
  digitalWrite(13, HIGH);

  Console.begin();
  
  // wait for a Console connection
  while (!Console);
  
  // Connect to HTTP server
  client.setTimeout(10000);
  if (!client.connect("opendata.epa.gov.tw", 80)) {
    Console.println(F("Connection failed"));
    return;
  } else {
    Console.println(F("Connected to HTTP server"));
  }

  // Send HTTP request
  client.println(F("GET /ws/Data/ATM00625/?$format=json HTTP/1.0"));
  client.println(F("Host: opendata.epa.gov.tw"));
  client.println(F("Connection: close"));
  if (client.println() == 0) {
    Console.println(F("Failed to send request"));
    return;
  } else {
    Console.println(F("Succeeded to send request"));
  }

  // Check HTTP status
  char status[32] = {0};
  client.readBytesUntil('\r', status, sizeof(status));
  if (strcmp(status, "HTTP/1.1 200 OK") != 0) {
    Console.print(F("Unexpected response: "));
    Console.println(status);
    return;
  } else {
    Console.println("Succeeded response");
  }

  // Skip HTTP headers
  char endOfHeaders[] = "\r\n\r\n";
  if (!client.find(endOfHeaders)) {
    Console.println(F("Invalid response"));
    return;
  } else {
    Console.println(F("Succeeded skip HTTP headers"));
  }
}

void loop() {    

  while (client.available()) {

    char c = client.read();
    Console.print(c);

//    const size_t bufferSize = JSON_ARRAY_SIZE(76) + 76*JSON_OBJECT_SIZE(5) + 6500;
//    DynamicJsonBuffer jsonBuffer(bufferSize);
//    JsonArray& root = jsonBuffer.parseArray(client);

//    if (root.success()) {
//      Console.println("Parsing success!");
//      return;
//      } else {
//        Console.println("Parsing failed!");
//      }
  }

  Console.println("The input isn't valid");
  
  Console.flush();

  delay(60000);
}
```
But when I  parsing JSON, I get "Parsing failed!". Maybe isn't enough RAM on Arduino Yùn or something?! This is my JSON data link: [opendata.epa.gov.tw](http://opendata.epa.gov.tw/ws/Data/ATM00625/?$format=json)

```
void loop() {    

  while (client.available()) {

//    char c = client.read();
//    Console.print(c);

    const size_t bufferSize = JSON_ARRAY_SIZE(76) + 76*JSON_OBJECT_SIZE(5) + 6500;
    DynamicJsonBuffer jsonBuffer(bufferSize);
    JsonArray& root = jsonBuffer.parseArray(client);

    if (root.success()) {
      Console.println("Parsing success!");
      return;
      } else {
        Console.println("Parsing failed!");
      }
  }

  Console.println("The input isn't valid");
  
  Console.flush();

  delay(60000);
}
```

**Comment by bblanchon** [comment]
Hello @MESA0511,

Indeed, this is too big for the microcontroller of the Arduino Yun.
You may try to parse the JSON stream in chunks.
See: [Can I parse a JSON input that is too big to fit in memory?](https://arduinojson.org/faq/can-i-parse-a-json-input-that-is-too-big-to-fit-in-memory/?utm_source=github&utm_medium=issues)

Regards,
Benoit

**Comment by bblanchon** [comment]
So if I understand correctly, you switch to another service provider were the JSON document were smaller?
That's a wise decision.
I'm glad you made it work ;-)
