### ISSUE TITLE
Order of values added to an array

### ISSUE THREAD

**Issue by dpetican** [bblanchon/ArduinoJson#744]
Is it possible for an array to end up out of order when adding values in a loop like this?  The macros are just looking up values in memory based on type. The position of each value has meaning in my application.
```
    StaticJsonBuffer<1024> reqBuffer;
    JsonObject& request = reqBuffer.createObject();
    request["cmd"] = "scktbcast";
    JsonArray& values = request.createNestedArray("values");

    for (int i = 0; i <= 29; i++) {
      switch (ramType[i]) {
        case 'u':
          values.add(RAM_UL(i));
          break;
        case 'f':
          values.add(RAM_FLOAT(i));
          break;
        case 'i':
          values.add(RAM_INT(i));
          break;
        case 'b':
          values.add(RAM_BOOL(i));
          break;
        case 'e':
          values.add(RAM_ENUM(i));
          break;
        case 's':
          values.add(RAM_STR(i));
          break;
      }
```
If they are/can be added out of order can I create the array as a string and add it to the key as a raw json?

`arr.add(RawJson("[1,2]"));`

See issue: https://github.com/bblanchon/ArduinoJson/issues/311

And page 84/85 seems to imply that the order is maintained if I add raw json.

Also, I think I could create an array of 30 values, initialize them to zero then replace the values into this array using an index. Thanks.

`array[i] = value[i]`

**Comment by bblanchon** [comment]
Hi,

> Is it possible for an array to end up out of order when adding values in a loop like this?

No. Did you observe a different behavior?

>     arr.add(RawJson("[1,2]"));

This line will add a nested array: `[[1,2]]`, I don't think that's what you want.

> Also, I think I could create an array of 30 values, initialize them to zero then replace the values into this array using an index.

Yes, you can do that too.
Also, you could populate the `value` array and then use [JsonArray::copyFrom()](https://arduinojson.org/api/jsonarray/copyfrom/?utm_source=github&utm_medium=issues) to fill the `JsonArray`.

Regards,
Benoit
