### ISSUE TITLE
Create stacked Json

### ISSUE THREAD

**Issue by ThoEngel** [bblanchon/ArduinoJson#748]
How can I create the following Json structure:

  "date":"2017-03-03 12:30:47",
  "deviceId":"f7645058-fe8c-11e6-bc64-92361f002671",
  "data" : [
    {
      "dataTypeId": 1,
      "value": 37.012
    },
    {
      "dataTypeId": 2,
      "value": 9.225
    }
  ]
}

**Comment by bblanchon** [comment]
Hi @ThoEngel,

Here is the code generated by the [ArduinoJson Assistant](https://arduinojson.org/assistant/?utm_source=github&utm_medium=issues):

```c++
const size_t bufferSize = JSON_ARRAY_SIZE(2) + 2*JSON_OBJECT_SIZE(2) + JSON_OBJECT_SIZE(3);
DynamicJsonBuffer jsonBuffer(bufferSize);

JsonObject& root = jsonBuffer.createObject();
root["date"] = "2017-03-03 12:30:47";
root["deviceId"] = "f7645058-fe8c-11e6-bc64-92361f002671";

JsonArray& data = root.createNestedArray("data");

JsonObject& data_0 = data.createNestedObject();
data_0["dataTypeId"] = 1;
data_0["value"] = 37.012;

JsonObject& data_1 = data.createNestedObject();
data_1["dataTypeId"] = 2;
data_1["value"] = 9.225;

root.printTo(Serial);
```

Regards,
Benoit
