### ISSUE TITLE
Compile errors (with example programs) for Adafruit Feather M0 (6.0.0-beta)

### ISSUE THREAD

**Issue by hoblins** [bblanchon/ArduinoJson#753]
The example programs (e.g. MsgPackParser.ino or JsonParserExample.ino) can't be compiled for Adafruit Feather M0.

Error message:
> In file included from /home/XXX/.arduino15/packages/adafruit/hardware/samd/1.2.0/cores/arduino/Arduino.h:27:0,
                 from /tmp/arduino_build_77010/sketch/MsgPackParser.ino.cpp:1:
/home/XXX/Arduino/libraries/ArduinoJson/src/ArduinoJson/Json/./../Numbers/../Polyfills/math.hpp:10:6: error: expected unqualified-id before 'sizeof'
 bool isnan(T x) {
      ^
/home/XXX/Arduino/libraries/ArduinoJson/src/ArduinoJson/Json/./../Numbers/../Polyfills/math.hpp:10:6: error: expected ')' before 'sizeof'
/home/XXX/Arduino/libraries/ArduinoJson/src/ArduinoJson/Json/./../Numbers/../Polyfills/math.hpp:10:6: error: expected ')' before 'sizeof'
/home/XXX/Arduino/libraries/ArduinoJson/src/ArduinoJson/Json/./../Numbers/../Polyfills/math.hpp:10:6: error: expected ')' before 'sizeof'
/home/XXX/Arduino/libraries/ArduinoJson/src/ArduinoJson/Json/./../Numbers/../Polyfills/math.hpp:15:6: error: expected unqualified-id before 'sizeof'
 bool isinf(T x) {
      ^
/home/XXX/Arduino/libraries/ArduinoJson/src/ArduinoJson/Json/./../Numbers/../Polyfills/math.hpp:15:6: error: expected ')' before 'sizeof'
/home/XXX/Arduino/libraries/ArduinoJson/src/ArduinoJson/Json/./../Numbers/../Polyfills/math.hpp:15:6: error: expected ')' before 'sizeof'
/home/XXX/Arduino/libraries/ArduinoJson/src/ArduinoJson/Json/./../Numbers/../Polyfills/math.hpp:15:6: error: expected ')' before 'sizeof'
Using library ArduinoJson at version 6.0.0-beta in folder: /home/XXX/Arduino/libraries/ArduinoJson 
exit status 1
Error compiling for board Adafruit Feather M0.

IDE: Arduino 1.8.6 Hourly Build 2018/05/28 01:27.

**Comment by bblanchon** [comment]
Thanks for reporting this.
It's the same bug as #752, so I'm closing this and keep the other open.
