### ISSUE TITLE
DynamicJsonBuffer not wroking anymore

### ISSUE THREAD

**Issue by doit4fun** [bblanchon/ArduinoJson#760]
DynamicJsonBuffer not supported in version greater than 5.x

**Comment by bblanchon** [comment]
Hi @doit4fun,

Indeed ArduinoJson 6 replaced the concept of JsonBuffer with the concept of JsonDocument.
To fix this error, you need either:

1. Downgrade ArduinoJson to 5.x (recommended as v6 is still in beta)
2. Upgrade your program to work with ArduinoJson 6 ([instructions here](https://arduinojson.org/v6/doc/upgrade/?utm_source=github&utm_medium=issues))

Note: I added this [question to the FAQ](https://arduinojson.org/v5/faq/error-jsonbuffer-was-not-declared-in-this-scope/?utm_source=github&utm_medium=issues)

Regards,
Benoit
