### ISSUE TITLE
Add data to file (not empty)

### ISSUE THREAD

**Issue by mcmega** [bblanchon/ArduinoJson#761]
Hi guys!
I use ESP8285.

I have a file config.json with Data:
```cpp
{
  "in1":"LoadOn-1",
  "in2":"LoadOn-2",
  "in3":"LoadOff-1"
}
```
I want to add more data there.
But need the matching keys are overwritten, and the nonexistent keys are added.
Help me make this function.

```cpp
void userSaveConfig(void) {
  File f = SPIFFS.open("config.json", "r+");    // The file is not empty
  DynamicJsonBuffer configBuffer;
  JsonObject& root = configBuffer.parseObject(f);
  root["in3"] = in3;  // "Ch3"
  root["in4"] = in4;  // "Ch4"
  root.printTo(f);
  f.flush();
  f.close();
  configBuffer.clear();
}
```

It should turn out in the end:
```cpp
{
  "in1":"LoadOn-1",   // Not write
  "in2":"LoadOn-2",   // Not wtire
  "in3":"Ch3",   // Has changed
  "in4":"Ch4"    // Add
}
```

**Comment by bblanchon** [comment]
Hi @mcmega,

I recommend that you start with the example [JsonConfigFile.ino](https://arduinojson.org/v5/example/config/?utm_source=github&utm_medium=issues); it uses the SD card, but you can easily adapt it for SPIFFS.

If you want an example use SPIFFS, please read the first of the Case Studies in [Mastering ArduinoJson](https://arduinojson.org/book/?utm_source=github&utm_medium=issues).

Regards,
Benoit
