### ISSUE TITLE
ArduinoJson SerialStream and Pin Change Interrupts

### ISSUE THREAD

**Issue by ksmiller99** [bblanchon/ArduinoJson#764]
Are there any issues or tips for using ArduinoJson in a script that parses the serial stream and also uses pin change interrupts? I have a project with several sensors and actuators connected to a Uno. A program on a PC sends commands to the Arduino over the serial port to control the actuators or poll for the sensor states. If an sensor state (digital input) changes, the pin change interrupt sends the sensor info to the PC.

**Comment by bblanchon** [comment]
Hi @ksmiller99,

The only trick is to add a loop to wait for available characters before calling `parseObject()`.
There is an example in the FAQ: [Can I parse data from a stream?](https://arduinojson.org/v5/faq/can-i-parse-data-from-a-stream/?utm_source=github&utm_medium=issues).

Also, don't forget to increase the timeout accordingly.

There is a complete example in the Case Studies of [Mastering ArduinoJson](https://arduinojson.org/book/
?utm_source=github&utm_medium=issues) that shows how to read objects and array from the Serial port.

Regards,
Benoit
