### ISSUE TITLE
Changing the default value for long integers fails

### ISSUE THREAD

**Issue by scotty007** [bblanchon/ArduinoJson#767]
When using the "or" operator to get a long value from a parsed json string, the returned value is wrong (see last test code comment). It is correct w/o the "or"ed default value and for integers.

target platform: Atmel AVR (mega2560)
compiler/IDE: PlatformIO v3.5.3 / atmelavr v1.9.0 / framework-arduinoavr v1.10621.1
compiler warnings/errors: none

test code:
```
#include <Arduino.h>
#include <ArduinoJson.h> // version 5.13.2

const char* json_string = "{\"int\": 1000, \"long\": 100000}";
const size_t buffer_size = JSON_OBJECT_SIZE(2) + 30;

void setup()
{
    Serial.begin(115200);

    StaticJsonBuffer<buffer_size> json_buffer;
    JsonObject& root = json_buffer.parseObject(json_string);

    signed int value16 = root["int"];
    Serial.println(value16); // -> 1000
    value16 = root["int"] | -1;
    Serial.println(value16); // -> 1000

    signed long value32 = root["long"];
    Serial.println(value32); // -> 100000
    value32 = root["long"] | -1;
    Serial.println(value32); // -> -31072
}

void loop() {}
```

**Comment by bblanchon** [comment]
Hi @scotty007,

You just discovered a pitfall that I didn't know.
[I updated the documentation on arduinojson.org](https://arduinojson.org/v5/api/jsonvariant/or/?utm_source=github&utm_medium=issues).

Here is what I added:

> When you use this operator, the type of the expression is inferred from the type of the default value.
> 
> Here is an example where this fact matters:
> 
> ```c++
> long value = root["key"] | -1;
> ```
> 
> In this example, the right side of the expression returns an `int` (and not a `long` as one could expect) because the default value is an integer. If `root["key"]` contains a big value, the integer overflows and you get a seemingly random result in `value`.
> 
> To fix this, you need to change the type of the default value:
> 
> ```c++
> long value = root["key"] | -1L;
> ```

Regards,
Benoit

**Comment by scotty007** [comment]
Hi Benoit,

works perfectly, thanks!
