### ISSUE TITLE
BUG: Failed to parse from Serial on PIC32

### ISSUE THREAD

**Issue by aj-ptw** [bblanchon/ArduinoJson#768]
I think I may have found a bug. If i use quotes around my serialized JSON, the `jb.parseObject(Serial)` will fail to parse!

I have read the Mastering AduinoJSON book twice now and keep looking back to it to try and figure this out. 

What does work however is when I don't use quotes! The JSON parser is able to read the information fine.

I'm using Arduino 5.13.2, with PIC32.

If I send over serial:

```
{type:loopback}
```

This works and gives me success:

```
Success
{
  "type": loopback
}{"type":loopback}
```

If I send over serial however:

```
{"type":loopback}
```
or

```
{"type":"loopback"}
```
I get a repeatable amount of `Failed to parse` i.e.

```
Failed to parse
Failed to parse
Failed to parse
Failed to parse
Failed to parse
Failed to parse
Failed to parse
Failed to parse
Failed to parse
Failed to parse
Failed to parse
Failed to parse
Failed to parse
Failed to parse
Failed to parse
Failed to parse
Failed to parse
Failed to parse
Failed to parse
Failed to parse
```

Here is a simplified example code I wrote, like you said to in the book!

```cpp
#include <ArduinoJson.h>

void setup() {
  // put your setup code here, to run once:
  Serial.begin(230400);
  Serial.println("Ready");
}

void loop() {
  // put your main code here, to run repeatedly:

  // Check the serial ports for new data
  if (Serial.available()) {
    delay(100);
    DynamicJsonBuffer jb(1024);
    JsonObject& root = jb.parseObject(Serial);
    if (root.success()){
      Serial.println("Success"); // NEVER CALLED
      root.prettyPrintTo(Serial);
    } else {
      Serial.println("Failed to parse");
      return;
    }


    // Get the text of the error
    const char* type = root["type"];
    // Is there a type?
    if (type != nullptr) {
      if (strcmp(type, "loopback") == 0) {
        root.printTo(Serial);
      }
    }
  }

}
```

**Comment by bblanchon** [comment]
Hello @aj-ptw,

At first sight, it seems that the input is invalid.

How do you send the data from the other end?
Are you sure that the right `"` character is sent?
I've seen cases where a resembling Unicode character was used.
I've also seen cases where the quote was escaped (`\"`) by the sender.

Regards,
Benoit

**Comment by aj-ptw** [comment]
Cool term was changing it to a unicode! Good call, yay, my code will work, awesome. Sorry for the issue!

You're the man @bblanchon 

-AJ
