### ISSUE TITLE
json array error: no matching function for call to 'ArduinoJson::JsonObject::createNestedArray()

### ISSUE THREAD

**Issue by gha2al** [bblanchon/ArduinoJson#770]
hi
if any ones know this please help me
it is really emergency
this is my code:

#include <ESP8266HTTPClient.h>
#include <ESP8266WiFi.h>
#include <ArduinoJson.h>
#include <SimpleDHT.h>

int pinDHT11 = 2;
SimpleDHT11 dht11;

int ledPin=5;

void setup() {

byte temperature = 0;
byte humidity = 0;
pinMode(ledPin, OUTPUT);

Serial.begin(115200); //Serial connection
WiFi.begin("iPhone", "kaz2y5:D"); //WiFi connection

while (WiFi.status() != WL_CONNECTED) { //Wait for the WiFI connection completion

delay(500);
Serial.println("Waiting for connection");
}

}
bool toggle=false;

void loop() {

if (WiFi.status() == WL_CONNECTED) { //Check WiFi connection status

DynamicJsonBuffer JSONbuffer;
JsonObject& JSONencoder = JSONbuffer.createObject(); 

JsonArray& t = JSONencoder.createNestedArray(); //JSON array
JsonArray& tvlue = t.createArray("value"); //JSON array
JsonArray& ttime = t.createArray("time"); //JSON array
JsonArray& h = JSONencoder.createNestedArray(); //JSON array
JsonArray& hvalue = h.createArray("value"); //JSON array
JsonArray& htime = h.createArray("time"); //JSON array

byte temperature;
byte humidity;
int err = SimpleDHTErrSuccess;
if ((err = dht11.read(pinDHT11, &temperature, &humidity, NULL)) != SimpleDHTErrSuccess) {
    Serial.print("Read DHT11 failed, err="); Serial.println(err);delay(1000);
    return;
  }

tvalue["value"]=((int)temperature); //Add value to array
ttime["time"]=(int(millis())); //Add value to array

hvalue["value"]=((int)humidity); //Add value to array
htime["time"]=(int(millis())); //Add value to array

char JSONmessageBuffer[300];
JSONencoder.prettyPrintTo(JSONmessageBuffer, sizeof(JSONmessageBuffer));
Serial.println(JSONmessageBuffer);

HTTPClient http;    //Declare object of class HTTPClient

http.begin("http://172.20.10.4:8001/postjson");      //Specify request destination
http.addHeader("Content-Type", "application/json");  //Specify content-type header

int httpCode = http.POST(JSONmessageBuffer);   //Send the request
String payload = http.getString();                                        //Get the response payload

Serial.println(httpCode);   //Print HTTP return code
Serial.println(payload);    //Print request response payload

http.end();  //Close connection
} else {

Serial.println("Error in WiFi connection");
}

delay(1000);  //Send a request every 1 second
if(toggle)
    digitalWrite(ledPin, HIGH);
else
    digitalWrite(ledPin, LOW);
toggle=!toggle;
}

and this is my error:

Arduino: 1.8.5 (Windows 8), Board: "WeMos D1 R2 & mini, 80 MHz, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 921600"

E:\iot\Final\4\wemos\q4\q4.ino: In function 'void loop()':

q4:42: error: no matching function for call to 'ArduinoJson::JsonObject::createNestedArray()'

 JsonArray& t = JSONencoder.createNestedArray(); //JSON array

                                              ^
E:\iot\Final\4\wemos\q4\q4.ino:42:50: note: candidates are:

In file included from C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:11:0,

             from C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,

             from E:\iot\Final\4\wemos\q4\q4.ino:3:
C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/JsonObject.hpp:195:14: note: template ArduinoJson::JsonArray& ArduinoJson::JsonObject::createNestedArray(const TString&)

JsonArray& createNestedArray(const TString& key) {

          ^
C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/JsonObject.hpp:195:14: note: template argument deduction/substitution failed:

E:\iot\Final\4\wemos\q4\q4.ino:42:50: note: candidate expects 1 argument, 0 provided

 JsonArray& t = JSONencoder.createNestedArray(); //JSON array

                                              ^
In file included from C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:11:0,

             from C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,

             from E:\iot\Final\4\wemos\q4\q4.ino:3:
C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/JsonObject.hpp:201:14: note: template ArduinoJson::JsonArray& ArduinoJson::JsonObject::createNestedArray(TString*)

JsonArray& createNestedArray(TString* key) {

          ^
C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/JsonObject.hpp:201:14: note: template argument deduction/substitution failed:

E:\iot\Final\4\wemos\q4\q4.ino:42:50: note: candidate expects 1 argument, 0 provided

 JsonArray& t = JSONencoder.createNestedArray(); //JSON array

                                              ^
q4:43: error: 'class ArduinoJson::JsonArray' has no member named 'createArray'

 JsonArray& tvlue = t.createArray("value"); //JSON array

                      ^
q4:44: error: 'class ArduinoJson::JsonArray' has no member named 'createArray'

 JsonArray& ttime = t.createArray("time"); //JSON array

                      ^
q4:45: error: no matching function for call to 'ArduinoJson::JsonObject::createNestedArray()'

 JsonArray& h = JSONencoder.createNestedArray(); //JSON array

                                              ^
E:\iot\Final\4\wemos\q4\q4.ino:45:50: note: candidates are:

In file included from C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:11:0,

             from C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,

             from E:\iot\Final\4\wemos\q4\q4.ino:3:
C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/JsonObject.hpp:195:14: note: template ArduinoJson::JsonArray& ArduinoJson::JsonObject::createNestedArray(const TString&)

JsonArray& createNestedArray(const TString& key) {

          ^
C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/JsonObject.hpp:195:14: note: template argument deduction/substitution failed:

E:\iot\Final\4\wemos\q4\q4.ino:45:50: note: candidate expects 1 argument, 0 provided

 JsonArray& h = JSONencoder.createNestedArray(); //JSON array

                                              ^
In file included from C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:11:0,

             from C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,

             from E:\iot\Final\4\wemos\q4\q4.ino:3:
C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/JsonObject.hpp:201:14: note: template ArduinoJson::JsonArray& ArduinoJson::JsonObject::createNestedArray(TString*)

JsonArray& createNestedArray(TString* key) {

          ^
C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/JsonObject.hpp:201:14: note: template argument deduction/substitution failed:

E:\iot\Final\4\wemos\q4\q4.ino:45:50: note: candidate expects 1 argument, 0 provided

 JsonArray& h = JSONencoder.createNestedArray(); //JSON array

                                              ^
q4:46: error: 'class ArduinoJson::JsonArray' has no member named 'createArray'

 JsonArray& hvalue = h.createArray("value"); //JSON array

                       ^
q4:47: error: 'class ArduinoJson::JsonArray' has no member named 'createArray'

 JsonArray& htime = h.createArray("time"); //JSON array

                      ^
q4:58: error: 'tvalue' was not declared in this scope

 tvalue["value"]=((int)temperature); //Add value to array

 ^
q4:59: error: invalid conversion from 'const char*' to 'size_t {aka unsigned int}' [-fpermissive]

 ttime["time"]=(int(millis())); //Add value to array

             ^
In file included from C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/JsonArrayImpl.hpp:8:0,

             from C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:15,

             from C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,

             from E:\iot\Final\4\wemos\q4\q4.ino:3:
C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/JsonArraySubscript.hpp:110:38: error: initializing argument 1 of 'ArduinoJson::Internals::JsonArraySubscript ArduinoJson::JsonArray::operator' [-fpermissive]

inline Internals::JsonArraySubscript JsonArray::operator[](size_t index) {

                                  ^
q4:61: error: invalid conversion from 'const char*' to 'size_t {aka unsigned int}' [-fpermissive]

 hvalue["value"]=((int)humidity); //Add value to array

               ^
In file included from C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/JsonArrayImpl.hpp:8:0,

             from C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:15,

             from C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,

             from E:\iot\Final\4\wemos\q4\q4.ino:3:
C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/JsonArraySubscript.hpp:110:38: error: initializing argument 1 of 'ArduinoJson::Internals::JsonArraySubscript ArduinoJson::JsonArray::operator' [-fpermissive]

inline Internals::JsonArraySubscript JsonArray::operator[](size_t index) {

                                  ^
q4:62: error: invalid conversion from 'const char*' to 'size_t {aka unsigned int}' [-fpermissive]

 htime["time"]=(int(millis())); //Add value to array

             ^
In file included from C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/JsonArrayImpl.hpp:8:0,

             from C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:15,

             from C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,

             from E:\iot\Final\4\wemos\q4\q4.ino:3:
C:\Users\sony\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/JsonArraySubscript.hpp:110:38: error: initializing argument 1 of 'ArduinoJson::Internals::JsonArraySubscript ArduinoJson::JsonArray::operator' [-fpermissive]

inline Internals::JsonArraySubscript JsonArray::operator[](size_t index) {

                                  ^
Multiple libraries were found for "WiFiClient.h"
Used: C:\Users\sony\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.1\libraries\ESP8266WiFi
Not used: E:\Narm Afzar\arduino 1.8.5\libraries\WiFi
Not used: E:\Narm Afzar\arduino 1.8.5\libraries\WiFi
Not used: E:\Narm Afzar\arduino 1.8.5\libraries\WiFi
Not used: E:\Narm Afzar\arduino 1.8.5\libraries\WiFi
exit status 1
no matching function for call to 'ArduinoJson::JsonObject::createNestedArray()'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

what should I do?

**Comment by bblanchon** [comment]
Hi @gha2al,

As described in the documentation for [JsonObject::createNestedArray()](https://arduinojson.org/v5/api/jsonobject/createnestedarray/?utm_source=github&utm_medium=issues), this method requires one string parameter that is the key in the object.

Regards,
Benoit
