### ISSUE TITLE
Post to Webservice : OK, but the entry can't entered to MYSQL database

### ISSUE THREAD

**Issue by okumaster** [bblanchon/ArduinoJson#777]
Hallo Beno,
Thank's for your arduinojson library, that's awesome.

But, I got a problem, I follow this encoding tutorial from [randomnerdtutorials.com](https://randomnerdtutorials.com/decoding-and-encoding-json-with-arduino-or-esp8266/) and I modified it to connect my webservice with my UNO and ENC28J60. 

My sketch  uses `23940 bytes (74%)` flash and `1581 bytes (77%)` ram : 

```c++
#include <ArduinoJson.h>
#include <UIPEthernet.h>
#include <SPI.h>


EthernetClient client;
// Localhost IP address
const char * server = "http://192.168.1.2";
int port = 80;

// Url post API
const char * resource = "/bus/";

const unsigned long HTTP_TIMEOUT = 10000; // maksimum respon time dari server

byte mac[] = {0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED};
IPAddress ip(192, 168, 1, 6);

void setup() {
    Serial.begin(9600);
    while(!Serial) {
        ; 
    }
   Ethernet.begin(mac, ip);
    Serial.println(F("Ip address : "));
    Serial.print(Ethernet.localIP());
    Serial.println();
    delay(5000);
    
}

void loop() {
    if(koneksi(server, port)) {         
        if(sendRequest()) {
            Serial.print(F("Post Success"));            
        }
    }
    client.stop();
    wait();
}

bool koneksi(const char * hostName, int port) {
  Serial.print(F("Connect to "));
  Serial.println(hostName);

  client.setTimeout(HTTP_TIMEOUT);
  bool ok = client.connect(hostName, port);

  Serial.println(ok ? "Connected" : "Connection Failed!");
  return ok;
}
// Mengirim HTTP post request ke server okubis.com
bool sendRequest() {
    
    StaticJsonBuffer<200> JsonBuffer;       
    // Membuat objek dalam memory yang akan dikirimkan dalam send request
    JsonObject& root = JsonBuffer.createObject();
    root["warna"] = "hitam";
    root["nomor"] = "A2987GA";
    root["perusahaan"] = "Jasaprima Corp";

    root.prettyPrintTo(Serial);
    Serial.println();
    // Generate the JSON string
    client.println("POST /bus/ HTTP/1.1");    
    client.println("Host: 192.168.1.2");   
    client.println("Content-Type: application/json");
    client.println("Connection: close");
    client.print("\r\n");
    client.println();
    root.prettyPrintTo(client);
    
    return 1;        
}

void wait() {
  Serial.println();
  Serial.println("Wait 5 seconds");
  delay(5000);
}
```

and the result from serial monitor is : 

```json
Ip address : 
192.168.1.6
Connect to http://192.168.1.2
Connected
{
  "warna": "hitam",
  "nomor": "A2987GA",
  "perusahaan": "Jasaprima Corp"
}
Post Success
Wait 5 seconds
```

Why the entry can't entered to MYSQL? I'm very confused, when I tried with  Postman, the entry is successfully entered on MYSQL :

```http
POST /bus/ HTTP/1.1
Host: 192.168.1.2
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: 607b63cf-f8e5-490a-9fe0-a3b446bc98dc

{
	"warna": "hitam",
        "nomor": "A2987GA",
        "perusahaan": "Jasaprima Corp"
}
```

And the response headers : 

```head
Cache-Control > no-store, no-cache, must-revalidate
Connection > close
Content-Length > 282
Content-Type > application/json;charset=utf-8
Date > Fri, 06 Jul 2018 07:09:31 GMT
Expires > Thu, 19 Nov 1981 08:52:00 GMT
Pragma > no-cache
Server > Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.5
X-Powered-By > PHP/7.2.5
```

What should i do?
Thank's for your attention

Regards,
Ashif

**Comment by okumaster** [comment]
Update my problem:
I tried to GET request, status OK, but when I tried POST request, the response is 403.
and I check the log visitor on my server, the arduino user agent is checked.

any solutions?

**Comment by bblanchon** [comment]
Hi @okumaster,

There are two empty lines before the request body, but it should be just one.

```c++
client.println("Connection: close");
client.print("\r\n"); // REMOVE THIS LINE
client.println();
root.prettyPrintTo(client);
```

Regards,
Benoit

**Comment by okumaster** [comment]
Hi @bblanchon 

The problem has been solved, the reason is my message of POST request does not use the PSR-7 standard, because my server uses a slim PHP framework v.3 that contains the PSR-7 standard.

With PSR-7, has a minimal headers key to accept POST requests, ie
- Connection
- Content length

and the important component is "don't use println to create a new line", do with CR+LF (/r/n), to make a empty line has to use double CR+LF (\r\n\r\n).

this is my post request message : 

```c++
    client.print("POST /data/post/ HTTP/1.1\r\n");
    client.print("Host: 192.168.1.2\r\n");
    client.print("Connection: close\r\n");
    client.print("Content-Type: application/json\r\n");
    client.print("Content-Length: ");
    client.print(root.measureLength()); 
    client.print("\r\n");
    client.print("\r\n");
    client.print(data);
```
thank you

Regards,
Ashif

**Comment by bblanchon** [comment]
All implementations of `println()` that I could find add CR and LF.
The [Arduino documentation](https://www.arduino.cc/reference/en/language/functions/communication/serial/println/) says it explicitly:

> followed by a carriage return character (ASCII 13, or '\r') and a newline character (ASCII 10, or '\n').

So I disagree with your conclusion, I think it's safe to use `println()`.

**Comment by okumaster** [comment]
yes, i agree about that, but this happened to me, if im using println, the response always 400
I use slim framework for my php backend.
you want to try with my server?

this my server, the body {bus_id: 1, templog: 28}
okubis.com/data/temperature
