### ISSUE TITLE
JsonArray as<String>() works but as<const char*>() does not

### ISSUE THREAD

**Issue by marecl** [bblanchon/ArduinoJson#786]
Library version 5.13.2
TLDR I've got a function that takes const char*. I have tried many times to return array as const char* but every attempt leads etiher to printTo(String) or returning NULL. Funny thing is, in other place im literally printing whole array nested in array.

Little test code:
```
  JsonObject& sensSet = sensBuff.parseObject(tmpSens);
  JsonArray& _saved = sensSet["saved"];
  tmpSens.close();

  Serial.print("1. ");
  Serial.println(sensSet["saved"].as<const char*>()); //Returns nothing

  Serial.print("2. ");
  Serial.println(sensSet["saved"].as<char*>()); //Returns nothing

  Serial.print("3. ");
  Serial.println((sensSet["saved"].as<String>()).c_str()); //Works as expected

  Serial.print("4. ");
  Serial.println(sensSet["saved"].as<String>()); //Works as expected

  Serial.print("5. ");
  Serial.println(sensSet["saved"].printTo(Serial)); //Works as expected

  /* Compile error */
  /*
    Serial.print("6. ");
    Serial.println(_saved.as<const char*>());
    Serial.print("7. ");
    Serial.println(_saved.as<char*>());
  */

  Serial.print("8. "); //Works as expected
  Serial.println(_saved.printTo(Serial));

  Serial.print("9. "); //Dosent work
  const char* _x = sensSet["saved"];
  Serial.println(_x);
```
9th example is done exactly like [here](https://arduinojson.org/v5/faq/invalid-conversion-from-const-char-to-char/)
Why is this so inconsistent? Am I missing something?

**Comment by bblanchon** [comment]
Hi @marecl,

There is a subtitle difference between the two:

* `as<const char*>()` returns a pointer to the string if the `JsonVariant` is a string
* `as<String>()` converts the `JsonVariant` to a string

In your case, the `JsonVariant` contains a `JsonArray`.
It's not a string, so `as<const char*>()` cannot return a pointer.
On the other hand, `as<String>()` serializes the array (using `printTo()`) and return the result.

`as<const char*>()` and `as<String>()` return the same value when the variant is a string.

Does that make sense?

Regards,
Benoit
