### ISSUE TITLE
Question: Is your code contains deletion of JsonObject?

### ISSUE THREAD

**Issue by domdetre** [bblanchon/ArduinoJson#793]
jsonBuffer.parseObject returns a reference which, technically, is a pointer. When working with pointers I learned you need to take care of their deletion, otherwise it will fill the memory very quickly.

Does your code takes care of it? Or am I missing something?

**Comment by bblanchon** [comment]
Hi @domdetre,

With ArduinoJson, it's the role of the [`JsonBuffer`](https://arduinojson.org/v5/api/jsonbuffer/?utm_source=github&utm_medium=issues) to manage the memory.
All the [`JsonObject`](https://arduinojson.org/v5/api/jsonobject/?utm_source=github&utm_medium=issues) and [`JsonArray`](https://arduinojson.org/v5/api/jsonarray/?utm_source=github&utm_medium=issues) are freed when the [`JsonBuffer`](https://arduinojson.org/v5/api/jsonbuffer/?utm_source=github&utm_medium=issues) is destroyed.

Regards,
Benoit.
