### ISSUE TITLE
buffer/memory size problems?

### ISSUE THREAD

**Issue by pacman24** [bblanchon/ArduinoJson#80]
hi there!

i´m new to arduino and i´m trying to send data to my workstation (by serial communication). i can see the output of my arduino on the serial monitor, but after a while it doesnt writes anymore. i still changed the JsonBuffer to 1000, now i can receive more data, but after a while i get {}{}{}{}{{}{} aswell.. do u know what´s the issue? how can i solve this problem? 

thanx for help

    #include <ArduinoJson.h>

    StaticJsonBuffer<1000> jsonBuffer;

    void setup() {
      
     Serial.begin(9600);

    }

    void loop() {
      // put your main code here, to run repeatedly:
    test();

    }

    void test(){
      
    JsonObject& root = jsonBuffer.createObject();
    root["sensor"] = "gps";
    root["time"] = 1351824120;

    JsonArray& data = root.createNestedArray("data");
    data.add(48.756080, 6);  // 6 is the number of decimals to print
    data.add(2.302038, 6);   // if not specified, 2 digits are printed

    root.printTo(Serial);

    delay(3000);
    }

**Comment by bblanchon** [comment]
You just need to move the declaration of `jsonBuffer` inside the `test()` function.
If you need more details, please refer to [the documentation](https://github.com/bblanchon/ArduinoJson/wiki/Avoiding%20pitfalls#4-dont-reuse-the-same-staticjsonbuffer).
