### ISSUE TITLE
Use JsonObject as class static property?

### ISSUE THREAD

**Issue by hostmit** [bblanchon/ArduinoJson#805]
Hello!  I made a class User, it has a static method =
```
void User::init() {
    File file = SPIFFS.open(USERCONFFILE, "r");
    StaticJsonBuffer<200> jsonBuffer;
    JsonArray& jsonarray = jsonBuffer.parseArray(file);
    if (jsonarray.success()) {
        User::addErr = "Failed to read file, please add users";
        }
    jsonarray.printTo(Serial);
    file.close();
}
```

How do I provide access to this object (parsed data) to other class members and outside of class?

Thanks.

**Comment by bblanchon** [comment]
Hi,

I recommend using a custom data structure, as suggested in [JsonConfigFile.ino](https://arduinojson.org/v5/example/config/?utm_source=github&utm_medium=issues), in [What's the best way to use the library?](https://arduinojson.org/v5/faq/whats-the-best-way-to-use-the-library/?utm_source=github&utm_medium=issues), and of course in [Mastering ArduinoJson](https://arduinojson.org/book/?utm_source=github&utm_medium=issues), chapter "Case Studies."

Regards,
Benoit
