### ISSUE TITLE
Problems with parsing my JSON string

### ISSUE THREAD

**Issue by powersoft** [bblanchon/ArduinoJson#811]
After automatic update my code is not working.
I'm not so a good programmer so now I am lost.
How to change this code to get it working

bool CheckJson(String Youless) //parse the JSon data
{
  DynamicJsonBuffer jsonBuffer;
  JsonObject& root = jsonBuffer.parseObject(Youless);
    // Test if parsing succeeds.
  if (!root.success()) 
    .............

Thanks for any help.

**Comment by bblanchon** [comment]
Hi @powersoft,

The Library Manager probably upgraded ArduinoJson to version 6.
I recommend that you downgrade to version 5.13.2 because version 6 is in beta and requires [some changes](https://arduinojson.org/v6/doc/upgrade/?utm_source=github&utm_medium=issues).

Regards,
Benoit
