### ISSUE TITLE
How to parse array

### ISSUE THREAD

**Issue by powersoft** [bblanchon/ArduinoJson#815]
I read this string from my Smart meter:

{"un":"Watt","tm":"2018-09-18T10:03:00","dt":60,"val":[" 92"," 91"," 91"," 89"," 69"," 68"," 68"," 68"," 68"," 68"," 110"," 120"," 143"," 169"," 119"," 117"," 146"," 1319"," 852"," 113"," 113"," 94"," 66"," 66"," 66"," 67"," 66"," 66"," 67"," 119",null]}

And use this code to extract the array "val"

``
bool CheckJson(String Youless) //parse the JSon data
{
  DynamicJsonBuffer jsonBuffer;
  JsonObject& root = jsonBuffer.parseObject(Youless);
    // Test if parsing succeeds.
  if (!root.success()) 
    return false;
  else {  
    /*Extract values "val"*/
        return true;
  }
}
``

Have no clou how to write this, please can you help.

Sorry for the code but have no idee while it is formatted on this manner!

**Comment by bblanchon** [comment]
Hi @powersoft,

Please read the documentation on `arduinojson.org`.
In particular, try the [ArduinoJson Assistant](https://arduinojson.org/v5/assistant/?utm_source=github&utm_medium=issues), it can generate the program.

Regards,
Benoit
