### ISSUE TITLE
JsonPair::value does not have class type

### ISSUE THREAD

**Issue by martinloren** [bblanchon/ArduinoJson#836]
Tring to run the example for V6 Beta:

```
char json[] = "{\"first\":\"hello\",\"second\":\"world\"}";
DynamicJsonDocument doc;
deserializeJson(doc, json);
JsonObject root = doc.as<JsonObject>();

// using C++11 syntax (preferred):
for (auto kv : root) {
    Serial.println(kv.key.c_str());
    Serial.println(kv.value.as<char*>());
}
```

Got:

> error: invalid use of non-static member function
>        Serial.println(kv.key);
> 
> error: 'kv.ArduinoJson650_0_0::JsonPair::value' does not have class type
>        Serial.println(kv.value.as<char*>());
>
> error:  expected primary-expression before 'char'
>        Serial.println(kv.value.as<char*>());
>

**Comment by martinloren** [comment]
Documentation need to be updated since **key** and **value** are private now.
Code become:
`Serial.print(kv.key());
Serial.print(": ");
Serial.println(kv.value().as<char*>());`

**Comment by bblanchon** [comment]
Sorry about that, I'll update the documentation ASAP

**Comment by martinloren** [comment]
Thanks!
