### ISSUE TITLE
JSON used intorno CodeBlock

### ISSUE THREAD

**Issue by luigi67** [bblanchon/ArduinoJson#848]
Hi
I would use ArduinoJson with CodeBlocks to debug "offline”  some objects and to do this I need to use ArduinoJson to reproduce JSON object. How I can do this
Best regards
Luigi Augello

**Comment by bblanchon** [comment]
Hi @luigi67,

Simply download the single header distribution as suggested in [Installation instructions](https://arduinojson.org/v5/doc/installation/?utm_source=github&utm_medium=issues).

* Download [this file](https://github.com/bblanchon/ArduinoJson/releases/download/v5.13.3/ArduinoJson-v5.13.3.h)
* Save it with your `.cpp` as if it were part you your project

Regards,
Benoit
