### ISSUE TITLE
How do I generate this?

### ISSUE THREAD

**Issue by probonopd** [bblanchon/ArduinoJson#85]
How would I generate this?

```
[  
   {  
      "error":{  
         "address":"",
         "description":"link button not pressed",
         "type":"101"
      }
   }
]
```

**Comment by bblanchon** [comment]
DynamicJsonBuffer jsonBuffer;
	JsonArray& root = jsonBuffer.createArray();
	JsonObject& error = root.createNestedObject().createNestedObject("error");
	error["address"] = "";
	error["description"] = "link button not pressed";
	error["type"] = "101";
	root.prettyPrintTo(Serial);

will generate 

	[
	  {
	    "error": {
	      "address": "",
	      "description": "link button not pressed",
	      "type": "101"
	    }
	  }
	]

Don't forget to replace the `DynamicJsonBuffer` by a `StaticJsonBuffer` if you need to run on an embedded platform like an Arduino.

**Comment by probonopd** [comment]
Thank you for the explanation. Maybe you'd like to add it to the examples.

**Comment by bblanchon** [comment]
[Example added to the wiki](https://github.com/bblanchon/ArduinoJson/wiki/Examples).

**Comment by pydesai** [comment]
How would I generate this?

{
  "timestamp" : 1483036273819,
  "values" : [ {
    "objectId" : 4,
    "datatype" : "int",
    "value" : "2"
  } ]
}
