### ISSUE TITLE
obj does not name a type

### ISSUE THREAD

**Issue by fgrs** [bblanchon/ArduinoJson#850]
I have followed documentation of how to create a simple object and I'm getting this error:

```
'obj' does not name a type
 obj.set("value", 42);
```

for:

```
StaticJsonBuffer<200> jsonBuffer;
JsonObject& obj = jsonBuffer.createObject();
obj.set("value", 42);
```

library version: 5.13.3

**Comment by Milan991** [comment]
@fgrs I've same library version as you and everything is fine on my side. Did you include ArduinoJson.h?

**Comment by bblanchon** [comment]
Hi @fgrs,

The library comes with several examples, can you try to compile them?
If the example works, check how your code differs from it; I'm sure you'll figure out what's wrong.

Regards,
Benoit
