### ISSUE TITLE
Want to update sensor value and control led from remote server: php, sql, html, arduino, json

### ISSUE THREAD

**Issue by magnumpro** [bblanchon/ArduinoJson#853]
Hi 
I have tried led control from remote server and i got an output. 
Even i have working code to Monitoring sensor value and updating that to remote server.

These are the 2 codes i have got.

Now i am facing challenge in integrating both codes together. LED control switch and Analog(Sensor value read and display) on the server. 

LED control Code:

#include <ESP8266WiFi.h>
#include <ArduinoJson.h>
 
const char* ssid     = "Raj";
const char* password = "8888888888";
const char* host = "pragatiprojects.com"; //replace it with your webhost url
String url;
  int count = 0;
void setup() {
  Serial.begin(115200);
  delay(10);
  pinMode(D1, OUTPUT);

  digitalWrite(D1, 0);

  Serial.println();
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);
  
  WiFi.begin(ssid, password); 
  while (WiFi.status() != WL_CONNECTED) {
    delay(10);
    Serial.print(".");
  }
 
//  Serial.println("");
//  Serial.println("WiFi connected");  
//  Serial.println("IP address: ");
//  Serial.println(WiFi.localIP());
//  Serial.print("Netmask: ");
//  Serial.println(WiFi.subnetMask());
//  Serial.print("Gateway: ");
//  Serial.println(WiFi.gatewayIP());
}

void loop() {

  Serial.print("connecting to ");
  Serial.println(host);

  WiFiClient client;
  const int httpPort = 80;
  if (!client.connect(host, httpPort)) {
    Serial.println("connection failed");
    return;
  }

  if (count == 0){
    url = "/api/led/read_all.php?id=1";
    count = count + 1;
    Serial.println("Here1");
  }
 
  Serial.print("Requesting URL: ");
  Serial.println(url);
  
  client.print(String("GET ") + url + " HTTP/1.0\r\n" +
               "Host: " + host + "\r\n" + 
               "Connection: close\r\n\r\n");
  delay(500);
  String section="header";
  delay(500);
  while(client.available()){
    String line = client.readStringUntil('\r');
    //Serial.print(line);
    // we’ll parse the HTML body here
    if (section=="header") { // headers..
     
      if (line=="\n") { // skips the empty space at the beginning 
        section="json";
      }
    }
    else if (section=="json") {  // print the good stuff
      section="ignore";
      String result = line.substring(1);
      // Parse JSON
      int size = result.length() + 1;
      char json[size];
      result.toCharArray(json, size);
      StaticJsonBuffer<500> jsonBuffer;
      JsonObject& json_parsed = jsonBuffer.parseObject(json);
      if (!json_parsed.success())
      {
        Serial.println("parseObject() failed");
        return;
      }
      String led = json_parsed["led"][0]["status"];

      if(count == 1){
        if(led == "on"){
          digitalWrite(D1, 1);
          delay(100);
          Serial.println("D1 is On..!");
        }
        else if(led == "off"){
          digitalWrite(D1, 0);
          delay(100);
          Serial.println("D1 is Off..!");
        }
        count = 0;
      }
    }
  }
  Serial.println();
  Serial.println("closing connection");
  delay(10);
  if (count == 1)
        count = 0;
}

Sensor Monitoring adn updating to server Code:

#include <ESP8266WiFi.h>
#include <ArduinoJson.h>
 
const char* ssid     = "Raj";
const char* password = "8888888888";
const char* host = "www.pragatiprojects.com"; //replace it with your webhost url
String url;
  int count = 0;
void setup() {
  Serial.begin(115200);
  delay(100);
  pinMode(D1, OUTPUT);

  digitalWrite(D1, 0);

  Serial.println();
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);
  
  WiFi.begin(ssid, password); 
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
 
  Serial.println("");
  Serial.println("WiFi connected");  
  Serial.println("IP address: ");
  Serial.println(WiFi.localIP());
  Serial.print("Netmask: ");
  Serial.println(WiFi.subnetMask());
  Serial.print("Gateway: ");
  Serial.println(WiFi.gatewayIP());
  digitalWrite(D1, 1);
  delay(500);
  digitalWrite(D1, 0);
  delay(500);
}

void loop() {

  float t = analogRead(A0);
  
  Serial.print("connecting to ");
  Serial.println(host);

  WiFiClient client;
  const int httpPort = 80;
  if (!client.connect(host, httpPort)) {
    Serial.println("connection failed");
    return;
  }
String url = "/api/weather/insert.php?temp=" + String(t);
  Serial.print("Requesting URL: ");
  Serial.println(url);
  
 
  client.print(String("GET ") + url + " HTTP/1.0\r\n" +
               "Host: " + host + "\r\n" + 
               "Connection: close\r\n\r\n");
  delay(500);
 
  delay(500);
  while(client.available()){
    String line = client.readStringUntil('\r');
    //Serial.print(line);
    // we’ll parse the HTML body here
    
 }
  Serial.println();
  Serial.println("closing connection");
  delay(10);

}

Combined code:

#include <ESP8266WiFi.h>
#include <ArduinoJson.h>
 
const char* ssid     = "Raj";
const char* password = "8888888888";
const char* host = "pragatiprojects.com"; //replace it with your webhost url
String url;
  int count = 0;
void setup() {
  Serial.begin(115200);
  //delay(10);
  pinMode(D1, OUTPUT);

  digitalWrite(D1, 0);

  Serial.println();
  Serial.println();
  Serial.print("Connecting to ");
  Serial.println(ssid);
  
  WiFi.begin(ssid, password); 
  while (WiFi.status() != WL_CONNECTED) {
    delay(10);
    Serial.print(".");
  }
 
//  Serial.println("");
//  Serial.println("WiFi connected");  
//  Serial.println("IP address: ");
//  Serial.println(WiFi.localIP());
//  Serial.print("Netmask: ");
//  Serial.println(WiFi.subnetMask());
//  Serial.print("Gateway: ");
//  Serial.println(WiFi.gatewayIP());
}

void loop() {
  float t = analogRead(A0);
  Serial.print("connecting to ");
  Serial.println(host);

  WiFiClient client;
  const int httpPort = 80;
  if (!client.connect(host, httpPort)) {
    Serial.println("connection failed");
    return;
  }
   
  if (count == 0){
    url = "/api/led/read_all.php?id=1";
    count = count + 1;
    Serial.println("Here1");
  }
 
  Serial.print("Requesting URL: ");
  Serial.println(url);
  
  client.print(String("GET ") + url + " HTTP/1.0\r\n" +
               "Host: " + host + "\r\n" + 
               "Connection: close\r\n\r\n");
  delay(500);
  String section="header";
  delay(500);
  while(client.available()){
    String line = client.readStringUntil('\r');
    //Serial.print(line);
    // we’ll parse the HTML body here
    if (section=="header") { // headers..
     
      if (line=="\n") { // skips the empty space at the beginning 
        section="json";
      }
    }
    else if (section=="json") {  // print the good stuff
      section="ignore";
      String result = line.substring(1);
      // Parse JSON
      int size = result.length() + 1;
      char json[size];
      result.toCharArray(json, size);
      StaticJsonBuffer<500> jsonBuffer;
      JsonObject& json_parsed = jsonBuffer.parseObject(json);
      if (!json_parsed.success())
      {
        Serial.println("parseObject() failed");
        return;
      }
      String led = json_parsed["led"][0]["status"];

      if(count == 1){
        if(led == "on"){
          digitalWrite(D1, 1);
          delay(100);
          Serial.println("D1 is On..!");
        }
        else if(led == "off"){
          digitalWrite(D1, 0);
          delay(100);
          Serial.println("D1 is Off..!");
        }
        count = 0;
      }
    }
  }

  String url1 = "/api/weather/insert.php?temp=" + String(t);
  Serial.print("Requesting URL: ");
  Serial.println(url1);
  
  client.print(String("GET ") + url1 + " HTTP/1.0\r\n" +
               "Host: " + host + "\r\n" + 
               "Connection: close\r\n\r\n");
  delay(500);
 
  delay(500);
  while(client.available()){
    String line = client.readStringUntil('\r');
    //Serial.print(line);
    // we’ll parse the HTML body here
    
 }
  Serial.println();
  Serial.println("closing connection");
  delay(10);
  if (count == 1)
        count = 0;
}

**Comment by bblanchon** [comment]
Hi @magnumpro,

Thank you for shortening the code and explaining further the project.
Unfortunately, I still need crucial information: **what is wrong with the code above?**

Regards,
Benoit

**Comment by magnumpro** [comment]
I worked on LED control from server, it worked fine. 
Sensor reading updation to server even it also worked fine.

Now i combined both led control and sensor reading updation code.

In combined code only LED control part is working fine. Controller is reading sensor value , displaying on serial monitor but its not updating to server.

11th line from last line of the code is not working. So sensor value is not updating to server.
delay(500);
while(client.available()){
String line = client.readStringUntil('\r');
//Serial.print(line);
// we’ll parse the HTML body here

}

If this part of the code works fine then everything will be perfect.

Please help me in this.

Waiting for your positive response.

**Comment by bblanchon** [comment]
Hi @magnumpro,

Do you mean that `line` is empty?
It could be that your running out of memory, or it could be a [heap fragmentation](https://cpp4arduino.com/2018/11/06/what-is-heap-fragmentation.html) issue.

You should try to reduce the number of `String` instance, or at least [use them more efficiently](https://cpp4arduino.com/2018/11/21/eight-tips-to-use-the-string-class-efficiently.html).

For instance, instead of concatenating a `String` to make the request, call `client.print()` several times.
Also, reduce the lifetime of the `String` instances, to make some free space.

@magnumpro, that's all I can do for you; this issue is not related to ArduinoJson, I cannot afford to spend more time on it.

Thank you for your understanding.
Benoit
