### ISSUE TITLE
array of struct to JSON and then JSON to array of struct 

### ISSUE THREAD

**Issue by denden4444** [bblanchon/ArduinoJson#861]
Hi 
Is there an example somewhere to serialize a struct with arduinoJSON and then do the reverse (de-serialize) it and be able to see what the result looks like ?

My struct currently looks like this:
`
struct new_info {
  int id;
  char name[20];
  char location[20];
  unsigned long entryTime;
  unsigned long exitTime;
  char pattern[20];
  char height[6];
  char pod[3];
  bool altActive;
  bool enableUse;
};

const int TableSize = 4;//set size
new_info inTable[TableSize] = {
};
`
I would like to send the result through a webSocket and read it on the other side.

**Comment by bblanchon** [comment]
Hi @denden4444,

[JsonConfigFile.ino](https://arduinojson.org/v5/example/config/?utm_source=github&utm_medium=issues) shows how to map the members of a structure to the values in a JSON object. However, it only shows a flat structure; there is no array.

If you want to see a design pattern for arrays of structures, please read the case study "Configuration in SPIFFS" in [Mastering ArduinoJson](https://arduinojson.org/book/?utm_source=github&utm_medium=issues)

Regards,
Benoit
