### ISSUE TITLE
Is it possible to put a JSON Object in an array of the parent JSON Object ???

### ISSUE THREAD

**Issue by VoLinhTruc** [bblanchon/ArduinoJson#867]
I'm using the JsonParseExample.ino and modify a little to check out if array in Json able to content a inside Json or not.

I change the code like this:

```
  char json[] =
      "{\"sensor\":\"gps\",\"time\":1351824120,\"data\":[\"a\":{\"A\":\"1\"},2.302038]}";
```
and parse the "latitude" like this

`String latitude = root["data"][0]["A"];`

but after running, the monitor show like this
"parseObject() failed"

So that I think array in json can't content another json :D 

Any idea @bblanchon ???

**Comment by bblanchon** [comment]
Hi @VoLinhTruc,

The JSON document in invalid:

```json
{"sensor":"gps","time":1351824120,"data":["a":{"A":"1"},2.302038]}
```

I think you meant:

```json
{"sensor":"gps","time":1351824120,"data":[{"A":"1"},2.302038]}
```

Regards,
Benoit
