### ISSUE TITLE
Question: parsed values contain random data

### ISSUE THREAD

**Issue by Urs-Eppenberger** [bblanchon/ArduinoJson#868]
Hello Benoit

I'm using your library for two use cases in my code for ESP8266 based Sonoff devices.
One usage is to read a config file from the SPIFFS file system, works nicely.
The other is to parse a string which is sent via MQTT to the ESP8266 device. Here I fail miserably. Decoding seems to work, but the variable contains just garbage. Are you able to help here?

Many thanks and kind regards,

Urs.

I use the following libraries:
Debug       : telnet client, enables me to telnet into the esp8266 and see println output
MQTT        : I prefer this to the usual pubsubclient, since it supports encryption
ArduinoJSON : your code

Here is how I use your code in a callback routine, which is called when an MQTT message arrives:

`void command_callback(MQTTClient *mqttClient, char cctopic[], char ccpayload[], int ccpayload_length) {`
`  Debug.println("Rx: " + String(cctopic) + " - " + String(ccpayload) + " - " + String(ccpayload_length));`
`  StaticJsonBuffer<400> commandBuffer;`
`  JsonObject& root = commandBuffer.parseObject(ccpayload);`
`  if (root.success()) {                                           //  verify if parsing worked`
`    Debug.println("parsing worked somehow");`
`  } else {`
`    Debug.println("parsing failed, rest is just random");`
`  }`
`  int command_nr = root["Command"];`
`  Debug.println("Command Nr: " + command_nr);`
`}`

And here is the debug output
(D) Rx: command/sonoffpow1 - {"Command":1,"MsgNr":3,"Relay1":"on"} - 37
(D) parsing worked somehow
(D) ommand Nr:

The first debug shows, that a char array with 37 characters has been received.
The second debug line shows, that the parsing has been successful
The third line is the output for the first parameter I was trying to extract. As you can see, there seems to be a strange character instead of the expected Number 1, which deletes the C of the word Command. In other code versions, I received other random content.

Do you have any hint what I might be doing wrong here?

**Comment by bblanchon** [comment]
Hi @Urs-Eppenberger,

As a matter of fact, it's not related to ArduinoJson.
It is really a C++ programming puzzle that you could ask in an interview.
It could go like that:

> Given the following program
> 
> ```c++
> int x = 1;
> Serial.print("value = " + x);
> ```
>
> Explain why it prints `alue =` instead of `value = 1`

The problem is you forgot to construct a `String` object.
To print `value = 1`, you need to use the following program.

```c++
Serial.print(String("value = ") + x);
```

Why did it removes the first character of the string?
It's because the `+` operator performs pointer arithmetic: it increments the address.
I think it becomes clearer if we rewrite the program like that:

```c++
const char* s1 = "value = ";
const char* s2 = s1 + 1; // "alue = "
```

Thanks for this little puzzle @Urs-Eppenberger.

Regards,
Benoit

**Comment by Urs-Eppenberger** [comment]
Hello Benoit
Thanks for the help. I never suspected your library. It works in another use case and I'm very happy with it.
But I hate C pointers. Never know beforehand when it hits me.
In other words, I made an error in the print command when I tried to debug my code.
What I still can't wrap my head around is, that my real code is not working:

  int command_nr = root["Command"];
  if (command_nr == 1) {
    Debug.println("command Nr 1 detected");
  } else {
    Debug.println("something else detected");
  }

I never reach the "Nr 1 detected" section of the code. Somehow the "1" in the integer variable is not recognised as ==1
Again a C pointer error on my side?

**Comment by bblanchon** [comment]
Hi @Urs-Eppenberger,

The snippet above seems correct, can you share more code?
In particular, I wonder if `root` is initialized correctly and if you checked that the deserialization succeeded.

Regards,
Benoit

**Comment by Urs-Eppenberger** [comment]
Hi Benoit
I appreciate very much that you spend your valuable time on this.
The whole mqtt callback routine is a combination of the first snippet at the very top and the second snipped. To debug, I deleted all the unnecessary stuff, but I seem to have made a C beginners error.
Here is the full callback routine (with println commands instead of the real action code to make it more simple.

`void` command_callback(MQTTClient *mqttClient, char cctopic[], char ccpayload[], int ccpayload_length) {
`  Debug.println("Rx: " + String(cctopic) + " - " + String(ccpayload) + " - " + String(ccpayload_length));
`  StaticJsonBuffer<400> commandBuffer;
`  JsonObject& root = commandBuffer.parseObject(ccpayload);
`  if (root.success()) { // verify if parsing worked
`    Debug.println("parsing worked somehow");
`  } else {
`    Debug.println("parsing failed, rest is just random");
`  }
`  int command_nr = root["Command"];
`  if (command_nr == 1) {
`    Debug.println("command Nr 1 detected");
`  } else {
`    Debug.println("something else detected");
`  }
`}

The check for the parsing works, no problem there.
The "if (command_nr == 1) {" part does not work

But the problem at the moment lies somewhere else completely:
Since I had a problem with the code and no real explanation, I checked if I run the most recent versions of everything. I upgraded the Arduino IDE from 1.8.7 to 1.8.8 and I upgraded the ESP8266 board code from 2.4.x to 2.5-beta2. With this idiotic move, mqtt does not connect to the broker, so I can't continue to test the mqtt callback routine. Debugging that part is delayed, until the rest is working again. Most probably I need to downgrade and see, but not today.

Again, I very much appreciate your effort with the JSON library. It makes it very easy for me as a non-programmer to write code for my sonoff based sensor devices and the Node-RED based home automation system.

Kind regards,

Urs.

**Comment by Urs-Eppenberger** [comment]
I had to downgrade the ESP8266 board library to 2.4.2 to get MQTT over TLS running again.
And then I stored all the variables I retrieved from the JSON string into Arduino Strings. These I know how to handle in the code. And voilà, now everything works fine.
Case closed, thanks for the support

**Comment by bblanchon** [comment]
Hi @Urs-Eppenberger,

You're welcome, I'm glad you found the solution to your problem.

Thank you very much for using ArduinoJson.
If you like this library, please [star the project on GitHub](https://github.com/bblanchon/ArduinoJson/stargazers).

Regards,
Benoit
