### ISSUE TITLE
measureLength() missing in version 6

### ISSUE THREAD

**Issue by martinloren** [bblanchon/ArduinoJson#878]
What is the equivalent of the function measureLength() in V6? Can you please add in the guide?

Thanks!

**Comment by bblanchon** [comment]
Hi @martinloren,

The equivalent of the `measureLength()` method is the [measureJson()](https://arduinojson.org/v6/api/json/measurejson/) function.

By the way, when you need to find the equivalence from v5 to v6, simply change the version in the navigation bar, and it will show the equivalent function or class.

![2018-12-31_11-02-12](https://user-images.githubusercontent.com/5462433/50558131-c694d000-0ceb-11e9-97bc-1d844eda05c1.gif)

Regards,
Benoit
