### ISSUE TITLE
get key and value by index

### ISSUE THREAD

**Issue by boaschti** [bblanchon/ArduinoJson#879]
Hi, 
i want to read a json message like "{'24': 55, '25': 0, '26': 0, '27': 0, '20': 25, 'dmx':1}". The code i have written is too slow (as expected) but i don't know how to make it faster.
The Problem is, i dont know which keys are in the message they can be "1" - "512" and the value is always a byte 0-255.
My code: 

> 

    if (root.containsKey("dmx")){
        if (!DMXDevice){
            client.publish("DMX/Console", "DMX seen", false);
        }
        if (!DMXDevice){
          DMXDevice = true;
          Serial.begin(DMXSPEED, DMXFORMAT);
          pinMode(S20_Green_Led, OUTPUT);
        }
        char temp[10];
        for (uint16_t i = 1; i < DMXSize; i++){
            itoa(i, temp, 10);
            if (root.containsKey(temp)){
                DMXBuffer[i] = root[temp];
                itoa(DMXBuffer[i], temp, 10);
                if (lastUpdatedChannel < i){
                    lastUpdatedChannel = i;
                }
            }
        }
        if (lastUpdatedChannel == 0){
            lastUpdatedChannel = 1;
        }
     }

The sender is a Python srkipt and receiver a ESP8266 with a few DMX Lamps on its UART (with Transceiver sn75176). Perhabs there is a another way to solve this problem. What about streaming?

I checked [https://arduinojson.org/v5/faq/can-i-access-to-object-member-by-its-index-instead-of-its-key/](url) but then i don't know the keys.
Best regards

**Comment by bblanchon** [comment]
Hi @boaschti,

Now that's a seriously twisted JSON document.
If I were you I would change that instead!

Anyway, what's wrong with the loop suggested in the [FAQ](https://arduinojson.org/v5/faq/can-i-access-to-object-member-by-its-index-instead-of-its-key/)?
Simply increment an integer in the loop to get the index.
The key is in `it->key`.

Regards,
Benoit

**Comment by bblanchon** [comment]
No problem!
Thank you for using ArduinoJson.
If you like the library, please give it a star on GitHub 😄
