### ISSUE TITLE
Problem deserializing multidimensional Array

### ISSUE THREAD

**Issue by DavidHasterok** [bblanchon/ArduinoJson#886]
Hi, I'm inputting a simple JSON with 3 items in my project, Device, Profile, and length. Where Device is a String, Profile a multidimensional array int[][2] and length the amount of items in that array.
The Device and Length items deserialize just fine and if I treat Profile as a String it also comes out correctly, however I can't get it as an array.

An example JSON:

{ "Device" : "abc" , 
  "Profile" : "{{50, 10}, {30, 50}, {10, 10}}",
 "Length" : "3"}

String s  = json["Profile"] will give it correctly as a String, so it's not cut off or anything.
Trying things like int i = json["Profile"][0][0] will give me no value, however.

Am I missing something? Weird thing is, I remember being able to get the values before I took a longer break from the project, but I changed a lot since then and don't have that part of the code anymore and can't remember how I did it. I know, bad practice, only put the code on git after all that.

**Comment by bblanchon** [comment]
Hi @DavidHasterok,

The "Profile" member is a not an array, it's a string.

```c++
{ "Device" : "abc" ,
"Profile" : "{{50, 10}, {30, 50}, {10, 10}}",
"Length" : "3"}
```

Try to change the document like that:

```c++
{ "Device" : "abc" ,
"Profile" : [50, 10], [30, 50], [10, 10]],
"Length" : "3"}
```

Regards,
Benoit

**Comment by DavidHasterok** [comment]
Thank you! For some reason I thought the values have to be in quotes no matter what type they're supposed to be.

**Comment by bblanchon** [comment]
You're welcome David.
Thank you for using ArduinoJson.
Don't forget to [cast a star](https://github.com/bblanchon/ArduinoJson/stargazers) to support the project 😉
