### ISSUE TITLE
use AVR libc/libm for float-to-string

### ISSUE THREAD

**Issue by crackwitz** [bblanchon/ArduinoJson#896]
Why:
* it's been around for a long time
* it's widely used
* it's correct
* it's optimized in speed and program instructions
* Arduino relies on it already

What do I mean by "using" it?
* (s)printf-family of functions https://www.nongnu.org/avr-libc/user-manual/group__avr__stdio.html
* `dtostre`/`dtostrf` (for AVR, "double" is 32-bit float) https://www.nongnu.org/avr-libc/user-manual/group__avr__stdlib.html#ga6c140bdd3b9bd740a1490137317caa44

I really see no good reason to NIH in such a widely used Arduino library. Any downsides you see with using AVR libc/libm you should address by contributing to AVR libc/libm.

**Comment by crackwitz** [comment]
Upon discussion with some people on freenode, I now understand Core-avr _also_ implements its own float output routines and doesn't use avr libc/libm...

however, [String::String(float value, unsigned char decimalPlaces)](https://github.com/arduino/ArduinoCore-avr/blob/master/cores/arduino/WString.cpp#L108) uses `dtostrf`, which you can use as well.

I am puzzled as to why arduino doesn't use `dtostrf `for `Stream` as well.

**Comment by bblanchon** [comment]
What's wrong with the current implementation?
