### ISSUE TITLE
Unable to compile examples 

### ISSUE THREAD

**Issue by ebuzatti** [bblanchon/ArduinoJson#899]
Windows 10-64bit
Arduino IDE 1.8.8

**JsonConfigFile.ino:**
*C:\Users\...\Documents\Arduino\jsonex1\jsonex1.ino: In function 'void loadConfiguration(const char*, Config&)':
jsonex1:35:3: error: 'StaticJsonBuffer' was not declared in this scope
   StaticJsonBuffer<512> jsonBuffer;*

**StringExample.ino:**
*C:\Users\...\Documents\Arduino\jsonex1\jsonex1.ino: In function 'void setup()':
jsonex1:14:3: error: 'DynamicJsonBuffer' was not declared in this scope
   DynamicJsonBuffer jsonBuffer;*

**Comment by bblanchon** [comment]
Hi @ebuzatti,

`StaticJsonBuffer` and `DynamicJsonBuffer` are classes from version 5.
Make sure that you installed ArduinoJson version 5 and not version 6.

Regards,
Benoit
