### ISSUE TITLE
More efficient way to access array elements within an array?

### ISSUE THREAD

**Issue by BonShaw1** [bblanchon/ArduinoJson#902]
Below is an example of my Json data. The parsing program using ArduinoJson Assistant teaches how to easily access the elements of an array but suggests that the only way to access the different arrays is to create a different name such as fillset_agentType0, and fillset_agentType1 etc. This does not lend itself to parsing the data using a loop. Something like:

const char*  fillset_agentType[0,0] = fillset["agentType"][0,0] 
const char*  fillset_agentType[0,1] = fillset["agentType"][0,1]
const char*  fillset_agentType[1,0] = fillset["agentType"][1,0]
const char*  fillset_agentType[1,1] = fillset["agentType"][1,1]

would be easy.

Or, the ability to declare "JsonArray& fillset_agentType = fillset["agentType"][0] and later being able to declare JsonArray& fillset_agentType = fillset["agentType"][1] would also work great to simplify parsing.

I hope that I'm missing the obvious. Am I?

`const size_t capacity = 2*JSON_ARRAY_SIZE(2) + 2*JSON_ARRAY_SIZE(4) + JSON_ARRAY_SIZE(5) + 2*JSON_ARRAY_SIZE(10) + 2*JSON_OBJECT_SIZE(3) + 270;
DynamicJsonBuffer jsonBuffer(capacity);

const char* json = "{\"schema\":\"v0.1\",\"schemaDate\":1547067113,\"fillset\":{\"agentType\":[[\"HFC-227ea\",\"FM-200\",360,87.64,40,40,70,70,3.9865,-1.313],[\"HFC-125\",\"ECARO\",360,75.69,25,35,56,56,1.17,-1.068]],\"cylinderType\":[[\"20#\",\"20 pounds\",0.3,100],[\"35#\",\"35 pounds\",0.54,360]],\"pressure\":[125,360,500,650,900]}}";

JsonObject& root = jsonBuffer.parseObject(json);

const char* schema = root["schema"]; // "v0.1"
long schemaDate = root["schemaDate"]; // 1547067113

JsonObject& fillset = root["fillset"];

**JsonArray& fillset_agentType0** = fillset["agentType"][0];
const char* fillset_agentType00 = fillset_agentType0[0]; // "HFC-227ea"
const char* fillset_agentType01 = fillset_agentType0[1]; // "FM-200"
int fillset_agentType02 = fillset_agentType0[2]; // 360
float fillset_agentType03 = fillset_agentType0[3]; // 87.64

**JsonArray& fillset_agentType1** = fillset["agentType"][1];
const char* fillset_agentType10 = fillset_agentType1[0]; // "HFC-125"
const char* fillset_agentType11 = fillset_agentType1[1]; // "ECARO"
int fillset_agentType12 = fillset_agentType1[2]; // 360
float fillset_agentType13 = fillset_agentType1[3]; // 75.69`

**Comment by bblanchon** [comment]
Hi @BonShaw1,

Have a look at the [iterators for JsonArray](https://arduinojson.org/v5/api/jsonarray/begin_end/?utm_source=github&utm_medium=issues); unfortunatly the ArduinoJson Assistant doesn't use them.

In your case, it's probably something along those lines:

```c++
for (const JsonArray& a : root["fillset"]["agentType"].as<JsonArray>()) {
   const char* value0 = a[0];
   // ...
}
```

Regards,
Benoit

**Comment by BonShaw1** [comment]
With that I can easily move through the first element of ["fillset"]["agentType"]  (HFC-227ea, FM-200 etc.)  but I can't see how to address the second, third, . . . elements (HFC-125, ECARO) and so on. Can a[0] have two dimensions such as a[0][0] and a[1][0]?

**Comment by bblanchon** [comment]
Hi @BonShaw1,

I would be glad to help you, but I don't understand what you want to do.
In my previous message, I tried to be as close as possible to want you're looking for, but apparently, I missed the target.
Can you state clearly what you want to do?
You can use pseudo-code if it helps.

Regards,
Benoit

**Comment by BonShaw1** [comment]
Thank you so much. Perhaps this will clarify. 

{
"schema":"v0.1",
"schemaDate":1547067113,
"fillset":
{
"agentType":                     ( //Note: Up to 100 of these)
[
["HFC-227ea","FM-200",360,87.64,40,40,70,70,3.9865,-1.313],
["HFC-125","ECARO",360,75.69,25,35,56,56,1.17,-1.068]
["HFC-227ea","FM-200",500,75.69,25,35,56,56,1.17,-1.025]
],
"cylinderType":                  ( //Note: Up to 100 of these)
[
["20#","20 pounds",0.3,100],
["35#","35 pounds",0.54,360]
["60#","60 pounds",0.87,500]
],
"pressure":[125,360,500,650,900]
}
}


```
1) Find and extract array data from ["fillset"]["agentType"]  [0] elements 0 - 9
2) Find and extract array data from ["fillset"]["agentType"]  [1] elements 0 - 9
3) Find and extract array data from ["fillset"]["agentType"]  [2] elements 0 - 9
.                                                              . 
.                                                              . 
100)                                                          [99] elements 0 - 9

(Next Loop . . .)

1) Find and extract array data from ["fillset"]["cylinderType"]  [0] elements 0 - 9
2) Find and extract array data from ["fillset"]["cylinderType"]  [1] elements 0 - 9
3) Find and extract array data from ["fillset"]["cylinderType"]  [2] elements 0 - 9
.                                                                 .
.                                                                 .
100)                                                             [99] elements 0 - 9

(Final Loop . . .)

1) Find and extract array data from ["fillset"]["pressure"]  elements 0 - 9
```

**Comment by bblanchon** [comment]
Hi @BonShaw1,

I'm sorry, I still don't understand what you want, so I'll try to add comments to my previous code.

```c++
// (First Loop . . .)
// 1) Find and extract array data from ["fillset"]["agentType"]  [0]
// 2) Find and extract array data from ["fillset"]["agentType"]  [1] 
// 3) Find and extract array data from ["fillset"]["agentType"]  [2]
// .
// .
// 100)
for (const JsonArray& a : root["fillset"]["agentType"].as<JsonArray>()) {
   //  elements 0 - 9
   const char* element0 = a[0];
   const char* element1 = a[1];
   int element2 = a[2];
   float element3 = a[3];
   int element4 = a[4];
   int element5 = a[5];
   int element6 = a[6];
   int element7 = a[7];
   float element8 = a[8];
   float element9 = a[9];
}
```

You could use an inner loop for the "elements", but there are of different types so it might not be very practical. Here is what it would look like:

```c++
for (const JsonArray& a : root["fillset"]["agentType"].as<JsonArray>()) {
   for (JsonVariant element : a) {
     // elements 0 - 9
   }
}
```

Regards,
Benoit

**Comment by BonShaw1** [comment]
Okay, adding to your example, I need an outer loop for what you have shown here. The outer loop will select each group of 0-9 elements. The outer loop will step through the 100 elements that you show in your example. All together I need to parse all 1000 elements.
`
for (?????????????????????????????????????????????????????????????????) {
   for (const JsonArray& a : root["fillset"]["agentType"].as<JsonArray>()) {
     //  elements 0 - 9
     const char* element0 = a[0];
     const char* element1 = a[1];
     int element2 = a[2];
     float element3 = a[3];
     int element4 = a[4];
     int element5 = a[5];
     int element6 = a[6];
     int element7 = a[7];
     float element8 = a[8];
     float element9 = a[9];
  }
}
`

**Comment by bblanchon** [comment]
Hi @BonShaw1,

I think I understand. You want to iterate for each key-value pair in `root["fillset"]`, right?

To do that, you need to use [object iterators](https://arduinojson.org/v5/api/jsonobject/begin_end/?utm_source=github&utm_medium=issues):

```c++
for (const JsonPair &p : root["fillset"].as<JsonObject>()) {
  const char *name = p.key;

  for (const JsonArray &a : p.value.as<JsonArray>()) {
    const char *element0 = a[0];
    const char *element1 = a[1];
    int element2 = a[2];
    float element3 = a[3];
    int element4 = a[4];
    int element5 = a[5];
    int element6 = a[6];
    int element7 = a[7];
    float element8 = a[8];
    float element9 = a[9];
  }
}
```

Regards,
Benoit

**Comment by BonShaw1** [comment]
bblanchon, Thank you!! I have a lot to learn! You assistance has been invaluable. Your library has greatly simplified my parsing and will make maintaining my code vastly easier in the future. I'll certainly be buying your book to shorten my learning curve and begin to take full advantage of your knowledge and library.
 
My current implementation may not be the best it could be, yet, but it's getting the job done in a very short, concise, way. It now looks like this:
`        for (const JsonPair &p : root["fillset"].as<JsonObject>()) {
          const char* name = p.key;
          for (const JsonArray &a : p.value.as<JsonArray>()) {
            if (String(name) == "agentType") {
              const char* element0 = a[0]; 
              const char* element1 = a[1]; 
              int   element2       = a[2]; 
              float element3       = a[3]; 
              int   element4       = a[4]; 
              int   element5       = a[5]; 
              int   element6       = a[6]; 
              int   element7       = a[7]; 
              float element8       = a[8];
              float element9       = a[9];
            }
            if (String(name) == "cylinderType") {
              const char* element0 = a[0];
              const char* element1 = a[1];
              float element2       = a[2];
              int element3         = a[3];
            }
          }
        }
        JsonObject& fillset = root["fillset"];
        JsonArray& fillset_pressure = fillset["pressure"];
        for (byte i=0; i <= 24; i++){
          Storage_element(i) = fillset_pressure[i]; 
        }
`

**Comment by bblanchon** [comment]
Hi @BonShaw1,

I'm so glad to read that!
Thank you very much for the kind words :-)

Maybe we can close this issue now?

Regards,
Benoit

**Comment by BonShaw1** [comment]
You're welcome. One last word. I've been reading your book. Love it. It's paid for itself in one day, and I'm still in **Chapter 1**! Can't beat that. Best Regards, Bon Shaw.
