### ISSUE TITLE
can't add string variables to nested array ?

### ISSUE THREAD

**Issue by mohamedpsx** [bblanchon/ArduinoJson#91]
having problems when trying to add a string variable to a nested array, any one aware about this problem?

**Comment by bblanchon** [comment]
This usually comes from the fact that string are not duplicated.
https://github.com/bblanchon/ArduinoJson/wiki/Avoiding%20pitfalls#6-do-not-assume-that-strings-are-copied.

The behavior is different in version 5.0 beta.
It automatically makes copies of `String`variables and provides `JsonBuffer::strdup()` if you want to manually make a copy of a `char*`.
Please, give it a try.
