### ISSUE TITLE
Serialize appends to strings

### ISSUE THREAD

**Issue by abaskin** [bblanchon/ArduinoJson#918]
When serialize is called with a string (std::string or String), a second call using the same string appends to the string as opposed to overwriting the string. This seems counterintuitive to me as I can not think of a case where this behavior would be useful. At minimum I would think that this behavior should be documented to avoid confusion.

**Comment by bblanchon** [comment]
Hi @abaskin,

You're right it was not clearly stated in the documentation.
I added the following sentence:

 > :warning: This function treats String and std::string as streams: it doesn’t replace the content, it appends to the end.

Thank you for reporting this issue and for using ArduinoJson.

Regards,
Benoit
