### ISSUE TITLE
no type named 'const_iterator' in 'class ArduinoJson691_000::ObjectRef'

### ISSUE THREAD

**Issue by JeffrySteegmans** [bblanchon/ArduinoJson#927]
I just update from version 5.x to 6.x and now I get the following error in the file ArduinoJson/Deserialization/IteratorReader.cpp on line 27.

![QHX7ssH](https://user-images.githubusercontent.com/17906736/54085453-af530e00-433e-11e9-8cf7-b82f6c2d7ec8.png)

Any solutions?

**Comment by bblanchon** [comment]
Hi @JeffrySteegmans,

I'm going to need a bit more context...

**Comment by JeffrySteegmans** [comment]
I'm building with VS code and platformIO. Also installed the update with platformIO.
I changed my code according to the upgrade wizzard but this is an error within the library i think.

This is my complete build log: https://pastebin.com/VKWreL7H

**Comment by bblanchon** [comment]
It seems that the call to [deserializeJson()](https://arduinojson.org/v6/api/json/deserializejson/) is incorrect.
Can you verify?

**Comment by JeffrySteegmans** [comment]
Damn you're right. I did something wrong when converting from 5.x to 6.x.
Tx for the help!!
