### ISSUE TITLE
sending multidimensional array and reuse  it again   

### ISSUE THREAD

**Issue by aii1** [bblanchon/ArduinoJson#929]
I know we should not reuse the JSONdocument (jsonbuffer v5) but how can I do below task:

I have a loop which creates below a nested array(data logger sample/min), and when Arduino receive a Get(JSON) from the web will send the data.  but the problem is I do not need the old data anymore and I need to recreate new nested array or overwrite the existing one, since if I do not do that the array will be huge 100k rows. (can I even use Arduinojson for this task)

I declare  extern StaticJsonDocument<500> doc; in process.h

```c++
void process::checker(){
	for (int i=1; i<3; i++) {
		if(Analyzer_status[i][0] == 1 ) {
			if (current_time-Analyzer_status[i][2] >= Analyzer_status[i][1]) {
		
        JsonArray   nested = doc.createNestedArray();
        nested.add(i);
        nested.add(this->analogtodigital(i));
        nested.add(actual_time);
       
      	log_counter++;


			}
		}
	}
}
```

**Comment by bblanchon** [comment]
Hi @aii1,

With ArduinoJson, you need to recreate the complete `JsonDocument` each time.

In your case, it means that you need to store your points in another data structure, such as a circular buffer.
Something along those lines:

```c++
struct DataPoint {
   int index;
   int value;
   long timestamp;
};

DataPoint points[256];
int pointsStart = 0;
int pointsEnd = 0;
```

And then create the `JsonDocument` from this data structure each time you need to send/save it.

Regards,
Benoit
