### ISSUE TITLE
when casting a json value to bool, 1 should be true

### ISSUE THREAD

**Issue by firepick1** [bblanchon/ArduinoJson#93]
Benoit, I made the following change in my fork to reduce JSON size. I got the idea from Jansson, which is the other JSON library I use as well.

https://github.com/firepick1/ArduinoJson/commit/f7f2d1dce29fca2886914253c8308cc0221ec580

(ignore the precision change, that's irrelevant)

**Comment by bblanchon** [comment]
This is a very good idea.
Other casts have been identified, I'll implement all of them in version 5.0.
I'll close this issue and update #69 instead.
