### ISSUE TITLE
custom allocator

### ISSUE THREAD

**Issue by sticilface** [bblanchon/ArduinoJson#933]
I'm moving development to the ESP32, specifically the WROVER which has 4Mb PSRAM. 

What are the odds on gaining a template overload for dynamicjsondoc that would allow the allocation of memory on PSRAM instead of normal RAM?  would allow parsing of significantly larger documents? 

it has several restrictions, hence not too keen to make it available to the whole device... 

https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/external-ram.html#restrictions

**Comment by bblanchon** [comment]
Odds are very high!
Please vote on issue #876 and close this one if it's a duplicate.
Hopefully, I can put this in 6.10 ;-)
