### ISSUE TITLE
How to use it from gcc on RPI

### ISSUE THREAD

**Issue by kuzmanzs** [bblanchon/ArduinoJson#935]
Hi,

I would like to use your code on RPI.
I have downloaded the header and zip from release.
Where should I put the zip? Should I unpack it?

I would like to use it from command line with gcc in a simple hello word json.

Br,
Zsolt

**Comment by kuzmanzs** [comment]
I have runned cmake. with original (repo version) CMakeLists.txt
then make
..
Scanning dependencies of target msgpack_fuzzer
[ 98%] Building CXX object fuzzing/CMakeFiles/msgpack_fuzzer.dir/msgpack_fuzzer.cpp.o
[ 99%] Building CXX object fuzzing/CMakeFiles/msgpack_fuzzer.dir/fuzzer_main.cpp.o
[100%] Linking CXX executable msgpack_fuzzer
[100%] Built target msgpack_fuzzer

How should I install it? I could not find nowhere the compilled/installed lib.

**Comment by bblanchon** [comment]
Hi @kuzmanzs,

ArduinoJson is a header-only library; there is nothing to install 😉 

Simply download the latest `ArduinoJson-6.x.x.h` from GitHub:
https://github.com/bblanchon/ArduinoJson/releases/latest/

Save it with your project's files, where the compiler can find it.

Regards,
Benoit

**Comment by kuzmanzs** [comment]
thanks, it works.

Br,
Zsolt

**Comment by bblanchon** [comment]
You're welcome.
Thank you for using ArduinoJson
