### ISSUE TITLE
parsing string that is in a <vector>

### ISSUE THREAD

**Issue by mars000** [bblanchon/ArduinoJson#937]
Hi 

I have <vector> of chars containing a json message within it.
Is it possible for parse this <vector> without me requiring to copying it into a standard c char array and then passing it for parsing ? If so is there a simple example or doc as I have not been able to find one.

e.g. just for illustration only...
```cpp
   std::vector <char> message_local
   // assume a well constructed json message resides within message_local vector array
 
    DynamicJsonBuffer jBuffer;

// ??? can you something like this using <vector> array
    JsonObject &root = jBuffer.parseObject(message_local); 
```

**Comment by bblanchon** [comment]
Hi @mars000,

It should already work with ArduinoJson 6:

```c++
deserializeJson(doc, message_local);
```

Can you upgrade to version 6?

Regards
Benoit
