### ISSUE TITLE
What is the Benefit of V6 compared to V5

### ISSUE THREAD

**Issue by hasenradball** [bblanchon/ArduinoJson#940]
Hi Benoit,

can you please tell me in a view word the benefit of upgrading to V6 when actually using V5 of ArduiniJSON?

Thanks

**Comment by bblanchon** [comment]
Hi @hasenradball,

In short:

- simpler to use (no reference and JsonDocument)
- tells why parsing fails
- MessagePack
- lower memory usage

But if your code works fine with v5, keep it like this.

Regards,
Benoit

**Comment by hasenradball** [comment]
Hi Benoit,

Thank you very much.
Is the V6 documented in a new version of the book?

Thanks

**Comment by bblanchon** [comment]
Yes, the book is in sync with 6.9.

**Comment by hasenradball** [comment]
One last question Benoit,

if I have one book which has original foil and is in original wrapping.
Is ther the posibility to excahange this to a versin which has the V6.9 inside?

Regards Frank

**Comment by bblanchon** [comment]
Please send me an email, we'll fix that.
