### ISSUE TITLE
JsonObjectRef does not name a type

### ISSUE THREAD

**Issue by fsicre** [bblanchon/ArduinoJson#942]
can't find class JsonObjectRef mentioned in README
```
JsonObjectRef root = doc.as<JsonObject>();
```

**Comment by bblanchon** [comment]
Hi @fsicre,

You're right, the code snippets in the README were wrong; [I just fixed them](https://github.com/bblanchon/ArduinoJson/commit/2fc220fa33ac03f069251c3d8bc822ece5940081).
Thank you very much for reporting this issue.

Regards,
Benoit
