### ISSUE TITLE
ArduinoJson v6 not compiling on Sloeber Plugin

### ISSUE THREAD

**Issue by karpenet** [bblanchon/ArduinoJson#947]
Using ArduinoJSON v6 produces compilation error. Suggests that StaticJsonDocument is an invalid keyword. But using keyword StaticJsonBuffer, the code compiles without any hassle.

While the Arduino IDE displays V6.10 as the currently installed version of ArduinoJSON, the Sloeber plugin shows v5 versions in the preferences menu.

**Comment by bblanchon** [comment]
Hi @karpenet,

I'm sorry, I'm not familiar with the Sloeber plugin.
I suppose it looks for ArduinoJson in the wrong location, possibly in an older installation of Arduino.
You can look for `ArduinoJson.h` on your hard-drive to see where the library is installed.
Then, maybe you should ask for assistance to the Sloeber team.

Regards,
Benoit

**Comment by bblanchon** [comment]
Did you make it work?
