### ISSUE TITLE
Communication with BluetoothSerial

### ISSUE THREAD

**Issue by mois770** [bblanchon/ArduinoJson#948]

**Comment by bblanchon** [comment]
Hi @mois770,

It seems that `BluetoothSerial` implement `Stream` so you should be able to use it with ArduinoJson.
What did you try?

Regards,
Benoit

**Comment by mois770** [comment]
bsd

Thank you for your answer.
Right after I wrote this issue I tryied again and it worked well.
Congratulation for your  work and your attention.
Regards

**Comment by bblanchon** [comment]
You're welcome. Thank you for using ArduinoJson.
Don't forget to [cast a star](https://github.com/bblanchon/ArduinoJson/stargazers) to support the project ;-)
