### ISSUE TITLE
Parse Json array in other function

### ISSUE THREAD

**Issue by MaxESP** [bblanchon/ArduinoJson#949]
here is my function:

void firebasedata(){
Firebase.stream("/Alarme/", [](FirebaseStream stream) {
  
//String eventType = stream.getEvent();
//Serial.println(eventType);
//String data = stream.getDataString();
//Serial.println(data);

const size_t capacity = JSON_ARRAY_SIZE(6) + 5*JSON_OBJECT_SIZE(3) + 130;
DynamicJsonBuffer jsonBuffer(capacity);
////StaticJsonBuffer<500> jsonBuffer;
////char json[] =stream.getDataString();
JsonArray& root = jsonBuffer.parseArray(stream.getDataString());

JsonObject& root_1 = root[1];

int root_1_H1 = root_1["H1"]; // 9
int root_1_Mn1 = root_1["Mn1"]; // 6
int root_1_scID1 = root_1["scID1"]; // 1

JsonObject& root_2 = root[2];
int root_2_H2 = root_2["H2"]; // 14
int root_2_Mn2 = root_2["Mn2"]; // 11
int root_2_scID2 = root_2["scID2"]; // 2

JsonObject& root_3 = root[3];
int root_3_H3 = root_3["H3"]; // 14
int root_3_Mn3 = root_3["Mn3"]; // 11
int root_3_scID3 = root_3["scID3"]; // 2﻿
 Firebase.stopStream();
      });
}

I want to parse those int root to an other function 

the goal is to compare the time int of firebase to int time system of esp8266

**Comment by bblanchon** [comment]
Hi @MaxESP,

Please apologize for the late answer, I somehow missed the notification.
If you want to move the extraction from `root` to another function, you simply need to have a parameter of type `JsonObject&`:

```c++
void myOtherFunction(JsonObject& root) {
  // ...
}
```

Is that what you're looking for?

Regards, 
Benoit
