### ISSUE TITLE
How to get booleans

### ISSUE THREAD

**Issue by delcomp** [bblanchon/ArduinoJson#95]
How can the lib handle these:
"valet_mode":false,
"valet_pin_needed":true,

How to get the boolean values?

**Comment by bblanchon** [comment]
As usual:

    bool valet_mode = root["valet_mode"];

**Comment by fedor1210** [comment]
Hmm... I cannot do this. 
My JSON is: `{"name":"TableLED","service_name":"LED","characteristic":"On","value":true}`
And when I `bool val = root["value"];`, I get `0`.

What am I doing wrong? Other objects are parsing.
