### ISSUE TITLE
How to create dynamic Nested Object to Array?

### ISSUE THREAD

**Issue by Findus76** [bblanchon/ArduinoJson#955]
Lib version: 6.10.0
Compiler: PlatformIO
Target: ESP8266

I can't figure out how to add dynamic Nested Object to Array.
e.g
{"Type" : "Event", "Event list": [
   {"Name": "Voltage L1", "Value": 230},
   {"Name": Current L1", "Value": 1.23},
   {"Name": "Temperature", "Value": 23.3}]}

It can be up to 45 object in the "Event list" array.
![bild](https://user-images.githubusercontent.com/43476491/55197268-5266ad00-51b2-11e9-8971-3e077724f8fc.png)

Brg
Findus

**Comment by bblanchon** [comment]
Hi Findus,

The compiler says it cannot find `JsonArray::createNestedObject(const char*)` but it found a `JsonArray::createNestedObject()`.
Indeed, [JsonArray::createNestedObject()](https://arduinojson.org/v6/api/jsonarray/createnestedobject/) doesn't take any argument.

Regards,
Benoit

**Comment by Findus76** [comment]
Okey
is this correct? It feels strange in the loop with the creation of NestedObject
![bild](https://user-images.githubusercontent.com/43476491/55293849-43267000-53fb-11e9-9bbd-18692ddf4827.png)
Brg Findus

**Comment by bblanchon** [comment]
Hi Findus,

Yes, it looks good.
Does the code work as you expect?

Regards,
Benoit

**Comment by Findus76** [comment]
Thanks!

haven't tried yet, have got big problems with the hardware. Need to resolder.
But the compiler runs with 0 error now :)

Big thanks for your review.

Brg
Findus

**Comment by bblanchon** [comment]
You're welcome Findus; thank you for using ArduinoJson.
Don't forget to [cast a start](https://github.com/bblanchon/ArduinoJson/stargazers) to support the project 😉
