### ISSUE TITLE
StaticJsonBuffer

### ISSUE THREAD

**Issue by Player76** [bblanchon/ArduinoJson#957]
I have the version 6 of the Json files but I receive this
![a](https://user-images.githubusercontent.com/49133283/55297401-9a3d3c80-541d-11e9-8abf-a9196de8c7fe.png)

**Comment by smuellener** [comment]
With ArduinoJson v6 you have to use StaticJsonDocument instead of StaticJsonBuffer. See the following link and video:
https://arduinojson.org/v6/doc/upgrade/
https://www.youtube.com/watch?v=Kn0xtXlAot8

**Comment by Player76** [comment]
The issue is in the FirebaseArduino.h file, and I'm not advanced enough to understand his update

**Comment by bblanchon** [comment]
Hi @Player76,

Since you cannot upgrade the code, I recommend that you **downgrade the library**.
Open the library manager, find ArduinoJson, select the version 5.13.5 and click install.

Regards,
Benoit

**Comment by Player76** [comment]
Thanks it helped
