### ISSUE TITLE
String to JsonArray

### ISSUE THREAD

**Issue by Ikswoknib** [bblanchon/ArduinoJson#964]
I need to convert an String to an JsonArray:
I want to use a function which needs an JsonArray as Paramter. Normaly the Function is started due to an URL with the JsonArray in it. But in some cases I need to read the JsonArray from an SPIFFS File. The Function I defined as:
void rawblast(JsonArray &raw, int khz, int rdelay, int pulse, int pdelay, int repeat)

The Data for the Array are stored in an SPIFFS File, so I have the Data in an String if I read it in.
Example Data:
[112,32243,34,44,25,56,123]
So the Data are stored in Form of an Array, but I could change the format of the data in the File if it is easier then.

So how can I convert the String to an new JsonArray ?

**Comment by bblanchon** [comment]
Hi @Ikswoknib,

Just ask the [ArduinoJson Assitant](https://arduinojson.org/v6/assistant/) 😉 
Here is what it says:

```c++
const size_t capacity = JSON_ARRAY_SIZE(7);
DynamicJsonDocument doc(capacity);

const char* json = "[112,32243,34,44,25,56,123]";

deserializeJson(doc, json);

int root_0 = doc[0]; // 112
long root_1 = doc[1]; // 32243
int root_2 = doc[2]; // 34
int root_3 = doc[3]; // 44
int root_4 = doc[4]; // 25
int root_5 = doc[5]; // 56
int root_6 = doc[6]; // 123
```

To iterate, have a look at [JsonArray::begin() / end()](https://arduinojson.org/v6/api/jsonarray/begin_end/)

Regards,
Benoit
