### ISSUE TITLE
copyArray() failed

### ISSUE THREAD

**Issue by Rayuu** [bblanchon/ArduinoJson#965]
Hi,Benoît Blanchon:
    I used "copyArray()" function,but it does not work. The software's version is V6.10.0. 
![20190409172501](https://user-images.githubusercontent.com/11494597/55789608-3be31e80-5aed-11e9-966c-91dca0bea179.png)

**Comment by Rayuu** [comment]
I'm sorry, now I know why it is wrong.
> int values[] = [1,2,3];

it's wrong.[https://arduinojson.org/v6/api/misc/copyarray/](https://arduinojson.org/v6/api/misc/copyarray/)

it should be

> int values[] = {0};

**Comment by bblanchon** [comment]
Oops! Sorry about that.
It should be fixed now.
Thanks, @Rayuu.
