### ISSUE TITLE
Unable to use to my cpp project -- (usin arm compiler in VC++)

### ISSUE THREAD

**Issue by carter3rix** [bblanchon/ArduinoJson#966]
Am building a cpp application using VC++ 2008... I have put the ArduinoJson dir in my project 
but anytime i compile... i get the error below.... Help...
`error ArduinoJson requires a C++ compiler, please change file extension to .cc or .cpp `

**Comment by bblanchon** [comment]
Are you sure the compiler supports C++?

**Comment by carter3rix** [comment]
> Are you sure the compiler supports C++?

Yes it does, am building a POS application with telpo sdk... Any help

**Comment by bblanchon** [comment]
I'm not familiar with this toolchain, can you give more details?
I never saw a C++ compiler that doesn't define `__cplusplus`, are you sure it supports C++?
Did you set the file extension to `.cpp` as advised in the error message?

**Comment by bblanchon** [comment]
@carter3rix, any update?
