### ISSUE TITLE
ArduinoJson6 and Arduino Due board compiling errors. Arduino 1.8.9 IDE

### ISSUE THREAD

**Issue by sx126** [bblanchon/ArduinoJson#968]
Hi!
I have problem when I'm trying to compile my sketch on Arduino Due board. On my Mega 2560 rev. 3 works fine, but I have to replace Mega to Due, because my Mega has not enaugh RAM space for my project. I have this errors:

**Arduino: 1.8.9 (Windows 10), Board: "Arduino Due (Native USB Port)"

In file included from d:\dokumenty\arduino\libraries\arduinojson\src\arduinojson\operators\variantoperators.hpp:7:0,

                 from d:\dokumenty\arduino\libraries\arduinojson\src\arduinojson\variant\variantref.hpp:12,

                 from D:\Dokumenty\Arduino\libraries\ArduinoJson\src/ArduinoJson/Array/ArrayIterator.hpp:8,

                 from D:\Dokumenty\Arduino\libraries\ArduinoJson\src/ArduinoJson/Array/ArrayRef.hpp:9,

                 from D:\Dokumenty\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:17,

                 from D:\Dokumenty\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,

                 from D:\Dokumenty\Arduino\sx_blinds_v5_stable\sx_blinds_v5_stable.ino:2:

d:\dokumenty\arduino\libraries\arduinojson\src\arduinojson\operators\VariantCasts.hpp: In instantiation of 'ArduinoJson6100_000::VariantCasts<TImpl>::operator T() const [with T = char*; TImpl = ArduinoJson6100_000::MemberProxy<ArduinoJson6100_000::JsonDocument&, const char*>]':

D:\Dokumenty\Arduino\sx_blinds_v5_stable\sx_blinds_v5_stable.ino:319:38:   required from here

d:\dokumenty\arduino\libraries\arduinojson\src\arduinojson\operators\VariantCasts.hpp:16:35: error: invalid conversion from 'ArduinoJson6100_000::VariantAs<char*>::type {aka const char*}' to 'char*' [-fpermissive]

     return impl()->template as<T>();

                                   ^
exit status 1
Error compiling for board Arduino Due (Native USB Port).**

I'm using Json like that:
Serialize:

            **DynamicJsonDocument conf(200);
            conf["command"] = "c";
            conf["action"] = "!";
            conf["blinds"] = w1.getBlindsCount();
            conf["rtc"] = RTCLK;
            conf["sd_mem"] = SDMemory;
            conf["input_temperature_sensor"] = inputTemperatureSensor;
            conf["output_temperature_sensor"] = outputTemperatureSensor;
            Serial1.print("$");
            serializeJson(conf, Serial1);
            Serial1.println();**

Deserialize:

           **String  jsonString = eventFile.readStringUntil('\n');
           DynamicJsonDocument SDevent(200);
           deserializeJson(SDevent, jsonString);
           char* jType = SDevent["e_type"];
           bool jActive = SDevent["e_active"];
           if (strcmp(jType, "o") == 0)
           {
             unsigned int jYear = SDevent["e_year"];
             unsigned int jMonth = SDevent["e_month"];
             unsigned int jDay = SDevent["e_day"];
             unsigned int jHour = SDevent["e_hour"];
             unsigned int jMinute = SDevent["e_minute"];
             String jBlinds = SDevent["e_blinds"];
             String jAction = SDevent["e_action"];
             addOneEvent(jYear, jMonth, jDay, jHour, jMinute, jAction, jBlinds, jActive, false);
           }
           if (strcmp(jType, "t") == 0)
           {
             String jDays = SDevent["e_days"];
             unsigned int jHour = SDevent["e_hour"];
             unsigned int jMinute = SDevent["e_minute"];
             String jBlinds = SDevent["e_blinds"];
             String jAction = SDevent["e_action"];
             addMultiEvent(jDays, jHour, jMinute, jAction, jBlinds, jActive, false);
           }
           jType = NULL;**

I'm looking forward to sulution of this problem.

Best Regards
Sebastian

**Comment by bblanchon** [comment]
Hi Sebastian,

See: [Error: invalid conversion from 'const char*' to 'char*' [-fpermissive]](https://arduinojson.org/v6/faq/error-invalid-conversion-from-const-char-to-char/)

In your case, the compiler says it's on line 319 of `sx_blinds_v5_stable.ino`.

Regards,
Benoit
