### ISSUE TITLE
How to parse anonymous object inside an object

### ISSUE THREAD

**Issue by kingcobra4545** [bblanchon/ArduinoJson#970]
My json string as below
{
  "history" : {
    "-LcbpeVkKyZiFIHPzXzb" : {
      "alarm_at" : "Wed Apr 12 01:58:59 2019\n",
      "pill_name" : "Avil 50",
      "pill_no" : 1
    },
    "-Lcbph8ezG06QmsxFKbo" : {
      "alarm_at" : "Wed Apr 11 01:59:10 2019\n",
      "pill_name" : "Dolo",
      "pill_no" : 4
    },
    "-LcbrK6FhsEqph90oUEX" : {
      "alarm_at" : "Wed Apr 17 02:06:16 2019\n",
      "pill_name" : "Dolo",
      "pill_no" : 4
    },
    "-LcbrVWTyB22D838FZU8" : {
      "alarm_at" : "Wed Apr 17 02:07:02 2019\n",
      "pill_name" : "Avil 25",
      "pill_no" : 2
    }
  },
  "test" : {
    "pill_1" : {
      "alarm_at" : "1851",
      "pill_name" : "Slot 1",
      "pill_no" : 1
    },
    "pill_2" : {
      "alarm_at" : "1848",
      "pill_name" : "Slot 3",
      "pill_no" : 2
    }
  }
}

The keys "LcbrVWTyB22D838FZU8" are auto generated and I would not know them. Now how to parse through the data that are stored under such UID keys ?
If I try like json.get("history")[0].get("alarm_at"), I should be getting value as "Wed Apr 12 01:58:59 2019\n".

Please help me !

**Comment by bblanchon** [comment]
Hi @kingcobra4545,

See [JsonObject::begin() / end()](https://arduinojson.org/v6/api/jsonobject/begin_end/).

Regards,
Benoit
