### ISSUE TITLE
404! Broken link to examples in readme

### ISSUE THREAD

**Issue by PRO2XY** [bblanchon/ArduinoJson#974]
Hey! Just a quick heads up. 
The link to Examples in the Readme points to 
```https://arduinojson.org/example/?utm_source=github&utm_medium=readme```
which returns a 404: Page not found error.

**Comment by bblanchon** [comment]
Hi @PRO2XY,

It's fixed now.
Thank you very much for reporting this issue.

Best regards,
Benoit
