### ISSUE TITLE
Function deserializeJson is error

### ISSUE THREAD

**Issue by sipt91** [bblanchon/ArduinoJson#980]
#include <ArduinoJson.h>
void setup() {
  Serial.begin(9600);
  char json[] = "11,12,13,14";  // wrong json format
  StaticJsonDocument<200> jsonBuffer;
  DeserializationError err = deserializeJson(jsonBuffer, json);
  Serial.print(F("err="));
  Serial.println(err.c_str());
}

void loop() {
}

=>Result: err=Ok

**Comment by bblanchon** [comment]
Hi @sipt91 

Indeed, ArduinoJson isn't a very strict parser and doesn't pretend to be.
I understand that, in theory, this could be a problem, but in practice, it has never been.

Do you have a concrete use case where this is problematic?

Best Regards,
Benoit

**Comment by sipt91** [comment]
Hi @bblanchon 

This's my case.

Thank you.


<pre>
<font color="#5e6d03">#include</font> <font color="#434f54">&lt;</font><font color="#000000">ArduinoJson</font><font color="#434f54">.</font><font color="#000000">h</font><font color="#434f54">&gt;</font>

<font color="#5e6d03">#include</font> <font color="#434f54">&lt;</font><b><font color="#d35400">SoftwareSerial</font></b><font color="#434f54">.</font><font color="#000000">h</font><font color="#434f54">&gt;</font>
<b><font color="#d35400">SoftwareSerial</font></b> <font color="#000000">esp8266</font><font color="#000000">(</font><font color="#000000">9</font><font color="#434f54">,</font> <font color="#000000">10</font><font color="#000000">)</font><font color="#000000">;</font>

<font color="#00979c">void</font> <font color="#000000">config_device</font><font color="#000000">(</font><font color="#000000">)</font> <font color="#000000">{</font>
 &nbsp;<font color="#000000">esp8266</font><font color="#434f54">.</font><font color="#d35400">setTimeout</font><font color="#000000">(</font><font color="#000000">3000</font><font color="#000000">)</font><font color="#000000">;</font>

 &nbsp;<font color="#000000">esp8266</font><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#005c5f">&#34;AT+RST&#34;</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<font color="#000000">esp8266</font><font color="#434f54">.</font><font color="#d35400">find</font><font color="#000000">(</font><font color="#005c5f">&#34;ready\r\n&#34;</font><font color="#000000">)</font><font color="#000000">;</font>

 &nbsp;<font color="#000000">esp8266</font><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#000000">F</font><font color="#000000">(</font><font color="#005c5f">&#34;AT+CWMODE=2&#34;</font><font color="#000000">)</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<font color="#000000">esp8266</font><font color="#434f54">.</font><font color="#d35400">find</font><font color="#000000">(</font><font color="#005c5f">&#34;OK\r\n&#34;</font><font color="#000000">)</font><font color="#000000">;</font>

 &nbsp;<font color="#000000">esp8266</font><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#000000">F</font><font color="#000000">(</font><font color="#005c5f">&#34;AT+CWSAP=\&#34;WiFi-IoT\&#34;,\&#34;\&#34;,1,0&#34;</font><font color="#000000">)</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<font color="#000000">esp8266</font><font color="#434f54">.</font><font color="#d35400">find</font><font color="#000000">(</font><font color="#005c5f">&#34;OK\r\n&#34;</font><font color="#000000">)</font><font color="#000000">;</font>

 &nbsp;<font color="#000000">esp8266</font><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#000000">F</font><font color="#000000">(</font><font color="#005c5f">&#34;AT+CIPMUX=1&#34;</font><font color="#000000">)</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<font color="#000000">esp8266</font><font color="#434f54">.</font><font color="#d35400">find</font><font color="#000000">(</font><font color="#005c5f">&#34;OK\r\n&#34;</font><font color="#000000">)</font><font color="#000000">;</font>

 &nbsp;<font color="#000000">esp8266</font><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#000000">F</font><font color="#000000">(</font><font color="#005c5f">&#34;AT+CIPSERVER=1,1234&#34;</font><font color="#000000">)</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<font color="#000000">esp8266</font><font color="#434f54">.</font><font color="#d35400">find</font><font color="#000000">(</font><font color="#005c5f">&#34;OK\r\n&#34;</font><font color="#000000">)</font><font color="#000000">;</font>

 &nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#000000">F</font><font color="#000000">(</font><font color="#005c5f">&#34;Config Mode&#34;</font><font color="#000000">)</font><font color="#000000">)</font><font color="#000000">;</font>

 &nbsp;<font color="#5e6d03">while</font> <font color="#000000">(</font><font color="#000000">1</font><font color="#000000">)</font>
 &nbsp;<font color="#000000">{</font>
 &nbsp;&nbsp;&nbsp;<font color="#00979c">String</font> <font color="#000000">read_data</font> <font color="#434f54">=</font> <font color="#000000">esp8266</font><font color="#434f54">.</font><font color="#d35400">readStringUntil</font><font color="#000000">(</font><font color="#00979c">&#39;\n&#39;</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;<font color="#00979c">String</font> <font color="#000000">split_read_data</font> <font color="#434f54">=</font> <font color="#000000">read_data</font><font color="#434f54">.</font><font color="#d35400">substring</font><font color="#000000">(</font><font color="#000000">read_data</font><font color="#434f54">.</font><font color="#d35400">indexOf</font><font color="#000000">(</font><font color="#00979c">&#39;{&#39;</font><font color="#000000">)</font><font color="#434f54">,</font> <font color="#000000">read_data</font><font color="#434f54">.</font><font color="#d35400">lastIndexOf</font><font color="#000000">(</font><font color="#00979c">&#39;}&#39;</font><font color="#000000">)</font> <font color="#434f54">+</font> <font color="#000000">1</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">print</font><font color="#000000">(</font><font color="#000000">F</font><font color="#000000">(</font><font color="#005c5f">&#34;split_read_data=&#34;</font><font color="#000000">)</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#000000">split_read_data</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;<font color="#5e6d03">if</font> <font color="#000000">(</font><font color="#000000">parse_data</font><font color="#000000">(</font><font color="#000000">split_read_data</font><font color="#000000">)</font><font color="#000000">)</font>
 &nbsp;&nbsp;&nbsp;<font color="#000000">{</font>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="#5e6d03">break</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;<font color="#000000">}</font>
 &nbsp;<font color="#000000">}</font>
<font color="#000000">}</font>

<font color="#434f54">&#47;&#47; {&#34;conf&#34;:[&#34;SSID&#34;,&#34;PASSWORD&#34;]}</font>
<font color="#434f54">&#47;&#47; For version 5.x</font>
<font color="#434f54">&#47;&#47;int parse_data(String data) {</font>
<font color="#434f54">&#47;&#47; &nbsp;StaticJsonBuffer&lt;200&gt; jsonBuffer;</font>
<font color="#434f54">&#47;&#47; &nbsp;JsonObject&amp; root = jsonBuffer.parseObject(data);</font>
<font color="#434f54">&#47;&#47;</font>
<font color="#434f54">&#47;&#47; &nbsp;if (!root.success()) {</font>
<font color="#434f54">&#47;&#47; &nbsp;&nbsp;&nbsp;Serial.println(F(&#34;parseObject() failed&#34;));</font>
<font color="#434f54">&#47;&#47; &nbsp;&nbsp;&nbsp;return false;</font>
<font color="#434f54">&#47;&#47; &nbsp;}</font>
<font color="#434f54">&#47;&#47; &nbsp;else</font>
<font color="#434f54">&#47;&#47; &nbsp;{</font>
<font color="#434f54">&#47;&#47; &nbsp;&nbsp;&nbsp;String ssid_ap = root[&#34;conf&#34;][0];</font>
<font color="#434f54">&#47;&#47; &nbsp;&nbsp;&nbsp;String password_ap = root[&#34;conf&#34;][1];</font>
<font color="#434f54">&#47;&#47; &nbsp;&nbsp;&nbsp;Serial.print(&#34;ssid_ap=&#34;);</font>
<font color="#434f54">&#47;&#47; &nbsp;&nbsp;&nbsp;Serial.println(ssid_ap);</font>
<font color="#434f54">&#47;&#47; &nbsp;&nbsp;&nbsp;Serial.print(&#34;password_ap=&#34;);</font>
<font color="#434f54">&#47;&#47; &nbsp;&nbsp;&nbsp;Serial.println(password_ap);</font>
<font color="#434f54">&#47;&#47; &nbsp;&nbsp;&nbsp;return true;</font>
<font color="#434f54">&#47;&#47; &nbsp;}</font>
<font color="#434f54">&#47;&#47;}</font>

<font color="#95a5a6">&#47;*</font>
<font color="#95a5a6"> &nbsp;For version 6.x</font>
<font color="#95a5a6"> &nbsp;{&#34;conf&#34;:[&#34;SSID&#34;,&#34;PASSWORD&#34;]}</font>
<font color="#95a5a6">*&#47;</font>
<font color="#00979c">int</font> <font color="#000000">parse_data</font><font color="#000000">(</font><font color="#00979c">String</font> <font color="#000000">data</font><font color="#000000">)</font> <font color="#000000">{</font>
 &nbsp;<b><font color="#d35400">StaticJsonDocument</font></b><font color="#434f54">&lt;</font><font color="#000000">200</font><font color="#434f54">&gt;</font> <font color="#000000">jsonBuffer</font><font color="#000000">;</font>
 &nbsp;<b><font color="#d35400">DeserializationError</font></b> <font color="#000000">err</font> <font color="#434f54">=</font> <font color="#d35400">deserializeJson</font><font color="#000000">(</font><font color="#000000">jsonBuffer</font><font color="#434f54">,</font> <font color="#000000">data</font><font color="#000000">)</font><font color="#000000">;</font>

 &nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">print</font><font color="#000000">(</font><font color="#000000">F</font><font color="#000000">(</font><font color="#005c5f">&#34;err=&#34;</font><font color="#000000">)</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#000000">err</font><font color="#434f54">.</font><font color="#000000">c_str</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">)</font><font color="#000000">;</font>

 &nbsp;<font color="#5e6d03">if</font> <font color="#000000">(</font><font color="#000000">err</font><font color="#000000">)</font> <font color="#000000">{</font>
 &nbsp;&nbsp;&nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#000000">F</font><font color="#000000">(</font><font color="#005c5f">&#34;parseObject() failed&#34;</font><font color="#000000">)</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;<font color="#5e6d03">return</font> <font color="#00979c">false</font><font color="#000000">;</font>
 &nbsp;<font color="#000000">}</font>
 &nbsp;<font color="#5e6d03">else</font>
 &nbsp;<font color="#000000">{</font>
 &nbsp;&nbsp;&nbsp;<font color="#00979c">String</font> <font color="#000000">ssid_ap</font> <font color="#434f54">=</font> <font color="#000000">jsonBuffer</font><font color="#000000">[</font><font color="#005c5f">&#34;conf&#34;</font><font color="#000000">]</font><font color="#000000">[</font><font color="#000000">0</font><font color="#000000">]</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;<font color="#00979c">String</font> <font color="#000000">password_ap</font> <font color="#434f54">=</font> <font color="#000000">jsonBuffer</font><font color="#000000">[</font><font color="#005c5f">&#34;conf&#34;</font><font color="#000000">]</font><font color="#000000">[</font><font color="#000000">1</font><font color="#000000">]</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">print</font><font color="#000000">(</font><font color="#005c5f">&#34;ssid_ap=&#34;</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#000000">ssid_ap</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">print</font><font color="#000000">(</font><font color="#005c5f">&#34;password_ap=&#34;</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">println</font><font color="#000000">(</font><font color="#000000">password_ap</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;&nbsp;&nbsp;<font color="#5e6d03">return</font> <font color="#00979c">true</font><font color="#000000">;</font>
 &nbsp;<font color="#000000">}</font>
<font color="#000000">}</font>


<font color="#00979c">void</font> <font color="#5e6d03">setup</font><font color="#000000">(</font><font color="#000000">)</font> <font color="#000000">{</font>
 &nbsp;<b><font color="#d35400">Serial</font></b><font color="#434f54">.</font><font color="#d35400">begin</font><font color="#000000">(</font><font color="#000000">9600</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<font color="#000000">esp8266</font><font color="#434f54">.</font><font color="#d35400">begin</font><font color="#000000">(</font><font color="#000000">9600</font><font color="#000000">)</font><font color="#000000">;</font>
 &nbsp;<font color="#000000">config_device</font><font color="#000000">(</font><font color="#000000">)</font><font color="#000000">;</font>
<font color="#000000">}</font>

<font color="#00979c">void</font> <font color="#5e6d03">loop</font><font color="#000000">(</font><font color="#000000">)</font> <font color="#000000">{</font>
<font color="#000000">}</font>

</pre>

**Comment by bblanchon** [comment]
Hi @sipt91,

Thank you for posting this example, but I don't see how a false positive from ArduinoJson could be a problem here.
Of course, I could make the parser more strict, but it would inevitably have a cost in term of code size.
Also, there are many other places where the parser is forgiving, so I don't think it's the right direction.

Best Regards,
Benoit

**Comment by sipt91** [comment]
Hi @bblanchon,

This is test case. Thank you very much. :)

1) arduino receive string **{"conf":["SSID","PASSWORD"]}** from esp8266.
Result is:
err=OK
ssid_ap=SSID
password_ap=PASSWORD
=> function parse_data return true
2) arduino receive string **SSID,PASSWORD** (wrong json format) from esp8266.
Result is:
err=OK
ssid_ap=null
password_ap=null
=> function parse_data return true (It should be wrong)

**Comment by bblanchon** [comment]
Hi @sipt91,

`parse_data()` should check the presence of `conf` anyway.

Take this example: `{}`
It's a valid JSON document, right?
And yet, you'd get:
err=OK
ssid_ap=null
password_ap=null

I'll try to make the parser pickier (if that's cheap), but it won't solve your problem.

Best Regards,
Benoit

**Comment by sipt91** [comment]
Hi @bblanchon,

I understand your solution.
Thank you very much. :)

**Comment by bblanchon** [comment]
On AVR, this feature adds 64 bytes to the size of the parser; I could not do better 😞

**Comment by sipt91** [comment]
No problem. Thank you very very much. :)
