### ISSUE TITLE
Weird Trailing Int at end of each JSON line.....

### ISSUE THREAD

**Issue by bcodermicro** [bblanchon/ArduinoJson#983]
CODE:
```
#include <ArduinoJson.h>

char owner[] = "";
const int capacity = JSON_OBJECT_SIZE(2);
DynamicJsonDocument doc(capacity);


void setup() {

Serial.begin(115200);


}

void loop() {
  doc["function"]="timereport";
  doc["values"]=millis();
  Serial.println(serializeJson(doc, Serial));
  delay(5000);
}
```

RESULT:

> {"function":"timereport","values":545028}41

I don't think the 41 should be at the end of the JSON block....

**Comment by bblanchon** [comment]
Hi @bostonmacosx,

This line:

```c++
Serial.println(serializeJson(doc, Serial));
```

is equivalent to

```c++
unsigned int n = serializeJson(doc, Serial);
Serial.println(n);
```

The trailing integer that you see is the return value of [serializeJson()](https://arduinojson.org/v6/api/json/serializejson/).

Best Regards,
Benoit

**Comment by bcodermicro** [comment]
So the correct way of just gettng the JSON back then?

I went to 

```
char json_string[256];  
serializeJson(doc, json_string);  
int httpResponseCode = http.POST(json_string);
```
 
and still the web server is ending up with the int character at the end.........so how do I remove that last int?

**Comment by bblanchon** [comment]
Hi @bostonmacosx,

I don't know how to remove the integer you see, but I'm pretty sure this is not related to ArduinoJson.
Did you make any progress?

Best Regards,
Benoit
